import type { FaqLangContent } from '../faqContent';

const da: FaqLangContent = {
  subtitle: 'Alt hvad du behøver at vide om nordlys, rumvejr og hvordan du bedst ser nordlyset.',
  categories: {
    'Aurora Basics': 'Nordlysgrundlæggende',
    'Kp Index': 'Kp-indeks',
    'Solar Wind': 'Solvind',
    'Viewing Tips': 'Tips til nordlysobservation',
    'Space Weather': 'Rumvejr',
    'Moon & Darkness': 'Måne og mørke',
    'Location Guides': 'Stedguider',
  },
  items: [
    { question: 'Hvad er Aurora Borealis (Nordlyset)?', answer: 'Aurora Borealis, eller nordlyset, er et naturligt lysshow forårsaget af ladede partikler fra Solen, der kolliderer med gasser i jordens atmosfære. Når solvindpartikler interagerer med ilt- og kvælstofmolekyler, udsender de fotoner — og skaber de betagende grønne, lilla, røde og blå lysforhæng, der er synlige nær polområderne.' },
    { question: 'Hvad er forskellen mellem Aurora Borealis og Aurora Australis?', answer: 'Aurora Borealis (nordlys) forekommer på den nordlige halvkugle, mens Aurora Australis (sydlys) forekommer på den sydlige halvkugle. Begge er forårsaget af de samme solarvejrsfænomener — ladede partikler, der interagerer med jordens magnetfelt. De opstår ofte simultaneously ved begge poler som spejlbilleder.' },
    { question: 'Hvad er solvind og hvordan påvirker det Jorden?', answer: 'Solvind er en kontinuerlig strøm af ladede partikler (hovedsagelig protoner og elektroner), der strømmer fra Solen med hastigheder på 300–800 km/s. Når hastigheden overstiger 500 km/s, komprimerer den jordens magnetosfære og kan udløse geomagnetiske storme og nordlys. Koronale masseudbrud (CME\'er) forårsager de mest dramatiske nordlysbegivenheder.' },
    { question: 'Hvad er de bedste betingelser for at se Nordlyset?', answer: 'For den bedste nordlysobservation: (1) Mørk himmel — væk fra bylys, (2) Klar himmel — skydække under 30%, (3) Aktive geomagnetiske forhold — Kp 4+, (4) Mørk måne — nymåne eller halvmåne, (5) Tidspunkt — typisk mellem kl. 22 og 02, (6) Sæson — september til marts. Vores synlighedstjekliste kombinerer alle faktorer i realtid.' },
    { question: 'Hvordan fotograferer jeg Nordlyset?', answer: 'Kameraindstillinger til nordlysfotografering: (1) Brug stativ med eksponeringstider på 5–25 sekunder, (2) Vidvinkelobjektiv f/2.8 eller lysere, (3) ISO 1600–3200, (4) Lukkertid 8–15 sekunder, (5) Manuel fokus på uendeligt, (6) Tag billeder i RAW. Moderne telefoner som iPhone 15+ og Samsung S24+ har fremragende nattilstande.' },
    { question: 'Hvad er Solcyklussen og hvornår er det bedst for nordlys?', answer: 'Solen følger en omtrent 11-årig aktivitetscyklus. Under solmaksimum er solpletter, soludbrud og CME\'er hyppigst. Vi befinder os i øjeblikket nær maksimum for solcyklus 25 (2024–2026) — en af de bedste perioder for nordlysjagt i over et årti.' },
    { question: 'Påvirker Månen synligheden af nordlyset?', answer: 'Ja — en lys fuldmåne udvisker svagere nordlys, ligesom lysforurening. Den bedste observation sker ved nymåne eller nogle dage efter, når himmelen er mørkest. Meget stærkt nordlys (Kp 7+) kan dog ses selv under fuldmåne. Vores tjekliste tager automatisk højde for den aktuelle månefase.' },
    { question: 'Hvad er Kp-indekset og hvad betyder det for nordlysobservation?', answer: 'Kp-indekset er en global 0–9-skala for forstyrrelser i jordens magnetfelt, opdateret af NOAA hvert 3. time. Kp 0–2 betyder aktivitet begrænset til polområderne, mens Kp 5+ driver nordlyset længere sydpå — muligvis til Skotland, Sydcanada eller endda Centraleuropa. Live data vises på The Storm Watchers Dashboard.' },
    { question: 'Hvilket Kp-niveau kræves for at se nordlyset?', answer: 'Det nødvendige Kp afhænger af breddegraden. Ved 65°N (Nordskandinavien, Island, Alaska) er Kp 1–2 ofte nok. Ved 60°N (Sydnorge, Helsinki) er Kp 3–4 typisk. Ved 55°N (Skotland, Stockholm) er Kp 5–6 normalt nødvendigt. Ved 50°N (Centraltyskland, Prag) kræves Kp 7–8.' },
    { question: 'Hvad er forskellen mellem Kp 5, Kp 7 og Kp 9?', answer: 'Kp 5 (G1-storm) er minimumsgrænsen — nordlyset bliver synligt i Sydskandinavien og Skotland som en bleg bue. Kp 7 (G3-storm) bringer levende nordlys til Tyskland og det nordlige USA. Kp 9 (G5-storm) er maksniveauet — senest i maj 2024, da nordlys blev observeret over Spanien, Italien, Texas og Florida.' },
    { question: 'Hvad er en geomagnetisk storm og hvordan måles den?', answer: 'En geomagnetisk storm er en storskaleret forstyrrelse af jordens magnetosfære fra forstærket solvind — typisk efter en CME eller højhastighedsstrøm fra et koronalt hul. NOAA klassificerer storme på G-skalaen: G1 (Kp 5) til G5 (Kp 9). Storme kan forstyrre satellitter, GPS, KV-radio og elnet.' },
    { question: 'Hvad er et røntgen-soludbrud og hvad betyder det?', answer: 'Soludbrud er intense strålingsudsendinger klassificeret efter røntgentop: A, B, C, M og X (hvert trin er 10× stærkere). C-klassen er lille; M kan forårsage korte radiobortfald; X er de kraftigste. Et enkelt udbrud garanterer ikke nordlys — afgørende er om det ledsages af et jordrettet CME.' },
    { question: 'Hvad er et CME (koronalt masseudbrud)?', answer: 'Et koronalt masseudbrud er en massiv eksplosion af magnetiseret plasma fra solens korona, der frigiver op til en milliard ton solmateriale med hastigheder på 250–3 000 km/s. Når et jordrettet CME ankommer — typisk 1–4 dage efter udbruddet — komprimerer det magnetosfæren og udløser de mest spektakulære nordlysbegivenheder.' },
    { question: 'Hvad er Bz-komponenten og hvorfor er den vigtig for nordlys?', answer: 'Bz er nord-syd-komponenten af det interplanetariske magnetfelt, målt af DSCOVR- og ACE-satelliterne ved L1-punktet. Når Bz er negativ, tillader magnetisk rekobling ladede partikler at strømme ind i polaratmosfæren. Vedvarende Bz under −10 nT giver normalt 15–45 minutters forvarsel.' },
    { question: 'Hvad er solvindshastigheden og hvordan påvirker den nordlyset?', answer: 'Solvinden strømmer med typiske hastigheder på 300–500 km/s under rolige forhold. Over 500 km/s komprimerer den magnetosfæren; over 700 km/s er den forbundet med stærk geomagnetisk aktivitet. Højhastighedsstrømme fra koronale huller er ofte forudsigelige op til 27 dage i forvejen.' },
    { question: 'Hvad er nordlysovalen?', answer: 'Nordlysovalen er en ringformet zone rundt om hvert magnetpol, hvor nordlyset er mest konsistent aktivt, centreret ved omtrent 65–70° geomagnetisk breddegrad. Under storme udvider ovalen sig mod ækvator — en Kp 9-storm kan drive den helt til subtroperne. NOAA OVATION-modellen viser den i realtid på The Storm Watchers 3D-globus.' },
    { question: 'Hvorfor ser nordlyset grønt, rødt eller lilla ud?', answer: 'Nordlysets farver bestemmes af hvilket atmosfærisk gas der aktiveres og på hvilken højde. Grønt — den hyppigste farve — kommer fra ilt ved 100–150 km. Rødt nordlys stammer fra ilt over 200 km. Blå og lilla nuancer kommer fra kvælstof under 100 km. Under intense storme aktiveres flere lag simultant.' },
    { question: 'Hvad er den bedste årstid for at se Nordlyset?', answer: 'Nordlyset er aktivt hele året, men synlighed kræver mørke — hvilket gør september til marts til højsæsonen. Høst- og forårsjævndøgnet er statistisk mere aktive på grund af Russell–McPherron-effekten. Sommeren er problematisk ved høje breddegrader på grund af midnatssolens. Oktober til februar giver den bedste kombination.' },
    { question: 'Hvad er den bedste tid på natten for nordlysobservation?', answer: 'Nordlysaktiviteten topper sig ved lokal magnetisk midnat — typisk mellem kl. 22 og 02 — når feltlinjerne overhead kobler mest direkte til nordlyszonen. Indstil en Kp-tærskelvarsel i The Storm Watcher for at blive underrettet på præcis det rigtige tidspunkt.' },
    { question: 'Hvordan får jeg nordlysvarsler på min telefon?', answer: 'The Storm Watcher tilbyder gratis push-notifikationer — angiv din Kp-tærskel i Indstillinger (f.eks. "giv besked når Kp ≥ 5") og du underrettes i det øjeblik NOAA-data krydser det niveau. Beskeden inkluderer aktuelt Kp, Bz, solvindshastighed og estimeret skydække ved din gemte lokation.' },
    { question: 'Kan jeg se nordlyset i Skotland / Storbritannien?', answer: 'Ja — Skotland er en af de bedste nordlysdestinationer uden for Skandinavien. De skotske Highlands, Orkneyøerne og Shetland ligger ved 57–60°N, hvor Kp 4–5 typisk er nok på en klar, mørk nat. Under stærkere storme (Kp 6+) er nordlys regelmæssigt synligt i det nordlige England, og ved Kp 8+ endog fra det sydlige England.' },
    { question: 'Kan jeg se nordlyset i Tyskland / Centraleuropa?', answer: 'Nordlysobservationer i Tyskland, Østrig, Schweiz, Polen og nabolande er sjældnere, men fuldt mulige under stærke geomagnetiske storme. Ved 47–54°N er Kp 7–8 typisk nødvendigt, og Kp 9 kan bringe nordlys til Middelhavet — dramatisk demonstreret under G5-stormen i maj 2024. Indstil en stormvarsel i The Storm Watcher.' },
  ],
};

export default da;
