import type { FaqLangContent } from '../faqContent';

const de: FaqLangContent = {
  subtitle: 'Alles, was Sie über das Nordlicht, Weltraumwetter und die Aurora-Beobachtung wissen müssen.',
  categories: {
    'Aurora Basics': 'Aurora-Grundlagen',
    'Kp Index': 'Kp-Index',
    'Solar Wind': 'Sonnenwind',
    'Viewing Tips': 'Beobachtungstipps',
    'Space Weather': 'Weltraumwetter',
    'Moon & Darkness': 'Mond & Dunkelheit',
    'Location Guides': 'Standortführer',
  },
  items: [
    { question: 'Was ist das Aurora Borealis (Nordlicht)?', answer: 'Das Aurora Borealis, auch Nordlicht genannt, ist ein natürliches Lichtphänomen, das entsteht, wenn geladene Teilchen von der Sonne mit den Gasen in der Erdatmosphäre kollidieren. Wenn Sonnenwindteilchen mit Sauerstoff- und Stickstoffmolekülen interagieren, emittieren sie Lichtphotonen — und erzeugen dabei die faszinierenden grünen, lila, roten und blauen Lichtvorhänge in den Polarregionen.' },
    { question: 'Was ist der Unterschied zwischen Aurora Borealis und Aurora Australis?', answer: 'Aurora Borealis (Nordlicht) tritt auf der Nordhalbkugel auf, während Aurora Australis (Südlicht) auf der Südhalbkugel erscheint. Beide werden durch das gleiche Sonnenwetterereignis verursacht — geladene Teilchen, die mit dem Erdmagnetfeld interagieren. Sie erscheinen häufig gleichzeitig an beiden Polen als Spiegelbilder.' },
    { question: 'Was ist Sonnenwind und wie beeinflusst er die Erde?', answer: 'Sonnenwind ist ein kontinuierlicher Strom geladener Teilchen (hauptsächlich Protonen und Elektronen), der von der Sonne mit Geschwindigkeiten von 300–800 km/s strömt. Wenn die Sonnenwindgeschwindigkeit 500 km/s überschreitet, komprimiert er die Magnetosphäre der Erde und kann geomagnetische Stürme auslösen. Koronale Massenauswürfe (CMEs) verursachen die dramatischsten Nordlichtereignisse.' },
    { question: 'Was sind die besten Bedingungen für die Nordlichtbeobachtung?', answer: 'Für die beste Polarlichtbeobachtung: (1) Dunkler Himmel — weg von Stadtlicht, (2) Klarer Himmel — Bewölkung unter 30%, (3) Aktive geomagnetische Bedingungen — Kp 4+, (4) Dunkler Mond — Neumond oder Sichelmond, (5) Zeit — typischerweise zwischen 22 und 2 Uhr Ortszeit, (6) Saison — September bis März. Unsere Aurora-Sichtbarkeitsliste kombiniert all diese Faktoren in Echtzeit.' },
    { question: 'Wie fotografiere ich das Nordlicht?', answer: 'Kameraeinstellungen für Polarlichtfotografie: (1) Stativ verwenden — Belichtungszeiten 5–25 Sekunden, (2) Weitwinkelobjektiv f/2.8 oder lichtstärker, (3) ISO 1600–3200, (4) Verschlusszeit 8–15 Sekunden, (5) Manueller Fokus auf Unendlich, (6) RAW-Format für beste Nachbearbeitung. Tipp: Moderne Smartphones wie iPhone 15+ und Samsung S24+ haben ausgezeichnete Nachtmodi.' },
    { question: 'Was ist der Sonnenzyklus und wann ist die beste Zeit für Polarlichter?', answer: 'Die Sonne folgt einem etwa 11-jährigen Aktivitätszyklus. Während des Sonnenmaximums sind Sonnenflecken, Sonneneruptionen und CMEs am häufigsten. Wir befinden uns derzeit nahe dem Maximum des Sonnenzyklus 25 (2024–2026) — eine der besten Phasen für Polarlichter seit über einem Jahrzehnt. Die erhöhte Aktivität sollte bis 2027 anhalten.' },
    { question: 'Beeinflusst der Mond die Polarlicht-Sichtbarkeit?', answer: 'Ja — ein heller Vollmond überstrahlt schwächere Polarlichter, ähnlich wie Lichtverschmutzung. Die beste Beobachtung findet bei Neumond oder wenige Tage danach statt, wenn der Himmel am dunkelsten ist. Sehr starke Polarlichter (Kp 7+) sind jedoch auch unter einem Vollmond sichtbar. Unsere Sichtbarkeitsliste berücksichtigt automatisch die aktuelle Mondphase.' },
    { question: 'Was ist der Kp-Index und was bedeutet er für die Polarlichtsichtbarkeit?', answer: 'Der Kp-Index (Planetarische Kennziffer) ist eine globale 0–9-Skala für Störungen im Erdmagnetfeld, die NOAA alle 3 Stunden aktualisiert. Kp 0–2 bedeutet Aktivität nur nahe der Polarregionen, während Kp 5+ das Nordlicht weiter nach Süden verlagert — möglicherweise bis Schottland, Südkanada oder sogar Mitteleuropa. Live-Kp-Daten werden im Dashboard von The Storm Watcher angezeigt.' },
    { question: 'Welchen Kp-Wert benötige ich für das Nordlicht?', answer: 'Der erforderliche Kp hängt von Ihrem Breitengrad ab. Bei 65°N (Nordskandinavien, Island, Alaska) reicht oft Kp 1–2. Bei 60°N (Süd-Norwegen, Helsinki) typisch Kp 3–4. Bei 55°N (Schottland, Stockholm) benötigen Sie Kp 5–6. Bei 50°N (Mitteldeutschland, Prag) Kp 7–8. Diese Schwellenwerte gelten für völlig dunklen, klaren Himmel.' },
    { question: 'Was ist der Unterschied zwischen Kp 5, Kp 7 und Kp 9?', answer: 'Kp 5 (G1-Sturm) ist der Mindestschwellenwert — Polarlichter werden in Südskandinavien und Schottland oft als blasser Bogen sichtbar. Kp 7 (G3-Sturm) bringt lebhafte Polarlichter bis nach Deutschland und Nordengland. Kp 9 (G5-Sturm) ist das Maximum — zuletzt im Mai 2024, als Nordlichter über Spanien, Italien, Texas und Florida zu sehen waren.' },
    { question: 'Was ist ein geomagnetischer Sturm und wie wird er gemessen?', answer: 'Ein geomagnetischer Sturm ist eine großräumige Störung der Magnetosphäre durch verstärkten Sonnenwind — typisch nach einem CME oder schnellen Strömen aus Koronalöchern. NOAA klassifiziert Stürme auf der G-Skala: G1 (Kp 5) bis G5 (Kp 9). Stürme können Satelliten, GPS, Kurzwellenradio und Stromnetze beeinträchtigen. Ein Sturmhinweis von The Storm Watcher signalisiert optimale Polarlichtbedingungen.' },
    { question: 'Was ist ein Röntgen-Sonneneruptionen und was bedeutet das?', answer: 'Sonneneruptionen sind intensive Strahlungsausbrüche von der Sonnenoberfläche, klassifiziert nach Röntgen-Spitzenleistung: A, B, C, M und X (jede Klasse ist 10× stärker). C-Klasse ist gering; M-Klasse kann kurze Funkausfälle verursachen; X-Klasse ist am stärksten. Eine Eruption allein garantiert kein Polarlicht — entscheidend ist, ob ein erdgerichtetes CME begleitet wird.' },
    { question: 'Was ist ein CME (koronaler Massenauswurf)?', answer: 'Ein koronaler Massenauswurf ist ein massiver Ausbruch magnetisierten Plasmas aus der Sonnenkorona, der bis zu einer Milliarde Tonnen Sonnenmaterial mit 250–3.000 km/s freisetzt. Wenn ein erdgerichtetes CME eintrifft — typischerweise 1–4 Tage nach dem Ausbruch — komprimiert es die Magnetosphäre und löst die spektakulärsten Polarlichtereignisse des Sonnenzyklus aus.' },
    { question: 'Was ist die Bz-Komponente und warum ist sie für Polarlichter wichtig?', answer: 'Bz ist die Nord-Süd-Komponente des Interplanetaren Magnetfelds, gemessen von DSCOVR- und ACE-Satelliten am L1-Lagrangepunkt. Wenn Bz negativ ist, ermöglicht magnetische Rekonnexion, dass geladene Teilchen in die Polatatmosphäre eindringen. Ein anhaltender Bz unter −10 nT gibt oft 15–45 Minuten Vorwarnung vor einem Kp-Anstieg.' },
    { question: 'Was ist die Sonnenwindgeschwindigkeit und wie beeinflusst sie Polarlichter?', answer: 'Sonnenwind strömt mit typischen Geschwindigkeiten von 300–500 km/s bei ruhigen Bedingungen. Über 500 km/s komprimiert er die Magnetosphäre; über 700 km/s ist er mit starker geomagnetischer Aktivität verbunden. Hochgeschwindigkeitsströme aus Koronalöchern sind oft bis zu 27 Tage im Voraus vorhersagbar.' },
    { question: 'Was ist das Aurora-Oval?', answer: 'Das Aurora-Oval ist eine ringförmige Zone um jeden Magnetpol, wo Aurora am gleichmäßigsten aktiv ist, zentriert bei etwa 65–70° geomagnetischer Breite unter ruhigen Bedingungen. Bei geomagnetischen Stürmen dehnt sich das Oval äquatorwärts aus — ein Kp-9-Sturm kann es bis in die Subtropen schieben. Das NOAA-OVATION-Modell zeigt die Lage in Echtzeit auf The Storm Watchers 3D-Globus.' },
    { question: 'Warum erscheint das Polarlicht grün, rot oder lila?', answer: 'Aurora-Farben hängen davon ab, welches atmosphärische Gas angeregt wird und in welcher Höhe. Grün — die häufigste Farbe — stammt von Sauerstoffatomen in 100–150 km Höhe. Rote Aurora entsteht aus Sauerstoff über 200 km. Blau- und Lilatöne stammen von Stickstoffmolekülen unter 100 km. Bei starken Stürmen werden mehrere Schichten gleichzeitig angeregt.' },
    { question: 'Wann ist die beste Jahreszeit für Nordlichter?', answer: 'Die Aurora ist ganzjährig aktiv, aber Sichtbarkeit erfordert Dunkelheit — September bis März ist die Hauptsaison. Herbst- und Frühlings-Tagundnachtgleichen sind statistisch aktiver durch den Russell–McPherron-Effekt. Im Sommer ist es in hohen Breiten wegen der Mitternachtssonne nie dunkel genug. Oktober bis Februar bietet die beste Kombination.' },
    { question: 'Welche Tageszeit ist für die Polarlichtsichtung am besten?', answer: 'Die Polarlichtaktivität erreicht ihren Höhepunkt um lokale magnetische Mitternacht — typisch zwischen 22 und 2 Uhr — wenn die Feldlinien am direktesten mit der Auroralen Zone verbunden sind. Stellen Sie einen Kp-Alarm in The Storm Watcher ein, um genau dann benachrichtigt zu werden, wenn die Bedingungen optimal sind.' },
    { question: 'Wie erhalte ich Polarlichtwarnungen auf meinem Smartphone?', answer: 'The Storm Watcher bietet kostenlose Push-Benachrichtigungen für geomagnetische Sturmwarnungen — stellen Sie Ihren Kp-Schwellenwert in den Einstellungen ein (z. B. "Warnung bei Kp ≥ 5") und werden Sie sofort informiert. Die Benachrichtigung enthält aktuellen Kp, Bz, Sonnenwindgeschwindigkeit und Bewölkung an Ihrem gespeicherten Standort.' },
    { question: 'Kann man das Polarlicht in Schottland / Großbritannien sehen?', answer: 'Ja — Schottland ist eines der besten Polarlicht-Ziele außerhalb Skandinaviens. Scottish Highlands, Orkney und Shetland liegen bei 57–60°N, wo Kp 4–5 bei klarer, dunkler Nacht typischerweise ausreicht. Bei stärkeren Stürmen (Kp 6+) ist Polarlicht regelmäßig in Nordengland sichtbar, bei Kp 8+ sogar in Südengland. Dunkelste Orte: Galloway Forest Dark Sky Park und Northumberland.' },
    { question: 'Kann man das Polarlicht in Deutschland / Mitteleuropa sehen?', answer: 'Polarlichtsichtungen in Deutschland, Österreich, der Schweiz und Polen sind seltener, aber bei starken geomagnetischen Stürmen durchaus möglich. Bei 47–54°N wird typischerweise Kp 7–8 benötigt, und Kp 9 kann Polarlichter bis ans Mittelmeer bringen — eindrucksvoll bewiesen beim G5-Sturm im Mai 2024. Stellen Sie eine Sturmwarnung in The Storm Watcher ein und finden Sie einen dunklen Beobachtungsplatz.' },
  ],
};

export default de;
