import type { FaqLangContent } from '../faqContent';

const en: FaqLangContent = {
  subtitle: 'Everything you need to know about the Northern Lights, space weather, and how to catch the aurora.',
  categories: {
    'Aurora Basics': 'Aurora Basics',
    'Kp Index': 'Kp Index',
    'Solar Wind': 'Solar Wind',
    'Viewing Tips': 'Viewing Tips',
    'Space Weather': 'Space Weather',
    'Moon & Darkness': 'Moon & Darkness',
    'Location Guides': 'Location Guides',
  },
  items: [
    { question: 'What is the Aurora Borealis (Northern Lights)?', answer: 'The Aurora Borealis, or Northern Lights, is a natural light display caused by charged particles from the Sun colliding with gases in Earth\'s atmosphere. When solar wind particles interact with oxygen and nitrogen molecules, they emit photons of light — creating the stunning green, purple, red, and blue curtains of light visible near the polar regions.' },
    { question: 'What is the difference between Aurora Borealis and Aurora Australis?', answer: 'Aurora Borealis (Northern Lights) occurs in the Northern Hemisphere, while Aurora Australis (Southern Lights) occurs in the Southern Hemisphere. Both are caused by the same solar phenomena — charged particles from the Sun interacting with Earth\'s magnetic field. They often appear simultaneously at both poles as mirror images.' },
    { question: 'What is solar wind and how does it affect Earth?', answer: 'Solar wind is a continuous stream of charged particles (mainly protons and electrons) flowing from the Sun at speeds of 300–800 km/s. When solar wind speed increases above 500 km/s and density rises, it compresses Earth\'s magnetosphere, potentially triggering geomagnetic storms and aurora. Coronal Mass Ejections (CMEs) — massive bursts of solar wind — can cause the most dramatic aurora events.' },
    { question: 'What are the best conditions for seeing the Northern Lights?', answer: 'For the best aurora viewing: (1) Dark skies — get away from city lights, (2) Clear skies — cloud cover below 30%, (3) Active geomagnetic conditions — Kp 4+, (4) Dark moon — new moon or crescent phases are ideal, (5) Time — typically between 10 PM and 2 AM local time, (6) Season — September to March in the Northern Hemisphere. Our Aurora Visibility Checklist combines all these factors in real-time.' },
    { question: 'How do I photograph the Northern Lights?', answer: 'Camera settings for aurora photography: (1) Use a tripod — exposures are 5–25 seconds, (2) Wide-angle lens, f/2.8 or faster, (3) ISO 1600–3200, (4) Shutter speed 8–15 seconds for sharp curtains, (5) Manual focus set to infinity, (6) Shoot in RAW for best post-processing flexibility. Smartphone tip: modern phones like iPhone 15+ and Samsung S24+ have excellent night modes that can capture aurora automatically.' },
    { question: 'What is the Solar Cycle and when is the best time for aurora?', answer: 'The Sun follows an approximately 11-year activity cycle. During Solar Maximum, sunspots, solar flares, and CMEs are most frequent, producing more geomagnetic storms and aurora. We are currently near Solar Cycle 25\'s maximum (2024–2026), making this one of the best periods for aurora hunting in over a decade. Activity should remain elevated through 2027.' },
    { question: 'Does the Moon affect aurora visibility?', answer: 'Yes — a bright full moon washes out fainter aurora displays, similar to light pollution. The best aurora viewing occurs during new moon or within a few days of it, when skies are darkest. However, very strong aurora (Kp 7+) can be visible even under a full moon. Our Visibility Checklist automatically factors in the current moon phase.' },
    { question: 'What is the Kp index and what does it mean for aurora viewing?', answer: 'The Kp index (Planetarische Kennziffer) is a global 0–9 scale measuring disturbances in Earth\'s magnetic field, updated every 3 hours by NOAA. For aurora viewing, it indicates how far south the aurora oval expands: Kp 0–2 means activity is confined near the polar regions, while Kp 5+ pushes the northern lights further south — potentially to Scotland, southern Canada, or even Central Europe during extreme events. Live Kp data is displayed on The Storm Watcher\'s Dashboard, updated every minute from the GFZ Potsdam and NOAA feeds.' },
    { question: 'What Kp level do I need to see the northern lights?', answer: 'The required Kp depends on your latitude. At 65°N (northern Scandinavia, Iceland, Alaska), Kp 1–2 is often enough. At 60°N (southern Norway, Helsinki, Anchorage), Kp 3–4 is typical. At 55°N (Scotland, Stockholm, southern Canada), you generally need Kp 5–6. At 50°N (central Germany, Prague, northern France), Kp 7–8 is required. Use The Storm Watcher\'s Aurora Visibility page for a prediction tailored to your exact coordinates.' },
    { question: 'What is the difference between Kp 5, Kp 7, and Kp 9?', answer: 'Kp 5 (G1 minor storm) is the entry-level threshold — aurora becomes visible in southern Scandinavia, Scotland, and northern Canada, often as a pale arc on the horizon. Kp 7 (G3 strong storm) pushes aurora vividly to Germany, the northern US, and much of the UK, bright enough to photograph with a smartphone. Kp 9 (G5 extreme storm) is the maximum level — the last major example was May 2024, when aurora was seen across Spain, Italy, Texas, and Florida. Each Kp step pushes the aurora oval roughly 2–3° further toward the equator.' },
    { question: 'What is a geomagnetic storm and how is it measured?', answer: 'A geomagnetic storm is a large-scale disturbance of Earth\'s magnetosphere caused by enhanced solar wind — typically following a CME or a high-speed stream from a coronal hole. NOAA classifies storms on the G-scale: G1 (minor, Kp 5), G2 (moderate, Kp 6), G3 (strong, Kp 7), G4 (severe, Kp 8), G5 (extreme, Kp 9). Storms produce aurora at lower latitudes and can disrupt satellites, GPS, HF radio, and power grids. A geomagnetic storm alert from The Storm Watcher means conditions are ripe for an aurora sighting.' },
    { question: 'What is an X-ray solar flare and what does it mean?', answer: 'Solar flares are intense bursts of radiation from the Sun\'s surface, classified by peak X-ray output: A, B, C, M, and X (each letter is 10× stronger). C-class flares are minor; M-class flares can cause brief radio blackouts; X-class flares are the most powerful and can trigger radiation storms. A flare alone doesn\'t guarantee aurora — what matters is whether it is accompanied by an Earth-directed CME. The Storm Watcher\'s Dashboard shows real-time X-ray flux from NOAA\'s GOES satellite.' },
    { question: 'What is a CME (coronal mass ejection)?', answer: 'A coronal mass ejection is a massive eruption of magnetized plasma from the Sun\'s corona, releasing up to a billion tonnes of solar material at speeds of 250–3,000 km/s. When an Earth-directed CME arrives — typically 1–4 days after the eruption — it compresses Earth\'s magnetosphere, spikes the Kp index, and triggers the most spectacular aurora events of the solar cycle. NOAA\'s DONKI database tracks every active CME, and The Storm Watcher integrates this data into its storm alert system.' },
    { question: 'What is the Bz component and why does it matter for aurora?', answer: 'Bz is the north-south component of the Interplanetary Magnetic Field (IMF), measured by the DSCOVR and ACE satellites at the L1 Lagrange point. When Bz is negative (southward), magnetic reconnection allows charged solar particles to stream into the polar atmosphere and produce aurora. A sustained Bz below −10 nT often gives 15–45 minutes of advance warning before the Kp index rises. Monitoring Bz on The Storm Watcher\'s Dashboard is one of the most actionable signals for deciding whether to head outside tonight.' },
    { question: 'What is solar wind speed and how does it affect aurora?', answer: 'Solar wind flows from the Sun\'s corona at typical speeds of 300–500 km/s during quiet conditions. When speed exceeds 500 km/s it compresses Earth\'s magnetosphere; above 700 km/s it is associated with strong geomagnetic activity. High-speed streams from coronal holes are often predictable up to 27 days in advance. The most powerful aurora events combine elevated solar wind speed with a strongly negative Bz — both are displayed live on The Storm Watcher\'s Dashboard.' },
    { question: 'What is the aurora oval?', answer: 'The aurora oval is a ring-shaped zone around each magnetic pole where aurora is most consistently active, centered at approximately 65–70° geomagnetic latitude under quiet conditions. During geomagnetic storms the oval expands equatorward — a Kp 9 storm can push it to the subtropics. The NOAA OVATION model provides a real-time estimate of the oval\'s location and intensity, displayed on The Storm Watcher\'s 3D aurora globe.' },
    { question: 'Why does the aurora appear green, red, or purple?', answer: 'Aurora colors depend on which atmospheric gas is energized and at what altitude. Green — the most common — comes from oxygen at 100–150 km altitude. Red aurora comes from oxygen above 200 km, where atoms take longer to release energy. Blue and purple hues come from nitrogen below 100 km. During intense storms multiple layers are energized simultaneously, producing vivid multi-colored displays — green curtains topped with red and purple fringes.' },
    { question: 'When is the best time of year to see the northern lights?', answer: 'The aurora is active year-round, but visibility requires darkness — making September through March the prime season. The autumn and spring equinoxes are statistically more active due to the Russell–McPherron effect. Summer is problematic at high latitudes because of the midnight sun. October through February offers the best combination of long nights, reasonable temperatures, and elevated geomagnetic activity during Solar Cycle 25\'s maximum.' },
    { question: 'What time of night is best for aurora viewing?', answer: 'Aurora activity peaks around local magnetic midnight — typically between 10 PM and 2 AM — when field lines overhead connect most directly to the auroral zone. Faint aurora can appear any time after astronomical twilight, but the most dynamic displays concentrate in this window. Setting a Kp threshold alert on The Storm Watcher means you\'ll be notified the moment conditions peak, so you can head out at precisely the right time.' },
    { question: 'How do I get aurora alerts on my phone?', answer: 'The Storm Watcher offers free push notifications for geomagnetic storm alerts — set your Kp threshold in the Settings page (e.g., "alert me when Kp ≥ 5") and you\'ll be notified the moment NOAA data crosses that level. The alert includes current Kp, Bz, solar wind speed, and estimated cloud cover at your saved location, giving you a complete forecast in a single notification. This is far more reliable than checking manually, since strong activity can develop within minutes of a CME\'s arrival.' },
    { question: 'Can I see the aurora in Scotland / UK?', answer: 'Yes — Scotland is one of the best aurora destinations outside Scandinavia. The Scottish Highlands, Orkney, and Shetland sit at 57–60°N, where Kp 4–5 is typically enough on a clear, dark night. During stronger storms (Kp 6+), aurora is regularly visible across northern England and, at Kp 8+, even from southern England. The biggest challenge is cloud cover — check The Storm Watcher\'s forecast alongside a cloud cover chart before heading out. The darkest spots are Galloway Forest Dark Sky Park, the Cairngorms, and Northumberland International Dark Sky Park.' },
    { question: 'Can I see the aurora in Germany / Central Europe?', answer: 'Aurora sightings in Germany, Austria, Switzerland, Poland, and neighbouring countries are rarer but entirely possible during strong geomagnetic storms. At 47–54°N, Kp 7–8 is typically needed, and Kp 9 can bring aurora to the Mediterranean — as demonstrated in May 2024, when the northern lights were photographed across Germany, France, northern Italy, and Spain. Set a geomagnetic storm alert on The Storm Watcher, identify a dark-sky site within driving distance, and watch for a sustained negative Bz.' },
  ],
};

export default en;
