import type { FaqLangContent } from '../faqContent';

const es: FaqLangContent = {
  subtitle: 'Todo lo que necesitas saber sobre las auroras boreales, el tiempo espacial y cómo observarlas.',
  categories: {
    'Aurora Basics': 'Conceptos básicos de la aurora',
    'Kp Index': 'Índice Kp',
    'Solar Wind': 'Viento solar',
    'Viewing Tips': 'Consejos de observación',
    'Space Weather': 'Tiempo espacial',
    'Moon & Darkness': 'Luna y oscuridad',
    'Location Guides': 'Guías de ubicación',
  },
  items: [
    { question: '¿Qué es la Aurora Boreal (Luces del Norte)?', answer: 'La Aurora Boreal, o Luces del Norte, es un fenómeno luminoso natural causado por partículas cargadas del Sol que colisionan con los gases de la atmósfera terrestre. Cuando las partículas del viento solar interactúan con moléculas de oxígeno y nitrógeno, emiten fotones de luz, creando los impresionantes cortinajes de luz verde, morada, roja y azul visibles en las regiones polares.' },
    { question: '¿Cuál es la diferencia entre la Aurora Boreal y la Aurora Austral?', answer: 'La Aurora Boreal (Luces del Norte) se produce en el hemisferio norte, mientras que la Aurora Austral (Luces del Sur) se produce en el hemisferio sur. Ambas tienen la misma causa: partículas cargadas del Sol que interactúan con el campo magnético de la Tierra. Con frecuencia aparecen simultáneamente en ambos polos como imágenes especulares.' },
    { question: '¿Qué es el viento solar y cómo afecta a la Tierra?', answer: 'El viento solar es una corriente continua de partículas cargadas (principalmente protones y electrones) que fluye del Sol a velocidades de 300–800 km/s. Cuando supera los 500 km/s y aumenta la densidad, comprime la magnetosfera terrestre, pudiendo desencadenar tormentas geomagnéticas y auroras. Las Eyecciones de Masa Coronal (CMEs) causan los eventos de aurora más espectaculares.' },
    { question: '¿Cuáles son las mejores condiciones para ver las Luces del Norte?', answer: 'Para la mejor observación de auroras: (1) Cielos oscuros, lejos de luces urbanas, (2) Cielos despejados con menos del 30% de nubosidad, (3) Condiciones geomagnéticas activas — Kp 4+, (4) Luna oscura — luna nueva o creciente, (5) Hora — entre las 22:00 y las 2:00 hora local, (6) Temporada — de septiembre a marzo. Nuestra lista de verificación combina todos estos factores en tiempo real.' },
    { question: '¿Cómo fotografío las Luces del Norte?', answer: 'Ajustes de cámara para fotografiar auroras: (1) Usa un trípode con exposiciones de 5–25 segundos, (2) Objetivo gran angular f/2.8 o más luminoso, (3) ISO 1600–3200, (4) Velocidad de obturación 8–15 segundos, (5) Enfoque manual al infinito, (6) Dispara en RAW. Consejo para móvil: los teléfonos modernos como iPhone 15+ y Samsung S24+ tienen excelentes modos nocturnos.' },
    { question: '¿Qué es el Ciclo Solar y cuándo es el mejor momento para auroras?', answer: 'El Sol sigue un ciclo de actividad de aproximadamente 11 años. Durante el Máximo Solar, las manchas solares, llamaradas y CMEs son más frecuentes. Actualmente estamos cerca del máximo del Ciclo Solar 25 (2024–2026), lo que convierte este período en uno de los mejores para cazar auroras en más de una década.' },
    { question: '¿Afecta la Luna a la visibilidad de las auroras?', answer: 'Sí — una luna llena brillante atenúa las auroras más débiles, similar a la contaminación lumínica. La mejor observación ocurre en luna nueva o pocos días después, cuando los cielos son más oscuros. Sin embargo, las auroras muy fuertes (Kp 7+) pueden verse incluso con luna llena. Nuestra lista verifica automáticamente la fase lunar actual.' },
    { question: '¿Qué es el índice Kp y qué significa para ver auroras?', answer: 'El índice Kp es una escala global de 0–9 que mide perturbaciones en el campo magnético terrestre, actualizado cada 3 horas por la NOAA. Kp 0–2 significa actividad confinada cerca de las regiones polares, mientras que Kp 5+ empuja las auroras más al sur — posiblemente hasta Escocia, el sur de Canadá o incluso Europa Central. Los datos se muestran en el Panel de The Storm Watcher.' },
    { question: '¿Qué nivel de Kp necesito para ver las auroras?', answer: 'El Kp requerido depende de tu latitud. A 65°N (norte de Escandinavia, Islandia, Alaska), Kp 1–2 suele ser suficiente. A 60°N (sur de Noruega, Helsinki), típicamente Kp 3–4. A 55°N (Escocia, Estocolmo), generalmente Kp 5–6. A 50°N (centro de Alemania, Praga), Kp 7–8. Estos umbrales asumen cielos completamente oscuros y despejados.' },
    { question: '¿Cuál es la diferencia entre Kp 5, Kp 7 y Kp 9?', answer: 'Kp 5 (tormenta G1 menor) es el umbral mínimo: la aurora se hace visible en el sur de Escandinavia y Escocia como un arco pálido. Kp 7 (tormenta G3 fuerte) lleva auroras vívidas a Alemania y el norte de EE.UU. Kp 9 (tormenta G5 extrema) es el nivel máximo — el último ejemplo fue mayo de 2024, con auroras vistas en España, Italia, Texas y Florida.' },
    { question: '¿Qué es una tormenta geomagnética y cómo se mide?', answer: 'Una tormenta geomagnética es una perturbación a gran escala de la magnetosfera causada por viento solar intensificado — típicamente tras una CME o corrientes de alta velocidad de agujeros coronales. NOAA clasifica las tormentas en la escala G: G1 (Kp 5) a G5 (Kp 9). Las tormentas pueden perturbar satélites, GPS, radio HF y redes eléctricas.' },
    { question: '¿Qué es una llamarada solar de rayos X y qué significa?', answer: 'Las llamaradas solares son intensas explosiones de radiación clasificadas por su producción de rayos X: A, B, C, M y X (cada clase es 10 veces más potente). Las de clase C son menores; las M pueden causar apagones de radio breves; las X son las más poderosas. Una llamarada sola no garantiza auroras — lo importante es si va acompañada de una CME dirigida hacia la Tierra.' },
    { question: '¿Qué es una CME (eyección de masa coronal)?', answer: 'Una eyección de masa coronal es una erupción masiva de plasma magnetizado de la corona solar, liberando hasta mil millones de toneladas de material solar a velocidades de 250–3.000 km/s. Cuando una CME dirigida a la Tierra llega — típicamente 1–4 días después — comprime la magnetosfera y desencadena los eventos de aurora más espectaculares del ciclo solar.' },
    { question: '¿Qué es la componente Bz y por qué importa para las auroras?', answer: 'Bz es la componente norte-sur del Campo Magnético Interplanetario, medida por los satélites DSCOVR y ACE en el punto L1. Cuando Bz es negativo, la reconexión magnética permite que partículas solares fluyan hacia la atmósfera polar. Un Bz sostenido por debajo de −10 nT suele dar 15–45 minutos de aviso antes de que suba el índice Kp.' },
    { question: '¿Qué es la velocidad del viento solar y cómo afecta a las auroras?', answer: 'El viento solar fluye a velocidades típicas de 300–500 km/s en condiciones tranquilas. Cuando supera 500 km/s, comprime la magnetosfera; por encima de 700 km/s se asocia con actividad geomagnética intensa. Las corrientes de alta velocidad de agujeros coronales son predecibles hasta 27 días antes. Los eventos de aurora más potentes combinan alta velocidad con Bz negativo.' },
    { question: '¿Qué es el óvalo auroral?', answer: 'El óvalo auroral es una zona en forma de anillo alrededor de cada polo magnético donde la aurora es más activa, centrada a unos 65–70° de latitud geomagnética en condiciones tranquilas. Durante las tormentas se expande hacia el ecuador — una tormenta Kp 9 puede empujarlo hasta los subtrópicos. El modelo OVATION de NOAA muestra su posición en tiempo real en el globo 3D de The Storm Watcher.' },
    { question: '¿Por qué la aurora aparece verde, roja o morada?', answer: 'Los colores de la aurora dependen del gas atmosférico que se excita y a qué altitud. El verde — el más común — viene del oxígeno a 100–150 km. El rojo auroral viene del oxígeno a más de 200 km. Los tonos azulados y morados provienen del nitrógeno por debajo de los 100 km. Durante tormentas intensas varias capas se excitan simultáneamente produciendo coloridos displays.' },
    { question: '¿Cuál es la mejor época del año para ver las auroras boreales?', answer: 'La aurora es activa todo el año, pero la visibilidad requiere oscuridad — haciendo que de septiembre a marzo sea la temporada principal. Los equinoccios de otoño y primavera son estadísticamente más activos debido al efecto Russell–McPherron. El verano es problemático en latitudes altas por el sol de medianoche. Octubre a febrero ofrece la mejor combinación.' },
    { question: '¿A qué hora de la noche es mejor observar auroras?', answer: 'La actividad auroral alcanza su pico alrededor de la medianoche magnética local — típicamente entre las 22:00 y las 2:00 — cuando las líneas de campo conectan más directamente con la zona auroral. Configura una alerta de umbral Kp en The Storm Watcher para ser notificado exactamente cuando las condiciones sean óptimas.' },
    { question: '¿Cómo recibo alertas de auroras en mi teléfono?', answer: 'The Storm Watcher ofrece notificaciones push gratuitas — configura tu umbral Kp en la página de Ajustes (p. ej., "avísame cuando Kp ≥ 5") y serás notificado en el momento en que los datos de NOAA superen ese nivel. La alerta incluye Kp actual, Bz, velocidad del viento solar y nubosidad estimada en tu ubicación guardada.' },
    { question: '¿Se pueden ver auroras en Escocia / Reino Unido?', answer: 'Sí — Escocia es uno de los mejores destinos para auroras fuera de Escandinavia. Las Highlands escocesas, Orkney y Shetland están a 57–60°N, donde Kp 4–5 suele ser suficiente en una noche clara y oscura. Con tormentas más fuertes (Kp 6+), las auroras son visibles en el norte de Inglaterra, y con Kp 8+, incluso desde el sur de Inglaterra.' },
    { question: '¿Se pueden ver auroras en Alemania / Europa Central?', answer: 'Los avistamientos en Alemania, Austria, Suiza, Polonia y países vecinos son menos frecuentes pero totalmente posibles durante tormentas geomagnéticas fuertes. A 47–54°N se necesita típicamente Kp 7–8, y Kp 9 puede traer auroras hasta el Mediterráneo — demostrado espectacularmente en mayo de 2024. Configura una alerta en The Storm Watcher y localiza un lugar oscuro cercano.' },
  ],
};

export default es;
