import type { FaqLangContent } from '../faqContent';

const fi: FaqLangContent = {
  subtitle: 'Kaikki mitä sinun täytyy tietää revontulista, avaruussäästä ja niiden katsomisesta.',
  categories: {
    'Aurora Basics': 'Revontulten perusteet',
    'Kp Index': 'Kp-indeksi',
    'Solar Wind': 'Aurinkotuuli',
    'Viewing Tips': 'Katseluvinkkejä',
    'Space Weather': 'Avaruussää',
    'Moon & Darkness': 'Kuu ja pimeys',
    'Location Guides': 'Paikkaoppaat',
  },
  items: [
    { question: 'Mikä on Aurora Borealis (Revontulet)?', answer: 'Aurora Borealis eli revontulet on luonnollinen valonnäytös, jonka aiheuttavat Auringosta tulevat varautuneet hiukkaset törmätessään maapallon ilmakehän kaasuihin. Kun aurinkotuulen hiukkaset vuorovaikuttavat happi- ja typpimolekyylien kanssa, ne emittoivat valofotoneita — luoden hämmästyttävät vihreät, violetit, punaiset ja siniset valoverhoт, jotka näkyvät napapiirin tuntumassa.' },
    { question: 'Mikä ero on Aurora Borealiksella ja Aurora Australiksella?', answer: 'Aurora Borealis (revontulet) esiintyy pohjoisella pallonpuoliskolla, kun taas Aurora Australis (eteläiset revontulet) esiintyy eteläisellä pallonpuoliskolla. Molemmat aiheutuvat samoista auringon ilmiöistä — Auringosta tulevista varautuneista hiukkasista, jotka vuorovaikuttavat maapallon magneettikenttään. Ne esiintyvät usein samanaikaisesti molemmilla navoilla peilikuvinaan.' },
    { question: 'Mikä on aurinkotuuli ja miten se vaikuttaa Maahan?', answer: 'Aurinkotuuli on jatkuva varautuneiden hiukkasten (pääasiassa protonien ja elektronien) virta, joka virtaa Auringosta nopeuksilla 300–800 km/s. Kun nopeus ylittää 500 km/s, se puristaa Maan magnetosfääriä ja voi laukaista geomagneettisia myrskyjä. Koronaaliset massapurkaukset (CME:t) aiheuttavat dramaattisimmat revontulet.' },
    { question: 'Mitkä ovat parhaat olosuhteet revontulien katsomiseen?', answer: 'Parasta revontulihavainnointia varten: (1) Pimeä taivas — kauas kaupunkivaloista, (2) Kirkas taivas — pilvisyys alle 30%, (3) Aktiiviset geomagneettisет olosuhteet — Kp 4+, (4) Pimeä kuu — uusikuu tai sirppi, (5) Aika — yleensä klo 22–02 paikallista aikaa, (6) Vuodenaika — syyskuusta maaliskuuhun.' },
    { question: 'Miten valokuvaan revontulia?', answer: 'Kamera-asetukset revontulivalokuvaukseen: (1) Käytä kolmijalkaa — valotusajat 5–25 sekuntia, (2) Laajakulmaobjektiivi f/2.8 tai valoisampi, (3) ISO 1600–3200, (4) Suljinnopeus 8–15 sekuntia, (5) Manuaalitarkennus äärettömään, (6) Kuvaa RAW-muodossa. iPhone 15+ ja Samsung S24+ toimivat erinomaisesti yötilassa.' },
    { question: 'Mikä on Aurinkosykli ja milloin revontulia on parhaiten?', answer: 'Aurinko seuraa noin 11 vuoden aktiivisuussykliä. Auringon maksimin aikana auringonpilkut, purkaukset ja CME:t ovat yleisimpiä. Olemme tällä hetkellä lähellä auringonsyklin 25 maksimia (2024–2026) — yksi parhaista ajanjaksoista revontulien metsästykseen yli vuosikymmeneen.' },
    { question: 'Vaikuttaako Kuu revontulien näkyvyyteen?', answer: 'Kyllä — kirkas täysikuu himmertää heikompia revontulia, kuten valosaaste. Paras havainnointiaika on uusikuun aikana tai muutama päivä sen jälkeen, kun taivas on pimein. Hyvin voimakkaat revontulet (Kp 7+) voivat kuitenkin näkyä jopa täysikuun aikana. Tarkistuslistamme ottaa automaattisesti huomioon nykyisen kuunvaiheen.' },
    { question: 'Mikä on Kp-indeksi ja mitä se tarkoittaa revontulien kannalta?', answer: 'Kp-indeksi on globaali 0–9-asteikko maapallon magneettikentän häiriöille, jonka NOAA päivittää kolmen tunnin välein. Kp 0–2 tarkoittaa, että aktiivisuus rajoittuu napapiirille, kun taas Kp 5+ siirtää revontulia etelään — mahdollisesti Skotlantiin, Etelä-Kanadaan tai jopa Keski-Eurooppaan. Tiedot näkyvät The Storm Watcherin kojelaudalla.' },
    { question: 'Mikä Kp-taso tarvitaan revontulien näkemiseen?', answer: 'Tarvittava Kp riippuu leveysasteesta. 65°N:ssä (Pohjois-Skandinavia, Islanti, Alaska) riittää usein Kp 1–2. 60°N:ssä (Etelä-Norja, Helsinki) tyypillisesti Kp 3–4. 55°N:ssä (Skotlanti, Tukholma) tarvitaan Kp 5–6. 50°N:ssä (Keski-Saksa, Praha) vaaditaan Kp 7–8. Nämä kynnysarvot edellyttävät täysin pimeää ja kirkasta taivasta.' },
    { question: 'Mikä ero on Kp 5:llä, Kp 7:llä ja Kp 9:llä?', answer: 'Kp 5 (G1-myrsky) on minimiraja — revontulet näkyvät Etelä-Skandinaviassa ja Skotlannissa vaaleana kaarena. Kp 7 (G3-myrsky) tuo eloisan revontulinäytöksen Saksaan ja Pohjois-USA:han. Kp 9 (G5-myrsky) on enimmäistaso — viimeisin esimerkki oli toukokuu 2024, jolloin revontulia havaittiin Espanjassa, Italiassa, Texasissa ja Floridassa.' },
    { question: 'Mikä on geomagneettinen myrsky ja miten sitä mitataan?', answer: 'Geomagneettinen myrsky on laajamittainen häiriö maapallon magnetosfäärissä, jonka aiheuttaa voimistunut aurinkotuuli — yleensä CME:n tai koronaaliaukosta tulevan nopean virran jälkeen. NOAA luokittelee myrskyt G-asteikolla: G1 (Kp 5) – G5 (Kp 9). Myrskyt voivat häiritä satelliitteja, GPS:ää, lyhytaaltoradiota ja sähköverkkoja.' },
    { question: 'Mikä on röntgen-auringonpurkaus ja mitä se tarkoittaa?', answer: 'Auringonpurkaukset ovat intensiivisiä säteilyräjähdyksiä, jotka luokitellaan röntgenhuipun mukaan: A, B, C, M ja X (jokainen luokka on 10× voimakkaampi). C-luokka on pieni; M voi aiheuttaa lyhyitä radiokatkoksia; X on voimakkain. Pelkkä purkaus ei takaa revontulia — ratkaisevaa on, seuraaako sitä maahan suuntautuva CME.' },
    { question: 'Mikä on CME (koronaalinen massapurkaus)?', answer: 'Koronaalinen massapurkaus on massiivinen magneettisen plasman räjähdys Auringon koroonasta, joka vapauttaa jopa miljardin tonnin aurinkomateriaalia nopeuksilla 250–3 000 km/s. Kun maahan suuntautuva CME saapuu — yleensä 1–4 päivää purkauksen jälkeen — se puristaa magnetosfääriä ja laukaisee näyttävimmät revontulitapahtumat.' },
    { question: 'Mikä on Bz-komponentti ja miksi se on tärkeä revontulille?', answer: 'Bz on interplanetaarisen magneettikentän pohjois-etelä-komponentti, jota mitataan DSCOVR- ja ACE-satelliiteilla L1-pisteessä. Kun Bz on negatiivinen, magneettinen rekytkentä sallii varautuneiden hiukkasten virrata napaatmosfääriin. Jatkuva Bz alle −10 nT antaa yleensä 15–45 minuutin varoituksen ennen Kp-indeksin nousua.' },
    { question: 'Mikä on aurinkotuulen nopeus ja miten se vaikuttaa revontuliin?', answer: 'Aurinkotuuli virtaa tyypillisillä nopeuksilla 300–500 km/s rauhallisissa olosuhteissa. Yli 500 km/s se puristaa magnetosfääriä; yli 700 km/s se liittyy voimakkaaseen geomagneettiseen aktiivisuuteen. Koronaaliaukoista tulevat nopeat virrat ovat usein ennustettavissa 27 päivää etukäteen.' },
    { question: 'Mikä on revontuliovaali?', answer: 'Revontuliovaali on rengasmainen vyöhyke jokaisen magneettinavan ympärillä, jossa revontulet ovat aktiivisimpia, noin 65–70° geomagneettisella leveysasteella rauhallisissa olosuhteissa. Geomagneettisten myrskyjen aikana ovaali laajenee päiväntasaajaa kohti — Kp 9 -myrsky voi siirtää sen subtropiikkiin. NOAA OVATION näyttää sen reaaliajassa The Storm Watcherin 3D-maapallolla.' },
    { question: 'Miksi revontulet näyttävät vihreiltä, punaisilta tai violeteiltä?', answer: 'Revontulten värit määräytyvät sen mukaan, mikä ilmakehän kaasu virittyy ja millä korkeudella. Vihreä — yleisin väri — tulee hapesta 100–150 km korkeudella. Punainen tulee hapesta yli 200 km korkeudelta. Siniset ja violetit sävyt tulevat typestä alle 100 km korkeudelta. Voimakkaiden myrskyjen aikana useita kerroksia virittyy samanaikaisesti.' },
    { question: 'Mikä on paras vuodenaika revontulten katseluun?', answer: 'Revontulet ovat aktiivisia ympäri vuoden, mutta näkyvyys vaatii pimeyttä — mikä tekee syyskuusta maaliskuuhun pääsesongin. Syys- ja kevätpäiväntasaukset ovat tilastollisesti aktiivisempia Russell–McPherron-ilmiön vuoksi. Kesä on ongelmallinen korkeilla leveysasteilla keskiyön auringon takia. Lokakuu–helmikuu tarjoaa parhaan yhdistelmän.' },
    { question: 'Mihin aikaan yöstä revontulia on parhaiten?', answer: 'Revontulten aktiivisuus huipentuu paikallisen magneettisen puoliyön aikaan — yleensä klo 22–02 — kun kenttäviivat ylhäällä yhdistyvät suoraan revontulialueeseen. Aseta Kp-kynnysvaroitus The Storm Watcheriin, niin saat ilmoituksen juuri oikeaan aikaan.' },
    { question: 'Miten saan revontuli-ilmoituksia puhelimeeni?', answer: 'The Storm Watcher tarjoaa ilmaisia push-ilmoituksia — aseta Kp-kynnys Asetukset-sivulla (esim. "ilmoita, kun Kp ≥ 5") ja saat ilmoituksen heti, kun NOAA:n data ylittää sen tason. Ilmoitus sisältää nykyisen Kp:n, Bz:n, aurinkotuulen nopeuden ja pilvisyyden tallennetussa sijainnissasi.' },
    { question: 'Voinko nähdä revontulet Skotlannissa / Isossa-Britanniassa?', answer: 'Kyllä — Skotlanti on yksi parhaista revontulten katselupaikoista Skandinavian ulkopuolella. Skotlannin ylänkömaa, Orkney ja Shetland sijaitsevat 57–60°N, jossa Kp 4–5 riittää yleensä kirkkaana, pimeänä yönä. Voimakkaampien myrskyjen aikana (Kp 6+) revontulet näkyvät säännöllisesti Pohjois-Englannissa, ja Kp 8+ jopa Etelä-Englannissa.' },
    { question: 'Voinko nähdä revontulet Saksassa / Keski-Euroopassa?', answer: 'Revontulihavainnot Saksassa, Itävallassa, Sveitsissä, Puolassa ja naapurimaissa ovat harvinaisempia, mutta täysin mahdollisia voimakkaiden geomagneettisten myrskyjen aikana. 47–54°N:ssä tarvitaan yleensä Kp 7–8, ja Kp 9 voi tuoda revontulet Välimerellekin — dramaattisesti osoitettu G5-myrskyllä toukokuussa 2024. Aseta stormhälytys The Storm Watcheriin.' },
  ],
};

export default fi;
