import type { FaqLangContent } from '../faqContent';

const fr: FaqLangContent = {
  subtitle: 'Tout ce que vous devez savoir sur les aurores boréales, la météo spatiale et comment les observer.',
  categories: {
    'Aurora Basics': 'Les bases de l\'aurore',
    'Kp Index': 'Indice Kp',
    'Solar Wind': 'Vent solaire',
    'Viewing Tips': 'Conseils d\'observation',
    'Space Weather': 'Météo spatiale',
    'Moon & Darkness': 'Lune et obscurité',
    'Location Guides': 'Guides de lieux',
  },
  items: [
    { question: 'Qu\'est-ce que l\'Aurora Borealis (aurores boréales) ?', answer: 'L\'Aurora Borealis, ou aurores boréales, est un phénomène lumineux naturel provoqué par des particules chargées du Soleil qui entrent en collision avec les gaz de l\'atmosphère terrestre. Quand les particules du vent solaire interagissent avec les molécules d\'oxygène et d\'azote, elles émettent des photons — créant les saisissants rideaux de lumière verte, violette, rouge et bleue visibles près des régions polaires.' },
    { question: 'Quelle est la différence entre l\'Aurora Borealis et l\'Aurora Australis ?', answer: 'L\'Aurora Borealis (aurores boréales) se produit dans l\'hémisphère nord, tandis que l\'Aurora Australis (aurores australes) a lieu dans l\'hémisphère sud. Toutes deux résultent du même phénomène solaire — des particules chargées interagissant avec le champ magnétique terrestre. Elles apparaissent souvent simultanément aux deux pôles en miroir.' },
    { question: 'Qu\'est-ce que le vent solaire et comment affecte-t-il la Terre ?', answer: 'Le vent solaire est un flux continu de particules chargées (principalement des protons et des électrons) s\'écoulant du Soleil à des vitesses de 300–800 km/s. Quand la vitesse dépasse 500 km/s, il comprime la magnétosphère terrestre et peut déclencher des tempêtes géomagnétiques. Les Éjections de Masse Coronale (CME) causent les événements d\'aurores les plus dramatiques.' },
    { question: 'Quelles sont les meilleures conditions pour observer les aurores boréales ?', answer: 'Pour la meilleure observation : (1) Ciel sombre, loin des lumières urbaines, (2) Ciel dégagé avec moins de 30% de nuages, (3) Conditions géomagnétiques actives — Kp 4+, (4) Lune sombre — nouvelle lune ou croissant, (5) Heure — entre 22h et 2h du matin, (6) Saison — de septembre à mars. Notre liste de contrôle de visibilité combine tous ces facteurs en temps réel.' },
    { question: 'Comment photographier les aurores boréales ?', answer: 'Réglages pour photographier les aurores : (1) Utilisez un trépied avec des expositions de 5–25 secondes, (2) Objectif grand-angle f/2.8 ou plus lumineux, (3) ISO 1600–3200, (4) Vitesse d\'obturation 8–15 secondes, (5) Mise au point manuelle sur l\'infini, (6) Prenez en RAW. Conseil smartphone : les iPhone 15+ et Samsung S24+ ont d\'excellents modes nuit qui capturent les aurores automatiquement.' },
    { question: 'Qu\'est-ce que le Cycle Solaire et quand est le meilleur moment pour les aurores ?', answer: 'Le Soleil suit un cycle d\'activité d\'environ 11 ans. Pendant le Maximum Solaire, les taches solaires, les éruptions et les CME sont les plus fréquents. Nous sommes actuellement près du maximum du Cycle Solaire 25 (2024–2026), ce qui en fait l\'une des meilleures périodes pour chasser les aurores depuis plus d\'une décennie.' },
    { question: 'La Lune affecte-t-elle la visibilité des aurores ?', answer: 'Oui — une pleine lune brillante atténue les aurores plus faibles, à l\'instar de la pollution lumineuse. La meilleure observation se produit lors de la nouvelle lune ou quelques jours après, quand les cieux sont les plus sombres. Les aurores très fortes (Kp 7+) restent visibles même sous une pleine lune. Notre liste de contrôle tient compte automatiquement de la phase lunaire.' },
    { question: 'Qu\'est-ce que l\'indice Kp et que signifie-t-il pour observer les aurores ?', answer: 'L\'indice Kp (Planetarische Kennziffer) est une échelle mondiale de 0–9 mesurant les perturbations du champ magnétique terrestre, mise à jour toutes les 3 heures par la NOAA. Kp 0–2 signifie que l\'activité est confinée près des régions polaires, tandis que Kp 5+ pousse les aurores vers le sud — jusqu\'en Écosse, au sud du Canada, voire en Europe centrale. Les données en direct sont affichées sur le tableau de bord de The Storm Watcher.' },
    { question: 'Quel niveau de Kp faut-il pour voir les aurores ?', answer: 'Le Kp requis dépend de votre latitude. À 65°N (Scandinavie du Nord, Islande, Alaska), Kp 1–2 suffit souvent. À 60°N (sud de la Norvège, Helsinki), Kp 3–4 est typique. À 55°N (Écosse, Stockholm), il faut généralement Kp 5–6. À 50°N (centre de l\'Allemagne, Prague, nord de la France), Kp 7–8 est nécessaire. Ces seuils supposent un ciel complètement sombre et dégagé.' },
    { question: 'Quelle est la différence entre Kp 5, Kp 7 et Kp 9 ?', answer: 'Kp 5 (tempête G1 mineure) est le seuil d\'entrée — l\'aurore devient visible en Scandinavie du Sud et en Écosse, souvent comme un arc pâle à l\'horizon. Kp 7 (tempête G3 forte) amène des aurores vives en Allemagne et dans le nord des États-Unis. Kp 9 (tempête G5 extrême) est le niveau maximum — le dernier exemple remonte à mai 2024, avec des aurores observées en Espagne, Italie, Texas et Floride.' },
    { question: 'Qu\'est-ce qu\'une tempête géomagnétique et comment est-elle mesurée ?', answer: 'Une tempête géomagnétique est une perturbation à grande échelle de la magnétosphère causée par un vent solaire renforcé — typiquement après une CME ou des courants rapides de trous coronaux. La NOAA classe les tempêtes sur l\'échelle G : G1 (Kp 5) à G5 (Kp 9). Les tempêtes peuvent perturber les satellites, le GPS, la radio HF et les réseaux électriques.' },
    { question: 'Qu\'est-ce qu\'une éruption solaire en rayons X et que signifie-t-elle ?', answer: 'Les éruptions solaires sont des explosions de rayonnement classées par émission de rayons X : A, B, C, M et X (chaque classe est 10 fois plus forte). Les éruptions de classe C sont mineures ; M peut causer des pannes radio brèves ; X sont les plus puissantes. Une éruption seule ne garantit pas d\'aurores — l\'essentiel est de savoir si elle est accompagnée d\'une CME dirigée vers la Terre.' },
    { question: 'Qu\'est-ce qu\'une CME (éjection de masse coronale) ?', answer: 'Une éjection de masse coronale est une éruption massive de plasma magnétisé de la couronne solaire, libérant jusqu\'à un milliard de tonnes de matière solaire à des vitesses de 250–3 000 km/s. Quand une CME arrive — typiquement 1–4 jours après l\'éruption — elle comprime la magnétosphère, fait monter brusquement le Kp et déclenche les événements d\'aurores les plus spectaculaires du cycle.' },
    { question: 'Qu\'est-ce que la composante Bz et pourquoi est-elle importante pour les aurores ?', answer: 'Le Bz est la composante nord-sud du Champ Magnétique Interplanétaire, mesuré par les satellites DSCOVR et ACE au point L1. Quand Bz est négatif, la reconnexion magnétique permet aux particules solaires de pénétrer dans l\'atmosphère polaire. Un Bz soutenu en dessous de −10 nT donne souvent 15–45 minutes d\'avertissement avant la montée de l\'indice Kp.' },
    { question: 'Qu\'est-ce que la vitesse du vent solaire et comment affecte-t-elle les aurores ?', answer: 'Le vent solaire s\'écoule à des vitesses typiques de 300–500 km/s en conditions calmes. Au-delà de 500 km/s, il comprime la magnétosphère ; au-delà de 700 km/s, il est associé à une forte activité géomagnétique. Les courants rapides des trous coronaux sont souvent prévisibles jusqu\'à 27 jours à l\'avance.' },
    { question: 'Qu\'est-ce que l\'ovale auroral ?', answer: 'L\'ovale auroral est une zone en forme d\'anneau autour de chaque pôle magnétique où l\'aurore est la plus régulièrement active, centrée à environ 65–70° de latitude géomagnétique. Pendant les tempêtes, il s\'étend vers l\'équateur — une tempête Kp 9 peut le pousser jusqu\'aux subtropiques. Le modèle OVATION de la NOAA affiche sa position en temps réel sur le globe 3D de The Storm Watcher.' },
    { question: 'Pourquoi l\'aurore apparaît-elle en vert, rouge ou violet ?', answer: 'Les couleurs des aurores dépendent du gaz atmosphérique excité et de l\'altitude. Le vert — la couleur la plus courante — vient de l\'oxygène à 100–150 km. Le rouge provient de l\'oxygène au-dessus de 200 km. Les teintes bleues et violettes viennent de l\'azote en dessous de 100 km. Lors des tempêtes intenses, plusieurs couches sont excitées simultanément.' },
    { question: 'Quelle est la meilleure période de l\'année pour observer les aurores boréales ?', answer: 'L\'aurore est active toute l\'année, mais la visibilité nécessite l\'obscurité — faisant de septembre à mars la saison principale. Les équinoxes d\'automne et de printemps sont statistiquement plus actifs grâce à l\'effet Russell–McPherron. L\'été est problématique aux hautes latitudes en raison du soleil de minuit. Octobre à février offre la meilleure combinaison.' },
    { question: 'À quelle heure de la nuit est-il le mieux pour observer les aurores ?', answer: 'L\'activité aurorale atteint son maximum autour de minuit magnétique local — typiquement entre 22h et 2h — quand les lignes de champ sont le plus directement connectées à la zone aurorale. Configurez une alerte de seuil Kp sur The Storm Watcher pour être notifié exactement au bon moment.' },
    { question: 'Comment recevoir des alertes d\'aurores sur mon téléphone ?', answer: 'The Storm Watcher propose des notifications push gratuites — définissez votre seuil Kp dans la page Paramètres (ex. : "alerte quand Kp ≥ 5") et vous serez notifié dès que les données NOAA dépassent ce niveau. L\'alerte inclut le Kp actuel, le Bz, la vitesse du vent solaire et la couverture nuageuse estimée à votre emplacement sauvegardé.' },
    { question: 'Peut-on voir les aurores en Écosse / au Royaume-Uni ?', answer: 'Oui — l\'Écosse est l\'une des meilleures destinations pour les aurores en dehors de la Scandinavie. Les Highlands, les Orcades et les Shetlands se trouvent à 57–60°N, où Kp 4–5 suffit généralement. Lors de tempêtes plus fortes (Kp 6+), les aurores sont régulièrement visibles dans le nord de l\'Angleterre, et à Kp 8+, même depuis le sud de l\'Angleterre.' },
    { question: 'Peut-on voir les aurores en Allemagne / en Europe centrale ?', answer: 'Les observations en Allemagne, Autriche, Suisse, Pologne et pays voisins sont plus rares mais tout à fait possibles lors de fortes tempêtes géomagnétiques. À 47–54°N, Kp 7–8 est généralement nécessaire, et Kp 9 peut amener les aurores jusqu\'à la Méditerranée — spectaculairement démontré lors de la tempête G5 de mai 2024. Configurez une alerte sur The Storm Watcher et repérez un site sombre.' },
  ],
};

export default fr;
