import type { FaqLangContent } from '../faqContent';

const is: FaqLangContent = {
  subtitle: 'Allt sem þú þarft að vita um norðurljós, geimveður og hvernig á að sjá þau.',
  categories: {
    'Aurora Basics': 'Norðurljós – grunnatriðin',
    'Kp Index': 'Kp-vísitala',
    'Solar Wind': 'Sólvindur',
    'Viewing Tips': 'Ráð til að sjá norðurljósin',
    'Space Weather': 'Geimveður',
    'Moon & Darkness': 'Tungl og myrkur',
    'Location Guides': 'Staðarleiðbeiningar',
  },
  items: [
    { question: 'Hvað er Aurora Borealis (Norðurljós)?', answer: 'Aurora Borealis, eða norðurljós, er náttúrulegt ljósfyrirbæri af völdum hlaðinna agna frá Sólinni sem rekast á gös í lofthjúpi jarðar. Þegar agnir sólvindsins hafa samskipti við súrefnis- og köfnunarefnissameind gefa þær frá sér ljóseinda — og skapa þar með þær glæsilegu grænar, fjólubláar, rauðar og bláar ljósfortjaldirnar sem sjást nær heimsskautssvæðunum.' },
    { question: 'Hver er munurinn á Aurora Borealis og Aurora Australis?', answer: 'Aurora Borealis (norðurljós) kemur fram á norðurhveli jarðar, en Aurora Australis (suðurljós) á suðurhveli. Báðar eru af völdum sömu sólarfyrirbæra — hlaðnum agnum sem hafa samskipti við segulsvið jarðar. Þær birtast oft samtímis á báðum skautunum sem spegilmyndir.' },
    { question: 'Hvað er sólvindur og hvernig hefur hann áhrif á jörðina?', answer: 'Sólvindur er stöðugur straumur hlaðinna agna (aðallega próton og rafeinda) sem streymir frá Sólinni á hraða 300–800 km/s. Þegar hraðinn fer yfir 500 km/s þjappar hann segulhjúp jarðar og getur valdið geomagnetísk stormum. Kórónamassamyntingar (CME) valda dramatísku norðurljósaatburðunum.' },
    { question: 'Hverjar eru bestu aðstæður til að sjá norðurljósin?', answer: 'Til að sjá norðurljós sem best: (1) Dökkt himinn — fjarri borgarljósum, (2) Skýlaus himinn — skýjahula undir 30%, (3) Virk geomagnetísk skilyrði — Kp 4+, (4) Dökkt tungl — nýmáni eða sigð, (5) Tími — venjulega milli kl. 22 og 02, (6) Árstíð — september til mars.' },
    { question: 'Hvernig ljósmynda ég norðurljósin?', answer: 'Myndavélastillingar fyrir norðurljósmyndatöku: (1) Notaðu þrífót með 5–25 sekúndna lýsingu, (2) Breiðhornslins f/2.8 eða ljósara, (3) ISO 1600–3200, (4) Skjáhraði 8–15 sekúndur, (5) Handstýring á óendanlegt, (6) Myndaðu í RAW. iPhone 15+ og Samsung S24+ hafa framúrskarandi næturham.' },
    { question: 'Hvað er Sólhringurinn og hvenær er best fyrir norðurljós?', answer: 'Sólin fylgir um það bil 11 ára virkniferli. Í hámarki sólarinnar eru sólblettir, sólgos og CME tíðust. Við erum nú nærri hámarki sólhrings 25 (2024–2026) — eitt besta tímabilið til að veiða norðurljós í meira en áratug.' },
    { question: 'Hefur tunglið áhrif á sjón norðurljósanna?', answer: 'Já — bjart fullt tungl þvær út veikari norðurljós, líkt og ljósmengun. Bestur tími er við nýmána eða nokkrum dögum á eftir, þegar himinninn er myrkastur. Mjög sterk norðurljós (Kp 7+) má þó sjá jafnvel við fulla tunglskin. Gátlistinn okkar tekur sjálfkrafa tillit til núverandi tunglsfasa.' },
    { question: 'Hvað er Kp-vísitalan og hvað þýðir hún fyrir norðurljósin?', answer: 'Kp-vísitalan er altækur 0–9 kvarði fyrir truflanir í segulsviði jarðar, uppfærður af NOAA á 3 tíma fresti. Kp 0–2 þýðir virkni takmörkuð við heimsskautssvæðin, en Kp 5+ þrýstir norðurljósunum lengra suður — hugsanlega til Skotlands, suður-Kanada eða jafnvel Mið-Evrópu. Gögn eru sýnd á mæliborði The Storm Watcher.' },
    { question: 'Hvaða Kp þarf ég til að sjá norðurljósin?', answer: 'Nauðsynlegt Kp fer eftir breiddargráðu. Við 65°N (Norður-Skandinavía, Ísland, Alaska) nægir oft Kp 1–2. Við 60°N (Suður-Noregur, Helsinki) er Kp 3–4 dæmigert. Við 55°N (Skotland, Stokkhólmur) þarf Kp 5–6. Við 50°N (Mið-Þýskaland, Prag) þarf Kp 7–8.' },
    { question: 'Hver er munurinn á Kp 5, Kp 7 og Kp 9?', answer: 'Kp 5 (G1 storm) er lágmarksþröskuldurinn — norðurljós verða sýnileg í Suður-Skandinavíu og Skotlandi sem föl bogi. Kp 7 (G3 storm) flytur lifleg norðurljós til Þýskalands og norðurríkja Bandaríkjanna. Kp 9 (G5 storm) er hámarksstigið — síðasta dæmið var í maí 2024, þegar norðurljós sáust yfir Spáni, Ítalíu, Texas og Flórída.' },
    { question: 'Hvað er geomagnetískt storm og hvernig er það mælt?', answer: 'Geomagnetískt storm er umfangsmikil truflun á segulhjúp jarðar af völdum þéttaðs sólvinds — venjulega eftir CME eða hraðstraum úr kórónaugu. NOAA flokkar storm á G-kvarðanum: G1 (Kp 5) til G5 (Kp 9). Storm geta truflað gervihnetti, GPS, KV-útvarpssamband og rafmagnsnet.' },
    { question: 'Hvað er röntgen-sólgos og hvað þýðir það?', answer: 'Sólgos eru kröftug geislunarbrot, flokkuð eftir röntgenhámarki: A, B, C, M og X (hvert stig er 10× sterkara). C-flokkur er lítill; M getur valdið stuttum útvarpstruflunum; X er öflugastur. Eitt gos ein og sér tryggir ekki norðurljós — það sem skiptir máli er hvort það fylgir jarðbeint CME.' },
    { question: 'Hvað er CME (kórónamassamyntun)?', answer: 'Kórónamassamyntun er geysilegt sprenging af segulmagnaðri plasma úr kórón sólarinnar, sem losar allt að milljarð tonna af sólefni á hraða 250–3 000 km/s. Þegar jarðbeint CME berst — venjulega 1–4 dögum eftir gosið — þjappar það segulhjúpinn og hvetur til glæsilegrustu norðurljósaatburðanna.' },
    { question: 'Hvað er Bz-þátturinn og hvers vegna skiptir hann máli fyrir norðurljós?', answer: 'Bz er norður-suður-þáttur reikistjörnumagnetsvæðisins, mældur af DSCOVR- og ACE-gervihnöttum við L1-punktinn. Þegar Bz er neikvætt gerir segultenging hlaðnum agnum kleift að streyma inn í heimsskautsatmósferuna. Viðvarandi Bz undir −10 nT gefur venjulega 15–45 mínútna fyrirvara.' },
    { question: 'Hvað er hraði sólvindsins og hvernig hefur hann áhrif á norðurljós?', answer: 'Sólvindur streymir á dæmigerðum hraða 300–500 km/s við rólegar aðstæður. Yfir 500 km/s þjappar hann segulhjúpinn; yfir 700 km/s tengist hann sterkri geomagnetískri virkni. Hraðstraumar úr kórónaaugum eru oft fyrirsjáanlegir allt að 27 dögum fyrirfram.' },
    { question: 'Hvað er norðurljósasneiðin?', answer: 'Norðurljósasneiðin er hringform svæði í kringum hvort segulskaut þar sem norðurljós eru virkust, miðuð við um 65–70° geomagnetíska breiddargráðu við rólegar aðstæður. Í stormum þenst sneiðin í átt að miðbaug — Kp 9 storm getur þrýst henni allt á subtrópar. NOAA OVATION-líkanið sýnir hana í rauntíma á 3D-hnettinum hjá The Storm Watcher.' },
    { question: 'Hvers vegna líta norðurljósin grœn, rauð eða fjólublá út?', answer: 'Litir norðurljósanna ráðast af því hvaða lofttegundir eru orkuðar og á hvaða hæð. Grænt — algengasta liturinn — kemur frá súrefni á 100–150 km hæð. Rautt kemur frá súrefni yfir 200 km. Blár og fjólublár koma frá köfnunarefni undir 100 km. Við kröftug stormur eru mörg lög orkuð samtímis.' },
    { question: 'Hvenær á árinu er best að sjá norðurljósin?', answer: 'Norðurljós eru virk allt árið, en sjón krefst myrkurs — sem gerir september til mars að aðaltímabilinu. Haust- og vorstöðupunktar eru tölfræðilega virkari vegna Russell–McPherron-áhrifanna. Sumarið er vandræðalegt á háum breiddargráðum vegna miðnætursólar. Október til febrúar gefur besta samsetninguna.' },
    { question: 'Hvenær á nóttinni er best að horfa á norðurljós?', answer: 'Norðurljósavirkni nær hámarki í kringum staðbundinn segulmidnætti — venjulega milli kl. 22 og 02 — þegar svæðislínurnar yfirhaus tengjast beint við norðurljósasvæðið. Settu upp Kp-þröskuldsskilaboð á The Storm Watcher til að fá tilkynningu á nákvæmlega réttum tíma.' },
    { question: 'Hvernig fæ ég norðurljósaviðvaranir í símann?', answer: 'The Storm Watcher býður upp á ókeypis push-tilkynningar — stilltu Kp-þröskuldinn á Stillingar-síðunni (t.d. "tilkynna mér þegar Kp ≥ 5") og þú færð tilkynningu um leið og NOAA-gögn fara yfir það stig. Tilkynningin inniheldur núverandi Kp, Bz, hraða sólvinds og skýjahulu á vistaðri staðsetningu þinni.' },
    { question: 'Get ég séð norðurljósin í Skotlandi / Bretlandi?', answer: 'Já — Skotland er eitt besta norðurljósaáfangastaðanna utan Skandinavíu. Skotska hálendið, Orkneyjar og Hjaltland liggja við 57–60°N þar sem Kp 4–5 nægir venjulega á skýrri, myrkri nóttu. Í sterkari stormum (Kp 6+) eru norðurljós reglulega sýnileg í Norður-Englandi, og við Kp 8+ jafnvel frá Suður-Englandi.' },
    { question: 'Get ég séð norðurljósin í Þýskalandi / Mið-Evrópu?', answer: 'Norðurljósaathuganir í Þýskalandi, Austurríki, Sviss, Póllandi og nágrannalöndum eru sjaldgæfari en fullkomlega mögulegar við sterk geomagnetísk stormum. Við 47–54°N þarf venjulega Kp 7–8, og Kp 9 getur fært norðurljós allt að Miðjarðarhafssvæðið — dramatískt sannað við G5-storminn í maí 2024. Stilltu stormviðvörun á The Storm Watcher.' },
  ],
};

export default is;
