import type { FaqLangContent } from '../faqContent';

const no: FaqLangContent = {
  subtitle: 'Alt du trenger å vite om nordlyset, romvær og hvordan du best ser nordlyset.',
  categories: {
    'Aurora Basics': 'Nordlysgrunnleggende',
    'Kp Index': 'Kp-indeks',
    'Solar Wind': 'Solvind',
    'Viewing Tips': 'Tips for å se nordlyset',
    'Space Weather': 'Romvær',
    'Moon & Darkness': 'Måne og mørke',
    'Location Guides': 'Stedguider',
  },
  items: [
    { question: 'Hva er Aurora Borealis (Nordlyset)?', answer: 'Aurora Borealis, eller nordlyset, er et naturlig lysshow forårsaket av ladede partikler fra Solen som kolliderer med gasser i jordens atmosfære. Når solvindpartikler samhandler med oksygen- og nitrogenmolekyler, sender de ut fotoner — og skaper de fantastiske grønne, lilla, røde og blå lysforhengene som er synlige nær polområdene.' },
    { question: 'Hva er forskjellen mellom Aurora Borealis og Aurora Australis?', answer: 'Aurora Borealis (nordlys) forekommer på den nordlige halvkule, mens Aurora Australis (sydlys) forekommer på den sørlige halvkule. Begge er forårsaket av de samme solfenomenene — ladede partikler som samhandler med jordens magnetfelt. De oppstår ofte samtidig ved begge polene som speilbilder.' },
    { question: 'Hva er solvind og hvordan påvirker det Jorden?', answer: 'Solvind er en kontinuerlig strøm av ladede partikler (hovedsakelig protoner og elektroner) som strømmer fra Solen med hastigheter på 300–800 km/s. Når solvindshastigheten overstiger 500 km/s, komprimerer den jordens magnetosfære og kan utløse geomagnetiske stormer og nordlys. Koronale masseutkast (CME-er) forårsaker de mest dramatiske nordlysbegivenhetene.' },
    { question: 'Hva er de beste forholdene for å se nordlyset?', answer: 'For best nordlysvisning: (1) Mørk himmel — unna bylys, (2) Klar himmel — skydekke under 30%, (3) Aktive geomagnetiske forhold — Kp 4+, (4) Mørk måne — nymåne eller sigd, (5) Tid — vanligvis mellom kl. 22 og 02, (6) Sesong — september til mars. Vår synlighetsjekkliste kombinerer alle disse faktorene i sanntid.' },
    { question: 'Hvordan fotograferer jeg nordlyset?', answer: 'Kamerainnstillinger for nordlysfotografering: (1) Bruk stativ med eksponeringstider på 5–25 sekunder, (2) Vidvinkelobjektiv f/2.8 eller lysere, (3) ISO 1600–3200, (4) Lukkertid 8–15 sekunder, (5) Manuell fokus satt til uendelig, (6) Ta bilder i RAW. Moderne telefoner som iPhone 15+ og Samsung S24+ har utmerkede nattmodus som automatisk kan fange nordlys.' },
    { question: 'Hva er solsyklusen og når er det best for nordlys?', answer: 'Solen følger en omtrent 11-årig aktivitetssyklus. Under solfasen maksimum er solflekker, solutbrudd og CME-er hyppigst. Vi er for tiden nær maksimum for solsyklus 25 (2024–2026) — en av de beste periodene for nordlysjakt på over et tiår. Aktiviteten forventes å forbli høy frem til 2027.' },
    { question: 'Påvirker Månen synligheten av nordlyset?', answer: 'Ja — en lys fullmåne visker ut svakere nordlys, på samme måte som lysforurensning. Den beste nordlysvisningen skjer ved nymåne eller noen dager etter, når himmelen er mørkest. Svært sterkt nordlys (Kp 7+) kan imidlertid sees selv under fullmåne. Sjekklisten vår tar automatisk hensyn til gjeldende månefase.' },
    { question: 'Hva er Kp-indeksen og hva betyr den for nordlysvisning?', answer: 'Kp-indeksen er en global 0–9-skala for forstyrrelser i jordens magnetfelt, oppdatert hvert 3. time av NOAA. Kp 0–2 betyr at aktiviteten er begrenset nær polområdene, mens Kp 5+ presser nordlyset lenger sørover — muligens til Skottland, Sør-Canada eller Mellom-Europa. Sanntidsdata vises på The Storm Watchers Dashboard.' },
    { question: 'Hvilket Kp-nivå trenger jeg for å se nordlyset?', answer: 'Nødvendig Kp avhenger av breddegrad. Ved 65°N (Nord-Skandinavia, Island, Alaska) er Kp 1–2 ofte nok. Ved 60°N (Sør-Norge, Helsinki) er Kp 3–4 typisk. Ved 55°N (Skottland, Stockholm) trenger du Kp 5–6. Ved 50°N (Mellom-Tyskland, Praha) kreves Kp 7–8. Disse tersklene forutsetter helt mørk, klar himmel.' },
    { question: 'Hva er forskjellen mellom Kp 5, Kp 7 og Kp 9?', answer: 'Kp 5 (G1-storm) er minimumsgrensen — nordlyset blir synlig i Sør-Skandinavia og Skottland som en blek bue. Kp 7 (G3-storm) bringer levende nordlys til Tyskland og Nord-USA. Kp 9 (G5-storm) er maksimalnivået — sist sett i mai 2024, da nordlys ble observert over Spania, Italia, Texas og Florida.' },
    { question: 'Hva er en geomagnetisk storm og hvordan måles den?', answer: 'En geomagnetisk storm er en storskala forstyrrelse av jordens magnetosfære fra forsterket solvind — vanligvis etter en CME eller høyhastighetsstrøm fra et koronalt hull. NOAA klassifiserer stormer på G-skalaen: G1 (Kp 5) til G5 (Kp 9). Stormer kan forstyrre satellitter, GPS, KV-radio og strømnett.' },
    { question: 'Hva er et røntgen-solutbrudd og hva betyr det?', answer: 'Solutbrudd er intense strålingsutsendinger klassifisert etter røntgentopp: A, B, C, M og X (hvert trinn er 10× sterkere). C-klasse er ubetydelig; M kan forårsake korte radiobortfall; X er de kraftigste. Et enkelt utbrudd garanterer ikke nordlys — det avgjørende er om det er ledsaget av en jordrettet CME.' },
    { question: 'Hva er en CME (koroal masseutkast)?', answer: 'Et koronalt masseutkast er en massiv eksplosjon av magnetisert plasma fra solens korona, som frigjør opptil en milliard tonn solmateriale med hastigheter på 250–3 000 km/s. Når en jordrettet CME ankommer — vanligvis 1–4 dager etter utbruddet — komprimerer den magnetosfæren og utløser de mest spektakulære nordlysbegivenhetene.' },
    { question: 'Hva er Bz-komponenten og hvorfor betyr den noe for nordlyset?', answer: 'Bz er nord-sør-komponenten av det interplanetariske magnetfeltet, målt av DSCOVR- og ACE-satellitter ved L1-punktet. Når Bz er negativ, tillater magnetisk rekonneksjon ladede partikler å strømme inn i polæratmosfæren. En vedvarende Bz under −10 nT gir vanligvis 15–45 minutters forvarsel.' },
    { question: 'Hva er solvindshastigheten og hvordan påvirker den nordlyset?', answer: 'Solvinden strømmer med typiske hastigheter på 300–500 km/s under rolige forhold. Når hastigheten overstiger 500 km/s, komprimerer den magnetosfæren; over 700 km/s er den forbundet med sterk geomagnetisk aktivitet. Høyhastighetsstrømmer fra koronale hull er ofte forutsigbare opptil 27 dager på forhånd.' },
    { question: 'Hva er nordlysovalen?', answer: 'Nordlysovalen er en ringformet sone rundt hvert magnetpol der nordlyset er mest konsistent aktivt, sentrert ved omtrent 65–70° geomagnetisk bredde. Under geomagnetiske stormer utvider ovalen seg mot ekvator — en Kp 9-storm kan presse den helt til subtropene. NOAA OVATION-modellen viser den i sanntid på The Storm Watchers 3D-globus.' },
    { question: 'Hvorfor ser nordlyset grønt, rødt eller lilla ut?', answer: 'Nordlysets farger bestemmes av hvilket atmosfærisk gass som eksiteres og på hvilken høyde. Grønt — den vanligste fargen — kommer fra oksygen ved 100–150 km høyde. Rødt nordlys stammer fra oksygen over 200 km. Blå og lilla fargetoner kommer fra nitrogen under 100 km. Under intense stormer eksiteres flere lag simultant.' },
    { question: 'Hva er den beste årstiden for å se nordlyset?', answer: 'Nordlyset er aktivt hele året, men synlighet krever mørke — noe som gjør september til mars til høysesong. Høst- og vårjevndøgnet er statistisk mer aktive på grunn av Russell–McPherron-effekten. Sommer er problematisk i høye breddegrader på grunn av midnattssolen. Oktober til februar gir den beste kombinasjonen.' },
    { question: 'Hvilken tid på natten er best for nordlysvisning?', answer: 'Nordlysaktiviteten topper seg rundt lokal magnetisk midnatt — vanligvis mellom kl. 22 og 02 — når feltlinjene overhead kobler seg mest direkte til nordlyssonen. Still en Kp-terskelvarsel på The Storm Watcher for å bli varslet i det øyeblikket forholdene er optimale.' },
    { question: 'Hvordan får jeg nordlysvarsler på telefonen?', answer: 'The Storm Watcher tilbyr gratis push-varsler for geomagnetiske stormvarsler — still Kp-terskelen i Innstillinger-siden (f.eks. "varsle meg når Kp ≥ 5") og du vil bli varslet i det øyeblikket NOAA-data krysser det nivået. Varselet inkluderer aktuell Kp, Bz, solvindshastighet og estimert skydekke.' },
    { question: 'Kan jeg se nordlyset i Skottland / Storbritannia?', answer: 'Ja — Skottland er et av de beste nordlysmålene utenfor Skandinavia. De skotske høylandet, Orknøyene og Shetland ligger ved 57–60°N, der Kp 4–5 vanligvis er nok på en klar, mørk natt. Under sterkere stormer (Kp 6+) er nordlys jevnlig synlig i Nord-England, og ved Kp 8+ til og med fra Sør-England.' },
    { question: 'Kan jeg se nordlyset i Tyskland / Mellom-Europa?', answer: 'Nordlysobservasjoner i Tyskland, Østerrike, Sveits, Polen og naboland er sjeldnere, men fullt mulig under sterke geomagnetiske stormer. Ved 47–54°N trengs typisk Kp 7–8, og Kp 9 kan bringe nordlys til Middelhavet — dramatisk demonstrert under G5-stormen i mai 2024. Still inn et stormvarsel på The Storm Watcher.' },
  ],
};

export default no;
