import type { FaqLangContent } from '../faqContent';

const pl: FaqLangContent = {
  subtitle: 'Wszystko, co musisz wiedzieć o zorzach polarnych, pogodzie kosmicznej i jak je obserwować.',
  categories: {
    'Aurora Basics': 'Podstawy zorzy polarnej',
    'Kp Index': 'Indeks Kp',
    'Solar Wind': 'Wiatr słoneczny',
    'Viewing Tips': 'Wskazówki obserwacyjne',
    'Space Weather': 'Pogoda kosmiczna',
    'Moon & Darkness': 'Księżyc i ciemność',
    'Location Guides': 'Przewodniki po lokalizacjach',
  },
  items: [
    { question: 'Czym jest Aurora Borealis (Zorza Polarna)?', answer: 'Aurora Borealis, czyli zorza polarna, to naturalne zjawisko świetlne spowodowane przez naładowane cząstki ze Słońca zderzające się z gazami w atmosferze Ziemi. Gdy cząstki wiatru słonecznego oddziałują z cząsteczkami tlenu i azotu, emitują fotony — tworząc oszałamiające zielone, fioletowe, czerwone i niebieskie kurtyny światła widoczne w okolicach biegunów.' },
    { question: 'Jaka jest różnica między Aurora Borealis a Aurora Australis?', answer: 'Aurora Borealis (zorza polarna) występuje na półkuli północnej, natomiast Aurora Australis (zorza australna) — na półkuli południowej. Obie są spowodowane tymi samymi zjawiskami słonecznymi — naładowanymi cząstkami oddziałującymi z polem magnetycznym Ziemi. Często pojawiają się jednocześnie na obu biegunach jako lustrzane odbicia.' },
    { question: 'Czym jest wiatr słoneczny i jak wpływa na Ziemię?', answer: 'Wiatr słoneczny to ciągły strumień naładowanych cząstek (głównie protonów i elektronów) płynących ze Słońca z prędkościami 300–800 km/s. Gdy prędkość przekracza 500 km/s, ściska magnetosferę Ziemi i może wywołać burze geomagnetyczne oraz zorze. Koronalne wyrzuty masy (CME) powodują najbardziej dramatyczne zdarzenia zorzowe.' },
    { question: 'Jakie są najlepsze warunki do obserwacji Zorzy Polarnej?', answer: 'Do najlepszej obserwacji zorzy: (1) Ciemne niebo — z dala od miejskich świateł, (2) Czyste niebo — zachmurzenie poniżej 30%, (3) Aktywne warunki geomagnetyczne — Kp 4+, (4) Ciemny Księżyc — nów lub sierp, (5) Czas — zazwyczaj między 22:00 a 2:00 czasu lokalnego, (6) Sezon — wrzesień–marzec.' },
    { question: 'Jak fotografować Zorzę Polarną?', answer: 'Ustawienia aparatu do fotografii zorzy: (1) Statyw z czasami ekspozycji 5–25 sekund, (2) Obiektyw szerokokątny f/2.8 lub jaśniejszy, (3) ISO 1600–3200, (4) Czas naświetlania 8–15 sekund, (5) Ręczne ustawienie ostrości na nieskończoność, (6) Fotografuj w formacie RAW. Nowoczesne telefony iPhone 15+ i Samsung S24+ mają doskonałe tryby nocne.' },
    { question: 'Czym jest Cykl Słoneczny i kiedy najlepiej obserwować zorze?', answer: 'Słońce podąża za około 11-letnim cyklem aktywności. Podczas Maksimum Słonecznego plamy słoneczne, rozbłyski i CME są najczęstsze. Obecnie jesteśmy blisko maksimum cyklu 25 (2024–2026) — jednego z najlepszych okresów do łowienia zorzy od ponad dekady.' },
    { question: 'Czy Księżyc wpływa na widoczność zorzy?', answer: 'Tak — jasna pełnia Księżyca przyćmiewa słabszą zorzę, podobnie jak zanieczyszczenie świetlne. Najlepsza obserwacja ma miejsce podczas nowiu lub kilka dni po nim, gdy niebo jest najciemniejsze. Jednak bardzo silna zorza (Kp 7+) jest widoczna nawet podczas pełni. Nasza lista kontrolna automatycznie uwzględnia aktualną fazę Księżyca.' },
    { question: 'Czym jest indeks Kp i co oznacza dla obserwacji zorzy?', answer: 'Indeks Kp to globalna skala 0–9 mierząca zakłócenia pola magnetycznego Ziemi, aktualizowana co 3 godziny przez NOAA. Kp 0–2 oznacza aktywność ograniczoną do okolic biegunów, podczas gdy Kp 5+ przesuwa zorzę dalej na południe — być może do Szkocji, Kanady Południowej lub Europy Środkowej. Dane wyświetlane są na Panelu The Storm Watcher.' },
    { question: 'Jakiego Kp potrzebuję do obserwacji zorzy polarnej?', answer: 'Wymagany Kp zależy od szerokości geograficznej. Na 65°N (Skandynawia Północna, Islandia, Alaska) często wystarczy Kp 1–2. Na 60°N (Norwegia Południowa, Helsinki) typowo Kp 3–4. Na 55°N (Szkocja, Sztokholm) potrzeba Kp 5–6. Na 50°N (Niemcy Centralne, Praga) wymagane jest Kp 7–8.' },
    { question: 'Jaka jest różnica między Kp 5, Kp 7 a Kp 9?', answer: 'Kp 5 (burza G1) to minimalny próg — zorza staje się widoczna w Skandynawii Południowej i Szkocji jako blady łuk. Kp 7 (burza G3) przynosi żywą zorzę do Niemiec i północnych USA. Kp 9 (burza G5) to maksymalny poziom — ostatni przykład w maju 2024, gdy zorze obserwowano nad Hiszpanią, Włochami, Teksasem i Florydą.' },
    { question: 'Czym jest burza geomagnetyczna i jak jest mierzona?', answer: 'Burza geomagnetyczna to wieloskalowe zakłócenie magnetosfery Ziemi spowodowane nasilonym wiatrem słonecznym — zazwyczaj po CME lub szybkich strumieniach z dziur koronalnych. NOAA klasyfikuje burze w skali G: G1 (Kp 5) do G5 (Kp 9). Burze mogą zakłócić satelity, GPS, radio krótkofalowe i sieci energetyczne.' },
    { question: 'Czym jest rozbłysk słoneczny rentgenowski i co oznacza?', answer: 'Rozbłyski słoneczne to intensywne eksplozje promieniowania klasyfikowane według szczytowej emisji rentgenowskiej: A, B, C, M i X (każda klasa jest 10× silniejsza). Klasa C jest nieznaczna; M może powodować krótkie zakłócenia radiowe; X jest najpotężniejsza. Sam rozbłysk nie gwarantuje zorzy — liczy się, czy towarzyszy mu CME skierowane w stronę Ziemi.' },
    { question: 'Czym jest CME (koronalny wyrzut masy)?', answer: 'Koronalny wyrzut masy to masywna erupcja zmagnetyzowanej plazmy z korony Słońca, uwalniająca do miliarda ton materiału słonecznego z prędkościami 250–3 000 km/s. Gdy CME dociera do Ziemi — zazwyczaj 1–4 dni po erupcji — ściska magnetosferę, gwałtownie podnosi indeks Kp i wywołuje najbardziej spektakularne zdarzenia zorzowe.' },
    { question: 'Czym jest składowa Bz i dlaczego jest ważna dla zorzy?', answer: 'Bz to składowa północ-południe Międzyplanetarnego Pola Magnetycznego, mierzona przez satelity DSCOVR i ACE w punkcie L1. Gdy Bz jest ujemny, rekoneksja magnetyczna pozwala naładowanym cząstkom napływać do polarnej atmosfery. Trwały Bz poniżej −10 nT zazwyczaj daje 15–45 minut ostrzeżenia przed wzrostem indeksu Kp.' },
    { question: 'Czym jest prędkość wiatru słonecznego i jak wpływa na zorzę?', answer: 'Wiatr słoneczny płynie z typowymi prędkościami 300–500 km/s przy spokojnych warunkach. Powyżej 500 km/s ściska magnetosferę; powyżej 700 km/s wiąże się z silną aktywnością geomagnetyczną. Szybkie strumienie z dziur koronalnych są często przewidywalne do 27 dni z wyprzedzeniem.' },
    { question: 'Czym jest owal zorzy?', answer: 'Owal zorzy to pierścieniowa strefa wokół każdego bieguna magnetycznego, gdzie zorza jest najbardziej aktywna, skupiona przy około 65–70° szerokości geomagnetycznej. Podczas burz owal rozszerza się ku równikowi — burza Kp 9 może go przesunąć aż do subtropów. Model NOAA OVATION wyświetla go w czasie rzeczywistym na globusie 3D The Storm Watcher.' },
    { question: 'Dlaczego zorza jest zielona, czerwona lub fioletowa?', answer: 'Kolory zorzy zależą od tego, jaki gaz jest wzbudzany i na jakiej wysokości. Zielony — najczęstszy — pochodzi z tlenu na wysokości 100–150 km. Czerwony pochodzi z tlenu powyżej 200 km. Odcienie niebieskie i fioletowe pochodzą z azotu poniżej 100 km. Podczas intensywnych burz wiele warstw jest wzbudzanych jednocześnie.' },
    { question: 'Kiedy jest najlepszy czas roku na obserwację zorzy?', answer: 'Zorza jest aktywna przez cały rok, ale widoczność wymaga ciemności — co sprawia, że wrzesień–marzec to główny sezon. Przesilenia wiosenne i jesienne są statystycznie bardziej aktywne ze względu na efekt Russella–McPherrona. Lato jest problematyczne na wysokich szerokościach z powodu słońca o północy. Październik–luty oferuje najlepsze połączenie.' },
    { question: 'O jakiej porze nocy najlepiej obserwować zorzę?', answer: 'Aktywność zorzy osiąga szczyt około lokalnej magnetycznej północy — zazwyczaj między 22:00 a 2:00 — gdy linie pola łączą się najbardziej bezpośrednio z pasem zorzy. Ustaw próg Kp w The Storm Watcher, aby otrzymać powiadomienie dokładnie w odpowiednim momencie.' },
    { question: 'Jak otrzymywać alerty o zorzach na telefonie?', answer: 'The Storm Watcher oferuje bezpłatne powiadomienia push — ustaw próg Kp na stronie Ustawienia (np. "powiadom mnie, gdy Kp ≥ 5") i otrzymasz powiadomienie, gdy dane NOAA przekroczą ten poziom. Alert zawiera aktualny Kp, Bz, prędkość wiatru słonecznego i zachmurzenie w twojej lokalizacji.' },
    { question: 'Czy można zobaczyć zorzę w Szkocji / Wielkiej Brytanii?', answer: 'Tak — Szkocja to jeden z najlepszych celów zorzowych poza Skandynawią. Szkockie Highlands, Orkady i Szetlandy leżą na 57–60°N, gdzie Kp 4–5 zazwyczaj wystarczy przy jasnej, ciemnej nocy. Przy silniejszych burzach (Kp 6+) zorza jest regularnie widoczna w Anglii Północnej, a przy Kp 8+ nawet z Anglii Południowej.' },
    { question: 'Czy można zobaczyć zorzę w Niemczech / Europie Środkowej?', answer: 'Obserwacje zorzy w Niemczech, Austrii, Szwajcarii, Polsce i krajach sąsiednich są rzadsze, ale całkowicie możliwe podczas silnych burz geomagnetycznych. Na 47–54°N zazwyczaj potrzeba Kp 7–8, a Kp 9 może sprowadzić zorzę aż na Morze Śródziemne — dramatycznie zademonstrowane podczas burzy G5 w maju 2024 r. Ustaw alert w The Storm Watcher.' },
  ],
};

export default pl;
