import type { FaqLangContent } from '../faqContent';

const sv: FaqLangContent = {
  subtitle: 'Allt du behöver veta om norrsken, rymdväder och hur du observerar nordljuset.',
  categories: {
    'Aurora Basics': 'Norrskensgrunder',
    'Kp Index': 'Kp-index',
    'Solar Wind': 'Solvind',
    'Viewing Tips': 'Observationstips',
    'Space Weather': 'Rymdväder',
    'Moon & Darkness': 'Måne och mörker',
    'Location Guides': 'Platsguider',
  },
  items: [
    { question: 'Vad är Aurora Borealis (Norrsken)?', answer: 'Aurora Borealis, eller norrsken, är ett naturligt ljusfenomen som uppstår när laddade partiklar från Solen kolliderar med gaser i jordens atmosfär. När solvindpartiklar interagerar med syre- och kvävemolekyler sänder de ut fotoner — och skapar de fantastiska gröna, lila, röda och blå ljusridåerna som syns nära polartrakterna.' },
    { question: 'Vad är skillnaden mellan Aurora Borealis och Aurora Australis?', answer: 'Aurora Borealis (norrsken) förekommer på norra halvklotet, medan Aurora Australis (sydsken) förekommer på södra halvklotet. Båda orsakas av samma solarvädershändelser — laddade partiklar som interagerar med jordens magnetfält. De uppträder ofta simultant vid båda polerna som spegelbrildspar.' },
    { question: 'Vad är solvind och hur påverkar det Jorden?', answer: 'Solvind är en kontinuerlig ström av laddade partiklar (huvudsakligen protoner och elektroner) som flödar från Solen med hastigheter på 300–800 km/s. När hastigheten överstiger 500 km/s komprimerar den jordens magnetosfär och kan utlösa geomagnetiska stormar och norrsken. Koronala massautkast (CME:er) orsakar de mest dramatiska norrskenshändelserna.' },
    { question: 'Vilka är de bästa förhållandena för att se norrsken?', answer: 'För bästa norrskensobservation: (1) Mörk himmel — bort från stadslysens skimmer, (2) Klar himmel — molntäcke under 30%, (3) Aktiva geomagnetiska förhållanden — Kp 4+, (4) Mörk måne — nymåne eller skära, (5) Tid — vanligtvis mellan 22 och 02, (6) Säsong — september till mars. Vår synlighetschecklista kombinerar alla faktorer i realtid.' },
    { question: 'Hur fotograferar jag norrsken?', answer: 'Kamerainställningar för norrskensfotografering: (1) Stativ med exponeringstider 5–25 sekunder, (2) Vidvinkelobjektiv f/2.8 eller ljusare, (3) ISO 1600–3200, (4) Slutartid 8–15 sekunder, (5) Manuell fokus inställd på oändlighet, (6) Fotografera i RAW. Moderna telefoner som iPhone 15+ och Samsung S24+ har utmärkta nattlägen.' },
    { question: 'Vad är solcykeln och när är det bäst för norrsken?', answer: 'Solen följer en ungefär 11-årig aktivitetscykel. Under solmaximum är solfläckar, solutbrott och CME:er vanligast. Vi befinner oss för närvarande nära maximum för solcykel 25 (2024–2026) — en av de bästa perioderna för norrskensjakt på mer än ett decennium.' },
    { question: 'Påverkar Månen synligheten av norrsken?', answer: 'Ja — en ljus fullmåne suddar ut svagare norrsken, liknande ljusföroreningar. Den bästa observationen sker vid nymåne eller några dagar därefter, när himmelen är som mörkast. Mycket starkt norrsken (Kp 7+) kan dock ses även under fullmåne. Vår checklista tar automatiskt hänsyn till aktuell månfas.' },
    { question: 'Vad är Kp-index och vad betyder det för norrskensobservation?', answer: 'Kp-index är en global 0–9-skala som mäter störningar i jordens magnetfält, uppdaterad av NOAA var 3:e timme. Kp 0–2 innebär aktivitet begränsad till polartrakterna, medan Kp 5+ driver norrsken längre söderut — möjligtvis till Skottland, södra Kanada eller Centraleuropa. Live-data visas på The Storm Watchers Dashboard.' },
    { question: 'Vilket Kp behöver jag för att se norrsken?', answer: 'Nödvändigt Kp beror på din breddgrad. Vid 65°N (norra Skandinavien, Island, Alaska) räcker Kp 1–2. Vid 60°N (södra Norge, Helsingfors) krävs Kp 3–4. Vid 55°N (Skottland, Stockholm) behövs Kp 5–6. Vid 50°N (centrala Tyskland, Prag) krävs Kp 7–8. Dessa trösklar förutsätter helt mörk, klar himmel.' },
    { question: 'Vad är skillnaden mellan Kp 5, Kp 7 och Kp 9?', answer: 'Kp 5 (G1-storm) är minimigränsen — norrsken syns i södra Skandinavien och Skottland som en blek båge. Kp 7 (G3-storm) ger levande norrsken till Tyskland och norra USA. Kp 9 (G5-storm) är maxnivån — senast i maj 2024, då norrsken fotograferades i Spanien, Italien, Texas och Florida.' },
    { question: 'Vad är en geomagnetisk storm och hur mäts den?', answer: 'En geomagnetisk storm är en storskalig störning av jordens magnetosfär från förstärkt solvind — typiskt efter en CME eller höghastighetsström från ett koronalt hål. NOAA klassificerar stormar på G-skalan: G1 (Kp 5) till G5 (Kp 9). Stormar kan störa satelliter, GPS, KV-radio och elnät.' },
    { question: 'Vad är ett röntgensolutbrott och vad betyder det?', answer: 'Solutbrott är intensiva strålningsexplosioner klassificerade efter röntgentopp: A, B, C, M och X (varje klass är 10× starkare). C-klassen är liten; M kan orsaka korta radiobortfall; X är kraftigast. Ett enstaka utbrott garanterar inte norrsken — avgörande är om det åtföljs av ett jordriktat CME.' },
    { question: 'Vad är ett CME (koronalt massautkast)?', answer: 'Ett koronalt massautkast är en massiv explosion av magnetiserat plasma från solens korona, som frigör upp till en miljard ton solmaterial med hastigheter på 250–3 000 km/s. När ett jordriktat CME anländer — typiskt 1–4 dagar efter utbrottet — komprimerar det magnetosfären och utlöser de mest spektakulära norrskenssäsongerna.' },
    { question: 'Vad är Bz-komponenten och varför spelar den roll för norrsken?', answer: 'Bz är nord-syd-komponenten av det interplanetariska magnetfältet, mätt av DSCOVR- och ACE-satelliterna vid L1-punkten. När Bz är negativ möjliggör magnetisk rekopling att laddade partiklar strömmar in i polärатmosfären. Varaktigt Bz under −10 nT ger vanligtvis 15–45 minuters förvarning.' },
    { question: 'Vad är solvindhastigheten och hur påverkar den norrsken?', answer: 'Solvinden flödar med typiska hastigheter på 300–500 km/s under lugna förhållanden. Över 500 km/s komprimerar den magnetosfären; över 700 km/s är den förknippad med stark geomagnetisk aktivitet. Höghastighetsströmmar från koronala hål är förutsägbara upp till 27 dagar i förväg.' },
    { question: 'Vad är norrskensovalen?', answer: 'Norrskensovalen är en ringformad zon runt varje magnetpol där norrsken är mest konsekvent aktivt, centrerat vid ungefär 65–70° geomagnetisk breddgrad. Under stormar expanderar ovalen mot ekvatorn — en Kp 9-storm kan driva den till subtroperna. NOAA OVATION-modellen visar den i realtid på The Storm Watchers 3D-glob.' },
    { question: 'Varför syns norrsken i grönt, rött eller lila?', answer: 'Norrskenets färger bestäms av vilket atmosfäriskt gas som exalteras och på vilken höjd. Grönt — vanligast — kommer från syre vid 100–150 km. Rött norrsken härstammar från syre ovan 200 km. Blå och lila toner kommer från kväve under 100 km. Under intensiva stormar exalteras flera lager simultant.' },
    { question: 'Vilken tid på året är bäst för norrsken?', answer: 'Norrsken är aktivt året runt, men synlighet kräver mörker — vilket gör september till mars till högsäsong. Höst- och vårjämndagarna är statistiskt mer aktiva tack vare Russell–McPherron-effekten. Sommaren är problematisk på höga breddgrader på grund av midnattssolen. Oktober till februari erbjuder bäst kombination.' },
    { question: 'Vilken tid på natten är bäst för norrskensobservation?', answer: 'Norrskenaktiviteten toppar sig runt lokal magnetisk midnatt — typiskt mellan 22 och 02 — när fältlinjerna overhead kopplar direkt till norrskenzonen. Ställ in en Kp-tröskelvarning på The Storm Watcher för att aviseras i rätt ögonblick.' },
    { question: 'Hur får jag norrskensvarningar på telefonen?', answer: 'The Storm Watcher erbjuder gratis push-notiser — ange din Kp-tröskel i Inställningar (t.ex. "varna mig vid Kp ≥ 5") och du aviseras i det ögonblick NOAA-data passerar den nivån. Avisering inkluderar aktuellt Kp, Bz, solvindhastighet och molntäcke vid din sparade plats.' },
    { question: 'Kan man se norrsken i Skottland / Storbritannien?', answer: 'Ja — Skottland är ett av de bästa norrskensresemålen utanför Skandinavien. Skottska höglandet, Orkney och Shetland ligger vid 57–60°N, där Kp 4–5 vanligtvis räcker en klar, mörk natt. Vid kraftigare stormar (Kp 6+) syns norrsken regelbundet i norra England, och vid Kp 8+ även från södra England.' },
    { question: 'Kan man se norrsken i Tyskland / Centraleuropa?', answer: 'Norrskensobservationer i Tyskland, Österrike, Schweiz, Polen och grannländer är mer sällsynta men fullt möjliga under starka geomagnetiska stormar. Vid 47–54°N behövs typiskt Kp 7–8, och Kp 9 kan föra norrsken till Medelhavet — dramatiskt visat under G5-stormen i maj 2024. Ange en stormvarning i The Storm Watcher.' },
  ],
};

export default sv;
