const fs = require('fs');

const data = fs.readFileSync('src/contexts/LanguageContext.tsx', 'utf-8');

const t = {
  en: {
    'iss.subtitle': 'International Space Station — live position & pass predictions',
    'iss.livePosition': 'Live Position',
    'iss.updates5s': 'updates every 5s',
    'iss.latitude': 'Latitude',
    'iss.longitude': 'Longitude',
    'iss.altitude': 'Altitude',
    'iss.speed': 'Speed',
    'iss.passesSubtitle': 'Next 7 days · minimum elevation 10°',
    'iss.noPasses': 'No visible passes in the next 7 days.',
    'iss.excellent': ' Excellent (60+)',
    'iss.good': ' Good (30°+)',
    'iss.low': ' Low (10°+)',
    'iss.yourLocation': 'Your location',
    'iss.nextPassTitle': 'Next',
  },
  bg: {
    'iss.subtitle': 'Международна космическа станция — позиция на живо и прогноза за преминавания',
    'iss.livePosition': 'Текуща позиция',
    'iss.updates5s': 'обновява се на 5 сек',
    'iss.latitude': 'Ширина',
    'iss.longitude': 'Дължина',
    'iss.altitude': 'Височина',
    'iss.speed': 'Скорост',
    'iss.passesSubtitle': 'Следващите 7 дни · минимална елевация 10°',
    'iss.noPasses': 'Няма видими преминавания в следващите 7 дни.',
    'iss.excellent': ' Отлично (60°+)',
    'iss.good': ' Добро (30°+)',
    'iss.low': ' Ниско (10°+)',
    'iss.yourLocation': 'Къде се намирате',
    'iss.nextPassTitle': 'Следващо',
  },
  es: {
    'iss.subtitle': 'Estación Espacial Internacional — posición en vivo y pases',
    'iss.livePosition': 'Posición en Vivo',
    'iss.updates5s': 'se actualiza cada 5s',
    'iss.latitude': 'Latitud',
    'iss.longitude': 'Longitud',
    'iss.altitude': 'Altitud',
    'iss.speed': 'Velocidad',
    'iss.passesSubtitle': 'Próximos 7 días · elevación mínima 10°',
    'iss.noPasses': 'No hay pases visibles en los próximos 7 días.',
    'iss.excellent': ' Excelente (60°+)',
    'iss.good': ' Bueno (30°+)',
    'iss.low': ' Bajo (10°+)',
    'iss.yourLocation': 'Tu ubicación',
    'iss.nextPassTitle': 'Siguiente',
  },
  fr: {
    'iss.subtitle': 'Station Spatiale Internationale — position en direct et passages',
    'iss.livePosition': 'Position en Direct',
    'iss.updates5s': 'mis à jour toutes les 5s',
    'iss.latitude': 'Latitude',
    'iss.longitude': 'Longitude',
    'iss.altitude': 'Altitude',
    'iss.speed': 'Vitesse',
    'iss.passesSubtitle': 'Prochains 7 jours · élévation min. 10°',
    'iss.noPasses': 'Aucun passage visible dans les 7 prochains jours.',
    'iss.excellent': ' Excellent (60°+)',
    'iss.good': ' Bon (30°+)',
    'iss.low': ' Faible (10°+)',
    'iss.yourLocation': 'Votre position',
    'iss.nextPassTitle': 'Prochain',
  },
  de: {
    'iss.subtitle': 'Internationale Raumstation — Live-Position und Überflüge',
    'iss.livePosition': 'Live-Position',
    'iss.updates5s': 'Aktualisierung alle 5s',
    'iss.latitude': 'Breite',
    'iss.longitude': 'Länge',
    'iss.altitude': 'Höhe',
    'iss.speed': 'Geschwindigkeit',
    'iss.passesSubtitle': 'Nächste 7 Tage · mind. 10° Höhe',
    'iss.noPasses': 'Keine sichtbaren Überflüge in den nächsten 7 Tagen.',
    'iss.excellent': ' Hervorragend (60°+)',
    'iss.good': ' Gut (30°+)',
    'iss.low': ' Gering (10°+)',
    'iss.yourLocation': 'Ihr Standort',
    'iss.nextPassTitle': 'Nächster',
  },
  ru: {
    'iss.subtitle': 'МКС — позиция в реальном времени и пролеты',
    'iss.livePosition': 'Текущая позиция',
    'iss.updates5s': 'обновление каждые 5 сек',
    'iss.latitude': 'Широта',
    'iss.longitude': 'Долгота',
    'iss.altitude': 'Высота',
    'iss.speed': 'Скорость',
    'iss.passesSubtitle': 'Следующие 7 дней · мин. высота 10°',
    'iss.noPasses': 'Нет видимых пролетов в течение 7 дней.',
    'iss.excellent': ' Отлично (60°+)',
    'iss.good': ' Хорошо (30°+)',
    'iss.low': ' Низко (10°+)',
    'iss.yourLocation': 'Ваше расположение',
    'iss.nextPassTitle': 'Следующий',
  },
  zh: {
    'iss.subtitle': '国际空间站 — 实时位置及过境预测',
    'iss.livePosition': '实时位置',
    'iss.updates5s': '每5秒更新',
    'iss.latitude': '纬度',
    'iss.longitude': '经度',
    'iss.altitude': '高度',
    'iss.speed': '速度',
    'iss.passesSubtitle': '未来7天 · 最低高度角 10°',
    'iss.noPasses': '未来7天无可见过境。',
    'iss.excellent': ' 极佳 (60°+)',
    'iss.good': ' 良好 (30°+)',
    'iss.low': ' 较低 (10°+)',
    'iss.yourLocation': '您的位置',
    'iss.nextPassTitle': '下一次',
  },
  ja: {
    'iss.subtitle': '国際宇宙ステーション — 現在位置と通過予測',
    'iss.livePosition': '現在位置',
    'iss.updates5s': '5秒ごとに更新',
    'iss.latitude': '緯度',
    'iss.longitude': '経度',
    'iss.altitude': '高度',
    'iss.speed': '速度',
    'iss.passesSubtitle': '今後7日間 · 最小仰角 10°',
    'iss.noPasses': '今後7日間に目視可能な通過はありません。',
    'iss.excellent': ' 良好 (60°+)',
    'iss.good': ' 普通 (30°+)',
    'iss.low': ' 低い (10°+)',
    'iss.yourLocation': 'あなたの現在地',
    'iss.nextPassTitle': '次',
  }
};

let updatedData = data;
for (const [lang, trans] of Object.entries(t)) {
  const marker = `${lang}: {`;
  const insertStr = Object.entries(trans)
    .map(([k, v]) => `\n    '${k}': '${v}',`)
    .join('');
  updatedData = updatedData.replace(marker, marker + insertStr);
}

fs.writeFileSync('src/contexts/LanguageContext.tsx', updatedData);
console.log('LanguageContext populated with ISS');
