const fs = require('fs');

const data = fs.readFileSync('src/contexts/LanguageContext.tsx', 'utf-8');

const t = {
  en: {
    'uv.errorLoad': 'Could not load UV data.',
    'uv.currentUvIndex': 'Current UV Index',
    'uv.todaysMax': "Today's Maximum",
    'uv.indexToday': 'UV Index — Today',
    'uv.scale': 'UV Scale',
    'uv.chartTooltip': 'UV Index',
    'uv.defaultLocation': 'Sofia, Bulgaria (default)',
    'uv.level.low.label': 'Low',
    'uv.level.low.advice': 'No protection needed. Safe to be outside.',
    'uv.level.moderate.label': 'Moderate',
    'uv.level.moderate.advice': 'Wear sunscreen SPF 30+. Seek shade during midday.',
    'uv.level.high.label': 'High',
    'uv.level.high.advice': 'Sunscreen SPF 50+, hat and sunglasses required. Limit time outdoors.',
    'uv.level.veryHigh.label': 'Very High',
    'uv.level.veryHigh.advice': 'Extra protection needed. Avoid sun between 10am–4pm.',
    'uv.level.extreme.label': 'Extreme',
    'uv.level.extreme.advice': 'Stay indoors during midday. Full protection mandatory if outside.',
  },
  bg: {
    'uv.errorLoad': 'Грешка при зареждане на УВ данни.',
    'uv.currentUvIndex': 'Текущ УВ индекс',
    'uv.todaysMax': "Дневен максимум",
    'uv.indexToday': 'УВ индекс — Днес',
    'uv.scale': 'УВ скала',
    'uv.chartTooltip': 'УВ индекс',
    'uv.defaultLocation': 'София, България (по подразбиране)',
    'uv.level.low.label': 'Нисък',
    'uv.level.low.advice': 'Не е нужна защита. Безопасно за навън.',
    'uv.level.moderate.label': 'Умерен',
    'uv.level.moderate.advice': 'Слънцезащита SPF 30+. Търсете сянка по обед.',
    'uv.level.high.label': 'Висок',
    'uv.level.high.advice': 'Задължително SPF 50+, шапка и очила. Ограничете излагането.',
    'uv.level.veryHigh.label': 'Много висок',
    'uv.level.veryHigh.advice': 'Нужна е допълнителна защита. Избягвайте слънцето от 10 до 16ч.',
    'uv.level.extreme.label': 'Екстремен',
    'uv.level.extreme.advice': 'Останете на закрито. Задължителна пълна защита навън.',
  },
  es: {
    'uv.errorLoad': 'No se pudieron cargar los datos UV.',
    'uv.currentUvIndex': 'Índice UV Actual',
    'uv.todaysMax': 'Máximo de Hoy',
    'uv.indexToday': 'Índice UV — Hoy',
    'uv.scale': 'Escala UV',
    'uv.chartTooltip': 'Índice UV',
    'uv.defaultLocation': 'Sofía, Bulgaria (por defecto)',
    'uv.level.low.label': 'Bajo',
    'uv.level.low.advice': 'No se necesita protección. Seguro para estar afuera.',
    'uv.level.moderate.label': 'Moderado',
    'uv.level.moderate.advice': 'Protector solar SPF 30+. Busque sombra al mediodía.',
    'uv.level.high.label': 'Alto',
    'uv.level.high.advice': 'SPF 50+, sombrero y gafas obligatorios. Limite el tiempo al aire libre.',
    'uv.level.veryHigh.label': 'Muy Alto',
    'uv.level.veryHigh.advice': 'Se necesita protección adicional. Evite el sol de 10am a 4pm.',
    'uv.level.extreme.label': 'Extremo',
    'uv.level.extreme.advice': 'Permanezca adentro al mediodía. Protección total obligatoria.',
  },
  fr: {
    'uv.errorLoad': 'Impossible de charger les données UV.',
    'uv.currentUvIndex': 'Indice UV Actuel',
    'uv.todaysMax': "Maximum d'Aujourd'hui",
    'uv.indexToday': "Indice UV — Aujourd'hui",
    'uv.scale': 'Échelle UV',
    'uv.chartTooltip': 'Indice UV',
    'uv.defaultLocation': 'Sofia, Bulgarie (par défaut)',
    'uv.level.low.label': 'Faible',
    'uv.level.low.advice': 'Aucune protection nécessaire. Sans danger à l’extérieur.',
    'uv.level.moderate.label': 'Modéré',
    'uv.level.moderate.advice': 'Crème solaire SPF 30+. Cherchez l’ombre à midi.',
    'uv.level.high.label': 'Élevé',
    'uv.level.high.advice': 'SPF 50+, chapeau et lunettes obligatoires. Limitez le temps dehors.',
    'uv.level.veryHigh.label': 'Très Élevé',
    'uv.level.veryHigh.advice': 'Protection supplémentaire nécessaire. Évitez le soleil de 10h à 16h.',
    'uv.level.extreme.label': 'Extrême',
    'uv.level.extreme.advice': 'Restez à l’intérieur à midi. Protection totale obligatoire.',
  },
  de: {
    'uv.errorLoad': 'UV-Daten konnten nicht geladen werden.',
    'uv.currentUvIndex': 'Aktueller UV-Index',
    'uv.todaysMax': 'Heutiges Maximum',
    'uv.indexToday': 'UV-Index — Heute',
    'uv.scale': 'UV-Skala',
    'uv.chartTooltip': 'UV-Index',
    'uv.defaultLocation': 'Sofia, Bulgarien (Standard)',
    'uv.level.low.label': 'Niedrig',
    'uv.level.low.advice': 'Kein Schutz erforderlich. Sicher im Freien.',
    'uv.level.moderate.label': 'Moderat',
    'uv.level.moderate.advice': 'Sonnencreme LSF 30+. Suchen Sie mittags Schatten.',
    'uv.level.high.label': 'Hoch',
    'uv.level.high.advice': 'LSF 50+, Hut und Sonnenbrille erforderlich.',
    'uv.level.veryHigh.label': 'Sehr Hoch',
    'uv.level.veryHigh.advice': 'Zusätzlicher Schutz nötig. Spaziergänge 10–16 Uhr meiden.',
    'uv.level.extreme.label': 'Extrem',
    'uv.level.extreme.advice': 'Bleiben Sie mittags drinnen. Voller Schutz zwingend.',
  },
  ru: {
    'uv.errorLoad': 'Не удалось загрузить данные УФ.',
    'uv.currentUvIndex': 'Текущий УФ-индекс',
    'uv.todaysMax': 'Максимум сегодня',
    'uv.indexToday': 'УФ-индекс — Сегодня',
    'uv.scale': 'Шкала УФ',
    'uv.chartTooltip': 'УФ-индекс',
    'uv.defaultLocation': 'София, Болгария (по умолчанию)',
    'uv.level.low.label': 'Низкий',
    'uv.level.low.advice': 'Защита не требуется. Безопасно снаружи.',
    'uv.level.moderate.label': 'Умеренный',
    'uv.level.moderate.advice': 'Солнцезащитный крем SPF 30+. Ищите тень.',
    'uv.level.high.label': 'Высокий',
    'uv.level.high.advice': 'Необходимы SPF 50+, шляпа и очки. Ограничьте время на солнце.',
    'uv.level.veryHigh.label': 'Очень Высокий',
    'uv.level.veryHigh.advice': 'Нужна дополнительная защита. Избегайте солнца с 10 до 16ч.',
    'uv.level.extreme.label': 'Экстремальный',
    'uv.level.extreme.advice': 'Оставайтесь дома в полдень. Полная защита обязательна.',
  },
  zh: {
    'uv.errorLoad': '无法加载紫外线数据。',
    'uv.currentUvIndex': '当前紫外线指数',
    'uv.todaysMax': '今日最高',
    'uv.indexToday': '紫外线指数 — 今日',
    'uv.scale': '紫外线等级',
    'uv.chartTooltip': '紫外线指数',
    'uv.defaultLocation': '索菲亚，保加利亚 (默认)',
    'uv.level.low.label': '低',
    'uv.level.low.advice': '无需防护，可在户外自由活动。',
    'uv.level.moderate.label': '中等',
    'uv.level.moderate.advice': '需要 SPF 30+ 防晒霜，中午尽量遮阳。',
    'uv.level.high.label': '高',
    'uv.level.high.advice': '需要 SPF 50+ 防晒霜、帽子和墨镜。',
    'uv.level.veryHigh.label': '极高',
    'uv.level.veryHigh.advice': '需要额外防护。上午10点至下午4点避免户外。',
    'uv.level.extreme.label': '极端',
    'uv.level.extreme.advice': '中午留在室内。户外务必进行全面防护。',
  },
  ja: {
    'uv.errorLoad': 'UVデータを読み込めませんでした。',
    'uv.currentUvIndex': '現在のUV指数',
    'uv.todaysMax': '本日の最高',
    'uv.indexToday': 'UV指数 — 本日',
    'uv.scale': 'UVスケール',
    'uv.chartTooltip': 'UV指数',
    'uv.defaultLocation': 'ソフィア、ブルガリア (デフォルト)',
    'uv.level.low.label': '低い',
    'uv.level.low.advice': '対策は不要。安全に外出できます。',
    'uv.level.moderate.label': '中程度',
    'uv.level.moderate.advice': 'SPF 30+の日焼け止めを使用し、日陰に。',
    'uv.level.high.label': '高い',
    'uv.level.high.advice': 'SPF 50+、帽子、サングラスが必須。',
    'uv.level.veryHigh.label': '非常に高い',
    'uv.level.veryHigh.advice': '追加の対策が必要。10時〜16時は外出を避ける。',
    'uv.level.extreme.label': '極端',
    'uv.level.extreme.advice': '日中は室内に。外出時は完全な対策が必須。',
  }
};

let updatedData = data;
for (const [lang, trans] of Object.entries(t)) {
  const marker = `${lang}: {`;
  const insertStr = Object.entries(trans)
    .map(([k, v]) => `\n    '${k}': '${v}',`)
    .join('');
  updatedData = updatedData.replace(marker, marker + insertStr);
}

fs.writeFileSync('src/contexts/LanguageContext.tsx', updatedData);
console.log('LanguageContext populated from script');
