// GENERATED by scripts/generate-blog-metadata.mjs — do not edit by hand.
// Run `node scripts/generate-blog-metadata.mjs` after changing a post's title,
// description or translations. blogMetadata.test.ts fails if this drifts.
import type { BlogPostMeta } from './types';

export const blogMeta: BlogPostMeta[] = [
  {
    "slug": "what-is-kp-index",
    "title": "What is the Kp Index? A Complete Guide",
    "description": "The Kp index is the most important number in space weather. Learn what it means, how it's measured, and why it matters for aurora visibility.",
    "date": "2026-02-15",
    "readingTime": 6,
    "category": "space-weather",
    "coverEmoji": "📊",
    "translations": {
      "bg": {
        "title": "Какво е Kp index? Пълно ръководство",
        "description": "Kp index е най-важното число в космическото време. Научете какво означава, как се измерва и защо е важно за видимостта на aurora."
      },
      "de": {
        "title": "Was ist der Kp index? Ein vollständiger Leitfaden",
        "description": "Der Kp index ist die wichtigste Zahl im Weltraumwetter. Erfahren Sie, was er bedeutet, wie er gemessen wird und warum er für die Sichtbarkeit von aurora wichtig ist."
      },
      "es": {
        "title": "¿Qué es el Kp index? Una guía completa",
        "description": "El Kp index es el número más importante en el clima espacial. Conozca qué significa, cómo se mide y por qué es clave para la visibilidad de la aurora."
      },
      "fr": {
        "title": "Qu'est-ce que le Kp index ? Un guide complet",
        "description": "Le Kp index est le chiffre le plus important de la météo spatiale. Découvrez ce qu'il signifie, comment il est mesuré et pourquoi il compte pour la visibilité des aurora."
      },
      "ja": {
        "title": "Kp indexとは？完全ガイド",
        "description": "Kp indexは宇宙天気における最も重要な数値です。その意味、測定方法、そしてauroraの視認性にとってなぜ重要なのかを解説します。"
      },
      "ru": {
        "title": "Что такое Kp index? Полное руководство",
        "description": "Kp index — это самое важное число в космической погоде. Узнайте, что оно значит, как измеряется и почему важно для видимости aurora."
      },
      "zh": {
        "title": "什么是 Kp index？完整指南",
        "description": "Kp index是空间天气中最重要的数字。了解它的含义、如何测量以及为什么它对aurora能见度至关重要。"
      },
      "da": {
        "title": "Hvad er Kp index? En komplet guide",
        "description": "Kp index er det vigtigste tal inden for rumvejr. Lær hvad det betyder, hvordan det måles, og hvorfor det har betydning for aurora-synlighed."
      },
      "fi": {
        "title": "Mikä on Kp index? Täydellinen opas",
        "description": "Kp index on avaruussään tärkein luku. Lue, mitä se tarkoittaa, miten se mitataan ja miksi se on tärkeä aurora-näkyvyyden kannalta."
      },
      "is": {
        "title": "Hvað er Kp index? Heildarleiðarvísir",
        "description": "Kp index er mikilvægasta talan í geimveðri. Lærðu hvað hún þýðir, hvernig hún er mæld og hvers vegna hún skiptir máli fyrir sýnileika aurora."
      },
      "ko": {
        "title": "Kp index란 무엇인가요? 완전 가이드",
        "description": "Kp index는 우주 날씨에서 가장 중요한 숫자입니다. 이것이 무엇을 의미하고 어떻게 측정되며, aurora 관측에 왜 중요한지 알아보세요."
      }
    }
  },
  {
    "slug": "what-is-geomagnetic-storm",
    "title": "What is a Geomagnetic Storm?",
    "description": "Geomagnetic storms are disturbances in Earth's magnetic field caused by solar activity. Learn how they form, their effects, and how to prepare.",
    "date": "2026-02-22",
    "readingTime": 5,
    "category": "space-weather",
    "coverEmoji": "🌍"
  },
  {
    "slug": "how-to-see-northern-lights",
    "title": "How to See the Northern Lights: A Practical Guide",
    "description": "Everything you need to know to see the aurora borealis — best locations, ideal conditions, timing, and gear. Stop missing the lights.",
    "date": "2026-03-05",
    "readingTime": 7,
    "category": "aurora",
    "coverEmoji": "🌌",
    "translations": {
      "bg": {
        "title": "Как да видите Северните сияния: Практическо ръководство",
        "description": "Всичко, което трябва да знаете, за да видите aurora borealis — най-добри локации, идеални условия, време и екипировка."
      },
      "de": {
        "title": "Wie man das Nordlicht sieht: Ein praktischer Leitfaden",
        "description": "Alles, was Sie wissen müssen, um die aurora borealis zu sehen — beste Orte, ideale Bedingungen, Timing und Ausrüstung."
      },
      "es": {
        "title": "Cómo ver la aurora boreal: una guía práctica",
        "description": "Todo lo que necesitas saber para ver la aurora borealis: mejores ubicaciones, condiciones ideales, horarios y equipo."
      },
      "fr": {
        "title": "Comment voir les aurores boréales : Un guide pratique",
        "description": "Tout ce que vous devez savoir pour voir l'aurora borealis — meilleurs endroits, conditions idéales, timing et équipement."
      },
      "ja": {
        "title": "オーロラを見る方法：実践ガイド",
        "description": "aurora borealis を見るために必要なすべて — 最適な場所、理想的な条件、時期、そして装備について。"
      },
      "ru": {
        "title": "Как увидеть северное сияние: практическое руководство",
        "description": "Все, что вам нужно знать, чтобы увидеть aurora borealis — лучшие места, идеальные условия, время и снаряжение."
      },
      "zh": {
        "title": "如何观看北极光：实用指南",
        "description": "观看 aurora borealis 所需了解的内容——最佳地点、理想条件、时机和装备。"
      },
      "da": {
        "title": "Sådan ser du nordlys: En praktisk guide",
        "description": "Alt hvad du behøver at vide for at se aurora borealis — bedste steder, ideelle betingelser, timing og udstyr."
      },
      "fi": {
        "title": "Miten nähdä revontulet: Käytännön opas",
        "description": "Kaikki mitä sinun tarvitsee tietää nähdäksesi aurora borealis -ilmiön — parhaat paikat, ihanteelliset olosuhteet, ajoitus ja varusteet."
      },
      "is": {
        "title": "Hvernig á að sjá norðurljósin: Hagnýt leiðbeining",
        "description": "Allt sem þú þarft að vita til að sjá aurora borealis — bestu staðirnir, kjöraðstæður, tímasetning og búnaður."
      },
      "ko": {
        "title": "오로라 보는 방법: 실용 가이드",
        "description": "aurora borealis 를 보기 위해 알아야 할 모든 것 — 최적의 장소, 이상적인 조건, 타이밍 및 장비."
      },
      "no": {
        "title": "Hvordan se nordlys: En praktisk guide",
        "description": "Alt du trenger å vite for å se aurora borealis — beste steder, ideelle forhold, timing og utstyr."
      },
      "pl": {
        "title": "Jak zobaczyć zorzę polarną: Praktyczny przewodnik",
        "description": "Wszystko, co musisz wiedzieć, aby zobaczyć aurora borealis — najlepsze lokalizacje, idealne warunki, czas i sprzęt."
      },
      "sv": {
        "title": "Hur man ser norrsken: En praktisk guide",
        "description": "Allt du behöver veta för att se aurora borealis — bästa platserna, ideala förhållanden, timing och utrustning."
      },
      "uk": {
        "title": "Як побачити північне сяйво: практичний посібник",
        "description": "Все, що вам потрібно знати, щоб побачити aurora borealis — найкращі локації, ідеальні умови, час та спорядження."
      }
    }
  },
  {
    "slug": "what-is-solar-wind",
    "title": "What is Solar Wind and Why Does It Matter?",
    "description": "Solar wind is a constant stream of particles from the Sun that drives space weather on Earth. Learn how it works and what the numbers mean.",
    "date": "2026-03-12",
    "readingTime": 5,
    "category": "solar",
    "coverEmoji": "💨",
    "translations": {
      "bg": {
        "title": "Какво е слънчев вятър и защо е важен?",
        "description": "Слънчевият вятър е постоянен поток от частици от Слънцето, който задвижва космическото време на Земята. Научете как работи."
      },
      "de": {
        "title": "Was ist Sonnenwind und warum ist er wichtig?",
        "description": "Sonnenwind ist ein ständiger Strom von Teilchen von der Sonne, der das Weltraumwetter auf der Erde antreibt. Erfahren Sie, wie er funktioniert."
      }
    }
  },
  {
    "slug": "g1-to-g5-storm-levels",
    "title": "G1 to G5: Understanding Geomagnetic Storm Levels",
    "description": "NOAA's G-scale classifies geomagnetic storms from G1 (minor) to G5 (extreme). Here's exactly what each level means for aurora, technology, and daily life.",
    "date": "2026-03-20",
    "readingTime": 5,
    "category": "space-weather",
    "coverEmoji": "⚡",
    "translations": {
      "bg": {
        "title": "G1 до G5: Разбиране на нивата на геомагнитните бури",
        "description": "G-скалата на NOAA класифицира геомагнитните бури от G1 (малка) до G5 (екстремна). Ето какво означава всяко ниво за aurora и технологиите."
      }
    }
  },
  {
    "slug": "best-places-aurora-europe",
    "title": "Best Places to See the Aurora in Europe",
    "description": "From Norway's fjords to Iceland's lava fields — the definitive guide to the best aurora viewing locations in Europe, with practical tips for each.",
    "date": "2026-03-28",
    "readingTime": 6,
    "category": "aurora",
    "coverEmoji": "🗺️",
    "translations": {
      "bg": {
        "title": "Най-добрите места за виждане на aurora в Европа",
        "description": "От фиордите на Норвегия до лавовите полета на Исландия — окончателното ръководство за най-добрите локации за наблюдение на aurora в Европа."
      },
      "de": {
        "title": "Die besten Orte, um die aurora in Europa zu sehen",
        "description": "Von Norwegens Fjorden bis zu Islands Lavafeldern — der definitive Leitfaden zu den besten Orten für die aurora-Sichtung in Europa."
      },
      "es": {
        "title": "Los mejores lugares para ver la aurora en Europa",
        "description": "Desde los fiordos de Noruega hasta los campos de lava de Islandia: la guía definitiva de los mejores lugares para ver auroras en Europa."
      },
      "fr": {
        "title": "Les meilleurs endroits pour voir l'aurora en Europe",
        "description": "Des fjords de Norvège aux champs de lave d'Islande — le guide définitif des meilleurs lieux d'observation des aurora en Europe."
      },
      "ja": {
        "title": "ヨーロッパでauroraを見るのに最適な場所",
        "description": "ノルウェーのフィヨルドからアイスランドの溶岩地帯まで — ヨーロッパにおける最適なaurora観測地を実用的なコツと共にまとめた決定版ガイド。"
      },
      "ru": {
        "title": "Лучшие места, чтобы увидеть aurora в Европе",
        "description": "От фьордов Норвегии до лавовых полей Исландии — подробное руководство по лучшим местам для наблюдения за aurora в Европе."
      },
      "zh": {
        "title": "欧洲最佳 aurora 观测地点",
        "description": "从挪威的峡湾到冰岛的熔岩原——欧洲最佳 aurora 观测地点的终极指南，并附带针对每个地点的实用建议。"
      },
      "da": {
        "title": "De bedste steder at se aurora i Europa",
        "description": "Fra Norges fjorde til Islands lavafelter — den definitive guide til de bedste steder at se aurora i Europa."
      },
      "fi": {
        "title": "Parhaat paikat nähdä aurora Euroopassa",
        "description": "Norjan vuonoista Islannin laavakenttiin — lopullinen opas Euroopan parhaisiin aurora-katselupaikkoihin käytännön vinkeillä."
      },
      "is": {
        "title": "Bestu staðirnir til að sjá aurora í Evrópu",
        "description": "Frá fjörðum Noregs til hraunbreiða Íslands — endanlegur leiðarvísir um bestu staðina til að skoða aurora í Evrópu."
      },
      "ko": {
        "title": "유럽에서 aurora를 보기 가장 좋은 장소",
        "description": "노르웨이의 피오르드부터 아이슬란드의 용암 대지까지 — 유럽 최고의 aurora 관측 장소에 대한 최종 가이드와 실용적인 팁."
      },
      "no": {
        "title": "De beste stedene å se aurora i Europa",
        "description": "Fra Norges fjorder til Islands lavafelt — den definitive guiden til de beste stedene å se aurora i Europa."
      },
      "pl": {
        "title": "Najlepsze miejsca na zobaczenie aurora w Europie",
        "description": "Od fiordów Norwegii po pola lawowe Islandii — ostateczny przewodnik po najlepszych miejscach do obserwacji aurora w Europie."
      },
      "sv": {
        "title": "Bästa platserna att se aurora i Europa",
        "description": "Från Norges fjordar till Islands lavafält — den definitiva guiden till de bästa platserna att se aurora i Europa."
      },
      "uk": {
        "title": "Найкращі місця, щоб побачити aurora в Європі",
        "description": "Від фьордів Норвегії до лавових полів Ісландії — повне керівництво по найкращих місцях для спостереження за aurora в Європі."
      }
    }
  },
  {
    "slug": "what-is-solar-flare",
    "title": "What is a Solar Flare?",
    "description": "Solar flares are the most energetic explosions in our solar system. Learn what causes them, how they're classified, and whether they pose a danger to Earth.",
    "date": "2026-04-08",
    "readingTime": 5,
    "category": "solar",
    "coverEmoji": "☀️",
    "translations": {
      "bg": {
        "title": "Какво е слънчево изригване?",
        "description": "Слънчевите изригвания са най-енергийните експлозии в нашата слънчева система. Научете какво ги причинява, как се класифицират и дали са опасни."
      }
    }
  },
  {
    "slug": "aurora-forecast-explained",
    "title": "Aurora Forecast Explained: How to Read Space Weather Data",
    "description": "Aurora forecasts are full of jargon — Kp, Bz, solar wind speed, OVATION. This guide explains each number and how to interpret them together.",
    "date": "2026-04-15",
    "readingTime": 6,
    "category": "guide",
    "coverEmoji": "🔭",
    "translations": {
      "bg": {
        "title": "Прогнозата за aurora обяснена: Как да четем данни за космическото време",
        "description": "Прогнозите за сияния са пълни с жаргон — Kp, Bz, скорост на слънчевия вятър, OVATION. Това ръководство обяснява всяко число."
      }
    }
  },
  {
    "slug": "space-weather-effects-on-earth",
    "title": "Space Weather and Its Effects on Earth",
    "description": "Space weather affects power grids, satellites, GPS, aviation, and more. Here's how solar activity shapes modern technology and everyday life.",
    "date": "2026-04-24",
    "readingTime": 6,
    "category": "space-weather",
    "coverEmoji": "🛸",
    "translations": {
      "bg": {
        "title": "Космическото време и неговите ефекти върху Земята",
        "description": "Космическото време засяга електрическите мрежи, сателитите, GPS, авиацията и др. Ето как слънчевата активност оформя съвременните технологии."
      }
    }
  },
  {
    "slug": "what-is-iss-how-to-track",
    "title": "What is the ISS and How to Track It",
    "description": "The International Space Station is the brightest object in the night sky after the Moon. Learn what it is, how to spot it, and how to track it in real time.",
    "date": "2026-05-06",
    "readingTime": 5,
    "category": "guide",
    "coverEmoji": "🛰️",
    "translations": {
      "bg": {
        "title": "Какво е ISS и как да я проследим",
        "description": "Международната космическа станция е най-яркият обект в нощното небе след Луната. Научете как да я забележите и проследите в реално време."
      }
    }
  }
];
