import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'bg' | 'es' | 'fr' | 'de' | 'ru' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.forecast': 'Forecast',
    'nav.aurora': 'Aurora',
    'nav.alerts': 'Alerts',
    'nav.mood': 'Mood',
    'nav.pricing': 'Pricing',

    // Mood Page
    'mood.title': 'How are you feeling today?',
    'mood.subtitle': 'Share how you feel during space weather events',
    'mood.participants': 'Participants (24h)',
    'mood.currentKp': 'Current Kp Index',
    'mood.topMood': 'Most Common Rating',
    'mood.rateTitle': 'Rate how you feel',
    'mood.great': 'Great',
    'mood.good': 'Good',
    'mood.okay': 'Okay',
    'mood.bad': 'Bad',
    'mood.terrible': 'Terrible',
    'mood.symptomsQuestion': 'Do you have any of these symptoms? (optional)',
    'mood.symptom.headache': 'Headache',
    'mood.symptom.dizzy': 'Dizziness',
    'mood.symptom.anxiety': 'Anxiety',
    'mood.symptom.insomnia': 'Insomnia',
    'mood.symptom.fatigue': 'Fatigue',
    'mood.symptom.irritability': 'Irritability',
    'mood.symptom.concentration': 'Lack of concentration',
    'mood.symptom.palpitations': 'Heart palpitations',
    'mood.submit': 'Submit Rating',
    'mood.thankYou': 'Thank you!',
    'mood.alreadySubmitted': 'You have already rated how you feel today. You can vote again tomorrow.',
    'mood.stats24h': 'Statistics for the last 24 hours',
    'mood.noData': 'No data yet for the last 24 hours.',
    'mood.about': 'About this section',
    'mood.aboutText1': 'Space weather can affect how people feel. This page allows you to share how you feel and see how others feel.',
    'mood.aboutText2': 'Your data is completely anonymous and used only for statistical purposes. You can vote once a day.',
    'mood.error': 'Error saving. Please try again.',

    // Home Page
    'home.hero.title': 'Space Weather Monitoring',
    'home.hero.subtitle': 'Real-time data from NOAA Space Weather Prediction Center',
    'home.hero.cta': 'View Dashboard',
    'home.features.title': 'Comprehensive Space Weather Data',
    'home.features.subtitle': 'Everything you need to monitor solar activity',
    'home.feature1.title': 'Real-time Monitoring',
    'home.feature1.desc': 'Live data from NOAA satellites and ground stations',
    'home.feature2.title': 'Solar Flare Alerts',
    'home.feature2.desc': 'Instant notifications for X-class and M-class flares',
    'home.feature3.title': 'Aurora Predictions',
    'home.feature3.desc': 'Accurate forecasts for northern lights visibility',
    'home.feature4.title': '27-Day Forecast',
    'home.feature4.desc': 'Extended predictions based on solar rotation',

    // Dashboard
    'dashboard.title': 'Space Weather Dashboard',
    'dashboard.solarWind': 'Solar Wind',
    'dashboard.kpIndex': 'Kp Index',
    'dashboard.geomagneticActivity': 'Geomagnetic Activity',
    'dashboard.solarFlares': 'Solar Flares',
    'dashboard.noData': 'No data available',
    'dashboard.speed': 'Speed',
    'dashboard.density': 'Density',
    'dashboard.temperature': 'Temperature',
    'dashboard.currentLevel': 'Current Level',
    'dashboard.status': 'Status',
    'dashboard.recentActivity': 'Recent Activity',

    // Forecast
    'forecast.title': '27-Day Space Weather Forecast',
    'forecast.subtitle': 'Based on solar rotation and historical patterns',
    'forecast.kpForecast': 'Kp Index Forecast',
    'forecast.date': 'Date',
    'forecast.predicted': 'Predicted Kp',
    'forecast.confidence': 'Confidence',

    // Aurora
    'aurora.title': 'Aurora Forecast',
    'aurora.subtitle': 'Northern Lights visibility predictions',
    'aurora.currentConditions': 'Current Conditions',
    'aurora.visibility': 'Aurora Visibility',
    'aurora.location': 'Your Location',
    'aurora.excellent': 'Excellent',
    'aurora.good': 'Good',
    'aurora.moderate': 'Moderate',
    'aurora.low': 'Low',
    'aurora.none': 'None',

    // Alerts
    'alerts.title': 'Space Weather Alerts',
    'alerts.subtitle': 'Real-time notifications for significant events',
    'alerts.active': 'Active Alerts',
    'alerts.noActive': 'No active alerts',
    'alerts.recent': 'Recent Alerts',
    'alerts.type': 'Type',
    'alerts.severity': 'Severity',
    'alerts.issued': 'Issued',

    // Pricing
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Get the data you need',
    'pricing.free': 'Free',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.month': '/month',
    'pricing.getStarted': 'Get Started',
    'pricing.contactUs': 'Contact Us',

    // Footer
    'footer.tagline': 'Real-time space weather monitoring',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.api': 'API',
    'footer.support': 'Support',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',
    'footer.rights': 'All rights reserved',
  },
  bg: {
    // Navigation
    'nav.home': 'Начало',
    'nav.dashboard': 'Табло',
    'nav.forecast': 'Прогноза',
    'nav.aurora': 'Аврора',
    'nav.alerts': 'Известия',
    'nav.mood': 'Настроение',
    'nav.pricing': 'Цени',

    // Mood Page
    'mood.title': 'Как се чувствате днес?',
    'mood.subtitle': 'Споделете как се чувствате по време на космически събития',
    'mood.participants': 'Участници (24ч)',
    'mood.currentKp': 'Текущ Kp индекс',
    'mood.topMood': 'Най-честа оценка',
    'mood.rateTitle': 'Оценете как се чувствате',
    'mood.great': 'Чудесно',
    'mood.good': 'Добре',
    'mood.okay': 'Нормално',
    'mood.bad': 'Лошо',
    'mood.terrible': 'Ужасно',
    'mood.symptomsQuestion': 'Имате ли някои от тези симптоми? (по избор)',
    'mood.symptom.headache': 'Главоболие',
    'mood.symptom.dizzy': 'Замаяност',
    'mood.symptom.anxiety': 'Безпокойство',
    'mood.symptom.insomnia': 'Безсъние',
    'mood.symptom.fatigue': 'Умора',
    'mood.symptom.irritability': 'Раздразнителност',
    'mood.symptom.concentration': 'Липса на концентрация',
    'mood.symptom.palpitations': 'Сърцебиене',
    'mood.submit': 'Изпрати оценка',
    'mood.thankYou': 'Благодарим!',
    'mood.alreadySubmitted': 'Вече сте оценили как се чувствате днес. Можете да гласувате отново утре.',
    'mood.stats24h': 'Статистика за последните 24 часа',
    'mood.noData': 'Все още няма данни за последните 24 часа.',
    'mood.about': 'За този раздел',
    'mood.aboutText1': 'Космическото време може да влияе на самочувствието на хората. Тази страница ви позволява да споделите как се чувствате и да видите как се чувстват другите.',
    'mood.aboutText2': 'Вашите данни са напълно анонимни и се използват само за статистически цели. Можете да гласувате веднъж на ден.',
    'mood.error': 'Грешка при записване. Моля, опитайте отново.',

    // Home Page
    'home.hero.title': 'Наблюдение на космическото време',
    'home.hero.subtitle': 'Данни в реално време от NOAA Център за прогноза на космическото време',
    'home.hero.cta': 'Виж таблото',
    'home.features.title': 'Цялостни данни за космическото време',
    'home.features.subtitle': 'Всичко необходимо за наблюдение на слънчевата активност',
    'home.feature1.title': 'Наблюдение в реално време',
    'home.feature1.desc': 'Актуални данни от NOAA сателити и наземни станции',
    'home.feature2.title': 'Известия за слънчеви изригвания',
    'home.feature2.desc': 'Моментални уведомления за X и M клас изригвания',
    'home.feature3.title': 'Прогнози за аврора',
    'home.feature3.desc': 'Точни прогнози за видимост на северното сияние',
    'home.feature4.title': '27-дневна прогноза',
    'home.feature4.desc': 'Разширени прогнози базирани на слънчевата ротация',

    // Dashboard
    'dashboard.title': 'Табло за космическо време',
    'dashboard.solarWind': 'Слънчев вятър',
    'dashboard.kpIndex': 'Kp индекс',
    'dashboard.geomagneticActivity': 'Геомагнитна активност',
    'dashboard.solarFlares': 'Слънчеви изригвания',
    'dashboard.noData': 'Няма налични данни',
    'dashboard.speed': 'Скорост',
    'dashboard.density': 'Плътност',
    'dashboard.temperature': 'Температура',
    'dashboard.currentLevel': 'Текущо ниво',
    'dashboard.status': 'Статус',
    'dashboard.recentActivity': 'Скорошна активност',

    // Forecast
    'forecast.title': '27-дневна прогноза за космическо време',
    'forecast.subtitle': 'Базирана на слънчева ротация и исторически модели',
    'forecast.kpForecast': 'Прогноза за Kp индекс',
    'forecast.date': 'Дата',
    'forecast.predicted': 'Прогнозиран Kp',
    'forecast.confidence': 'Увереност',

    // Aurora
    'aurora.title': 'Прогноза за аврора',
    'aurora.subtitle': 'Прогнози за видимост на северното сияние',
    'aurora.currentConditions': 'Текущи условия',
    'aurora.visibility': 'Видимост на аврора',
    'aurora.location': 'Вашето местоположение',
    'aurora.excellent': 'Отлична',
    'aurora.good': 'Добра',
    'aurora.moderate': 'Умерена',
    'aurora.low': 'Ниска',
    'aurora.none': 'Няма',

    // Alerts
    'alerts.title': 'Известия за космическо време',
    'alerts.subtitle': 'Уведомления в реално време за значителни събития',
    'alerts.active': 'Активни известия',
    'alerts.noActive': 'Няма активни известия',
    'alerts.recent': 'Скорошни известия',
    'alerts.type': 'Тип',
    'alerts.severity': 'Сериозност',
    'alerts.issued': 'Издадено',

    // Pricing
    'pricing.title': 'Изберете вашия план',
    'pricing.subtitle': 'Получете необходимите данни',
    'pricing.free': 'Безплатно',
    'pricing.pro': 'Професионален',
    'pricing.enterprise': 'Корпоративен',
    'pricing.month': '/месец',
    'pricing.getStarted': 'Започнете',
    'pricing.contactUs': 'Свържете се с нас',

    // Footer
    'footer.tagline': 'Наблюдение на космическо време в реално време',
    'footer.resources': 'Ресурси',
    'footer.documentation': 'Документация',
    'footer.api': 'API',
    'footer.support': 'Поддръжка',
    'footer.company': 'Компания',
    'footer.about': 'За нас',
    'footer.contact': 'Контакт',
    'footer.privacy': 'Поверителност',
    'footer.rights': 'Всички права запазени',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.forecast': 'Pronóstico',
    'nav.aurora': 'Aurora',
    'nav.alerts': 'Alertas',
    'nav.mood': 'Estado de ánimo',
    'nav.pricing': 'Precios',

    // Mood Page
    'mood.title': '¿Cómo te sientes hoy?',
    'mood.subtitle': 'Comparte cómo te sientes durante eventos climáticos espaciales',
    'mood.participants': 'Participantes (24h)',
    'mood.currentKp': 'Índice Kp actual',
    'mood.topMood': 'Calificación más común',
    'mood.rateTitle': 'Califica cómo te sientes',
    'mood.great': 'Excelente',
    'mood.good': 'Bien',
    'mood.okay': 'Regular',
    'mood.bad': 'Mal',
    'mood.terrible': 'Terrible',
    'mood.symptomsQuestion': '¿Tienes alguno de estos síntomas? (opcional)',
    'mood.symptom.headache': 'Dolor de cabeza',
    'mood.symptom.dizzy': 'Mareos',
    'mood.symptom.anxiety': 'Ansiedad',
    'mood.symptom.insomnia': 'Insomnio',
    'mood.symptom.fatigue': 'Fatiga',
    'mood.symptom.irritability': 'Irritabilidad',
    'mood.symptom.concentration': 'Falta de concentración',
    'mood.symptom.palpitations': 'Palpitaciones',
    'mood.submit': 'Enviar calificación',
    'mood.thankYou': '¡Gracias!',
    'mood.alreadySubmitted': 'Ya has calificado cómo te sientes hoy. Puedes votar de nuevo mañana.',
    'mood.stats24h': 'Estadísticas de las últimas 24 horas',
    'mood.noData': 'Aún no hay datos de las últimas 24 horas.',
    'mood.about': 'Acerca de esta sección',
    'mood.aboutText1': 'El clima espacial puede afectar cómo se sienten las personas. Esta página te permite compartir cómo te sientes y ver cómo se sienten los demás.',
    'mood.aboutText2': 'Tus datos son completamente anónimos y se utilizan solo con fines estadísticos. Puedes votar una vez al día.',
    'mood.error': 'Error al guardar. Por favor, inténtalo de nuevo.',

    // Home Page
    'home.hero.title': 'Monitoreo del clima espacial',
    'home.hero.subtitle': 'Datos en tiempo real del Centro de Predicción del Clima Espacial de NOAA',
    'home.hero.cta': 'Ver panel',
    'home.features.title': 'Datos completos del clima espacial',
    'home.features.subtitle': 'Todo lo que necesitas para monitorear la actividad solar',
    'home.feature1.title': 'Monitoreo en tiempo real',
    'home.feature1.desc': 'Datos en vivo de satélites NOAA y estaciones terrestres',
    'home.feature2.title': 'Alertas de llamaradas solares',
    'home.feature2.desc': 'Notificaciones instantáneas para llamaradas clase X y M',
    'home.feature3.title': 'Predicciones de aurora',
    'home.feature3.desc': 'Pronósticos precisos de visibilidad de auroras boreales',
    'home.feature4.title': 'Pronóstico de 27 días',
    'home.feature4.desc': 'Predicciones extendidas basadas en rotación solar',

    // Dashboard
    'dashboard.title': 'Panel de clima espacial',
    'dashboard.solarWind': 'Viento solar',
    'dashboard.kpIndex': 'Índice Kp',
    'dashboard.geomagneticActivity': 'Actividad geomagnética',
    'dashboard.solarFlares': 'Llamaradas solares',
    'dashboard.noData': 'No hay datos disponibles',
    'dashboard.speed': 'Velocidad',
    'dashboard.density': 'Densidad',
    'dashboard.temperature': 'Temperatura',
    'dashboard.currentLevel': 'Nivel actual',
    'dashboard.status': 'Estado',
    'dashboard.recentActivity': 'Actividad reciente',

    // Forecast
    'forecast.title': 'Pronóstico del clima espacial de 27 días',
    'forecast.subtitle': 'Basado en rotación solar y patrones históricos',
    'forecast.kpForecast': 'Pronóstico del índice Kp',
    'forecast.date': 'Fecha',
    'forecast.predicted': 'Kp predicho',
    'forecast.confidence': 'Confianza',

    // Aurora
    'aurora.title': 'Pronóstico de aurora',
    'aurora.subtitle': 'Predicciones de visibilidad de auroras boreales',
    'aurora.currentConditions': 'Condiciones actuales',
    'aurora.visibility': 'Visibilidad de aurora',
    'aurora.location': 'Tu ubicación',
    'aurora.excellent': 'Excelente',
    'aurora.good': 'Buena',
    'aurora.moderate': 'Moderada',
    'aurora.low': 'Baja',
    'aurora.none': 'Ninguna',

    // Alerts
    'alerts.title': 'Alertas de clima espacial',
    'alerts.subtitle': 'Notificaciones en tiempo real de eventos significativos',
    'alerts.active': 'Alertas activas',
    'alerts.noActive': 'No hay alertas activas',
    'alerts.recent': 'Alertas recientes',
    'alerts.type': 'Tipo',
    'alerts.severity': 'Gravedad',
    'alerts.issued': 'Emitido',

    // Pricing
    'pricing.title': 'Elige tu plan',
    'pricing.subtitle': 'Obtén los datos que necesitas',
    'pricing.free': 'Gratis',
    'pricing.pro': 'Profesional',
    'pricing.enterprise': 'Empresarial',
    'pricing.month': '/mes',
    'pricing.getStarted': 'Comenzar',
    'pricing.contactUs': 'Contáctanos',

    // Footer
    'footer.tagline': 'Monitoreo de clima espacial en tiempo real',
    'footer.resources': 'Recursos',
    'footer.documentation': 'Documentación',
    'footer.api': 'API',
    'footer.support': 'Soporte',
    'footer.company': 'Compañía',
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Privacidad',
    'footer.rights': 'Todos los derechos reservados',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.forecast': 'Prévisions',
    'nav.aurora': 'Aurore',
    'nav.alerts': 'Alertes',
    'nav.mood': 'Humeur',
    'nav.pricing': 'Tarifs',

    // Mood Page
    'mood.title': 'Comment vous sentez-vous aujourd\'hui?',
    'mood.subtitle': 'Partagez comment vous vous sentez pendant les événements météorologiques spatiaux',
    'mood.participants': 'Participants (24h)',
    'mood.currentKp': 'Indice Kp actuel',
    'mood.topMood': 'Évaluation la plus courante',
    'mood.rateTitle': 'Évaluez comment vous vous sentez',
    'mood.great': 'Excellent',
    'mood.good': 'Bien',
    'mood.okay': 'Correct',
    'mood.bad': 'Mauvais',
    'mood.terrible': 'Terrible',
    'mood.symptomsQuestion': 'Avez-vous l\'un de ces symptômes? (facultatif)',
    'mood.symptom.headache': 'Mal de tête',
    'mood.symptom.dizzy': 'Vertiges',
    'mood.symptom.anxiety': 'Anxiété',
    'mood.symptom.insomnia': 'Insomnie',
    'mood.symptom.fatigue': 'Fatigue',
    'mood.symptom.irritability': 'Irritabilité',
    'mood.symptom.concentration': 'Manque de concentration',
    'mood.symptom.palpitations': 'Palpitations',
    'mood.submit': 'Soumettre l\'évaluation',
    'mood.thankYou': 'Merci!',
    'mood.alreadySubmitted': 'Vous avez déjà évalué comment vous vous sentez aujourd\'hui. Vous pouvez voter à nouveau demain.',
    'mood.stats24h': 'Statistiques des dernières 24 heures',
    'mood.noData': 'Pas encore de données pour les dernières 24 heures.',
    'mood.about': 'À propos de cette section',
    'mood.aboutText1': 'La météo spatiale peut affecter comment les gens se sentent. Cette page vous permet de partager comment vous vous sentez et de voir comment les autres se sentent.',
    'mood.aboutText2': 'Vos données sont complètement anonymes et utilisées uniquement à des fins statistiques. Vous pouvez voter une fois par jour.',
    'mood.error': 'Erreur lors de l\'enregistrement. Veuillez réessayer.',

    // Home Page
    'home.hero.title': 'Surveillance de la météo spatiale',
    'home.hero.subtitle': 'Données en temps réel du Centre de prévision de la météo spatiale de la NOAA',
    'home.hero.cta': 'Voir le tableau de bord',
    'home.features.title': 'Données complètes sur la météo spatiale',
    'home.features.subtitle': 'Tout ce dont vous avez besoin pour surveiller l\'activité solaire',
    'home.feature1.title': 'Surveillance en temps réel',
    'home.feature1.desc': 'Données en direct des satellites NOAA et des stations au sol',
    'home.feature2.title': 'Alertes d\'éruptions solaires',
    'home.feature2.desc': 'Notifications instantanées pour les éruptions de classe X et M',
    'home.feature3.title': 'Prédictions d\'aurores',
    'home.feature3.desc': 'Prévisions précises de la visibilité des aurores boréales',
    'home.feature4.title': 'Prévisions sur 27 jours',
    'home.feature4.desc': 'Prédictions étendues basées sur la rotation solaire',

    // Dashboard
    'dashboard.title': 'Tableau de bord de la météo spatiale',
    'dashboard.solarWind': 'Vent solaire',
    'dashboard.kpIndex': 'Indice Kp',
    'dashboard.geomagneticActivity': 'Activité géomagnétique',
    'dashboard.solarFlares': 'Éruptions solaires',
    'dashboard.noData': 'Aucune donnée disponible',
    'dashboard.speed': 'Vitesse',
    'dashboard.density': 'Densité',
    'dashboard.temperature': 'Température',
    'dashboard.currentLevel': 'Niveau actuel',
    'dashboard.status': 'Statut',
    'dashboard.recentActivity': 'Activité récente',

    // Forecast
    'forecast.title': 'Prévisions météo spatiales sur 27 jours',
    'forecast.subtitle': 'Basé sur la rotation solaire et les modèles historiques',
    'forecast.kpForecast': 'Prévisions de l\'indice Kp',
    'forecast.date': 'Date',
    'forecast.predicted': 'Kp prédit',
    'forecast.confidence': 'Confiance',

    // Aurora
    'aurora.title': 'Prévisions d\'aurores',
    'aurora.subtitle': 'Prédictions de visibilité des aurores boréales',
    'aurora.currentConditions': 'Conditions actuelles',
    'aurora.visibility': 'Visibilité de l\'aurore',
    'aurora.location': 'Votre emplacement',
    'aurora.excellent': 'Excellente',
    'aurora.good': 'Bonne',
    'aurora.moderate': 'Modérée',
    'aurora.low': 'Faible',
    'aurora.none': 'Aucune',

    // Alerts
    'alerts.title': 'Alertes météo spatiale',
    'alerts.subtitle': 'Notifications en temps réel pour les événements significatifs',
    'alerts.active': 'Alertes actives',
    'alerts.noActive': 'Aucune alerte active',
    'alerts.recent': 'Alertes récentes',
    'alerts.type': 'Type',
    'alerts.severity': 'Gravité',
    'alerts.issued': 'Émis',

    // Pricing
    'pricing.title': 'Choisissez votre plan',
    'pricing.subtitle': 'Obtenez les données dont vous avez besoin',
    'pricing.free': 'Gratuit',
    'pricing.pro': 'Professionnel',
    'pricing.enterprise': 'Entreprise',
    'pricing.month': '/mois',
    'pricing.getStarted': 'Commencer',
    'pricing.contactUs': 'Nous contacter',

    // Footer
    'footer.tagline': 'Surveillance de la météo spatiale en temps réel',
    'footer.resources': 'Ressources',
    'footer.documentation': 'Documentation',
    'footer.api': 'API',
    'footer.support': 'Support',
    'footer.company': 'Compagnie',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.privacy': 'Confidentialité',
    'footer.rights': 'Tous droits réservés',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.forecast': 'Vorhersage',
    'nav.aurora': 'Aurora',
    'nav.alerts': 'Warnungen',
    'nav.mood': 'Stimmung',
    'nav.pricing': 'Preise',

    // Mood Page
    'mood.title': 'Wie fühlen Sie sich heute?',
    'mood.subtitle': 'Teilen Sie mit, wie Sie sich während Weltraumwetterereignissen fühlen',
    'mood.participants': 'Teilnehmer (24h)',
    'mood.currentKp': 'Aktueller Kp-Index',
    'mood.topMood': 'Häufigste Bewertung',
    'mood.rateTitle': 'Bewerten Sie, wie Sie sich fühlen',
    'mood.great': 'Großartig',
    'mood.good': 'Gut',
    'mood.okay': 'Okay',
    'mood.bad': 'Schlecht',
    'mood.terrible': 'Schrecklich',
    'mood.symptomsQuestion': 'Haben Sie eines dieser Symptome? (optional)',
    'mood.symptom.headache': 'Kopfschmerzen',
    'mood.symptom.dizzy': 'Schwindel',
    'mood.symptom.anxiety': 'Angst',
    'mood.symptom.insomnia': 'Schlaflosigkeit',
    'mood.symptom.fatigue': 'Müdigkeit',
    'mood.symptom.irritability': 'Reizbarkeit',
    'mood.symptom.concentration': 'Konzentrationsmangel',
    'mood.symptom.palpitations': 'Herzrasen',
    'mood.submit': 'Bewertung absenden',
    'mood.thankYou': 'Vielen Dank!',
    'mood.alreadySubmitted': 'Sie haben heute bereits bewertet, wie Sie sich fühlen. Sie können morgen wieder abstimmen.',
    'mood.stats24h': 'Statistiken der letzten 24 Stunden',
    'mood.noData': 'Noch keine Daten für die letzten 24 Stunden.',
    'mood.about': 'Über diesen Bereich',
    'mood.aboutText1': 'Das Weltraumwetter kann beeinflussen, wie sich Menschen fühlen. Diese Seite ermöglicht es Ihnen, mitzuteilen, wie Sie sich fühlen und zu sehen, wie andere sich fühlen.',
    'mood.aboutText2': 'Ihre Daten sind völlig anonymisiert und werden nur für statistische Zwecke verwendet. Sie können einmal täglich abstimmen.',
    'mood.error': 'Fehler beim Speichern. Bitte versuchen Sie es erneut.',

    // Home Page
    'home.hero.title': 'Weltraumwetter-Überwachung',
    'home.hero.subtitle': 'Echtzeitdaten vom NOAA Weltraumwetter-Vorhersagezentrum',
    'home.hero.cta': 'Dashboard ansehen',
    'home.features.title': 'Umfassende Weltraumwetterdaten',
    'home.features.subtitle': 'Alles, was Sie zur Überwachung der Sonnenaktivität benötigen',
    'home.feature1.title': 'Echtzeitüberwachung',
    'home.feature1.desc': 'Live-Daten von NOAA-Satelliten und Bodenstationen',
    'home.feature2.title': 'Sonneneruptionswarnungen',
    'home.feature2.desc': 'Sofortige Benachrichtigungen für X- und M-Klasse-Eruptionen',
    'home.feature3.title': 'Polarlichtervorhersagen',
    'home.feature3.desc': 'Genaue Vorhersagen zur Sichtbarkeit von Polarlichtern',
    'home.feature4.title': '27-Tage-Vorhersage',
    'home.feature4.desc': 'Erweiterte Vorhersagen basierend auf Sonnenrotation',

    // Dashboard
    'dashboard.title': 'Weltraumwetter-Dashboard',
    'dashboard.solarWind': 'Sonnenwind',
    'dashboard.kpIndex': 'Kp-Index',
    'dashboard.geomagneticActivity': 'Geomagnetische Aktivität',
    'dashboard.solarFlares': 'Sonneneruptionen',
    'dashboard.noData': 'Keine Daten verfügbar',
    'dashboard.speed': 'Geschwindigkeit',
    'dashboard.density': 'Dichte',
    'dashboard.temperature': 'Temperatur',
    'dashboard.currentLevel': 'Aktuelles Niveau',
    'dashboard.status': 'Status',
    'dashboard.recentActivity': 'Letzte Aktivität',

    // Forecast
    'forecast.title': '27-Tage Weltraumwetter-Vorhersage',
    'forecast.subtitle': 'Basierend auf Sonnenrotation und historischen Mustern',
    'forecast.kpForecast': 'Kp-Index-Vorhersage',
    'forecast.date': 'Datum',
    'forecast.predicted': 'Vorhergesagter Kp',
    'forecast.confidence': 'Konfidenz',

    // Aurora
    'aurora.title': 'Polarlicht-Vorhersage',
    'aurora.subtitle': 'Vorhersagen zur Sichtbarkeit von Polarlichtern',
    'aurora.currentConditions': 'Aktuelle Bedingungen',
    'aurora.visibility': 'Aurora-Sichtbarkeit',
    'aurora.location': 'Ihr Standort',
    'aurora.excellent': 'Ausgezeichnet',
    'aurora.good': 'Gut',
    'aurora.moderate': 'Mäßig',
    'aurora.low': 'Niedrig',
    'aurora.none': 'Keine',

    // Alerts
    'alerts.title': 'Weltraumwetter-Warnungen',
    'alerts.subtitle': 'Echtzeitbenachrichtigungen für bedeutende Ereignisse',
    'alerts.active': 'Aktive Warnungen',
    'alerts.noActive': 'Keine aktiven Warnungen',
    'alerts.recent': 'Letzte Warnungen',
    'alerts.type': 'Typ',
    'alerts.severity': 'Schwere',
    'alerts.issued': 'Herausgegeben',

    // Pricing
    'pricing.title': 'Wählen Sie Ihren Plan',
    'pricing.subtitle': 'Erhalten Sie die Daten, die Sie benötigen',
    'pricing.free': 'Kostenlos',
    'pricing.pro': 'Professionell',
    'pricing.enterprise': 'Unternehmen',
    'pricing.month': '/Monat',
    'pricing.getStarted': 'Loslegen',
    'pricing.contactUs': 'Kontaktieren Sie uns',

    // Footer
    'footer.tagline': 'Echtzeit-Weltraumwetter-Überwachung',
    'footer.resources': 'Ressourcen',
    'footer.documentation': 'Dokumentation',
    'footer.api': 'API',
    'footer.support': 'Support',
    'footer.company': 'Unternehmen',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Datenschutz',
    'footer.rights': 'Alle Rechte vorbehalten',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель',
    'nav.forecast': 'Прогноз',
    'nav.aurora': 'Аврора',
    'nav.alerts': 'Оповещения',
    'nav.mood': 'Настроение',
    'nav.pricing': 'Цены',

    // Mood Page
    'mood.title': 'Как вы себя чувствуете сегодня?',
    'mood.subtitle': 'Поделитесь, как вы себя чувствуете во время космических событий',
    'mood.participants': 'Участники (24ч)',
    'mood.currentKp': 'Текущий Kp индекс',
    'mood.topMood': 'Наиболее частая оценка',
    'mood.rateTitle': 'Оцените, как вы себя чувствуете',
    'mood.great': 'Отлично',
    'mood.good': 'Хорошо',
    'mood.okay': 'Нормально',
    'mood.bad': 'Плохо',
    'mood.terrible': 'Ужасно',
    'mood.symptomsQuestion': 'Есть ли у вас какие-либо из этих симптомов? (необязательно)',
    'mood.symptom.headache': 'Головная боль',
    'mood.symptom.dizzy': 'Головокружение',
    'mood.symptom.anxiety': 'Тревожность',
    'mood.symptom.insomnia': 'Бессонница',
    'mood.symptom.fatigue': 'Усталость',
    'mood.symptom.irritability': 'Раздражительность',
    'mood.symptom.concentration': 'Отсутствие концентрации',
    'mood.symptom.palpitations': 'Учащенное сердцебиение',
    'mood.submit': 'Отправить оценку',
    'mood.thankYou': 'Спасибо!',
    'mood.alreadySubmitted': 'Вы уже оценили, как себя чувствуете сегодня. Вы можете проголосовать снова завтра.',
    'mood.stats24h': 'Статистика за последние 24 часа',
    'mood.noData': 'Пока нет данных за последние 24 часа.',
    'mood.about': 'Об этом разделе',
    'mood.aboutText1': 'Космическая погода может влиять на самочувствие людей. Эта страница позволяет вам поделиться, как вы себя чувствуете, и увидеть, как чувствуют себя другие.',
    'mood.aboutText2': 'Ваши данные полностью анонимны и используются только в статистических целях. Вы можете голосовать один раз в день.',
    'mood.error': 'Ошибка сохранения. Пожалуйста, попробуйте снова.',

    // Home Page
    'home.hero.title': 'Мониторинг космической погоды',
    'home.hero.subtitle': 'Данные в реальном времени от Центра прогнозирования космической погоды NOAA',
    'home.hero.cta': 'Просмотр панели',
    'home.features.title': 'Полные данные о космической погоде',
    'home.features.subtitle': 'Все, что вам нужно для мониторинга солнечной активности',
    'home.feature1.title': 'Мониторинг в реальном времени',
    'home.feature1.desc': 'Оперативные данные со спутников NOAA и наземных станций',
    'home.feature2.title': 'Оповещения о солнечных вспышках',
    'home.feature2.desc': 'Мгновенные уведомления о вспышках класса X и M',
    'home.feature3.title': 'Прогнозы полярных сияний',
    'home.feature3.desc': 'Точные прогнозы видимости северного сияния',
    'home.feature4.title': '27-дневный прогноз',
    'home.feature4.desc': 'Расширенные прогнозы на основе солнечного вращения',

    // Dashboard
    'dashboard.title': 'Панель космической погоды',
    'dashboard.solarWind': 'Солнечный ветер',
    'dashboard.kpIndex': 'Kp индекс',
    'dashboard.geomagneticActivity': 'Геомагнитная активность',
    'dashboard.solarFlares': 'Солнечные вспышки',
    'dashboard.noData': 'Нет доступных данных',
    'dashboard.speed': 'Скорость',
    'dashboard.density': 'Плотность',
    'dashboard.temperature': 'Температура',
    'dashboard.currentLevel': 'Текущий уровень',
    'dashboard.status': 'Статус',
    'dashboard.recentActivity': 'Последняя активность',

    // Forecast
    'forecast.title': '27-дневный прогноз космической погоды',
    'forecast.subtitle': 'На основе солнечного вращения и исторических данных',
    'forecast.kpForecast': 'Прогноз Kp индекса',
    'forecast.date': 'Дата',
    'forecast.predicted': 'Прогнозируемый Kp',
    'forecast.confidence': 'Достоверность',

    // Aurora
    'aurora.title': 'Прогноз полярных сияний',
    'aurora.subtitle': 'Прогнозы видимости северного сияния',
    'aurora.currentConditions': 'Текущие условия',
    'aurora.visibility': 'Видимость полярного сияния',
    'aurora.location': 'Ваше местоположение',
    'aurora.excellent': 'Отличная',
    'aurora.good': 'Хорошая',
    'aurora.moderate': 'Умеренная',
    'aurora.low': 'Низкая',
    'aurora.none': 'Нет',

    // Alerts
    'alerts.title': 'Оповещения о космической погоде',
    'alerts.subtitle': 'Уведомления о значительных событиях в реальном времени',
    'alerts.active': 'Активные оповещения',
    'alerts.noActive': 'Нет активных оповещений',
    'alerts.recent': 'Последние оповещения',
    'alerts.type': 'Тип',
    'alerts.severity': 'Серьезность',
    'alerts.issued': 'Выдано',

    // Pricing
    'pricing.title': 'Выберите свой план',
    'pricing.subtitle': 'Получите необходимые данные',
    'pricing.free': 'Бесплатный',
    'pricing.pro': 'Профессиональный',
    'pricing.enterprise': 'Корпоративный',
    'pricing.month': '/месяц',
    'pricing.getStarted': 'Начать',
    'pricing.contactUs': 'Свяжитесь с нами',

    // Footer
    'footer.tagline': 'Мониторинг космической погоды в реальном времени',
    'footer.resources': 'Ресурсы',
    'footer.documentation': 'Документация',
    'footer.api': 'API',
    'footer.support': 'Поддержка',
    'footer.company': 'Компания',
    'footer.about': 'О нас',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Конфиденциальность',
    'footer.rights': 'Все права защищены',
  },
  zh: {
    // Navigation
    'nav.home': '主页',
    'nav.dashboard': '仪表板',
    'nav.forecast': '预报',
    'nav.aurora': '极光',
    'nav.alerts': '警报',
    'nav.mood': '心情',
    'nav.pricing': '价格',

    // Mood Page
    'mood.title': '今天感觉如何？',
    'mood.subtitle': '分享您在太空天气事件期间的感受',
    'mood.participants': '参与者（24小时）',
    'mood.currentKp': '当前Kp指数',
    'mood.topMood': '最常见的评级',
    'mood.rateTitle': '评价您的感受',
    'mood.great': '很好',
    'mood.good': '好',
    'mood.okay': '还行',
    'mood.bad': '不好',
    'mood.terrible': '糟糕',
    'mood.symptomsQuestion': '您有这些症状吗？（可选）',
    'mood.symptom.headache': '头痛',
    'mood.symptom.dizzy': '头晕',
    'mood.symptom.anxiety': '焦虑',
    'mood.symptom.insomnia': '失眠',
    'mood.symptom.fatigue': '疲劳',
    'mood.symptom.irritability': '易怒',
    'mood.symptom.concentration': '注意力不集中',
    'mood.symptom.palpitations': '心悸',
    'mood.submit': '提交评价',
    'mood.thankYou': '谢谢！',
    'mood.alreadySubmitted': '您今天已经评价过感受了。明天可以再次投票。',
    'mood.stats24h': '过去24小时的统计',
    'mood.noData': '过去24小时尚无数据。',
    'mood.about': '关于此部分',
    'mood.aboutText1': '太空天气可能会影响人们的感受。此页面允许您分享自己的感受并查看他人的感受。',
    'mood.aboutText2': '您的数据完全匿名，仅用于统计目的。您每天可以投票一次。',
    'mood.error': '保存错误。请重试。',

    // Home Page
    'home.hero.title': '太空天气监测',
    'home.hero.subtitle': '来自NOAA太空天气预报中心的实时数据',
    'home.hero.cta': '查看仪表板',
    'home.features.title': '全面的太空天气数据',
    'home.features.subtitle': '监测太阳活动所需的一切',
    'home.feature1.title': '实时监测',
    'home.feature1.desc': '来自NOAA卫星和地面站的实时数据',
    'home.feature2.title': '太阳耀斑警报',
    'home.feature2.desc': 'X级和M级耀斑的即时通知',
    'home.feature3.title': '极光预测',
    'home.feature3.desc': '北极光可见性的准确预测',
    'home.feature4.title': '27天预报',
    'home.feature4.desc': '基于太阳自转的延长预测',

    // Dashboard
    'dashboard.title': '太空天气仪表板',
    'dashboard.solarWind': '太阳风',
    'dashboard.kpIndex': 'Kp指数',
    'dashboard.geomagneticActivity': '地磁活动',
    'dashboard.solarFlares': '太阳耀斑',
    'dashboard.noData': '无可用数据',
    'dashboard.speed': '速度',
    'dashboard.density': '密度',
    'dashboard.temperature': '温度',
    'dashboard.currentLevel': '当前水平',
    'dashboard.status': '状态',
    'dashboard.recentActivity': '近期活动',

    // Forecast
    'forecast.title': '27天太空天气预报',
    'forecast.subtitle': '基于太阳自转和历史模式',
    'forecast.kpForecast': 'Kp指数预报',
    'forecast.date': '日期',
    'forecast.predicted': '预测Kp',
    'forecast.confidence': '置信度',

    // Aurora
    'aurora.title': '极光预报',
    'aurora.subtitle': '北极光可见性预测',
    'aurora.currentConditions': '当前条件',
    'aurora.visibility': '极光可见度',
    'aurora.location': '您的位置',
    'aurora.excellent': '极好',
    'aurora.good': '好',
    'aurora.moderate': '中等',
    'aurora.low': '低',
    'aurora.none': '无',

    // Alerts
    'alerts.title': '太空天气警报',
    'alerts.subtitle': '重要事件的实时通知',
    'alerts.active': '活跃警报',
    'alerts.noActive': '没有活跃警报',
    'alerts.recent': '最近警报',
    'alerts.type': '类型',
    'alerts.severity': '严重程度',
    'alerts.issued': '发布时间',

    // Pricing
    'pricing.title': '选择您的计划',
    'pricing.subtitle': '获取您需要的数据',
    'pricing.free': '免费',
    'pricing.pro': '专业版',
    'pricing.enterprise': '企业版',
    'pricing.month': '/月',
    'pricing.getStarted': '开始',
    'pricing.contactUs': '联系我们',

    // Footer
    'footer.tagline': '实时太空天气监测',
    'footer.resources': '资源',
    'footer.documentation': '文档',
    'footer.api': 'API',
    'footer.support': '支持',
    'footer.company': '公司',
    'footer.about': '关于',
    'footer.contact': '联系',
    'footer.privacy': '隐私',
    'footer.rights': '保留所有权利',
  },
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.forecast': '予報',
    'nav.aurora': 'オーロラ',
    'nav.alerts': 'アラート',
    'nav.mood': '気分',
    'nav.pricing': '価格',

    // Mood Page
    'mood.title': '今日の気分はいかがですか？',
    'mood.subtitle': '宇宙天気イベント中の気分を共有しましょう',
    'mood.participants': '参加者（24時間）',
    'mood.currentKp': '現在のKp指数',
    'mood.topMood': '最も一般的な評価',
    'mood.rateTitle': '気分を評価する',
    'mood.great': '素晴らしい',
    'mood.good': '良い',
    'mood.okay': '普通',
    'mood.bad': '悪い',
    'mood.terrible': 'ひどい',
    'mood.symptomsQuestion': 'これらの症状はありますか？（任意）',
    'mood.symptom.headache': '頭痛',
    'mood.symptom.dizzy': 'めまい',
    'mood.symptom.anxiety': '不安',
    'mood.symptom.insomnia': '不眠',
    'mood.symptom.fatigue': '疲労',
    'mood.symptom.irritability': 'イライラ',
    'mood.symptom.concentration': '集中力の欠如',
    'mood.symptom.palpitations': '動悸',
    'mood.submit': '評価を送信',
    'mood.thankYou': 'ありがとうございます！',
    'mood.alreadySubmitted': '今日はすでに気分を評価しています。明日また投票できます。',
    'mood.stats24h': '過去24時間の統計',
    'mood.noData': '過去24時間のデータはまだありません。',
    'mood.about': 'このセクションについて',
    'mood.aboutText1': '宇宙天気は人々の気分に影響を与える可能性があります。このページでは、あなたの気分を共有し、他の人の気分を見ることができます。',
    'mood.aboutText2': 'あなたのデータは完全に匿名で、統計目的にのみ使用されます。1日1回投票できます。',
    'mood.error': '保存エラー。もう一度お試しください。',

    // Home Page
    'home.hero.title': '宇宙天気モニタリング',
    'home.hero.subtitle': 'NOAA宇宙天気予報センターからのリアルタイムデータ',
    'home.hero.cta': 'ダッシュボードを表示',
    'home.features.title': '包括的な宇宙天気データ',
    'home.features.subtitle': '太陽活動を監視するために必要なすべて',
    'home.feature1.title': 'リアルタイム監視',
    'home.feature1.desc': 'NOAA衛星と地上局からのライブデータ',
    'home.feature2.title': '太陽フレアアラート',
    'home.feature2.desc': 'XクラスとMクラスのフレアの即時通知',
    'home.feature3.title': 'オーロラ予報',
    'home.feature3.desc': 'オーロラの視認性の正確な予報',
    'home.feature4.title': '27日間予報',
    'home.feature4.desc': '太陽の自転に基づく拡張予測',

    // Dashboard
    'dashboard.title': '宇宙天気ダッシュボード',
    'dashboard.solarWind': '太陽風',
    'dashboard.kpIndex': 'Kp指数',
    'dashboard.geomagneticActivity': '地磁気活動',
    'dashboard.solarFlares': '太陽フレア',
    'dashboard.noData': 'データがありません',
    'dashboard.speed': '速度',
    'dashboard.density': '密度',
    'dashboard.temperature': '温度',
    'dashboard.currentLevel': '現在のレベル',
    'dashboard.status': 'ステータス',
    'dashboard.recentActivity': '最近の活動',

    // Forecast
    'forecast.title': '27日間宇宙天気予報',
    'forecast.subtitle': '太陽の自転と過去のパターンに基づく',
    'forecast.kpForecast': 'Kp指数予報',
    'forecast.date': '日付',
    'forecast.predicted': '予測Kp',
    'forecast.confidence': '信頼度',

    // Aurora
    'aurora.title': 'オーロラ予報',
    'aurora.subtitle': 'オーロラの視認性予測',
    'aurora.currentConditions': '現在の状態',
    'aurora.visibility': 'オーロラの視認性',
    'aurora.location': 'あなたの場所',
    'aurora.excellent': '優秀',
    'aurora.good': '良好',
    'aurora.moderate': '中程度',
    'aurora.low': '低い',
    'aurora.none': 'なし',

    // Alerts
    'alerts.title': '宇宙天気アラート',
    'alerts.subtitle': '重要なイベントのリアルタイム通知',
    'alerts.active': 'アクティブアラート',
    'alerts.noActive': 'アクティブなアラートはありません',
    'alerts.recent': '最近のアラート',
    'alerts.type': 'タイプ',
    'alerts.severity': '重大度',
    'alerts.issued': '発行日時',

    // Pricing
    'pricing.title': 'プランを選択',
    'pricing.subtitle': '必要なデータを取得',
    'pricing.free': '無料',
    'pricing.pro': 'プロ',
    'pricing.enterprise': 'エンタープライズ',
    'pricing.month': '/月',
    'pricing.getStarted': '始める',
    'pricing.contactUs': 'お問い合わせ',

    // Footer
    'footer.tagline': 'リアルタイム宇宙天気監視',
    'footer.resources': 'リソース',
    'footer.documentation': 'ドキュメント',
    'footer.api': 'API',
    'footer.support': 'サポート',
    'footer.company': '会社',
    'footer.about': '私たちについて',
    'footer.contact': '連絡先',
    'footer.privacy': 'プライバシー',
    'footer.rights': '全著作権所有',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const languages = [
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'bg' as Language, name: 'Български', flag: '🇧🇬' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ru' as Language, name: 'Русский', flag: '🇷🇺' },
  { code: 'zh' as Language, name: '中文', flag: '🇨🇳' },
  { code: 'ja' as Language, name: '日本語', flag: '🇯🇵' },
];
