import type { MagneticLangContent } from '../magneticEffectsContent';

const da: MagneticLangContent = {
  title: 'Magnetstorme og menneskelig sundhed',
  subtitle: 'Hvordan geomagnetisk aktivitet påvirker kroppen — og hvad du kan gøre ved det.',
  sections: [
    { heading: 'Hvad er en geomagnetisk storm?', body: 'En geomagnetisk storm opstår, når et udbrud af solvind — ladede partikler fra Solen — rammer Jordens magnetfelt kraftigt nok til at forstyrre det. Forstyrrelsen kan vare fra nogle timer til flere dage. Forskere måler dens styrke med Kp-indekset (0–9) og Dst-indekset, som sporer, hvor meget feltet falder under hændelsen.\n\nStormer klassificeres G1–G5. En G1-storm (Kp 5) forårsager mindre forstyrrelser; en G5 (Kp 9) er sjælden og kan lamme elnet og satellitter.' },
    { heading: 'Hjerte-kar-systemet', body: 'Flere fagfællebedømte studier har fundet en sammenhæng mellem kraftige geomagnetiske storme og en stigning i hjerteanfald, arytmier og pludselige hjertedødsfald — særligt i de 24–48 timer efter stormens begyndelse.\n\nMekanismen menes at involvere melatoninsuppression og forstyrrelse af det autonome nervesystem, som regulerer hjertefrekvens og blodtryk. Personer med eksisterende hjertesygdom, højt blodtryk eller blodkoagulationsforstyrrelser anses for mest sårbare.\n\nUnder en G2–G3-storm eller stærkere, hvis du har hjerte-kar-lidelser, skal du undgå intens fysisk anstrengelse, holde dig godt hydreret og have din medicin inden for rækkevidde.' },
    { heading: 'Hjerne og nervesystem', body: 'Det menneskelige nervesystem er følsomt over for lavfrekvente elektromagnetiske felter. Under geomagnetiske storme rapporterer mange om hovedpine, svimmelhed, koncentrationsbesvær og en generel følelse af mental tåge.\n\nForskning tyder på, at geomagnetisk aktivitet påvirker produktionen af serotonin og melatonin i hjernen. Forstyrrede serotoninniveauer kan påvirke humør, kognition og smertesensitivitet — hvilket forklarer, hvorfor nogle mennesker føler sig mere irritable, angste eller forvirrede i aktive perioder.\n\nPersoner med epilepsi, migræne eller neurologiske tilstande kan opleve hyppigere episoder under kraftige storme.' },
    { heading: 'Søvnforstyrrelser', body: 'Pinealkirtlen producerer melatonin — det søvnregulerende hormon — som respons på mørke og Jordens naturlige magnetfelt. Geomagnetiske storme forstyrrer denne proces, hæmmer melatoninproduktionen og forstyrrer de cirkadiane rytmer.\n\nResultatet: besvær med at falde i søvn, lettere søvn, mere levende eller forstyrrende drømme og at vågne uden at føle sig udhvilet. Studier viser, at nætter med Kp ≥ 5 korrelerer med øgede indberetninger om søvnløshed i store befolkningsgrupper.\n\nFor at modvirke dette, forsøg at opretholde et regelmæssigt søvnmønster i aktive perioder, undgå skærme før sengetid og hold soveværelset så mørkt som muligt.' },
    { heading: 'Hvem er mest i risiko?', body: 'Selvom de fleste raske voksne mærker lidt eller ingen effekt af moderat geomagnetisk aktivitet, er nogle grupper mere følsomme:\n\n• Personer med hjerte-kar-sygdomme, hypertension eller arytmier\n• Personer med pacemakere eller implanterede hjertedéfibriller — kraftige storme kan i sjældne tilfælde påvirke enhedens funktion\n• Personer med neurologiske lidelser (epilepsi, migræne, MS)\n• Ældre\n• Personer, der allerede er under betydeligt fysisk eller emotionelt stress\n• Følsomme individer, som konsekvent rapporterer symptomer under tidligere storme\n\nGravide kvinder anbefales også at begrænse langvarig udendørsophold under ekstreme G4–G5-hændelser som en forholdsregel.' },
    { heading: 'Hvad du kan gøre', body: 'Der er ingen måde at blokere geomagnetiske storme på, men du kan reducere deres indvirkning:\n\n• Overvåg aktiviteten — brug denne app for at holde dig informeret. En DISTURBED- eller STORM-status er dit signal til at være opmærksom.\n• Hvil mere — din krop er under ekstra stress. Tving dig ikke igennem træthed.\n• Hold dig hydreret — vand understøtter en sund blokviskositet og hjerte-kar-funktion.\n• Reducer stimulanser — koffein og alkohol forstærker belastningen på hjerte-kar- og nervesystemet.\n• Tilbring tid i naturen — jordning (at gå barfodet på græs eller jord) er vist at reducere fysiologiske stressmarkører.\n• Udskyd krævende opgaver — operationer, lange flyrejser og intense forhandlinger er bedst omplanlagt, når det er muligt.\n• Tag dine mediciner — spring ikke doser over i aktive perioder, hvis du har en kronisk sygdom.' },
  ],
  sources: 'Baseret på publiceret forskning i tidsskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Geomagnetiske data leveret af GFZ Potsdam og NIGGG.',
};

export default da;
