import type { MagneticLangContent } from '../magneticEffectsContent';

const de: MagneticLangContent = {
  title: 'Magnetstürme und menschliche Gesundheit',
  subtitle: 'Wie geomagnetische Aktivität den menschlichen Körper beeinflusst — und was Sie dagegen tun können.',
  sections: [
    { heading: 'Was ist ein geomagnetischer Sturm?', body: 'Ein geomagnetischer Sturm entsteht, wenn ein Ausbruch von Sonnenwind — geladene Teilchen von der Sonne — das Erdmagnetfeld stark genug trifft, um es zu stören. Die Störung kann von wenigen Stunden bis zu mehreren Tagen andauern. Wissenschaftler messen die Stärke mit dem Kp-Index (0–9) und dem Dst-Index, der verfolgt, wie stark das Feld während des Ereignisses abfällt.\n\nStürme werden in G1–G5 eingeteilt. Ein G1-Sturm (Kp 5) verursacht geringfügige Störungen; ein G5 (Kp 9) ist selten und kann Stromnetze und Satelliten lahmlegen.' },
    { heading: 'Herz-Kreislauf-System', body: 'Mehrere begutachtete Studien belegen eine Korrelation zwischen starken geomagnetischen Stürmen und einem Anstieg von Herzinfarkten, Herzrhythmusstörungen und plötzlichen Herztoden — besonders in den 24–48 Stunden nach Sturmbeginn.\n\nDer Mechanismus soll die Unterdrückung von Melatonin und eine Störung des autonomen Nervensystems umfassen, das Herzfrequenz und Blutdruck reguliert. Personen mit vorbestehenden Herzerkrankungen, Bluthochdruck oder Gerinnungsstörungen gelten als am stärksten gefährdet.\n\nBei einem G2–G3-Sturm oder stärker: Wenn Sie Herzerkrankungen haben, meiden Sie intensive körperliche Belastung, trinken Sie ausreichend und halten Sie Ihre Medikamente griffbereit.' },
    { heading: 'Gehirn und Nervensystem', body: 'Das menschliche Nervensystem reagiert empfindlich auf niederfrequente elektromagnetische Felder. Während geomagnetischer Stürme berichten viele Menschen von Kopfschmerzen, Schwindel, Konzentrationsschwierigkeiten und einem allgemeinen Gefühl mentaler Benommenheit.\n\nForschungsergebnisse deuten darauf hin, dass geomagnetische Aktivität die Serotonin- und Melatoninproduktion im Gehirn beeinflusst. Gestörte Serotoninspiegel können Stimmung, Kognition und Schmerzempfindlichkeit beeinflussen — was erklärt, warum manche Menschen in aktiven Perioden gereizter, ängstlicher oder verwirrter wirken.\n\nMenschen mit Epilepsie, Migräne oder neurologischen Erkrankungen können während starker Stürme häufigere Episoden erleben.' },
    { heading: 'Schlafstörungen', body: 'Die Zirbeldrüse produziert Melatonin — das schlafregulierendes Hormon — als Reaktion auf Dunkelheit und das natürliche Magnetfeld der Erde. Geomagnetische Stürme stören diesen Prozess, unterdrücken die Melatoninproduktion und bringen den circadianen Rhythmus durcheinander.\n\nDie Folge: Einschlafschwierigkeiten, leichterer Schlaf, lebhaftere oder beunruhigendere Träume und das Aufwachen ohne Erholungsgefühl. Studien zeigen, dass Nächte mit Kp ≥ 5 mit gehäuften Schlaflosigkeitsmeldungen in der Bevölkerung korrelieren.\n\nAls Gegenmittel: Halten Sie in aktiven Phasen einen gleichmäßigen Schlafrhythmus ein, meiden Sie Bildschirme vor dem Schlafengehen und halten Sie das Schlafzimmer so dunkel wie möglich.' },
    { heading: 'Wer ist am stärksten gefährdet?', body: 'Die meisten gesunden Erwachsenen spüren wenig oder keine Auswirkungen moderater geomagnetischer Aktivität, doch einige Gruppen sind empfindlicher:\n\n• Menschen mit Herz-Kreislauf-Erkrankungen, Bluthochdruck oder Herzrhythmusstörungen\n• Menschen mit Herzschrittmachern oder implantierten Defibrillatoren — starke Stürme können in seltenen Fällen die Gerätefunktion beeinflussen\n• Menschen mit neurologischen Erkrankungen (Epilepsie, Migräne, MS)\n• Ältere Menschen\n• Menschen unter erheblichem körperlichem oder emotionalem Stress\n• Empfindliche Personen, die bei früheren Stürmen regelmäßig Symptome berichten\n\nSchwangeren Frauen wird empfohlen, bei extremen G4–G5-Ereignissen längere Aufenthalte im Freien vorsorglich zu vermeiden.' },
    { heading: 'Was Sie tun können', body: 'Geomagnetische Stürme lassen sich nicht aufhalten, aber Sie können ihre Auswirkungen minimieren:\n\n• Aktivität überwachen — nutzen Sie diese App. Ein DISTURBED- oder STORM-Status ist Ihr Signal zur Vorsicht.\n• Mehr ausruhen — Ihr Körper steht unter zusätzlichem Stress. Kämpfen Sie nicht gegen die Erschöpfung an.\n• Ausreichend trinken — Wasser fördert eine gesunde Blutviskosität und Herzkreislauffunktion.\n• Stimulanzien reduzieren — Koffein und Alkohol verstärken die Belastung des Herz-Kreislauf- und Nervensystems.\n• Zeit in der Natur verbringen — Erden (Barfußgehen auf Gras oder Erde) senkt nachweislich physiologische Stressmarker.\n• Anspruchsvolle Aufgaben verschieben — Operationen, lange Flüge und intensive Verhandlungen nach Möglichkeit umlegen.\n• Medikamente einnehmen — bei chronischen Erkrankungen keine Dosis in aktiven Phasen auslassen.' },
  ],
  sources: 'Basierend auf Forschungsarbeiten in Fachzeitschriften wie Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics und Biomedicine & Pharmacotherapy. Geomagnetische Daten von GFZ Potsdam und NIGGG.',
};

export default de;
