import type { MagneticLangContent } from '../magneticEffectsContent';

const en: MagneticLangContent = {
  title: 'Magnetic Storms & Human Health',
  subtitle: 'How geomagnetic activity affects the human body — and what you can do about it.',
  sections: [
    { heading: 'What Is a Geomagnetic Storm?', body: 'A geomagnetic storm occurs when a burst of solar wind — charged particles from the Sun — strikes Earth\'s magnetic field hard enough to disturb it. The disturbance can last from a few hours to several days. Scientists measure its strength using the Kp index (0–9) and the Dst index, which tracks how much the field drops during the event.\n\nStorms are classified G1–G5. A G1 storm (Kp 5) causes minor disruptions; a G5 (Kp 9) is rare and can knock out power grids and satellites.' },
    { heading: 'Cardiovascular System', body: 'Multiple peer-reviewed studies have found a correlation between strong geomagnetic storms and an increase in heart attacks, arrhythmias, and sudden cardiac deaths — particularly in the 24–48 hours following storm onset.\n\nThe mechanism is thought to involve melatonin suppression and disruption of the autonomic nervous system, which regulates heart rate and blood pressure. People with pre-existing heart disease, high blood pressure, or blood-clotting disorders are considered most vulnerable.\n\nDuring a G2–G3 storm or higher, if you have cardiovascular conditions, avoid intense physical exertion, stay well hydrated, and keep your medication close.' },
    { heading: 'Brain & Nervous System', body: 'The human nervous system is sensitive to low-frequency electromagnetic fields. During geomagnetic storms, many people report headaches, dizziness, difficulty concentrating, and a general feeling of mental fog.\n\nResearch suggests that geomagnetic activity influences serotonin and melatonin production in the brain. Disrupted serotonin levels can affect mood, cognition, and pain sensitivity — which explains why some people feel more irritable, anxious, or confused during active periods.\n\nPeople with epilepsy, migraines, or neurological conditions may experience more frequent episodes during strong storms.' },
    { heading: 'Sleep Disturbances', body: 'The pineal gland produces melatonin — the hormone that regulates sleep — in response to darkness and the Earth\'s natural magnetic field. Geomagnetic storms interfere with this process, suppressing melatonin production and disrupting circadian rhythms.\n\nThe result: difficulty falling asleep, lighter sleep, more vivid or disturbing dreams, and waking up feeling unrested. Studies have shown that nights coinciding with Kp ≥ 5 correlate with increased reports of insomnia across large populations.\n\nTo counter this, try to maintain a consistent sleep schedule during active periods, avoid screens before bed, and keep the bedroom as dark as possible.' },
    { heading: 'Who Is Most at Risk?', body: 'While most healthy adults feel little or no effect from moderate geomagnetic activity, some groups are more sensitive:\n\n• People with cardiovascular disease, hypertension, or arrhythmias\n• People with pacemakers or implanted cardiac defibrillators — strong storms can in rare cases affect device function\n• People with neurological conditions (epilepsy, migraines, MS)\n• The elderly\n• People already under significant physical or emotional stress\n• Sensitive individuals who consistently report symptoms during past storms\n\nPregnant women are also advised to limit prolonged outdoor exposure during extreme G4–G5 events, as a precaution.' },
    { heading: 'What You Can Do', body: 'There is no way to block geomagnetic storms, but you can reduce their impact:\n\n• Monitor activity — use this app to stay informed. A DISTURBED or STORM status is your signal to be mindful.\n• Rest more — your body is under additional stress. Don\'t push through fatigue.\n• Stay hydrated — water supports healthy blood viscosity and cardiovascular function.\n• Reduce stimulants — caffeine and alcohol amplify cardiovascular and nervous system strain.\n• Spend time in nature — grounding (walking barefoot on grass or soil) has been shown to reduce physiological stress markers.\n• Postpone demanding tasks — surgeries, long flights, and intense negotiations are best rescheduled when possible.\n• Take your medication — do not skip doses during active periods if you have a chronic condition.' },
  ],
  sources: 'Based on published research in journals including Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics, and Biomedicine & Pharmacotherapy. Geomagnetic data provided by GFZ Potsdam and NIGGG.',
};

export default en;
