import type { MagneticLangContent } from '../magneticEffectsContent';

const es: MagneticLangContent = {
  title: 'Tormentas magnéticas y salud humana',
  subtitle: 'Cómo la actividad geomagnética afecta al cuerpo humano — y qué puede hacer al respecto.',
  sections: [
    { heading: '¿Qué es una tormenta geomagnética?', body: 'Una tormenta geomagnética ocurre cuando una ráfaga de viento solar — partículas cargadas procedentes del Sol — golpea el campo magnético terrestre con suficiente fuerza como para perturbarlo. La perturbación puede durar desde unas pocas horas hasta varios días. Los científicos miden su intensidad mediante el índice Kp (0–9) y el índice Dst, que rastrea cuánto cae el campo durante el evento.\n\nLas tormentas se clasifican en G1–G5. Una tormenta G1 (Kp 5) causa interrupciones menores; una G5 (Kp 9) es rara y puede dejar sin servicio las redes eléctricas y los satélites.' },
    { heading: 'Sistema cardiovascular', body: 'Múltiples estudios revisados por expertos han encontrado una correlación entre las fuertes tormentas geomagnéticas y un aumento de infartos de miocardio, arritmias y muertes cardíacas súbitas — especialmente en las 24–48 horas posteriores al inicio de la tormenta.\n\nSe cree que el mecanismo implica la supresión de melatonina y la alteración del sistema nervioso autónomo, que regula la frecuencia cardíaca y la presión arterial. Las personas con enfermedades cardíacas previas, hipertensión o trastornos de coagulación se consideran las más vulnerables.\n\nDurante una tormenta G2–G3 o superior, si tiene afecciones cardiovasculares, evite el esfuerzo físico intenso, manténgase bien hidratado y tenga su medicación a mano.' },
    { heading: 'Cerebro y sistema nervioso', body: 'El sistema nervioso humano es sensible a los campos electromagnéticos de baja frecuencia. Durante las tormentas geomagnéticas, muchas personas reportan dolores de cabeza, mareos, dificultad para concentrarse y una sensación general de niebla mental.\n\nLas investigaciones sugieren que la actividad geomagnética influye en la producción de serotonina y melatonina en el cerebro. Los niveles alterados de serotonina pueden afectar el estado de ánimo, la cognición y la sensibilidad al dolor — lo que explica por qué algunas personas se sienten más irritables, ansiosas o confundidas durante los períodos activos.\n\nLas personas con epilepsia, migrañas o afecciones neurológicas pueden experimentar episodios más frecuentes durante tormentas intensas.' },
    { heading: 'Trastornos del sueño', body: 'La glándula pineal produce melatonina — la hormona que regula el sueño — en respuesta a la oscuridad y al campo magnético natural de la Tierra. Las tormentas geomagnéticas interfieren con este proceso, suprimiendo la producción de melatonina y alterando los ritmos circadianos.\n\nEl resultado: dificultad para conciliar el sueño, sueño más ligero, sueños más vívidos o perturbadores y despertar sin sensación de descanso. Los estudios han demostrado que las noches coincidentes con Kp ≥ 5 correlacionan con mayor reporte de insomnio en grandes poblaciones.\n\nPara contrarrestarlo, intente mantener un horario de sueño regular durante los períodos activos, evite las pantallas antes de acostarse y mantenga el dormitorio lo más oscuro posible.' },
    { heading: '¿Quién está más en riesgo?', body: 'Aunque la mayoría de los adultos sanos sienten poco o ningún efecto de la actividad geomagnética moderada, algunos grupos son más sensibles:\n\n• Personas con enfermedades cardiovasculares, hipertensión o arritmias\n• Personas con marcapasos o desfibriladores cardíacos implantados — las tormentas fuertes pueden en casos raros afectar el funcionamiento del dispositivo\n• Personas con afecciones neurológicas (epilepsia, migrañas, EM)\n• Personas mayores\n• Personas bajo estrés físico o emocional significativo\n• Individuos sensibles que reportan síntomas de manera consistente durante tormentas anteriores\n\nTambién se aconseja a las mujeres embarazadas que limiten la exposición prolongada al aire libre durante eventos extremos G4–G5, como medida de precaución.' },
    { heading: 'Qué puede hacer', body: 'No es posible bloquear las tormentas geomagnéticas, pero puede reducir su impacto:\n\n• Monitoree la actividad — use esta aplicación para mantenerse informado. Un estado DISTURBED o STORM es su señal de alerta.\n• Descanse más — su cuerpo está bajo estrés adicional. No luche contra el cansancio.\n• Manténgase hidratado — el agua favorece una viscosidad sanguínea saludable y la función cardiovascular.\n• Reduzca estimulantes — la cafeína y el alcohol amplifican la carga sobre el sistema cardiovascular y nervioso.\n• Pase tiempo en la naturaleza — la conexión con la tierra (caminar descalzo sobre hierba o suelo) ha demostrado reducir marcadores fisiológicos de estrés.\n• Posponga tareas exigentes — cirugías, vuelos largos y negociaciones intensas es mejor reprogramarlos cuando sea posible.\n• Tome su medicación — no omita dosis durante períodos activos si tiene una afección crónica.' },
  ],
  sources: 'Basado en investigaciones publicadas en revistas como Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics y Biomedicine & Pharmacotherapy. Datos geomagnéticos proporcionados por GFZ Potsdam y NIGGG.',
};

export default es;
