import type { MagneticLangContent } from '../magneticEffectsContent';

const fi: MagneticLangContent = {
  title: 'Magneettimyrskyt ja ihmisten terveys',
  subtitle: 'Miten geomagneettinen aktiivisuus vaikuttaa ihmiskehoon — ja mitä voit tehdä sen suhteen.',
  sections: [
    { heading: 'Mikä on geomagneettinen myrsky?', body: 'Geomagneettinen myrsky syntyy, kun aurinkotuulen purkaus — Auringosta peräisin olevat varautuneet hiukkaset — iskee maan magneettikenttään riittävän voimakkaasti häiritäkseen sitä. Häiriö voi kestää muutamasta tunnista useaan päivään. Tutkijat mittaavat sen voimakkuutta Kp-indeksillä (0–9) ja Dst-indeksillä, joka seuraa kuinka paljon kenttä laskee tapahtuman aikana.\n\nMyrskyt luokitellaan G1–G5. G1-myrsky (Kp 5) aiheuttaa pieniä häiriöitä; G5 (Kp 9) on harvinainen ja voi kaataa sähköverkkoja ja satelliitteja.' },
    { heading: 'Sydän- ja verisuonijärjestelmä', body: 'Useat vertaisarvioidut tutkimukset ovat löytäneet yhteyden voimakkaiden geomagneettisten myrskyjen ja sydänkohtausten, rytmihäiriöiden sekä äkkikuolemien lisääntymisen välillä — erityisesti myrskyn alkua seuraavan 24–48 tunnin aikana.\n\nMekanismin uskotaan liittyvän melatoniinin tuotannon estymiseen ja autonomisen hermoston häiriintymiseen, joka säätelee sykettä ja verenpainetta. Sydänsairauden, korkean verenpaineen tai veren hyytymishäiriön kanssa elävät ovat herkimmin alttiina.\n\nG2–G3-myrskyn tai sitä voimakkaamman aikana, jos sinulla on sydän- ja verisuonisairauksia, vältä raskasta fyysistä rasitusta, pidä nesteytyksestä huolta ja pidä lääkkeet lähellä.' },
    { heading: 'Aivot ja hermosto', body: 'Ihmisen hermosto on herkkä matalataajuisille sähkömagneettisille kentille. Geomagneettisten myrskyjen aikana monet ihmiset ilmoittavat päänsärystä, huimauksesta, keskittymisvaikeuksista ja yleisestä ajatuksen sumuisuudesta.\n\nTutkimus viittaa siihen, että geomagneettinen aktiivisuus vaikuttaa serotoniinin ja melatoniinin tuotantoon aivoissa. Häiriintyneet serotoniinitasot voivat vaikuttaa mielialaan, kognitioon ja kipuherkkyyteen — mikä selittää, miksi jotkut ihmiset tuntevat itsensä ärtyneem­miksi, ahdistuneemmiksi tai hämmentyneemmiksi aktiivisina jaksoina.\n\nEpilepsian, migreenin tai neurologisten sairauksien kanssa elävät voivat kokea tiheämpiä kohtauksia voimakkaiden myrskyjen aikana.' },
    { heading: 'Unihäiriöt', body: 'Käpyrauhanen tuottaa melatoniinia — unta säätelevää hormonia — vastauksena pimeyteen ja maan luonnolliseen magneettikenttään. Geomaatriset myrskyt häiritsevät tätä prosessia, estävät melatoniinin tuotantoa ja sekoittavat vuorokausirytmin.\n\nSeurauksena on nukahtamisvaikeudet, kevyempi uni, eloisammat tai häiritsevät unet sekä herääminen väsyneenä. Tutkimukset ovat osoittaneet, että Kp ≥ 5 -öihin liittyy lisääntyneitä unettomuusraportteja suurissa väestöissä.\n\nVastapainoksi yritä pitää säännöllinen uniaikataulu aktiivisina jaksoina, vältä näyttöjä ennen nukkumaanmenoa ja pidä makuuhuone niin pimeänä kuin mahdollista.' },
    { heading: 'Kuka on suurimmassa vaarassa?', body: 'Vaikka useimmat terveet aikuiset tuntevat kohtalaisen geomagneettisen aktiivisuuden vaikutukset vain vähän tai ei lainkaan, jotkut ryhmät ovat herkempiä:\n\n• Sydän- ja verisuonisairauden, verenpainetaudin tai rytmihäiriöiden kanssa elävät\n• Sydämentahdistimen tai implantoitavan defibrillaattorin kanssa elävät — voimakkaat myrskyt voivat harvinaisissa tapauksissa vaikuttaa laitteen toimintaan\n• Neurologisten sairauksien (epilepsia, migreeni, MS) kanssa elävät\n• Vanhukset\n• Huomattavan fyysisen tai henkisen stressin alla olevat ihmiset\n• Herkät henkilöt, jotka johdonmukaisesti raportoivat oireita aiempien myrskyjen aikana\n\nRaskaana olevia naisia suositellaan myös rajoittamaan pitkäkestoista ulkona oleskelua äärimmäisten G4–G5-tapahtumien aikana varotoimena.' },
    { heading: 'Mitä voit tehdä', body: 'Geomagneettisia myrskyjä ei voi estää, mutta voit vähentää niiden vaikutusta:\n\n• Seuraa aktiivisuutta — käytä tätä sovellusta pysyäksesi ajan tasalla. DISTURBED- tai STORM-tila on merkki olla valppaana.\n• Lepää enemmän — kehosi on lisästressissä. Älä taistele väsymystä vastaan.\n• Pidä nesteytyksestä huolta — vesi tukee tervettä veren viskositeettia ja sydän- ja verisuonitoimintaa.\n• Vähennä stimulantteja — kofeiini ja alkoholi vahvistavat sydän- ja verisuoni- sekä hermoston kuormitusta.\n• Vietä aikaa luonnossa — maadoitus (paljasjaloin käveleminen ruoholla tai maalla) on todettu vähentävän fysiologisia stressimerkkejä.\n• Lykkää vaativia tehtäviä — leikkaukset, pitkät lennot ja vaativat neuvottelut on parasta siirtää mahdollisuuksien mukaan.\n• Ota lääkkeesi — älä jätä annoksia välistä aktiivisina jaksoina, jos sinulla on krooninen sairaus.' },
  ],
  sources: 'Perustuu julkaistuihin tutkimuksiin lehdissä kuten Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics ja Biomedicine & Pharmacotherapy. Geomagneettisen datan toimittivat GFZ Potsdam ja NIGGG.',
};

export default fi;
