import type { MagneticLangContent } from '../magneticEffectsContent';

const fr: MagneticLangContent = {
  title: 'Tempêtes magnétiques et santé humaine',
  subtitle: 'Comment l\'activité géomagnétique affecte le corps humain — et ce que vous pouvez y faire.',
  sections: [
    { heading: 'Qu\'est-ce qu\'une tempête géomagnétique ?', body: 'Une tempête géomagnétique se produit lorsqu\'une rafale de vent solaire — des particules chargées provenant du Soleil — frappe le champ magnétique terrestre avec assez de force pour le perturber. Cette perturbation peut durer de quelques heures à plusieurs jours. Les scientifiques en mesurent l\'intensité à l\'aide de l\'indice Kp (0–9) et de l\'indice Dst, qui suit la baisse du champ pendant l\'événement.\n\nLes tempêtes sont classées de G1 à G5. Une tempête G1 (Kp 5) provoque des perturbations mineures ; une G5 (Kp 9) est rare et peut paralyser les réseaux électriques et les satellites.' },
    { heading: 'Système cardiovasculaire', body: 'Plusieurs études évaluées par des pairs ont établi une corrélation entre les fortes tempêtes géomagnétiques et une augmentation des crises cardiaques, des arythmies et des morts cardiaques subites — particulièrement dans les 24 à 48 heures suivant le début de la tempête.\n\nLe mécanisme implique vraisemblablement une suppression de la mélatonine et une perturbation du système nerveux autonome, qui régule la fréquence cardiaque et la pression artérielle. Les personnes souffrant de maladies cardiaques préexistantes, d\'hypertension ou de troubles de la coagulation sont considérées comme les plus vulnérables.\n\nLors d\'une tempête G2–G3 ou plus forte, si vous avez des problèmes cardiovasculaires, évitez les efforts physiques intenses, restez bien hydraté et gardez vos médicaments à portée de main.' },
    { heading: 'Cerveau et système nerveux', body: 'Le système nerveux humain est sensible aux champs électromagnétiques basse fréquence. Lors des tempêtes géomagnétiques, beaucoup de personnes signalent des maux de tête, des vertiges, des difficultés de concentration et une sensation générale de brouillard mental.\n\nLes recherches indiquent que l\'activité géomagnétique influence la production de sérotonine et de mélatonine dans le cerveau. Des niveaux perturbés de sérotonine peuvent affecter l\'humeur, la cognition et la sensibilité à la douleur — ce qui explique pourquoi certaines personnes se sentent plus irritables, anxieuses ou confuses pendant les périodes actives.\n\nLes personnes épileptiques, migraineuses ou atteintes de maladies neurologiques peuvent connaître des épisodes plus fréquents lors de tempêtes importantes.' },
    { heading: 'Troubles du sommeil', body: 'La glande pinéale produit de la mélatonine — l\'hormone qui régule le sommeil — en réponse à l\'obscurité et au champ magnétique naturel de la Terre. Les tempêtes géomagnétiques perturbent ce processus, supprimant la production de mélatonine et désorganisant les rythmes circadiens.\n\nRésultat : difficulté à s\'endormir, sommeil plus léger, rêves plus vivaces ou perturbants et réveil sans sentiment de repos. Des études ont montré que les nuits coïncidant avec Kp ≥ 5 correspondent à une augmentation des signalements d\'insomnie dans de larges populations.\n\nPour y remédier, essayez de maintenir un rythme de sommeil régulier pendant les périodes actives, évitez les écrans avant de dormir et gardez la chambre aussi sombre que possible.' },
    { heading: 'Qui est le plus exposé ?', body: 'Si la plupart des adultes en bonne santé ressentent peu ou pas d\'effet lors d\'une activité géomagnétique modérée, certains groupes sont plus sensibles :\n\n• Les personnes atteintes de maladies cardiovasculaires, d\'hypertension ou d\'arythmies\n• Les personnes porteuses de pacemakers ou de défibrillateurs cardiaques implantés — les tempêtes fortes peuvent dans de rares cas affecter le fonctionnement du dispositif\n• Les personnes atteintes de pathologies neurologiques (épilepsie, migraines, SEP)\n• Les personnes âgées\n• Les personnes déjà soumises à un stress physique ou émotionnel important\n• Les individus sensibles qui signalent régulièrement des symptômes lors de tempêtes passées\n\nIl est également conseillé aux femmes enceintes de limiter leur exposition prolongée en extérieur lors d\'événements extrêmes G4–G5, par précaution.' },
    { heading: 'Ce que vous pouvez faire', body: 'Il n\'est pas possible de bloquer les tempêtes géomagnétiques, mais vous pouvez en réduire l\'impact :\n\n• Surveillez l\'activité — utilisez cette application pour rester informé. Un statut DISTURBED ou STORM est votre signal de vigilance.\n• Reposez-vous davantage — votre corps est soumis à un stress supplémentaire. Ne forcez pas sur la fatigue.\n• Restez hydraté — l\'eau contribue à une viscosité sanguine saine et à la fonction cardiovasculaire.\n• Réduisez les stimulants — la caféine et l\'alcool amplifient la pression sur le système cardiovasculaire et nerveux.\n• Passez du temps dans la nature — la mise à la terre (marcher pieds nus sur l\'herbe ou la terre) a démontré une réduction des marqueurs physiologiques de stress.\n• Reportez les tâches exigeantes — chirurgies, longs vols et négociations intenses sont mieux reprogrammés si possible.\n• Prenez vos médicaments — ne sautez pas de doses pendant les périodes actives si vous avez une maladie chronique.' },
  ],
  sources: 'Basé sur des recherches publiées dans des revues telles que Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics et Biomedicine & Pharmacotherapy. Données géomagnétiques fournies par GFZ Potsdam et NIGGG.',
};

export default fr;
