import type { MagneticLangContent } from '../magneticEffectsContent';

const is: MagneticLangContent = {
  title: 'Segulstormar og heilsa manna',
  subtitle: 'Hvernig jarðsegulvirkni hefur áhrif á líkamann — og hvað þú getur gert í þessu sambandi.',
  sections: [
    { heading: 'Hvað er jarðsegulstormur?', body: 'Jarðsegulstormur á sér stað þegar útbrot sólvinds — hlaðnar agnir frá Sólinni — berst á segulsvið jarðar með nægilegum krafti til að trufla það. Truflunin getur varað frá nokkrum klukkustundum upp í nokkra daga. Vísindamenn mæla styrk þess með Kp-vísitölunni (0–9) og Dst-vísitölunni, sem fylgist með því hversu mikið sviðið lækkar meðan á atburðinum stendur.\n\nStormar eru flokkaðir G1–G5. G1-stormur (Kp 5) veldur minniháttar truflunum; G5 (Kp 9) er sjaldgæfur og getur lagt rafmagnskerfi og gervitungla í rúst.' },
    { heading: 'Hjarta- og æðakerfi', body: 'Margar ritrýndar rannsóknir hafa fundið fylgni milli sterkra jarðsegulstorma og aukinnar tíðni hjartaáfalla, hjartsláttaróreglu og skyndilegs hjartadauða — sérstaklega á 24–48 klukkustundunum í kjölfar stormsbyrjunar.\n\nÁhrifameðferðin er talin fela í sér bælingu melatóníns og truflun á sjálfræna taugakerfinu, sem stjórnar hjartslætti og blóðþrýstingi. Einstaklingar með fyrirliggjandi hjartasjúkdóm, háþrýsting eða blóðstorknunartruflanir eru taldir hvað viðkvæmastir.\n\nÍ G2–G3-stormi eða sterkari: ef þú ert með hjarta- og æðasjúkdóma, forðastu kröftugar líkamlegar hreyfingar, vertu vel vökvaður og hafðu lyfin nálægt.' },
    { heading: 'Heili og taugakerfi', body: 'Taugakerfi mannsins er viðkvæmt fyrir lágíðni rafsegulsviðum. Í jarðsegulstormum greina margir frá höfuðverk, sundli, einbeitingarskorti og almennri tilfinningu um andlegt þoku.\n\nRannsóknir gefa til kynna að jarðsegulvirkni hafi áhrif á framleiðslu serótóníns og melatóníns í heila. Truflaðar serótónínstöður geta haft áhrif á skap, hugsunarferli og viðkvæmni fyrir sársauka — sem skýrir hvers vegna sumir einstaklingar líða meira fyrir pirringi, kvíða eða ringlunni á virkum tímabilum.\n\nEinstaklingar með flogaveiki, mígreni eða taugasjúkdóma geta upplifað tíðari köst í sterkum stormum.' },
    { heading: 'Svefntruflanir', body: 'Keilukirtillinn framleiðir melatónín — svefnstjórnandi hormón — sem svar við myrkri og náttúrulegu segulsviði jarðar. Jarðsegulstormar trufla þetta ferli, bæla framleiðslu melatóníns og raska dægurritmi.\n\nNiðurstaðan: erfiðleikar með að sofna, léttur svefn, líflegari eða órólegri draumar og að vakna þreyttur. Rannsóknir hafa sýnt að nætur með Kp ≥ 5 tengjast auknum skýrslum um svefnleysi hjá stórum þýðum.\n\nTil að vinna gegn þessu: reyndu að viðhalda reglulegu svefnlagi á virkum tímabilum, forðastu skjái fyrir svefn og haltu svefnherberginu eins dökku og mögulegt er.' },
    { heading: 'Hverjir eru í mestri hættu?', body: 'Þótt flestir heilbrigðir fullorðnir finni lítið eða ekkert fyrir hóflega jarðsegulvirkni, eru sumar hópar viðkvæmari:\n\n• Einstaklingar með hjarta- og æðasjúkdóma, háþrýsting eða hjartsláttarótreglu\n• Einstaklingar með gangráð eða ígrædd hjartahlaufarar — sterkir stormar geta í sjaldgæfum tilvikum haft áhrif á virkni tækjanna\n• Einstaklingar með taugasjúkdóma (flogaveiki, mígreni, MS)\n• Aldraðir\n• Einstaklingar sem þegar eru undir miklum líkamlegum eða tilfinningalegum streitu\n• Viðkvæmir einstaklingar sem stöðugt greina frá einkennum í stormum\n\nMæðgur er einnig ráðlagt að takmarka langa dvöl utandyra í G4–G5-atburðum sem varúðarráðstöfun.' },
    { heading: 'Hvað þú getur gert', body: 'Það er engin leið til að loka á jarðsegulstorma, en þú getur dregið úr áhrifum þeirra:\n\n• Fylgstu með virkni — notaðu þetta app til að vera upplýstur. DISTURBED eða STORM staða er merki þitt til að vera varkár.\n• Hvíl þig meira — líkami þinn er undir auknu álagi. Þvingaðu þig ekki í gegnum þreytu.\n• Haltu þig vökvaðan — vatn styður heilbrigðan blóðþykktarleika og hjarta- og æðastarfsemi.\n• Dragðu úr örvaefnum — koffín og áfengi gefa hjarta- og æðakerfi og taugakerfi meiri streitu.\n• Dveldu í náttúrunni — jarðtenging (að ganga berfættur á gras eða jörð) hefur reynst minnka lífeðlisfræðilegar stressvísur.\n• Frestaðu krefjandi verkefnum — aðgerðir, langar flugferðir og erfiðar samningaviðræður eru best að fresta þegar mögulegt er.\n• Taktu lyfin þín — slepptu ekki skömmtum á virkum tímabilum ef þú ert með langvinna sjúkdóma.' },
  ],
  sources: 'Byggt á birtum rannsóknum í tímaritum eins og Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Jarðsegulgögn frá GFZ Potsdam og NIGGG.',
};

export default is;
