import type { MagneticLangContent } from '../magneticEffectsContent';

const no: MagneticLangContent = {
  title: 'Magnetstormer og menneskelig helse',
  subtitle: 'Hvordan geomagnetisk aktivitet påvirker menneskekroppen — og hva du kan gjøre med det.',
  sections: [
    { heading: 'Hva er en geomagnetisk storm?', body: 'En geomagnetisk storm oppstår når et utbrudd av solvind — ladede partikler fra Solen — treffer Jordens magnetfelt med kraft nok til å forstyrre det. Forstyrrelsen kan vare fra noen timer til flere dager. Forskere måler styrken ved hjelp av Kp-indeksen (0–9) og Dst-indeksen, som sporer hvor mye feltet faller under hendelsen.\n\nStormer klassifiseres G1–G5. En G1-storm (Kp 5) forårsaker mindre forstyrrelser; en G5 (Kp 9) er sjelden og kan slå ut strømnett og satellitter.' },
    { heading: 'Hjerte- og karsystemet', body: 'Flere fagfellevurderte studier har funnet en sammenheng mellom sterke geomagnetiske stormer og økning i hjerteinfarkt, arytmier og plutselige hjertedødsfall — særlig i de 24–48 timene etter stormbegynnelsen.\n\nMekanismen antas å innebære melatoninsuppresjon og forstyrrelse av det autonome nervesystemet, som regulerer hjertefrekvens og blodtrykk. Personer med eksisterende hjertesykdom, høyt blodtrykk eller blodkoagulasjonsforstyrrelser anses som mest sårbare.\n\nUnder en G2–G3-storm eller sterkere bør du, hvis du har hjerte- og karlidelser, unngå intens fysisk anstrengelse, holde deg godt hydrert og ha medisinen tilgjengelig.' },
    { heading: 'Hjerne og nervesystem', body: 'Det menneskelige nervesystemet er følsomt for lavfrekvente elektromagnetiske felt. Under geomagnetiske stormer rapporterer mange hodepine, svimmelhet, konsentrasjonsvansker og en generell følelse av mental tåke.\n\nForskning tyder på at geomagnetisk aktivitet påvirker produksjonen av serotonin og melatonin i hjernen. Forstyrrelser i serotoninnivået kan påvirke humør, kognisjon og smertefølsomhet — noe som forklarer hvorfor noen føler seg mer irritable, engstelige eller forvirrede i aktive perioder.\n\nPersoner med epilepsi, migrene eller nevrologiske tilstander kan oppleve hyppigere episoder under kraftige stormer.' },
    { heading: 'Søvnforstyrrelser', body: 'Epifysen produserer melatonin — søvnreguleringshormonet — som respons på mørke og Jordens naturlige magnetfelt. Geomagnetiske stormer forstyrrer denne prosessen, hemmer melatoninproduksjonen og forstyrrer de sirkadiane rytmene.\n\nResultatet: vansker med å sovne, lettere søvn, mer livaktige eller plagsomme drømmer og å våkne uten å føle seg uthvilt. Studier viser at netter med Kp ≥ 5 korrelerer med økte rapporter om søvnløshet i store befolkninger.\n\nFor å motvirke dette, prøv å opprettholde et regelmessig søvnmønster i aktive perioder, unngå skjermer før sengetid og hold soverommet så mørkt som mulig.' },
    { heading: 'Hvem er mest utsatt?', body: 'Selv om de fleste friske voksne merker lite eller ingen effekt av moderat geomagnetisk aktivitet, er noen grupper mer følsomme:\n\n• Personer med hjerte- og karsykdommer, hypertensjon eller arytmier\n• Personer med pacemakere eller implanterte hjertedefibrillatorer — kraftige stormer kan i sjeldne tilfeller påvirke enhetens funksjon\n• Personer med nevrologiske tilstander (epilepsi, migrene, MS)\n• Eldre\n• Personer som allerede er under betydelig fysisk eller emosjonelt stress\n• Følsomme personer som konsekvent rapporterer symptomer under tidligere stormer\n\nGravide kvinner anbefales også å begrense langvarig utendørsopphold under ekstreme G4–G5-hendelser som en forholdsregel.' },
    { heading: 'Hva du kan gjøre', body: 'Det er ingen måte å blokkere geomagnetiske stormer på, men du kan redusere påvirkningen:\n\n• Overvåk aktiviteten — bruk denne appen for å holde deg informert. En DISTURBED- eller STORM-status er signalet ditt til å være oppmerksom.\n• Hvil mer — kroppen din er under ekstra stress. Ikke press deg gjennom tretthet.\n• Hold deg hydrert — vann støtter sunn blokviskositet og hjerte-karsystemets funksjon.\n• Reduser stimulanter — koffein og alkohol forsterker belastningen på hjerte-kar- og nervesystemet.\n• Tilbring tid i naturen — jording (å gå barbeint på gress eller jord) er vist å redusere fysiologiske stressmarkører.\n• Utsett krevende oppgaver — operasjoner, lange flyreiser og intense forhandlinger bør omdisponeres når mulig.\n• Ta medisinen din — ikke hopp over doser i aktive perioder hvis du har en kronisk tilstand.' },
  ],
  sources: 'Basert på publisert forskning i tidsskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Geomagnetiske data levert av GFZ Potsdam og NIGGG.',
};

export default no;
