import type { MagneticLangContent } from '../magneticEffectsContent';

const pl: MagneticLangContent = {
  title: 'Burze magnetyczne a zdrowie człowieka',
  subtitle: 'Jak aktywność geomagnetyczna wpływa na organizm człowieka — i co możesz z tym zrobić.',
  sections: [
    { heading: 'Czym jest burza geomagnetyczna?', body: 'Burza geomagnetyczna powstaje, gdy wybuch wiatru słonecznego — naładowanych cząstek ze Słońca — uderza w pole magnetyczne Ziemi z wystarczającą siłą, by je zakłócić. Zakłócenie może trwać od kilku godzin do kilku dni. Naukowcy mierzą jej intensywność za pomocą indeksu Kp (0–9) i indeksu Dst, który śledzi, o ile pole spada podczas zdarzenia.\n\nBurze klasyfikuje się od G1 do G5. Burza G1 (Kp 5) powoduje niewielkie zakłócenia; G5 (Kp 9) jest rzadka i może wyłączyć sieci energetyczne oraz satelity.' },
    { heading: 'Układ sercowo-naczyniowy', body: 'Wiele recenzowanych badań wykazało korelację między silnymi burzami geomagnetycznymi a wzrostem liczby zawałów serca, arytmii i nagłych zgonów sercowych — szczególnie w ciągu 24–48 godzin od początku burzy.\n\nPrzypuszcza się, że mechanizm obejmuje zahamowanie produkcji melatoniny i zaburzenie autonomicznego układu nerwowego, który reguluje częstość akcji serca i ciśnienie krwi. Osoby z istniejącymi chorobami serca, nadciśnieniem lub zaburzeniami krzepnięcia krwi są uważane za najbardziej narażone.\n\nPodczas burzy G2–G3 lub silniejszej, jeśli masz choroby układu sercowo-naczyniowego, unikaj intensywnego wysiłku fizycznego, dbaj o odpowiednie nawodnienie i miej leki pod ręką.' },
    { heading: 'Mózg i układ nerwowy', body: 'Ludzki układ nerwowy jest wrażliwy na niskoczęstotliwościowe pola elektromagnetyczne. Podczas burz geomagnetycznych wiele osób zgłasza bóle głowy, zawroty głowy, trudności z koncentracją i ogólne poczucie „zamglenia" umysłu.\n\nBadania sugerują, że aktywność geomagnetyczna wpływa na produkcję serotoniny i melatoniny w mózgu. Zaburzone poziomy serotoniny mogą wpływać na nastrój, funkcje poznawcze i wrażliwość na ból — co tłumaczy, dlaczego niektórzy czują się bardziej drażliwi, niespokojni lub zdezorientowani w aktywnych okresach.\n\nOsoby z epilepsją, migreną lub chorobami neurologicznymi mogą doświadczać częstszych epizodów podczas silnych burz.' },
    { heading: 'Zaburzenia snu', body: 'Szyszynka produkuje melatoninę — hormon regulujący sen — w odpowiedzi na ciemność i naturalne pole magnetyczne Ziemi. Burze geomagnetyczne zakłócają ten proces, hamują produkcję melatoniny i rozregulowują rytmy dobowe.\n\nEfekt: trudności z zasypianiem, płytszy sen, bardziej żywe lub niepokojące sny i budzenie się bez poczucia wypoczęcia. Badania wykazały, że noce z Kp ≥ 5 korelują ze zwiększonymi zgłoszeniami bezsenności w dużych populacjach.\n\nAby temu przeciwdziałać, staraj się zachowywać regularny harmonogram snu w aktywnych okresach, unikaj ekranów przed snem i trzymaj sypialnię tak ciemną, jak to możliwe.' },
    { heading: 'Kto jest najbardziej zagrożony?', body: 'Choć większość zdrowych dorosłych odczuwa niewielkie lub żadne skutki umiarkowanej aktywności geomagnetycznej, niektóre grupy są bardziej wrażliwe:\n\n• Osoby z chorobami sercowo-naczyniowymi, nadciśnieniem lub arytmiami\n• Osoby z rozrusznikami serca lub implantowanymi defibrylatorami — silne burze mogą w rzadkich przypadkach wpływać na działanie urządzenia\n• Osoby z chorobami neurologicznymi (epilepsja, migrena, SM)\n• Osoby starsze\n• Osoby już pod znacznym stresem fizycznym lub emocjonalnym\n• Wrażliwe osoby, które konsekwentnie zgłaszają objawy podczas poprzednich burz\n\nKobietom w ciąży zaleca się również ograniczenie długotrwałego przebywania na zewnątrz podczas ekstremalnych zdarzeń G4–G5 jako środek ostrożności.' },
    { heading: 'Co możesz zrobić', body: 'Nie ma sposobu na zablokowanie burz geomagnetycznych, ale możesz zmniejszyć ich wpływ:\n\n• Monitoruj aktywność — korzystaj z tej aplikacji, aby być na bieżąco. Status DISTURBED lub STORM to sygnał do zachowania ostrożności.\n• Odpoczywaj więcej — twój organizm jest pod dodatkowym stresem. Nie forsuj się przez zmęczenie.\n• Dbaj o nawodnienie — woda wspiera zdrową lepkość krwi i funkcję układu sercowo-naczyniowego.\n• Ogranicz stymulanty — kofeina i alkohol wzmacniają obciążenie układu sercowo-naczyniowego i nerwowego.\n• Spędzaj czas na łonie natury — uziemienie (chodzenie boso po trawie lub ziemi) udowodniono, że obniża fizjologiczne markery stresu.\n• Przekładaj wymagające zadania — operacje, długie loty i intensywne negocjacje najlepiej przekładać, gdy to możliwe.\n• Przyjmuj leki — nie pomijaj dawek w aktywnych okresach, jeśli masz chorobę przewlekłą.' },
  ],
  sources: 'Na podstawie opublikowanych badań w czasopismach takich jak Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics i Biomedicine & Pharmacotherapy. Dane geomagnetyczne dostarczone przez GFZ Potsdam i NIGGG.',
};

export default pl;
