import type { MagneticLangContent } from '../magneticEffectsContent';

const sv: MagneticLangContent = {
  title: 'Magnetstormar och mänsklig hälsa',
  subtitle: 'Hur geomagnetisk aktivitet påverkar kroppen — och vad du kan göra åt det.',
  sections: [
    { heading: 'Vad är en geomagnetisk storm?', body: 'En geomagnetisk storm uppstår när ett utbrott av solvind — laddade partiklar från Solen — träffar jordens magnetfält med tillräcklig kraft för att störa det. Störningen kan pågå från några timmar till flera dagar. Forskare mäter styrkan med Kp-index (0–9) och Dst-index, som följer hur mycket fältet sjunker under händelsen.\n\nStormar klassificeras G1–G5. En G1-storm (Kp 5) orsakar mindre störningar; en G5 (Kp 9) är sällsynt och kan slå ut elnät och satelliter.' },
    { heading: 'Hjärt-kärlsystemet', body: 'Flera expertgranskade studier har funnit ett samband mellan kraftiga geomagnetiska stormar och en ökning av hjärtinfarkter, arytmier och plötsliga hjärtdödsfall — särskilt under de 24–48 timmarna efter stormens start.\n\nMekanismen antas innebära melatoninsuppression och störning av det autonoma nervsystemet, som reglerar hjärtfrekvens och blodtryck. Personer med befintlig hjärtsjukdom, högt blodtryck eller blodkoagulationsstörningar anses vara mest utsatta.\n\nUnder en G2–G3-storm eller starkare, om du har hjärt-kärlsjukdomar, undvik intensiv fysisk ansträngning, håll dig välhydrerad och ha dina mediciner nära till hands.' },
    { heading: 'Hjärna och nervsystem', body: 'Det mänskliga nervsystemet är känsligt för lågfrekventa elektromagnetiska fält. Under geomagnetiska stormar rapporterar många huvudvärk, yrsel, koncentrationssvårigheter och en allmän känsla av mental dimma.\n\nForskning tyder på att geomagnetisk aktivitet påverkar produktionen av serotonin och melatonin i hjärnan. Störda serotoninnivåer kan påverka humör, kognition och smärtkänslighet — vilket förklarar varför en del människor känner sig mer irriterade, oroliga eller förvirrade under aktiva perioder.\n\nPersoner med epilepsi, migrän eller neurologiska tillstånd kan uppleva fler episoder under kraftiga stormar.' },
    { heading: 'Sömnstörningar', body: 'Tallkottkörteln producerar melatonin — det sömnreglerande hormonet — som respons på mörker och jordens naturliga magnetfält. Geomagnetiska stormar stör denna process, hämmar melatoninproduktionen och rubbar dygnsrytmen.\n\nResultatet: svårt att somna, lättare sömn, mer livfulla eller störande drömmar och att vakna utan känsla av vila. Studier visar att nätter med Kp ≥ 5 korrelerar med ökade sömnlöshetsrapporter i stora befolkningsgrupper.\n\nFör att motverka detta, försök hålla ett regelbundet sömnschema under aktiva perioder, undvik skärmar före sänggåendet och håll sovrummet så mörkt som möjligt.' },
    { heading: 'Vem löper störst risk?', body: 'Även om de flesta friska vuxna knappt märker av måttlig geomagnetisk aktivitet, är vissa grupper mer känsliga:\n\n• Personer med hjärt-kärlsjukdomar, hypertoni eller arytmier\n• Personer med pacemakers eller implanterade hjärtrytmdefibrillatorer — kraftiga stormar kan i sällsynta fall påverka enhetens funktion\n• Personer med neurologiska sjukdomar (epilepsi, migrän, MS)\n• Äldre\n• Personer som redan befinner sig under stor fysisk eller emotionell stress\n• Känsliga individer som konsekvent rapporterar symtom under tidigare stormar\n\nGravida kvinnor rekommenderas även att begränsa längre utomhusvistelse vid extrema G4–G5-händelser som en försiktighetsåtgärd.' },
    { heading: 'Vad du kan göra', body: 'Det går inte att blockera geomagnetiska stormar, men du kan minska deras inverkan:\n\n• Övervaka aktiviteten — använd den här appen för att hålla dig informerad. Status DISTURBED eller STORM är din signal att vara uppmärksam.\n• Vila mer — din kropp är under extra stress. Kämpa inte mot tröttheten.\n• Håll dig hydrerad — vatten stöder en sund blokviskositet och hjärt-karlfunktionen.\n• Minska stimulantia — koffein och alkohol förstärker belastningen på hjärt-kärl- och nervsystemet.\n• Tillbringa tid i naturen — jordning (att gå barfota på gräs eller jord) har visats minska fysiologiska stressmarkörer.\n• Skjut upp krävande uppgifter — operationer, långa flygningar och intensiva förhandlingar är bäst att boka om när möjligt.\n• Ta dina mediciner — hoppa inte över doser under aktiva perioder om du har ett kroniskt tillstånd.' },
  ],
  sources: 'Baserat på publicerad forskning i tidskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics och Biomedicine & Pharmacotherapy. Geomagnetiska data tillhandahållna av GFZ Potsdam och NIGGG.',
};

export default sv;
