export type SectionText = { heading: string; body: string };
export type MagneticLangContent = {
  title: string;
  subtitle: string;
  sections: SectionText[];
  sources: string;
};

export const magneticContent: Record<string, MagneticLangContent> = {
  en: {
    title: 'Magnetic Storms & Human Health',
    subtitle: 'How geomagnetic activity affects the human body — and what you can do about it.',
    sections: [
      { heading: 'What Is a Geomagnetic Storm?', body: 'A geomagnetic storm occurs when a burst of solar wind — charged particles from the Sun — strikes Earth\'s magnetic field hard enough to disturb it. The disturbance can last from a few hours to several days. Scientists measure its strength using the Kp index (0–9) and the Dst index, which tracks how much the field drops during the event.\n\nStorms are classified G1–G5. A G1 storm (Kp 5) causes minor disruptions; a G5 (Kp 9) is rare and can knock out power grids and satellites.' },
      { heading: 'Cardiovascular System', body: 'Multiple peer-reviewed studies have found a correlation between strong geomagnetic storms and an increase in heart attacks, arrhythmias, and sudden cardiac deaths — particularly in the 24–48 hours following storm onset.\n\nThe mechanism is thought to involve melatonin suppression and disruption of the autonomic nervous system, which regulates heart rate and blood pressure. People with pre-existing heart disease, high blood pressure, or blood-clotting disorders are considered most vulnerable.\n\nDuring a G2–G3 storm or higher, if you have cardiovascular conditions, avoid intense physical exertion, stay well hydrated, and keep your medication close.' },
      { heading: 'Brain & Nervous System', body: 'The human nervous system is sensitive to low-frequency electromagnetic fields. During geomagnetic storms, many people report headaches, dizziness, difficulty concentrating, and a general feeling of mental fog.\n\nResearch suggests that geomagnetic activity influences serotonin and melatonin production in the brain. Disrupted serotonin levels can affect mood, cognition, and pain sensitivity — which explains why some people feel more irritable, anxious, or confused during active periods.\n\nPeople with epilepsy, migraines, or neurological conditions may experience more frequent episodes during strong storms.' },
      { heading: 'Sleep Disturbances', body: 'The pineal gland produces melatonin — the hormone that regulates sleep — in response to darkness and the Earth\'s natural magnetic field. Geomagnetic storms interfere with this process, suppressing melatonin production and disrupting circadian rhythms.\n\nThe result: difficulty falling asleep, lighter sleep, more vivid or disturbing dreams, and waking up feeling unrested. Studies have shown that nights coinciding with Kp ≥ 5 correlate with increased reports of insomnia across large populations.\n\nTo counter this, try to maintain a consistent sleep schedule during active periods, avoid screens before bed, and keep the bedroom as dark as possible.' },
      { heading: 'Who Is Most at Risk?', body: 'While most healthy adults feel little or no effect from moderate geomagnetic activity, some groups are more sensitive:\n\n• People with cardiovascular disease, hypertension, or arrhythmias\n• People with pacemakers or implanted cardiac defibrillators — strong storms can in rare cases affect device function\n• People with neurological conditions (epilepsy, migraines, MS)\n• The elderly\n• People already under significant physical or emotional stress\n• Sensitive individuals who consistently report symptoms during past storms\n\nPregnant women are also advised to limit prolonged outdoor exposure during extreme G4–G5 events, as a precaution.' },
      { heading: 'What You Can Do', body: 'There is no way to block geomagnetic storms, but you can reduce their impact:\n\n• Monitor activity — use this app to stay informed. A DISTURBED or STORM status is your signal to be mindful.\n• Rest more — your body is under additional stress. Don\'t push through fatigue.\n• Stay hydrated — water supports healthy blood viscosity and cardiovascular function.\n• Reduce stimulants — caffeine and alcohol amplify cardiovascular and nervous system strain.\n• Spend time in nature — grounding (walking barefoot on grass or soil) has been shown to reduce physiological stress markers.\n• Postpone demanding tasks — surgeries, long flights, and intense negotiations are best rescheduled when possible.\n• Take your medication — do not skip doses during active periods if you have a chronic condition.' },
    ],
    sources: 'Based on published research in journals including Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics, and Biomedicine & Pharmacotherapy. Geomagnetic data provided by GFZ Potsdam and NIGGG.',
  },

  bg: {
    title: 'Магнитни бури и човешкото здраве',
    subtitle: 'Как геомагнитната активност влияе на човешкия организъм — и какво можете да направите.',
    sections: [
      { heading: 'Какво е геомагнитна буря?', body: 'Геомагнитна буря възниква, когато поток от слънчев вятър — заредени частици от Слънцето — удари магнитното поле на Земята достатъчно силно, за да го наруши. Смущението може да продължи от няколко часа до няколко дни. Учените измерват силата му чрез Kp индекса (0–9) и Dst индекса, който проследява доколко полето спада по време на събитието.\n\nБурите се класифицират от G1 до G5. Буря G1 (Kp 5) причинява леки смущения; G5 (Kp 9) е рядка и може да изключи електрически мрежи и да повреди сателити.' },
      { heading: 'Сърдечно-съдова система', body: 'Множество рецензирани научни изследвания намират корелация между силни геомагнитни бури и увеличаване на инфарктите, аритмиите и внезапните сърдечни смърти — особено в рамките на 24–48 часа след началото на бурята.\n\nПредполагаемият механизъм включва потискане на мелатонина и нарушаване на автономната нервна система, която регулира сърдечния ритъм и кръвното налягане. Хората с предшестващи сърдечни заболявания, хипертония или нарушения в кръвосъсирването са смятани за най-уязвими.\n\nПо време на буря G2–G3 или по-силна, ако имате сърдечно-съдови заболявания, избягвайте интензивно физическо натоварване, поддържайте добра хидратация и дръжте медикаментите си наблизо.' },
      { heading: 'Мозък и нервна система', body: 'Човешката нервна система е чувствителна към нискочестотни електромагнитни полета. По време на геомагнитни бури много хора съобщават за главоболие, световъртеж, затруднена концентрация и обща умствена мъгла.\n\nИзследванията показват, че геомагнитната активност влияе върху производството на серотонин и мелатонин в мозъка. Нарушените нива на серотонин могат да засегнат настроението, познавателните функции и болковата чувствителност — което обяснява защо някои хора се чувстват по-раздразнителни, тревожни или объркани по време на активни периоди.\n\nХора с епилепсия, мигрена или неврологични заболявания могат да изпитват по-чести епизоди по време на силни бури.' },
      { heading: 'Нарушения на съня', body: 'Епифизната жлеза произвежда мелатонин — хормонът, регулиращ съня — в отговор на тъмнина и естественото магнитно поле на Земята. Геомагнитните бури нарушават този процес, потискат производството на мелатонин и разстройват циркадните ритми.\n\nРезултатът: трудно заспиване, по-повърхностен сън, по-живи или обезпокоителни сънища и събуждане без усещане за почивка. Проучвания показват, че нощите, съвпадащи с Kp ≥ 5, корелират с увеличени съобщения за безсъние сред широки популации.\n\nЗа да противодействате, поддържайте постоянен режим на сън по време на активни периоди, избягвайте екрани преди лягане и поддържайте спалнята максимално тъмна.' },
      { heading: 'Кой е най-застрашен?', body: 'Докато повечето здрави възрастни усещат малко или никакъв ефект от умерена геомагнитна активност, някои групи са по-чувствителни:\n\n• Хора със сърдечно-съдови заболявания, хипертония или аритмии\n• Хора с пейсмейкъри или имплантирани сърдечни дефибрилатори — силните бури могат в редки случаи да засегнат функцията на устройствата\n• Хора с неврологични заболявания (епилепсия, мигрена, МС)\n• Възрастни хора\n• Хора, намиращи се под значителен физически или емоционален стрес\n• Чувствителни лица, които последователно съобщават за симптоми по време на предишни бури\n\nПрепоръчва се и бременните жени да ограничат продължителния престой на открито по време на екстремни събития G4–G5, като предпазна мярка.' },
      { heading: 'Какво можете да направите', body: 'Няма начин да блокирате геомагнитните бури, но можете да намалите въздействието им:\n\n• Следете активността — използвайте това приложение. Статус DISTURBED или STORM е сигнал за повишено внимание.\n• Почивайте повече — организмът ви е под допълнителен стрес. Не се принуждавайте да преодолявате умората.\n• Поддържайте хидратацията — водата подпомага здравия вискозитет на кръвта и сърдечно-съдовата функция.\n• Намалете стимулантите — кофеинът и алкохолът усилват натоварването върху сърдечно-съдовата и нервната система.\n• Прекарвайте време в природата — заземяването (ходене бос по трева или пръст) е доказано, че намалява физиологичните показатели за стрес.\n• Отложете натоварващи задачи — операции, дълги полети и интензивни преговори е най-добре да се пренасрочат, когато е възможно.\n• Приемайте медикаментите си — не пропускайте дози по време на активни периоди, ако имате хронично заболяване.' },
    ],
    sources: 'Базирано на публикувани изследвания в списания, включително Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics и Biomedicine & Pharmacotherapy. Геомагнитните данни са предоставени от GFZ Potsdam и NIGGG.',
  },

  de: {
    title: 'Magnetstürme und menschliche Gesundheit',
    subtitle: 'Wie geomagnetische Aktivität den menschlichen Körper beeinflusst — und was Sie dagegen tun können.',
    sections: [
      { heading: 'Was ist ein geomagnetischer Sturm?', body: 'Ein geomagnetischer Sturm entsteht, wenn ein Ausbruch von Sonnenwind — geladene Teilchen von der Sonne — das Erdmagnetfeld stark genug trifft, um es zu stören. Die Störung kann von wenigen Stunden bis zu mehreren Tagen andauern. Wissenschaftler messen die Stärke mit dem Kp-Index (0–9) und dem Dst-Index, der verfolgt, wie stark das Feld während des Ereignisses abfällt.\n\nStürme werden in G1–G5 eingeteilt. Ein G1-Sturm (Kp 5) verursacht geringfügige Störungen; ein G5 (Kp 9) ist selten und kann Stromnetze und Satelliten lahmlegen.' },
      { heading: 'Herz-Kreislauf-System', body: 'Mehrere begutachtete Studien belegen eine Korrelation zwischen starken geomagnetischen Stürmen und einem Anstieg von Herzinfarkten, Herzrhythmusstörungen und plötzlichen Herztoden — besonders in den 24–48 Stunden nach Sturmbeginn.\n\nDer Mechanismus soll die Unterdrückung von Melatonin und eine Störung des autonomen Nervensystems umfassen, das Herzfrequenz und Blutdruck reguliert. Personen mit vorbestehenden Herzerkrankungen, Bluthochdruck oder Gerinnungsstörungen gelten als am stärksten gefährdet.\n\nBei einem G2–G3-Sturm oder stärker: Wenn Sie Herzerkrankungen haben, meiden Sie intensive körperliche Belastung, trinken Sie ausreichend und halten Sie Ihre Medikamente griffbereit.' },
      { heading: 'Gehirn und Nervensystem', body: 'Das menschliche Nervensystem reagiert empfindlich auf niederfrequente elektromagnetische Felder. Während geomagnetischer Stürme berichten viele Menschen von Kopfschmerzen, Schwindel, Konzentrationsschwierigkeiten und einem allgemeinen Gefühl mentaler Benommenheit.\n\nForschungsergebnisse deuten darauf hin, dass geomagnetische Aktivität die Serotonin- und Melatoninproduktion im Gehirn beeinflusst. Gestörte Serotoninspiegel können Stimmung, Kognition und Schmerzempfindlichkeit beeinflussen — was erklärt, warum manche Menschen in aktiven Perioden gereizter, ängstlicher oder verwirrter wirken.\n\nMenschen mit Epilepsie, Migräne oder neurologischen Erkrankungen können während starker Stürme häufigere Episoden erleben.' },
      { heading: 'Schlafstörungen', body: 'Die Zirbeldrüse produziert Melatonin — das schlafregulierendes Hormon — als Reaktion auf Dunkelheit und das natürliche Magnetfeld der Erde. Geomagnetische Stürme stören diesen Prozess, unterdrücken die Melatoninproduktion und bringen den circadianen Rhythmus durcheinander.\n\nDie Folge: Einschlafschwierigkeiten, leichterer Schlaf, lebhaftere oder beunruhigendere Träume und das Aufwachen ohne Erholungsgefühl. Studien zeigen, dass Nächte mit Kp ≥ 5 mit gehäuften Schlaflosigkeitsmeldungen in der Bevölkerung korrelieren.\n\nAls Gegenmittel: Halten Sie in aktiven Phasen einen gleichmäßigen Schlafrhythmus ein, meiden Sie Bildschirme vor dem Schlafengehen und halten Sie das Schlafzimmer so dunkel wie möglich.' },
      { heading: 'Wer ist am stärksten gefährdet?', body: 'Die meisten gesunden Erwachsenen spüren wenig oder keine Auswirkungen moderater geomagnetischer Aktivität, doch einige Gruppen sind empfindlicher:\n\n• Menschen mit Herz-Kreislauf-Erkrankungen, Bluthochdruck oder Herzrhythmusstörungen\n• Menschen mit Herzschrittmachern oder implantierten Defibrillatoren — starke Stürme können in seltenen Fällen die Gerätefunktion beeinflussen\n• Menschen mit neurologischen Erkrankungen (Epilepsie, Migräne, MS)\n• Ältere Menschen\n• Menschen unter erheblichem körperlichem oder emotionalem Stress\n• Empfindliche Personen, die bei früheren Stürmen regelmäßig Symptome berichten\n\nSchwangeren Frauen wird empfohlen, bei extremen G4–G5-Ereignissen längere Aufenthalte im Freien vorsorglich zu vermeiden.' },
      { heading: 'Was Sie tun können', body: 'Geomagnetische Stürme lassen sich nicht aufhalten, aber Sie können ihre Auswirkungen minimieren:\n\n• Aktivität überwachen — nutzen Sie diese App. Ein DISTURBED- oder STORM-Status ist Ihr Signal zur Vorsicht.\n• Mehr ausruhen — Ihr Körper steht unter zusätzlichem Stress. Kämpfen Sie nicht gegen die Erschöpfung an.\n• Ausreichend trinken — Wasser fördert eine gesunde Blutviskosität und Herzkreislauffunktion.\n• Stimulanzien reduzieren — Koffein und Alkohol verstärken die Belastung des Herz-Kreislauf- und Nervensystems.\n• Zeit in der Natur verbringen — Erden (Barfußgehen auf Gras oder Erde) senkt nachweislich physiologische Stressmarker.\n• Anspruchsvolle Aufgaben verschieben — Operationen, lange Flüge und intensive Verhandlungen nach Möglichkeit umlegen.\n• Medikamente einnehmen — bei chronischen Erkrankungen keine Dosis in aktiven Phasen auslassen.' },
    ],
    sources: 'Basierend auf Forschungsarbeiten in Fachzeitschriften wie Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics und Biomedicine & Pharmacotherapy. Geomagnetische Daten von GFZ Potsdam und NIGGG.',
  },

  es: {
    title: 'Tormentas magnéticas y salud humana',
    subtitle: 'Cómo la actividad geomagnética afecta al cuerpo humano — y qué puede hacer al respecto.',
    sections: [
      { heading: '¿Qué es una tormenta geomagnética?', body: 'Una tormenta geomagnética ocurre cuando una ráfaga de viento solar — partículas cargadas procedentes del Sol — golpea el campo magnético terrestre con suficiente fuerza como para perturbarlo. La perturbación puede durar desde unas pocas horas hasta varios días. Los científicos miden su intensidad mediante el índice Kp (0–9) y el índice Dst, que rastrea cuánto cae el campo durante el evento.\n\nLas tormentas se clasifican en G1–G5. Una tormenta G1 (Kp 5) causa interrupciones menores; una G5 (Kp 9) es rara y puede dejar sin servicio las redes eléctricas y los satélites.' },
      { heading: 'Sistema cardiovascular', body: 'Múltiples estudios revisados por expertos han encontrado una correlación entre las fuertes tormentas geomagnéticas y un aumento de infartos de miocardio, arritmias y muertes cardíacas súbitas — especialmente en las 24–48 horas posteriores al inicio de la tormenta.\n\nSe cree que el mecanismo implica la supresión de melatonina y la alteración del sistema nervioso autónomo, que regula la frecuencia cardíaca y la presión arterial. Las personas con enfermedades cardíacas previas, hipertensión o trastornos de coagulación se consideran las más vulnerables.\n\nDurante una tormenta G2–G3 o superior, si tiene afecciones cardiovasculares, evite el esfuerzo físico intenso, manténgase bien hidratado y tenga su medicación a mano.' },
      { heading: 'Cerebro y sistema nervioso', body: 'El sistema nervioso humano es sensible a los campos electromagnéticos de baja frecuencia. Durante las tormentas geomagnéticas, muchas personas reportan dolores de cabeza, mareos, dificultad para concentrarse y una sensación general de niebla mental.\n\nLas investigaciones sugieren que la actividad geomagnética influye en la producción de serotonina y melatonina en el cerebro. Los niveles alterados de serotonina pueden afectar el estado de ánimo, la cognición y la sensibilidad al dolor — lo que explica por qué algunas personas se sienten más irritables, ansiosas o confundidas durante los períodos activos.\n\nLas personas con epilepsia, migrañas o afecciones neurológicas pueden experimentar episodios más frecuentes durante tormentas intensas.' },
      { heading: 'Trastornos del sueño', body: 'La glándula pineal produce melatonina — la hormona que regula el sueño — en respuesta a la oscuridad y al campo magnético natural de la Tierra. Las tormentas geomagnéticas interfieren con este proceso, suprimiendo la producción de melatonina y alterando los ritmos circadianos.\n\nEl resultado: dificultad para conciliar el sueño, sueño más ligero, sueños más vívidos o perturbadores y despertar sin sensación de descanso. Los estudios han demostrado que las noches coincidentes con Kp ≥ 5 correlacionan con mayor reporte de insomnio en grandes poblaciones.\n\nPara contrarrestarlo, intente mantener un horario de sueño regular durante los períodos activos, evite las pantallas antes de acostarse y mantenga el dormitorio lo más oscuro posible.' },
      { heading: '¿Quién está más en riesgo?', body: 'Aunque la mayoría de los adultos sanos sienten poco o ningún efecto de la actividad geomagnética moderada, algunos grupos son más sensibles:\n\n• Personas con enfermedades cardiovasculares, hipertensión o arritmias\n• Personas con marcapasos o desfibriladores cardíacos implantados — las tormentas fuertes pueden en casos raros afectar el funcionamiento del dispositivo\n• Personas con afecciones neurológicas (epilepsia, migrañas, EM)\n• Personas mayores\n• Personas bajo estrés físico o emocional significativo\n• Individuos sensibles que reportan síntomas de manera consistente durante tormentas anteriores\n\nTambién se aconseja a las mujeres embarazadas que limiten la exposición prolongada al aire libre durante eventos extremos G4–G5, como medida de precaución.' },
      { heading: 'Qué puede hacer', body: 'No es posible bloquear las tormentas geomagnéticas, pero puede reducir su impacto:\n\n• Monitoree la actividad — use esta aplicación para mantenerse informado. Un estado DISTURBED o STORM es su señal de alerta.\n• Descanse más — su cuerpo está bajo estrés adicional. No luche contra el cansancio.\n• Manténgase hidratado — el agua favorece una viscosidad sanguínea saludable y la función cardiovascular.\n• Reduzca estimulantes — la cafeína y el alcohol amplifican la carga sobre el sistema cardiovascular y nervioso.\n• Pase tiempo en la naturaleza — la conexión con la tierra (caminar descalzo sobre hierba o suelo) ha demostrado reducir marcadores fisiológicos de estrés.\n• Posponga tareas exigentes — cirugías, vuelos largos y negociaciones intensas es mejor reprogramarlos cuando sea posible.\n• Tome su medicación — no omita dosis durante períodos activos si tiene una afección crónica.' },
    ],
    sources: 'Basado en investigaciones publicadas en revistas como Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics y Biomedicine & Pharmacotherapy. Datos geomagnéticos proporcionados por GFZ Potsdam y NIGGG.',
  },

  fr: {
    title: 'Tempêtes magnétiques et santé humaine',
    subtitle: 'Comment l\'activité géomagnétique affecte le corps humain — et ce que vous pouvez y faire.',
    sections: [
      { heading: 'Qu\'est-ce qu\'une tempête géomagnétique ?', body: 'Une tempête géomagnétique se produit lorsqu\'une rafale de vent solaire — des particules chargées provenant du Soleil — frappe le champ magnétique terrestre avec assez de force pour le perturber. Cette perturbation peut durer de quelques heures à plusieurs jours. Les scientifiques en mesurent l\'intensité à l\'aide de l\'indice Kp (0–9) et de l\'indice Dst, qui suit la baisse du champ pendant l\'événement.\n\nLes tempêtes sont classées de G1 à G5. Une tempête G1 (Kp 5) provoque des perturbations mineures ; une G5 (Kp 9) est rare et peut paralyser les réseaux électriques et les satellites.' },
      { heading: 'Système cardiovasculaire', body: 'Plusieurs études évaluées par des pairs ont établi une corrélation entre les fortes tempêtes géomagnétiques et une augmentation des crises cardiaques, des arythmies et des morts cardiaques subites — particulièrement dans les 24 à 48 heures suivant le début de la tempête.\n\nLe mécanisme implique vraisemblablement une suppression de la mélatonine et une perturbation du système nerveux autonome, qui régule la fréquence cardiaque et la pression artérielle. Les personnes souffrant de maladies cardiaques préexistantes, d\'hypertension ou de troubles de la coagulation sont considérées comme les plus vulnérables.\n\nLors d\'une tempête G2–G3 ou plus forte, si vous avez des problèmes cardiovasculaires, évitez les efforts physiques intenses, restez bien hydraté et gardez vos médicaments à portée de main.' },
      { heading: 'Cerveau et système nerveux', body: 'Le système nerveux humain est sensible aux champs électromagnétiques basse fréquence. Lors des tempêtes géomagnétiques, beaucoup de personnes signalent des maux de tête, des vertiges, des difficultés de concentration et une sensation générale de brouillard mental.\n\nLes recherches indiquent que l\'activité géomagnétique influence la production de sérotonine et de mélatonine dans le cerveau. Des niveaux perturbés de sérotonine peuvent affecter l\'humeur, la cognition et la sensibilité à la douleur — ce qui explique pourquoi certaines personnes se sentent plus irritables, anxieuses ou confuses pendant les périodes actives.\n\nLes personnes épileptiques, migraineuses ou atteintes de maladies neurologiques peuvent connaître des épisodes plus fréquents lors de tempêtes importantes.' },
      { heading: 'Troubles du sommeil', body: 'La glande pinéale produit de la mélatonine — l\'hormone qui régule le sommeil — en réponse à l\'obscurité et au champ magnétique naturel de la Terre. Les tempêtes géomagnétiques perturbent ce processus, supprimant la production de mélatonine et désorganisant les rythmes circadiens.\n\nRésultat : difficulté à s\'endormir, sommeil plus léger, rêves plus vivaces ou perturbants et réveil sans sentiment de repos. Des études ont montré que les nuits coïncidant avec Kp ≥ 5 correspondent à une augmentation des signalements d\'insomnie dans de larges populations.\n\nPour y remédier, essayez de maintenir un rythme de sommeil régulier pendant les périodes actives, évitez les écrans avant de dormir et gardez la chambre aussi sombre que possible.' },
      { heading: 'Qui est le plus exposé ?', body: 'Si la plupart des adultes en bonne santé ressentent peu ou pas d\'effet lors d\'une activité géomagnétique modérée, certains groupes sont plus sensibles :\n\n• Les personnes atteintes de maladies cardiovasculaires, d\'hypertension ou d\'arythmies\n• Les personnes porteuses de pacemakers ou de défibrillateurs cardiaques implantés — les tempêtes fortes peuvent dans de rares cas affecter le fonctionnement du dispositif\n• Les personnes atteintes de pathologies neurologiques (épilepsie, migraines, SEP)\n• Les personnes âgées\n• Les personnes déjà soumises à un stress physique ou émotionnel important\n• Les individus sensibles qui signalent régulièrement des symptômes lors de tempêtes passées\n\nIl est également conseillé aux femmes enceintes de limiter leur exposition prolongée en extérieur lors d\'événements extrêmes G4–G5, par précaution.' },
      { heading: 'Ce que vous pouvez faire', body: 'Il n\'est pas possible de bloquer les tempêtes géomagnétiques, mais vous pouvez en réduire l\'impact :\n\n• Surveillez l\'activité — utilisez cette application pour rester informé. Un statut DISTURBED ou STORM est votre signal de vigilance.\n• Reposez-vous davantage — votre corps est soumis à un stress supplémentaire. Ne forcez pas sur la fatigue.\n• Restez hydraté — l\'eau contribue à une viscosité sanguine saine et à la fonction cardiovasculaire.\n• Réduisez les stimulants — la caféine et l\'alcool amplifient la pression sur le système cardiovasculaire et nerveux.\n• Passez du temps dans la nature — la mise à la terre (marcher pieds nus sur l\'herbe ou la terre) a démontré une réduction des marqueurs physiologiques de stress.\n• Reportez les tâches exigeantes — chirurgies, longs vols et négociations intenses sont mieux reprogrammés si possible.\n• Prenez vos médicaments — ne sautez pas de doses pendant les périodes actives si vous avez une maladie chronique.' },
    ],
    sources: 'Basé sur des recherches publiées dans des revues telles que Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics et Biomedicine & Pharmacotherapy. Données géomagnétiques fournies par GFZ Potsdam et NIGGG.',
  },

  ru: {
    title: 'Магнитные бури и здоровье человека',
    subtitle: 'Как геомагнитная активность влияет на организм человека — и что вы можете с этим сделать.',
    sections: [
      { heading: 'Что такое геомагнитная буря?', body: 'Геомагнитная буря возникает, когда поток солнечного ветра — заряженных частиц от Солнца — ударяет по магнитному полю Земли с достаточной силой, чтобы нарушить его. Возмущение может длиться от нескольких часов до нескольких дней. Учёные измеряют его интенсивность с помощью индекса Kp (0–9) и индекса Dst, который отслеживает, насколько снижается поле во время события.\n\nБури классифицируются от G1 до G5. Буря G1 (Kp 5) вызывает незначительные помехи; G5 (Kp 9) — редкое явление, способное вывести из строя электросети и спутники.' },
      { heading: 'Сердечно-сосудистая система', body: 'Ряд рецензируемых исследований выявил корреляцию между сильными геомагнитными бурями и увеличением числа инфарктов, аритмий и внезапных сердечных смертей — особенно в первые 24–48 часов после начала бури.\n\nПредполагаемый механизм связан с подавлением мелатонина и нарушением работы вегетативной нервной системы, регулирующей частоту сердечных сокращений и артериальное давление. Наиболее уязвимы люди с уже имеющимися заболеваниями сердца, гипертонией или нарушениями свёртываемости крови.\n\nВо время бури G2–G3 и выше при наличии сердечно-сосудистых заболеваний избегайте интенсивных физических нагрузок, поддерживайте водный баланс и держите лекарства под рукой.' },
      { heading: 'Мозг и нервная система', body: 'Нервная система человека чувствительна к низкочастотным электромагнитным полям. Во время геомагнитных бурь многие люди сообщают о головных болях, головокружении, трудностях с концентрацией и общем ощущении «туманности» в голове.\n\nИсследования показывают, что геомагнитная активность влияет на выработку серотонина и мелатонина в мозге. Нарушение уровня серотонина может сказываться на настроении, когнитивных функциях и болевой чувствительности — что объясняет, почему в активные периоды некоторые люди чувствуют себя более раздражительными, тревожными или растерянными.\n\nЛюди с эпилепсией, мигренью или неврологическими заболеваниями могут испытывать более частые эпизоды во время сильных бурь.' },
      { heading: 'Нарушения сна', body: 'Шишковидная железа вырабатывает мелатонин — гормон, регулирующий сон, — в ответ на темноту и естественное магнитное поле Земли. Геомагнитные бури нарушают этот процесс, подавляя выработку мелатонина и сбивая циркадные ритмы.\n\nРезультат: трудности с засыпанием, более поверхностный сон, яркие или тревожные сновидения и утреннее ощущение разбитости. Исследования показали, что ночи с Kp ≥ 5 коррелируют с более частыми жалобами на бессонницу среди широких слоёв населения.\n\nДля противодействия старайтесь в активные периоды придерживаться стабильного режима сна, избегайте экранов перед сном и делайте спальню как можно более тёмной.' },
      { heading: 'Кто находится в группе риска?', body: 'Большинство здоровых взрослых практически не ощущают воздействия умеренной геомагнитной активности, однако некоторые группы более восприимчивы:\n\n• Люди с сердечно-сосудистыми заболеваниями, гипертонией или аритмиями\n• Люди с кардиостимуляторами или имплантированными дефибрилляторами — сильные бури в редких случаях могут влиять на работу устройств\n• Люди с неврологическими заболеваниями (эпилепсия, мигрень, рассеянный склероз)\n• Пожилые люди\n• Люди, испытывающие значительный физический или эмоциональный стресс\n• Чувствительные люди, которые регулярно отмечают симптомы во время прошлых бурь\n\nБеременным женщинам также рекомендуется ограничить длительное пребывание на открытом воздухе во время экстремальных событий G4–G5 в качестве меры предосторожности.' },
      { heading: 'Что вы можете сделать', body: 'Заблокировать геомагнитные бури невозможно, но вы можете снизить их воздействие:\n\n• Следите за активностью — используйте это приложение. Статус DISTURBED или STORM — сигнал быть осторожным.\n• Больше отдыхайте — ваш организм испытывает дополнительную нагрузку. Не боритесь с усталостью через силу.\n• Пейте достаточно воды — она поддерживает здоровую вязкость крови и работу сердца.\n• Сократите стимуляторы — кофеин и алкоголь усиливают нагрузку на сердечно-сосудистую и нервную системы.\n• Проводите время на природе — заземление (ходьба босиком по траве или земле) доказанно снижает физиологические маркеры стресса.\n• Перенесите ответственные дела — операции, дальние перелёты и интенсивные переговоры лучше перенести при возможности.\n• Принимайте лекарства — при хронических заболеваниях в активные периоды не пропускайте дозы.' },
    ],
    sources: 'На основе опубликованных исследований в журналах Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics и Biomedicine & Pharmacotherapy. Геомагнитные данные предоставлены GFZ Potsdam и NIGGG.',
  },

  no: {
    title: 'Magnetstormer og menneskelig helse',
    subtitle: 'Hvordan geomagnetisk aktivitet påvirker menneskekroppen — og hva du kan gjøre med det.',
    sections: [
      { heading: 'Hva er en geomagnetisk storm?', body: 'En geomagnetisk storm oppstår når et utbrudd av solvind — ladede partikler fra Solen — treffer Jordens magnetfelt med kraft nok til å forstyrre det. Forstyrrelsen kan vare fra noen timer til flere dager. Forskere måler styrken ved hjelp av Kp-indeksen (0–9) og Dst-indeksen, som sporer hvor mye feltet faller under hendelsen.\n\nStormer klassifiseres G1–G5. En G1-storm (Kp 5) forårsaker mindre forstyrrelser; en G5 (Kp 9) er sjelden og kan slå ut strømnett og satellitter.' },
      { heading: 'Hjerte- og karsystemet', body: 'Flere fagfellevurderte studier har funnet en sammenheng mellom sterke geomagnetiske stormer og økning i hjerteinfarkt, arytmier og plutselige hjertedødsfall — særlig i de 24–48 timene etter stormbegynnelsen.\n\nMekanismen antas å innebære melatoninsuppresjon og forstyrrelse av det autonome nervesystemet, som regulerer hjertefrekvens og blodtrykk. Personer med eksisterende hjertesykdom, høyt blodtrykk eller blodkoagulasjonsforstyrrelser anses som mest sårbare.\n\nUnder en G2–G3-storm eller sterkere bør du, hvis du har hjerte- og karlidelser, unngå intens fysisk anstrengelse, holde deg godt hydrert og ha medisinen tilgjengelig.' },
      { heading: 'Hjerne og nervesystem', body: 'Det menneskelige nervesystemet er følsomt for lavfrekvente elektromagnetiske felt. Under geomagnetiske stormer rapporterer mange hodepine, svimmelhet, konsentrasjonsvansker og en generell følelse av mental tåke.\n\nForskning tyder på at geomagnetisk aktivitet påvirker produksjonen av serotonin og melatonin i hjernen. Forstyrrelser i serotoninnivået kan påvirke humør, kognisjon og smertefølsomhet — noe som forklarer hvorfor noen føler seg mer irritable, engstelige eller forvirrede i aktive perioder.\n\nPersoner med epilepsi, migrene eller nevrologiske tilstander kan oppleve hyppigere episoder under kraftige stormer.' },
      { heading: 'Søvnforstyrrelser', body: 'Epifysen produserer melatonin — søvnreguleringshormonet — som respons på mørke og Jordens naturlige magnetfelt. Geomagnetiske stormer forstyrrer denne prosessen, hemmer melatoninproduksjonen og forstyrrer de sirkadiane rytmene.\n\nResultatet: vansker med å sovne, lettere søvn, mer livaktige eller plagsomme drømmer og å våkne uten å føle seg uthvilt. Studier viser at netter med Kp ≥ 5 korrelerer med økte rapporter om søvnløshet i store befolkninger.\n\nFor å motvirke dette, prøv å opprettholde et regelmessig søvnmønster i aktive perioder, unngå skjermer før sengetid og hold soverommet så mørkt som mulig.' },
      { heading: 'Hvem er mest utsatt?', body: 'Selv om de fleste friske voksne merker lite eller ingen effekt av moderat geomagnetisk aktivitet, er noen grupper mer følsomme:\n\n• Personer med hjerte- og karsykdommer, hypertensjon eller arytmier\n• Personer med pacemakere eller implanterte hjertedefibrillatorer — kraftige stormer kan i sjeldne tilfeller påvirke enhetens funksjon\n• Personer med nevrologiske tilstander (epilepsi, migrene, MS)\n• Eldre\n• Personer som allerede er under betydelig fysisk eller emosjonelt stress\n• Følsomme personer som konsekvent rapporterer symptomer under tidligere stormer\n\nGravide kvinner anbefales også å begrense langvarig utendørsopphold under ekstreme G4–G5-hendelser som en forholdsregel.' },
      { heading: 'Hva du kan gjøre', body: 'Det er ingen måte å blokkere geomagnetiske stormer på, men du kan redusere påvirkningen:\n\n• Overvåk aktiviteten — bruk denne appen for å holde deg informert. En DISTURBED- eller STORM-status er signalet ditt til å være oppmerksom.\n• Hvil mer — kroppen din er under ekstra stress. Ikke press deg gjennom tretthet.\n• Hold deg hydrert — vann støtter sunn blokviskositet og hjerte-karsystemets funksjon.\n• Reduser stimulanter — koffein og alkohol forsterker belastningen på hjerte-kar- og nervesystemet.\n• Tilbring tid i naturen — jording (å gå barbeint på gress eller jord) er vist å redusere fysiologiske stressmarkører.\n• Utsett krevende oppgaver — operasjoner, lange flyreiser og intense forhandlinger bør omdisponeres når mulig.\n• Ta medisinen din — ikke hopp over doser i aktive perioder hvis du har en kronisk tilstand.' },
    ],
    sources: 'Basert på publisert forskning i tidsskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Geomagnetiske data levert av GFZ Potsdam og NIGGG.',
  },

  sv: {
    title: 'Magnetstormar och mänsklig hälsa',
    subtitle: 'Hur geomagnetisk aktivitet påverkar kroppen — och vad du kan göra åt det.',
    sections: [
      { heading: 'Vad är en geomagnetisk storm?', body: 'En geomagnetisk storm uppstår när ett utbrott av solvind — laddade partiklar från Solen — träffar jordens magnetfält med tillräcklig kraft för att störa det. Störningen kan pågå från några timmar till flera dagar. Forskare mäter styrkan med Kp-index (0–9) och Dst-index, som följer hur mycket fältet sjunker under händelsen.\n\nStormar klassificeras G1–G5. En G1-storm (Kp 5) orsakar mindre störningar; en G5 (Kp 9) är sällsynt och kan slå ut elnät och satelliter.' },
      { heading: 'Hjärt-kärlsystemet', body: 'Flera expertgranskade studier har funnit ett samband mellan kraftiga geomagnetiska stormar och en ökning av hjärtinfarkter, arytmier och plötsliga hjärtdödsfall — särskilt under de 24–48 timmarna efter stormens start.\n\nMekanismen antas innebära melatoninsuppression och störning av det autonoma nervsystemet, som reglerar hjärtfrekvens och blodtryck. Personer med befintlig hjärtsjukdom, högt blodtryck eller blodkoagulationsstörningar anses vara mest utsatta.\n\nUnder en G2–G3-storm eller starkare, om du har hjärt-kärlsjukdomar, undvik intensiv fysisk ansträngning, håll dig välhydrerad och ha dina mediciner nära till hands.' },
      { heading: 'Hjärna och nervsystem', body: 'Det mänskliga nervsystemet är känsligt för lågfrekventa elektromagnetiska fält. Under geomagnetiska stormar rapporterar många huvudvärk, yrsel, koncentrationssvårigheter och en allmän känsla av mental dimma.\n\nForskning tyder på att geomagnetisk aktivitet påverkar produktionen av serotonin och melatonin i hjärnan. Störda serotoninnivåer kan påverka humör, kognition och smärtkänslighet — vilket förklarar varför en del människor känner sig mer irriterade, oroliga eller förvirrade under aktiva perioder.\n\nPersoner med epilepsi, migrän eller neurologiska tillstånd kan uppleva fler episoder under kraftiga stormar.' },
      { heading: 'Sömnstörningar', body: 'Tallkottkörteln producerar melatonin — det sömnreglerande hormonet — som respons på mörker och jordens naturliga magnetfält. Geomagnetiska stormar stör denna process, hämmar melatoninproduktionen och rubbar dygnsrytmen.\n\nResultatet: svårt att somna, lättare sömn, mer livfulla eller störande drömmar och att vakna utan känsla av vila. Studier visar att nätter med Kp ≥ 5 korrelerar med ökade sömnlöshetsrapporter i stora befolkningsgrupper.\n\nFör att motverka detta, försök hålla ett regelbundet sömnschema under aktiva perioder, undvik skärmar före sänggåendet och håll sovrummet så mörkt som möjligt.' },
      { heading: 'Vem löper störst risk?', body: 'Även om de flesta friska vuxna knappt märker av måttlig geomagnetisk aktivitet, är vissa grupper mer känsliga:\n\n• Personer med hjärt-kärlsjukdomar, hypertoni eller arytmier\n• Personer med pacemakers eller implanterade hjärtrytmdefibrillatorer — kraftiga stormar kan i sällsynta fall påverka enhetens funktion\n• Personer med neurologiska sjukdomar (epilepsi, migrän, MS)\n• Äldre\n• Personer som redan befinner sig under stor fysisk eller emotionell stress\n• Känsliga individer som konsekvent rapporterar symtom under tidigare stormar\n\nGravida kvinnor rekommenderas även att begränsa längre utomhusvistelse vid extrema G4–G5-händelser som en försiktighetsåtgärd.' },
      { heading: 'Vad du kan göra', body: 'Det går inte att blockera geomagnetiska stormar, men du kan minska deras inverkan:\n\n• Övervaka aktiviteten — använd den här appen för att hålla dig informerad. Status DISTURBED eller STORM är din signal att vara uppmärksam.\n• Vila mer — din kropp är under extra stress. Kämpa inte mot tröttheten.\n• Håll dig hydrerad — vatten stöder en sund blokviskositet och hjärt-karlfunktionen.\n• Minska stimulantia — koffein och alkohol förstärker belastningen på hjärt-kärl- och nervsystemet.\n• Tillbringa tid i naturen — jordning (att gå barfota på gräs eller jord) har visats minska fysiologiska stressmarkörer.\n• Skjut upp krävande uppgifter — operationer, långa flygningar och intensiva förhandlingar är bäst att boka om när möjligt.\n• Ta dina mediciner — hoppa inte över doser under aktiva perioder om du har ett kroniskt tillstånd.' },
    ],
    sources: 'Baserat på publicerad forskning i tidskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics och Biomedicine & Pharmacotherapy. Geomagnetiska data tillhandahållna av GFZ Potsdam och NIGGG.',
  },

  da: {
    title: 'Magnetstorme og menneskelig sundhed',
    subtitle: 'Hvordan geomagnetisk aktivitet påvirker kroppen — og hvad du kan gøre ved det.',
    sections: [
      { heading: 'Hvad er en geomagnetisk storm?', body: 'En geomagnetisk storm opstår, når et udbrud af solvind — ladede partikler fra Solen — rammer Jordens magnetfelt kraftigt nok til at forstyrre det. Forstyrrelsen kan vare fra nogle timer til flere dage. Forskere måler dens styrke med Kp-indekset (0–9) og Dst-indekset, som sporer, hvor meget feltet falder under hændelsen.\n\nStormer klassificeres G1–G5. En G1-storm (Kp 5) forårsager mindre forstyrrelser; en G5 (Kp 9) er sjælden og kan lamme elnet og satellitter.' },
      { heading: 'Hjerte-kar-systemet', body: 'Flere fagfællebedømte studier har fundet en sammenhæng mellem kraftige geomagnetiske storme og en stigning i hjerteanfald, arytmier og pludselige hjertedødsfald — særligt i de 24–48 timer efter stormens begyndelse.\n\nMekanismen menes at involvere melatoninsuppression og forstyrrelse af det autonome nervesystem, som regulerer hjertefrekvens og blodtryk. Personer med eksisterende hjertesygdom, højt blodtryk eller blodkoagulationsforstyrrelser anses for mest sårbare.\n\nUnder en G2–G3-storm eller stærkere, hvis du har hjerte-kar-lidelser, skal du undgå intens fysisk anstrengelse, holde dig godt hydreret og have din medicin inden for rækkevidde.' },
      { heading: 'Hjerne og nervesystem', body: 'Det menneskelige nervesystem er følsomt over for lavfrekvente elektromagnetiske felter. Under geomagnetiske storme rapporterer mange om hovedpine, svimmelhed, koncentrationsbesvær og en generel følelse af mental tåge.\n\nForskning tyder på, at geomagnetisk aktivitet påvirker produktionen af serotonin og melatonin i hjernen. Forstyrrede serotoninniveauer kan påvirke humør, kognition og smertesensitivitet — hvilket forklarer, hvorfor nogle mennesker føler sig mere irritable, angste eller forvirrede i aktive perioder.\n\nPersoner med epilepsi, migræne eller neurologiske tilstande kan opleve hyppigere episoder under kraftige storme.' },
      { heading: 'Søvnforstyrrelser', body: 'Pinealkirtlen producerer melatonin — det søvnregulerende hormon — som respons på mørke og Jordens naturlige magnetfelt. Geomagnetiske storme forstyrrer denne proces, hæmmer melatoninproduktionen og forstyrrer de cirkadiane rytmer.\n\nResultatet: besvær med at falde i søvn, lettere søvn, mere levende eller forstyrrende drømme og at vågne uden at føle sig udhvilet. Studier viser, at nætter med Kp ≥ 5 korrelerer med øgede indberetninger om søvnløshed i store befolkningsgrupper.\n\nFor at modvirke dette, forsøg at opretholde et regelmæssigt søvnmønster i aktive perioder, undgå skærme før sengetid og hold soveværelset så mørkt som muligt.' },
      { heading: 'Hvem er mest i risiko?', body: 'Selvom de fleste raske voksne mærker lidt eller ingen effekt af moderat geomagnetisk aktivitet, er nogle grupper mere følsomme:\n\n• Personer med hjerte-kar-sygdomme, hypertension eller arytmier\n• Personer med pacemakere eller implanterede hjertedéfibriller — kraftige storme kan i sjældne tilfælde påvirke enhedens funktion\n• Personer med neurologiske lidelser (epilepsi, migræne, MS)\n• Ældre\n• Personer, der allerede er under betydeligt fysisk eller emotionelt stress\n• Følsomme individer, som konsekvent rapporterer symptomer under tidligere storme\n\nGravide kvinder anbefales også at begrænse langvarig udendørsophold under ekstreme G4–G5-hændelser som en forholdsregel.' },
      { heading: 'Hvad du kan gøre', body: 'Der er ingen måde at blokere geomagnetiske storme på, men du kan reducere deres indvirkning:\n\n• Overvåg aktiviteten — brug denne app for at holde dig informeret. En DISTURBED- eller STORM-status er dit signal til at være opmærksom.\n• Hvil mere — din krop er under ekstra stress. Tving dig ikke igennem træthed.\n• Hold dig hydreret — vand understøtter en sund blokviskositet og hjerte-kar-funktion.\n• Reducer stimulanser — koffein og alkohol forstærker belastningen på hjerte-kar- og nervesystemet.\n• Tilbring tid i naturen — jordning (at gå barfodet på græs eller jord) er vist at reducere fysiologiske stressmarkører.\n• Udskyd krævende opgaver — operationer, lange flyrejser og intense forhandlinger er bedst omplanlagt, når det er muligt.\n• Tag dine mediciner — spring ikke doser over i aktive perioder, hvis du har en kronisk sygdom.' },
    ],
    sources: 'Baseret på publiceret forskning i tidsskrifter som Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Geomagnetiske data leveret af GFZ Potsdam og NIGGG.',
  },

  fi: {
    title: 'Magneettimyrskyt ja ihmisten terveys',
    subtitle: 'Miten geomagneettinen aktiivisuus vaikuttaa ihmiskehoon — ja mitä voit tehdä sen suhteen.',
    sections: [
      { heading: 'Mikä on geomagneettinen myrsky?', body: 'Geomagneettinen myrsky syntyy, kun aurinkotuulen purkaus — Auringosta peräisin olevat varautuneet hiukkaset — iskee maan magneettikenttään riittävän voimakkaasti häiritäkseen sitä. Häiriö voi kestää muutamasta tunnista useaan päivään. Tutkijat mittaavat sen voimakkuutta Kp-indeksillä (0–9) ja Dst-indeksillä, joka seuraa kuinka paljon kenttä laskee tapahtuman aikana.\n\nMyrskyt luokitellaan G1–G5. G1-myrsky (Kp 5) aiheuttaa pieniä häiriöitä; G5 (Kp 9) on harvinainen ja voi kaataa sähköverkkoja ja satelliitteja.' },
      { heading: 'Sydän- ja verisuonijärjestelmä', body: 'Useat vertaisarvioidut tutkimukset ovat löytäneet yhteyden voimakkaiden geomagneettisten myrskyjen ja sydänkohtausten, rytmihäiriöiden sekä äkkikuolemien lisääntymisen välillä — erityisesti myrskyn alkua seuraavan 24–48 tunnin aikana.\n\nMekanismin uskotaan liittyvän melatoniinin tuotannon estymiseen ja autonomisen hermoston häiriintymiseen, joka säätelee sykettä ja verenpainetta. Sydänsairauden, korkean verenpaineen tai veren hyytymishäiriön kanssa elävät ovat herkimmin alttiina.\n\nG2–G3-myrskyn tai sitä voimakkaamman aikana, jos sinulla on sydän- ja verisuonisairauksia, vältä raskasta fyysistä rasitusta, pidä nesteytyksestä huolta ja pidä lääkkeet lähellä.' },
      { heading: 'Aivot ja hermosto', body: 'Ihmisen hermosto on herkkä matalataajuisille sähkömagneettisille kentille. Geomagneettisten myrskyjen aikana monet ihmiset ilmoittavat päänsärystä, huimauksesta, keskittymisvaikeuksista ja yleisestä ajatuksen sumuisuudesta.\n\nTutkimus viittaa siihen, että geomagneettinen aktiivisuus vaikuttaa serotoniinin ja melatoniinin tuotantoon aivoissa. Häiriintyneet serotoniinitasot voivat vaikuttaa mielialaan, kognitioon ja kipuherkkyyteen — mikä selittää, miksi jotkut ihmiset tuntevat itsensä ärtyneem­miksi, ahdistuneemmiksi tai hämmentyneemmiksi aktiivisina jaksoina.\n\nEpilepsian, migreenin tai neurologisten sairauksien kanssa elävät voivat kokea tiheämpiä kohtauksia voimakkaiden myrskyjen aikana.' },
      { heading: 'Unihäiriöt', body: 'Käpyrauhanen tuottaa melatoniinia — unta säätelevää hormonia — vastauksena pimeyteen ja maan luonnolliseen magneettikenttään. Geomaatriset myrskyt häiritsevät tätä prosessia, estävät melatoniinin tuotantoa ja sekoittavat vuorokausirytmin.\n\nSeurauksena on nukahtamisvaikeudet, kevyempi uni, eloisammat tai häiritsevät unet sekä herääminen väsyneenä. Tutkimukset ovat osoittaneet, että Kp ≥ 5 -öihin liittyy lisääntyneitä unettomuusraportteja suurissa väestöissä.\n\nVastapainoksi yritä pitää säännöllinen uniaikataulu aktiivisina jaksoina, vältä näyttöjä ennen nukkumaanmenoa ja pidä makuuhuone niin pimeänä kuin mahdollista.' },
      { heading: 'Kuka on suurimmassa vaarassa?', body: 'Vaikka useimmat terveet aikuiset tuntevat kohtalaisen geomagneettisen aktiivisuuden vaikutukset vain vähän tai ei lainkaan, jotkut ryhmät ovat herkempiä:\n\n• Sydän- ja verisuonisairauden, verenpainetaudin tai rytmihäiriöiden kanssa elävät\n• Sydämentahdistimen tai implantoitavan defibrillaattorin kanssa elävät — voimakkaat myrskyt voivat harvinaisissa tapauksissa vaikuttaa laitteen toimintaan\n• Neurologisten sairauksien (epilepsia, migreeni, MS) kanssa elävät\n• Vanhukset\n• Huomattavan fyysisen tai henkisen stressin alla olevat ihmiset\n• Herkät henkilöt, jotka johdonmukaisesti raportoivat oireita aiempien myrskyjen aikana\n\nRaskaana olevia naisia suositellaan myös rajoittamaan pitkäkestoista ulkona oleskelua äärimmäisten G4–G5-tapahtumien aikana varotoimena.' },
      { heading: 'Mitä voit tehdä', body: 'Geomagneettisia myrskyjä ei voi estää, mutta voit vähentää niiden vaikutusta:\n\n• Seuraa aktiivisuutta — käytä tätä sovellusta pysyäksesi ajan tasalla. DISTURBED- tai STORM-tila on merkki olla valppaana.\n• Lepää enemmän — kehosi on lisästressissä. Älä taistele väsymystä vastaan.\n• Pidä nesteytyksestä huolta — vesi tukee tervettä veren viskositeettia ja sydän- ja verisuonitoimintaa.\n• Vähennä stimulantteja — kofeiini ja alkoholi vahvistavat sydän- ja verisuoni- sekä hermoston kuormitusta.\n• Vietä aikaa luonnossa — maadoitus (paljasjaloin käveleminen ruoholla tai maalla) on todettu vähentävän fysiologisia stressimerkkejä.\n• Lykkää vaativia tehtäviä — leikkaukset, pitkät lennot ja vaativat neuvottelut on parasta siirtää mahdollisuuksien mukaan.\n• Ota lääkkeesi — älä jätä annoksia välistä aktiivisina jaksoina, jos sinulla on krooninen sairaus.' },
    ],
    sources: 'Perustuu julkaistuihin tutkimuksiin lehdissä kuten Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics ja Biomedicine & Pharmacotherapy. Geomagneettisen datan toimittivat GFZ Potsdam ja NIGGG.',
  },

  is: {
    title: 'Segulstormar og heilsa manna',
    subtitle: 'Hvernig jarðsegulvirkni hefur áhrif á líkamann — og hvað þú getur gert í þessu sambandi.',
    sections: [
      { heading: 'Hvað er jarðsegulstormur?', body: 'Jarðsegulstormur á sér stað þegar útbrot sólvinds — hlaðnar agnir frá Sólinni — berst á segulsvið jarðar með nægilegum krafti til að trufla það. Truflunin getur varað frá nokkrum klukkustundum upp í nokkra daga. Vísindamenn mæla styrk þess með Kp-vísitölunni (0–9) og Dst-vísitölunni, sem fylgist með því hversu mikið sviðið lækkar meðan á atburðinum stendur.\n\nStormar eru flokkaðir G1–G5. G1-stormur (Kp 5) veldur minniháttar truflunum; G5 (Kp 9) er sjaldgæfur og getur lagt rafmagnskerfi og gervitungla í rúst.' },
      { heading: 'Hjarta- og æðakerfi', body: 'Margar ritrýndar rannsóknir hafa fundið fylgni milli sterkra jarðsegulstorma og aukinnar tíðni hjartaáfalla, hjartsláttaróreglu og skyndilegs hjartadauða — sérstaklega á 24–48 klukkustundunum í kjölfar stormsbyrjunar.\n\nÁhrifameðferðin er talin fela í sér bælingu melatóníns og truflun á sjálfræna taugakerfinu, sem stjórnar hjartslætti og blóðþrýstingi. Einstaklingar með fyrirliggjandi hjartasjúkdóm, háþrýsting eða blóðstorknunartruflanir eru taldir hvað viðkvæmastir.\n\nÍ G2–G3-stormi eða sterkari: ef þú ert með hjarta- og æðasjúkdóma, forðastu kröftugar líkamlegar hreyfingar, vertu vel vökvaður og hafðu lyfin nálægt.' },
      { heading: 'Heili og taugakerfi', body: 'Taugakerfi mannsins er viðkvæmt fyrir lágíðni rafsegulsviðum. Í jarðsegulstormum greina margir frá höfuðverk, sundli, einbeitingarskorti og almennri tilfinningu um andlegt þoku.\n\nRannsóknir gefa til kynna að jarðsegulvirkni hafi áhrif á framleiðslu serótóníns og melatóníns í heila. Truflaðar serótónínstöður geta haft áhrif á skap, hugsunarferli og viðkvæmni fyrir sársauka — sem skýrir hvers vegna sumir einstaklingar líða meira fyrir pirringi, kvíða eða ringlunni á virkum tímabilum.\n\nEinstaklingar með flogaveiki, mígreni eða taugasjúkdóma geta upplifað tíðari köst í sterkum stormum.' },
      { heading: 'Svefntruflanir', body: 'Keilukirtillinn framleiðir melatónín — svefnstjórnandi hormón — sem svar við myrkri og náttúrulegu segulsviði jarðar. Jarðsegulstormar trufla þetta ferli, bæla framleiðslu melatóníns og raska dægurritmi.\n\nNiðurstaðan: erfiðleikar með að sofna, léttur svefn, líflegari eða órólegri draumar og að vakna þreyttur. Rannsóknir hafa sýnt að nætur með Kp ≥ 5 tengjast auknum skýrslum um svefnleysi hjá stórum þýðum.\n\nTil að vinna gegn þessu: reyndu að viðhalda reglulegu svefnlagi á virkum tímabilum, forðastu skjái fyrir svefn og haltu svefnherberginu eins dökku og mögulegt er.' },
      { heading: 'Hverjir eru í mestri hættu?', body: 'Þótt flestir heilbrigðir fullorðnir finni lítið eða ekkert fyrir hóflega jarðsegulvirkni, eru sumar hópar viðkvæmari:\n\n• Einstaklingar með hjarta- og æðasjúkdóma, háþrýsting eða hjartsláttarótreglu\n• Einstaklingar með gangráð eða ígrædd hjartahlaufarar — sterkir stormar geta í sjaldgæfum tilvikum haft áhrif á virkni tækjanna\n• Einstaklingar með taugasjúkdóma (flogaveiki, mígreni, MS)\n• Aldraðir\n• Einstaklingar sem þegar eru undir miklum líkamlegum eða tilfinningalegum streitu\n• Viðkvæmir einstaklingar sem stöðugt greina frá einkennum í stormum\n\nMæðgur er einnig ráðlagt að takmarka langa dvöl utandyra í G4–G5-atburðum sem varúðarráðstöfun.' },
      { heading: 'Hvað þú getur gert', body: 'Það er engin leið til að loka á jarðsegulstorma, en þú getur dregið úr áhrifum þeirra:\n\n• Fylgstu með virkni — notaðu þetta app til að vera upplýstur. DISTURBED eða STORM staða er merki þitt til að vera varkár.\n• Hvíl þig meira — líkami þinn er undir auknu álagi. Þvingaðu þig ekki í gegnum þreytu.\n• Haltu þig vökvaðan — vatn styður heilbrigðan blóðþykktarleika og hjarta- og æðastarfsemi.\n• Dragðu úr örvaefnum — koffín og áfengi gefa hjarta- og æðakerfi og taugakerfi meiri streitu.\n• Dveldu í náttúrunni — jarðtenging (að ganga berfættur á gras eða jörð) hefur reynst minnka lífeðlisfræðilegar stressvísur.\n• Frestaðu krefjandi verkefnum — aðgerðir, langar flugferðir og erfiðar samningaviðræður eru best að fresta þegar mögulegt er.\n• Taktu lyfin þín — slepptu ekki skömmtum á virkum tímabilum ef þú ert með langvinna sjúkdóma.' },
    ],
    sources: 'Byggt á birtum rannsóknum í tímaritum eins og Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics og Biomedicine & Pharmacotherapy. Jarðsegulgögn frá GFZ Potsdam og NIGGG.',
  },

  pl: {
    title: 'Burze magnetyczne a zdrowie człowieka',
    subtitle: 'Jak aktywność geomagnetyczna wpływa na organizm człowieka — i co możesz z tym zrobić.',
    sections: [
      { heading: 'Czym jest burza geomagnetyczna?', body: 'Burza geomagnetyczna powstaje, gdy wybuch wiatru słonecznego — naładowanych cząstek ze Słońca — uderza w pole magnetyczne Ziemi z wystarczającą siłą, by je zakłócić. Zakłócenie może trwać od kilku godzin do kilku dni. Naukowcy mierzą jej intensywność za pomocą indeksu Kp (0–9) i indeksu Dst, który śledzi, o ile pole spada podczas zdarzenia.\n\nBurze klasyfikuje się od G1 do G5. Burza G1 (Kp 5) powoduje niewielkie zakłócenia; G5 (Kp 9) jest rzadka i może wyłączyć sieci energetyczne oraz satelity.' },
      { heading: 'Układ sercowo-naczyniowy', body: 'Wiele recenzowanych badań wykazało korelację między silnymi burzami geomagnetycznymi a wzrostem liczby zawałów serca, arytmii i nagłych zgonów sercowych — szczególnie w ciągu 24–48 godzin od początku burzy.\n\nPrzypuszcza się, że mechanizm obejmuje zahamowanie produkcji melatoniny i zaburzenie autonomicznego układu nerwowego, który reguluje częstość akcji serca i ciśnienie krwi. Osoby z istniejącymi chorobami serca, nadciśnieniem lub zaburzeniami krzepnięcia krwi są uważane za najbardziej narażone.\n\nPodczas burzy G2–G3 lub silniejszej, jeśli masz choroby układu sercowo-naczyniowego, unikaj intensywnego wysiłku fizycznego, dbaj o odpowiednie nawodnienie i miej leki pod ręką.' },
      { heading: 'Mózg i układ nerwowy', body: 'Ludzki układ nerwowy jest wrażliwy na niskoczęstotliwościowe pola elektromagnetyczne. Podczas burz geomagnetycznych wiele osób zgłasza bóle głowy, zawroty głowy, trudności z koncentracją i ogólne poczucie „zamglenia" umysłu.\n\nBadania sugerują, że aktywność geomagnetyczna wpływa na produkcję serotoniny i melatoniny w mózgu. Zaburzone poziomy serotoniny mogą wpływać na nastrój, funkcje poznawcze i wrażliwość na ból — co tłumaczy, dlaczego niektórzy czują się bardziej drażliwi, niespokojni lub zdezorientowani w aktywnych okresach.\n\nOsoby z epilepsją, migreną lub chorobami neurologicznymi mogą doświadczać częstszych epizodów podczas silnych burz.' },
      { heading: 'Zaburzenia snu', body: 'Szyszynka produkuje melatoninę — hormon regulujący sen — w odpowiedzi na ciemność i naturalne pole magnetyczne Ziemi. Burze geomagnetyczne zakłócają ten proces, hamują produkcję melatoniny i rozregulowują rytmy dobowe.\n\nEfekt: trudności z zasypianiem, płytszy sen, bardziej żywe lub niepokojące sny i budzenie się bez poczucia wypoczęcia. Badania wykazały, że noce z Kp ≥ 5 korelują ze zwiększonymi zgłoszeniami bezsenności w dużych populacjach.\n\nAby temu przeciwdziałać, staraj się zachowywać regularny harmonogram snu w aktywnych okresach, unikaj ekranów przed snem i trzymaj sypialnię tak ciemną, jak to możliwe.' },
      { heading: 'Kto jest najbardziej zagrożony?', body: 'Choć większość zdrowych dorosłych odczuwa niewielkie lub żadne skutki umiarkowanej aktywności geomagnetycznej, niektóre grupy są bardziej wrażliwe:\n\n• Osoby z chorobami sercowo-naczyniowymi, nadciśnieniem lub arytmiami\n• Osoby z rozrusznikami serca lub implantowanymi defibrylatorami — silne burze mogą w rzadkich przypadkach wpływać na działanie urządzenia\n• Osoby z chorobami neurologicznymi (epilepsja, migrena, SM)\n• Osoby starsze\n• Osoby już pod znacznym stresem fizycznym lub emocjonalnym\n• Wrażliwe osoby, które konsekwentnie zgłaszają objawy podczas poprzednich burz\n\nKobietom w ciąży zaleca się również ograniczenie długotrwałego przebywania na zewnątrz podczas ekstremalnych zdarzeń G4–G5 jako środek ostrożności.' },
      { heading: 'Co możesz zrobić', body: 'Nie ma sposobu na zablokowanie burz geomagnetycznych, ale możesz zmniejszyć ich wpływ:\n\n• Monitoruj aktywność — korzystaj z tej aplikacji, aby być na bieżąco. Status DISTURBED lub STORM to sygnał do zachowania ostrożności.\n• Odpoczywaj więcej — twój organizm jest pod dodatkowym stresem. Nie forsuj się przez zmęczenie.\n• Dbaj o nawodnienie — woda wspiera zdrową lepkość krwi i funkcję układu sercowo-naczyniowego.\n• Ogranicz stymulanty — kofeina i alkohol wzmacniają obciążenie układu sercowo-naczyniowego i nerwowego.\n• Spędzaj czas na łonie natury — uziemienie (chodzenie boso po trawie lub ziemi) udowodniono, że obniża fizjologiczne markery stresu.\n• Przekładaj wymagające zadania — operacje, długie loty i intensywne negocjacje najlepiej przekładać, gdy to możliwe.\n• Przyjmuj leki — nie pomijaj dawek w aktywnych okresach, jeśli masz chorobę przewlekłą.' },
    ],
    sources: 'Na podstawie opublikowanych badań w czasopismach takich jak Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics i Biomedicine & Pharmacotherapy. Dane geomagnetyczne dostarczone przez GFZ Potsdam i NIGGG.',
  },

  uk: {
    title: 'Магнітні бурі та здоров\'я людини',
    subtitle: 'Як геомагнітна активність впливає на організм людини — і що ви можете зробити.',
    sections: [
      { heading: 'Що таке геомагнітна буря?', body: 'Геомагнітна буря виникає, коли сплеск сонячного вітру — заряджених частинок від Сонця — вдаряє по магнітному полю Землі з достатньою силою, щоб порушити його. Збурення може тривати від кількох годин до кількох днів. Вчені вимірюють його інтенсивність за допомогою індексу Kp (0–9) та індексу Dst, який відстежує, наскільки поле знижується під час події.\n\nБурі класифікуються від G1 до G5. Буря G1 (Kp 5) спричиняє незначні порушення; G5 (Kp 9) — рідкісна і може вивести з ладу електромережі та супутники.' },
      { heading: 'Серцево-судинна система', body: 'Ряд рецензованих досліджень виявив кореляцію між сильними геомагнітними бурями і збільшенням кількості серцевих нападів, аритмій та раптових серцевих смертей — особливо в перші 24–48 годин після початку бурі.\n\nПередбачається, що механізм включає пригнічення мелатоніну та порушення роботи вегетативної нервової системи, яка регулює частоту серцевих скорочень і артеріальний тиск. Найбільш вразливими вважаються люди з наявними серцевими захворюваннями, гіпертонією або порушеннями згортання крові.\n\nПід час бурі G2–G3 і вище, якщо у вас є серцево-судинні захворювання, уникайте інтенсивних фізичних навантажень, підтримуйте водний баланс і тримайте ліки під рукою.' },
      { heading: 'Мозок і нервова система', body: 'Нервова система людини чутлива до низькочастотних електромагнітних полів. Під час геомагнітних бурь багато людей скаржаться на головний біль, запаморочення, труднощі з концентрацією уваги та загальне відчуття «туману» в голові.\n\nДослідження свідчать про те, що геомагнітна активність впливає на вироблення серотоніну та мелатоніну в мозку. Порушені рівні серотоніну можуть впливати на настрій, когнітивні функції та больову чутливість — що пояснює, чому деякі люди відчувають більшу дратівливість, тривогу або розгубленість в активні періоди.\n\nЛюди з епілепсією, мігренню або неврологічними захворюваннями можуть відчувати частіші напади під час сильних бурь.' },
      { heading: 'Порушення сну', body: 'Шишкоподібна залоза виробляє мелатонін — гормон, що регулює сон, — у відповідь на темряву і природне магнітне поле Землі. Геомагнітні бурі порушують цей процес, пригнічують вироблення мелатоніну та руйнують циркадні ритми.\n\nРезультат: труднощі із засинанням, поверхневий сон, яскравіші або тривожні сновидіння та прокидання без відчуття відпочинку. Дослідження показали, що ночі з Kp ≥ 5 корелюють із збільшенням повідомлень про безсоння серед великих груп населення.\n\nЩоб протидіяти цьому, намагайтеся дотримуватися стабільного режиму сну в активні періоди, уникайте екранів перед сном і тримайте спальню якомога темнішою.' },
      { heading: 'Хто найбільше в групі ризику?', body: 'Більшість здорових дорослих практично не відчувають впливу помірної геомагнітної активності, однак деякі групи більш вразливі:\n\n• Люди з серцево-судинними захворюваннями, гіпертонією або аритміями\n• Люди з кардіостимуляторами або імплантованими дефібриляторами — сильні бурі в рідкісних випадках можуть впливати на роботу пристроїв\n• Люди з неврологічними захворюваннями (епілепсія, мігрень, розсіяний склероз)\n• Люди похилого віку\n• Люди, що перебувають під значним фізичним або емоційним стресом\n• Чутливі особи, які систематично повідомляють про симптоми під час попередніх бурь\n\nВагітним жінкам також рекомендується обмежити тривале перебування на відкритому повітрі під час екстремальних подій G4–G5 як запобіжний захід.' },
      { heading: 'Що ви можете зробити', body: 'Заблокувати геомагнітні бурі неможливо, але ви можете зменшити їх вплив:\n\n• Стежте за активністю — використовуйте цей застосунок. Статус DISTURBED або STORM — сигнал бути обережним.\n• Більше відпочивайте — ваш організм відчуває додаткове навантаження. Не змушуйте себе долати втому.\n• Пийте достатньо води — вона підтримує здорову в\'язкість крові та роботу серцево-судинної системи.\n• Скоротіть стимулятори — кофеїн і алкоголь підсилюють навантаження на серцево-судинну та нервову системи.\n• Проводьте час на природі — заземлення (ходіння босоніж по траві або землі) доведено знижує фізіологічні маркери стресу.\n• Відкладайте відповідальні справи — операції, далекі перельоти та інтенсивні переговори краще перенести при можливості.\n• Приймайте ліки — не пропускайте дози в активні періоди, якщо маєте хронічне захворювання.' },
    ],
    sources: 'На основі опублікованих досліджень у журналах Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics та Biomedicine & Pharmacotherapy. Геомагнітні дані надані GFZ Potsdam та NIGGG.',
  },

  ko: {
    title: '자기 폭풍과 인체 건강',
    subtitle: '지자기 활동이 인체에 미치는 영향 — 그리고 대처 방법.',
    sections: [
      { heading: '지자기 폭풍이란?', body: '지자기 폭풍은 태양풍 — 태양에서 방출된 하전 입자 — 이 지구 자기장을 교란할 만큼 강하게 충돌할 때 발생합니다. 교란은 수 시간에서 며칠까지 지속될 수 있습니다. 과학자들은 Kp 지수(0–9)와 Dst 지수를 이용해 강도를 측정하며, Dst 지수는 사건 중 자기장이 얼마나 감소하는지를 추적합니다.\n\n폭풍은 G1–G5로 분류됩니다. G1 폭풍(Kp 5)은 경미한 장애를 일으키고, G5(Kp 9)는 드물게 발생하며 전력망과 위성에 영향을 줄 수 있습니다.' },
      { heading: '심혈관계', body: '여러 동료 심사 연구에서 강한 지자기 폭풍과 심장마비, 부정맥, 돌연사 증가 사이의 상관관계가 확인되었습니다 — 특히 폭풍 발생 후 24–48시간 내에 두드러집니다.\n\n이 메커니즘은 멜라토닌 억제와 심박수 및 혈압을 조절하는 자율 신경계 교란과 관련된 것으로 추정됩니다. 기존 심장 질환, 고혈압 또는 혈액 응고 장애가 있는 사람이 가장 취약합니다.\n\nG2–G3 이상의 폭풍 시, 심혈관 질환이 있다면 격렬한 운동을 피하고 충분한 수분을 섭취하며 약을 가까이 두세요.' },
      { heading: '뇌와 신경계', body: '인간 신경계는 저주파 전자기장에 민감합니다. 지자기 폭풍 중 많은 사람이 두통, 어지러움, 집중력 저하, 정신적 안개감을 호소합니다.\n\n연구에 따르면 지자기 활동은 뇌에서 세로토닌과 멜라토닌 생성에 영향을 줍니다. 세로토닌 수치가 교란되면 기분, 인지 기능, 통증 민감도에 영향을 미칠 수 있어 — 활동기에 일부 사람이 더 예민하거나 불안하거나 혼란스러워하는 이유를 설명합니다.\n\n뇌전증, 편두통 또는 신경학적 질환이 있는 사람은 강한 폭풍 중 증상이 더 자주 나타날 수 있습니다.' },
      { heading: '수면 장애', body: '송과선은 어둠과 지구의 자연 자기장에 반응하여 수면을 조절하는 호르몬인 멜라토닌을 생성합니다. 지자기 폭풍은 이 과정을 방해하여 멜라토닌 생성을 억제하고 일주기 리듬을 교란합니다.\n\n그 결과 잠들기 어려움, 얕은 수면, 선명하거나 불안한 꿈, 피로감을 느끼며 깨어남이 나타납니다. 연구에 따르면 Kp ≥ 5인 밤에는 대규모 인구에서 불면증 보고가 증가하는 것으로 나타났습니다.\n\n대처법으로 활동기에 일정한 수면 스케줄을 유지하고, 자기 전 스크린을 피하며, 침실을 최대한 어둡게 유지하세요.' },
      { heading: '가장 위험한 사람은?', body: '대부분의 건강한 성인은 보통 수준의 지자기 활동에서 영향을 거의 느끼지 못하지만, 일부 그룹은 더 민감합니다:\n\n• 심혈관 질환, 고혈압 또는 부정맥이 있는 사람\n• 심박 조율기나 이식형 심율동 전환기가 있는 사람 — 강한 폭풍이 드물게 기기 기능에 영향을 줄 수 있음\n• 신경학적 질환이 있는 사람(뇌전증, 편두통, 다발성경화증)\n• 노인\n• 이미 심한 신체적 또는 정서적 스트레스를 받고 있는 사람\n• 이전 폭풍 때 일관되게 증상을 보고한 민감한 개인\n\n임산부는 극단적인 G4–G5 상황에서 예방 조치로 야외 장시간 노출을 제한하는 것이 권장됩니다.' },
      { heading: '대처 방법', body: '지자기 폭풍을 막을 수는 없지만 영향을 줄일 수 있습니다:\n\n• 활동 모니터링 — 이 앱을 사용해 최신 정보를 확인하세요. DISTURBED 또는 STORM 상태는 주의 신호입니다.\n• 더 쉬세요 — 몸이 추가 스트레스를 받고 있습니다. 피로를 억지로 이겨내지 마세요.\n• 충분히 수분을 섭취하세요 — 물은 건강한 혈액 점도와 심혈관 기능을 지원합니다.\n• 자극제를 줄이세요 — 카페인과 알코올은 심혈관계와 신경계 부담을 가중시킵니다.\n• 자연에서 시간을 보내세요 — 접지(잔디나 흙 위를 맨발로 걷기)는 생리적 스트레스 지표를 낮추는 것으로 입증되었습니다.\n• 부담스러운 일을 미루세요 — 수술, 장거리 비행, 집중 협상은 가능하면 일정을 조정하세요.\n• 약을 복용하세요 — 만성 질환이 있다면 활동기에 복용을 빠뜨리지 마세요.' },
    ],
    sources: 'Space Weather, Journal of Atmospheric and Solar-Terrestrial Physics, Biomedicine & Pharmacotherapy 등의 학술지에 발표된 연구를 바탕으로 작성되었습니다. 지자기 데이터는 GFZ Potsdam 및 NIGGG 제공.',
  },

  zh: {
    title: '磁暴与人类健康',
    subtitle: '地磁活动如何影响人体——以及您能做什么。',
    sections: [
      { heading: '什么是地磁暴？', body: '地磁暴发生在太阳风爆发——来自太阳的带电粒子——以足够强的力撞击地球磁场时。扰动可持续数小时至数天。科学家使用Kp指数（0–9）和Dst指数来衡量其强度，后者追踪事件期间磁场的下降幅度。\n\n磁暴按G1–G5分级。G1级磁暴（Kp 5）造成轻微干扰；G5（Kp 9）罕见，可导致电网和卫星瘫痪。' },
      { heading: '心血管系统', body: '多项同行评审研究发现，强地磁暴与心脏病发作、心律失常和心脏性猝死增加之间存在相关性——尤其在磁暴发生后24–48小时内最为明显。\n\n其机制被认为涉及褪黑素抑制和调节心率与血压的自主神经系统紊乱。患有心脏病、高血压或凝血障碍的人被认为最易受影响。\n\nG2–G3级以上磁暴期间，若您有心血管疾病，请避免剧烈运动，保持充分补水，并将药物放在随手可取之处。' },
      { heading: '大脑与神经系统', body: '人类神经系统对低频电磁场敏感。地磁暴期间，许多人会出现头痛、头晕、注意力难以集中以及整体思维迟钝的感觉。\n\n研究表明，地磁活动会影响大脑中血清素和褪黑素的分泌。血清素水平紊乱可影响情绪、认知和疼痛敏感性——这解释了为何部分人在活跃期感到更烦躁、焦虑或困惑。\n\n患有癫痫、偏头痛或神经系统疾病的人，在强磁暴期间可能会经历更频繁的发作。' },
      { heading: '睡眠障碍', body: '松果体响应黑暗和地球天然磁场产生褪黑素——调节睡眠的激素。地磁暴会干扰这一过程，抑制褪黑素分泌并破坏昼夜节律。\n\n结果是：难以入睡、睡眠变浅、梦境更生动或令人不安，以及醒来后依然疲惫。研究表明，Kp ≥ 5的夜晚与大规模人群失眠报告增加存在相关性。\n\n应对措施：活跃期尽量保持规律的睡眠时间，睡前避免使用屏幕，并尽量保持卧室黑暗。' },
      { heading: '哪些人风险最高？', body: '大多数健康成年人对适度地磁活动几乎没有感觉，但某些群体更为敏感：\n\n• 患有心血管疾病、高血压或心律失常的人\n• 安装心脏起搏器或植入式心律转复除颤器的人——强磁暴在罕见情况下可能影响设备功能\n• 患有神经系统疾病（癫痫、偏头痛、多发性硬化症）的人\n• 老年人\n• 已处于较大身体或情绪压力下的人\n• 曾在过往磁暴中持续报告症状的敏感个体\n\n孕妇也被建议在极端G4–G5事件期间，作为预防措施减少长时间户外暴露。' },
      { heading: '您能做什么', body: '无法阻止地磁暴，但可以减少其影响：\n\n• 监测活动——使用本应用保持了解。DISTURBED或STORM状态是您需要注意的信号。\n• 多休息——您的身体承受着额外压力。不要强撑疲惫。\n• 保持补水——水分有助于维持健康的血液黏度和心血管功能。\n• 减少刺激性物质——咖啡因和酒精会加重心血管系统和神经系统的负担。\n• 到大自然中去——接地（在草地或土壤上赤脚行走）已被证明能降低生理应激指标。\n• 推迟高要求任务——手术、长途飞行和高强度谈判最好在可能时重新安排。\n• 按时服药——若您有慢性病，在活跃期请勿漏服。' },
    ],
    sources: '基于发表在Space Weather、Journal of Atmospheric and Solar-Terrestrial Physics和Biomedicine & Pharmacotherapy等期刊上的研究。地磁数据由GFZ Potsdam和NIGGG提供。',
  },

  ja: {
    title: '磁気嵐と人体への影響',
    subtitle: '地磁気活動が人体に与える影響と、その対処法。',
    sections: [
      { heading: '地磁気嵐とは何か', body: '地磁気嵐は、太陽風の爆発——太陽から放出された荷電粒子——が地球の磁場を乱すほど強く衝突したときに発生します。乱れは数時間から数日間続くことがあります。科学者はKp指数（0–9）とDst指数を使って強度を測定します。Dst指数は現象の発生中に磁場がどれだけ低下するかを追跡します。\n\n嵐はG1–G5に分類されます。G1嵐（Kp 5）は軽微な障害を引き起こし、G5（Kp 9）はまれで、電力網や衛星を機能不全に陥らせる可能性があります。' },
      { heading: '心血管系', body: '複数の査読済み研究により、強い地磁気嵐と心筋梗塞、不整脈、突然死の増加との相関が確認されています——特に嵐の発生から24〜48時間以内に顕著です。\n\nそのメカニズムは、メラトニンの抑制と、心拍数・血圧を制御する自律神経系の乱れに関係すると考えられています。既往の心疾患、高血圧、血液凝固障害を持つ方が最も脆弱とされています。\n\nG2–G3以上の嵐の際、心血管系の疾患をお持ちの場合は、激しい運動を避け、水分を十分に摂り、薬を手の届くところに置いておいてください。' },
      { heading: '脳と神経系', body: '人間の神経系は低周波電磁場に敏感です。地磁気嵐の際、多くの人が頭痛、めまい、集中困難、全体的な思考の霞みを訴えます。\n\n研究によると、地磁気活動は脳内のセロトニンとメラトニンの産生に影響を与えます。セロトニン濃度の乱れは気分、認知、痛覚感受性に影響を及ぼすことがあり——これにより活発な時期に一部の人がより苛立ちやすく、不安になりやすく、混乱しやすくなることが説明できます。\n\nてんかん、偏頭痛、または神経疾患を持つ方は、強い嵐の際により頻繁なエピソードを経験する可能性があります。' },
      { heading: '睡眠障害', body: '松果体は、暗さと地球の自然磁場に応答して、睡眠を調節するホルモンであるメラトニンを産生します。地磁気嵐はこのプロセスを妨げ、メラトニンの産生を抑制し、概日リズムを乱します。\n\nその結果として、寝付きにくさ、浅い眠り、鮮明または不安な夢、疲労感を伴う目覚めが生じます。研究では、Kp ≥ 5の夜が大規模な集団における不眠の報告増加と相関することが示されています。\n\n対処法として、活動期には規則的な睡眠スケジュールを維持し、就寝前にスクリーンを避け、寝室をできる限り暗く保つようにしてください。' },
      { heading: '最もリスクが高いのは誰か', body: 'ほとんどの健康な成人は、中程度の地磁気活動にほとんど影響を感じませんが、一部のグループはより敏感です：\n\n• 心血管疾患、高血圧、または不整脈を持つ方\n• ペースメーカーや植込み型除細動器を持つ方——強い嵐がまれに機器の機能に影響する場合があります\n• 神経疾患（てんかん、偏頭痛、多発性硬化症）を持つ方\n• 高齢者\n• すでに重大な身体的・精神的ストレスを受けている方\n• 過去の嵐の際に一貫して症状を報告している敏感な方\n\n妊婦の方も、極端なG4–G5イベントの際には予防措置として長時間の屋外滞在を控えることが推奨されます。' },
      { heading: '対処できること', body: '地磁気嵐を防ぐことはできませんが、その影響を軽減することは可能です：\n\n• 活動を監視する——このアプリを使って最新情報を把握してください。DISTURBEDまたはSTORMのステータスは注意のサインです。\n• 多く休む——体は追加的なストレスを受けています。疲労を無理に押し切ろうとしないでください。\n• 水分を補給する——水は健全な血液粘度と心血管機能をサポートします。\n• 刺激物を減らす——カフェインとアルコールは心血管系と神経系への負担を増大させます。\n• 自然の中で過ごす——グラウンディング（草地や土の上を裸足で歩くこと）は生理的ストレス指標を低下させることが示されています。\n• 負担の大きい作業を延期する——手術、長距離フライト、集中した交渉は可能な限り予定を変更するのが最善です。\n• 薬を服用する——慢性疾患がある場合、活動期に服用を怠らないようにしてください。' },
    ],
    sources: 'Space Weather、Journal of Atmospheric and Solar-Terrestrial Physics、Biomedicine & Pharmacotherapyなどの学術誌に掲載された研究に基づいています。地磁気データはGFZ PotsdamおよびNIGGGより提供。',
  },
};
