// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Rumvejr Dashboard i Realtid","description":"Overvåg solaktivitet og nordlysprognoser. Live Kp-indeks, solvind og geomagnetiske stormadvarsler."},
  "/dashboard": {"title":"Rumvejr Dashboard — Live Kp-indeks | The Storm Watcher","description":"Live rumvejrdata: Kp-indeks, solvindshastighed, Bz-komponent, røntgenstråling og stormdiagrammer."},
  "/forecast": {"title":"27-Dages Geomagnetisk Prognose | The Storm Watcher","description":"27-dages geomagnetisk prognose med Kp-forudsigelser, Ap-indeks og stormssandsynlighed."},
  "/aurora": {"title":"Nordlys Prognose i Aften — Kan Jeg Se Nordlyset? | The Storm Watcher","description":"Tjek nordlyssynlighed for din placering. Realtids OVATION-model, Kp-indeks, skydække og 3D-globus."},
  "/alerts": {"title":"Solstorm & CME Advarsler — Realtids Rumvejr | The Storm Watcher","description":"Live advarsler om geomagnetiske storme, solflares og CME'er. Realtids NOAA DONKI-notifikationer."},
  "/mood": {"title":"Kosmisk Humørpuls — Hvordan Påvirker Rumvejret Dig? | The Storm Watcher","description":"Spor hvordan soludbrud påvirker dit humør. Deltag i fællesskabet og del, hvordan du har det."},
  "/uv": {"title":"UV-indeks — Realtids Solstrålingsprognose | The Storm Watcher","description":"Realtids UV-indeks og solstrålingsprognose for din placering. Vide hvornår du skal bruge solcreme."},
  "/sun": {"title":"Solopgang og Solnedgang — Den Gyldne Time | The Storm Watcher","description":"Nøjagtige tider for solopgang, solnedgang og gylden time for din placering."},
  "/sky": {"title":"Himmelssigt I Aften — Stjernekiggeri & Nordlys | The Storm Watcher","description":"Skydække, seeingforhold og nordlyssigt i aften. Planlæg din stjernekiggersession."},
  "/iss": {"title":"ISS Tracker — Live Internationale Rumstations Position | The Storm Watcher","description":"Spor den Internationale Rumstation i realtid. Live position, højde, hastighed og kommende passeringer."},
  "/faq": {"title":"Nordlys FAQ — Nordlysguide | The Storm Watcher","description":"Alt du behøver at vide om nordlyset, Kp-indekset og hvordan du ser nordlyset."},
  "/magnetic-effects": {"title":"Magnetstorme & Menneskelig Sundhed — The Storm Watcher","description":"Hvordan geomagnetisk aktivitet påvirker kroppen — hovedpine, søvn, humør — og hvad du kan gøre."},
  "/pricing": {"title":"Priser — The Storm Watcher Pro & Premium Planer","description":"Vælg din plan. Gratis nordlysovervågning eller Pro/Premium med avancerede advarsler og 14 dages gratis prøve."},
  "/about": {"title":"Om os — The Storm Watcher","description":"Realtids rumvejrovervågning og nordlysprognose app. Lær om vores mission og datakilder."},
  "/privacy": {"title":"Privatlivspolitik — The Storm Watcher","description":"Privatlivspolitik for The Storm Watcher. Lær, hvordan vi indsamler og beskytter dine personlige data."},
  "/terms": {"title":"Vilkår for Brug — The Storm Watcher","description":"Vilkår for brug af rumvejrovervågningsapplikationen The Storm Watcher."},
  "/gallery": {"title":"Aurora Fotogalleri — Fællesskabets Nordlysbilleder | The Storm Watcher","description":"Se fantastiske nordlysbilleder delt af Storm Watcher-fællesskabet fra hele verden."},
  "/hunt": {"title":"Nordlysjagt — Rapportér Observationer & Tjen Badges | The Storm Watcher","description":"Rapportér nordlysobservationer, tjen badges og konkurrér på det globale leaderboard."},
  "/livestream": {"title":"Aurora Livestream — Live Nordlys Kameraer | The Storm Watcher","description":"Se live nordlys kameraer fra Norge, Island og Finland. Realtids nordlysstreams 24/7."},
  "/calendar": {"title":"Aurora Kalender — Bedste Nætter for Nordlys | The Storm Watcher","description":"3-natters nordlysudsigtsprognose med Kp-prognose og skydække. Find din bedste nat til nordlys."},
  "/aurora-map": {"title":"Aurora Synlighedskort — Hvor Kan Du Se Nordlyset? | The Storm Watcher","description":"Live verdenskort med nordlyssynlighedszoner baseret på det aktuelle Kp-indeks."},
};

export default meta;
