// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Echtzeit-Weltraumwetter Dashboard","description":"Überwachen Sie Sonnenaktivität und Polarlichter. Live Kp-Index, Sonnenwind und geomagnetische Sturmwarnungen."},
  "/dashboard": {"title":"Weltraumwetter Dashboard — Live Kp-Index & Sonnenwind | The Storm Watcher","description":"Live-Weltraumwetterdaten: Kp-Index, Sonnenwindgeschwindigkeit, Bz-Komponente, Röntgenstrahlung und Sturmdiagramme."},
  "/forecast": {"title":"27-Tage Geomagnetische Prognose — Weltraumwetter | The Storm Watcher","description":"27-Tage-Prognose mit Kp-Vorhersagen, Ap-Index, Sonnenfluss F10.7 und Sturmwahrscheinlichkeit."},
  "/aurora": {"title":"Polarlichter Prognose Heute Nacht — Kann Ich die Nordlichter Sehen? | The Storm Watcher","description":"Prüfen Sie die Aurora-Sichtbarkeit für Ihren Standort. Echtzeit-OVATION-Modell, Kp-Index, Bewölkung und 3D-Globus."},
  "/alerts": {"title":"Sonnensturm & CME Warnungen — Echtzeit Weltraumwetter | The Storm Watcher","description":"Live-Warnungen für geomagnetische Stürme, Sonneneruptionen und CMEs. Echtzeit NOAA DONKI Benachrichtigungen."},
  "/mood": {"title":"Kosmischer Stimmungspuls — Wie Beeinflusst das Weltraumwetter Sie? | The Storm Watcher","description":"Verfolgen Sie, wie Sonnenstürme Ihre Stimmung beeinflussen. Teilen Sie, wie Sie sich heute fühlen."},
  "/uv": {"title":"UV-Index — Echtzeit Sonnenstrahlung Prognose | The Storm Watcher","description":"Echtzeit UV-Index und Sonnenstrahlung für Ihren Standort. Wissen Sie, wann Sie Sonnenschutz auftragen sollten."},
  "/sun": {"title":"Sonnenauf- & Untergang — Goldene Stunde Rechner | The Storm Watcher","description":"Genaue Sonnenaufgang-, Sonnenuntergang- und Golden-Hour-Zeiten für Ihren Standort."},
  "/sky": {"title":"Himmelsicht Heute Nacht — Sternbeobachtung & Polarlicht | The Storm Watcher","description":"Bewölkung, Seeing-Bedingungen und Aurora-Sichtbarkeit heute Nacht. Planen Sie Ihre Sternenbeobachtung."},
  "/iss": {"title":"ISS Tracker — Live Position der Internationalen Raumstation | The Storm Watcher","description":"Verfolgen Sie die ISS in Echtzeit. Live-Position, Höhe, Geschwindigkeit und bevorstehende Überflüge."},
  "/faq": {"title":"Polarlicht FAQ — Nordlichter Ratgeber | The Storm Watcher","description":"Alles, was Sie über Nordlichter, den Kp-Index und Sonnenwind wissen müssen. Expertenwissen zu Weltraumwetter."},
  "/magnetic-effects": {"title":"Magnetstürme & Menschliche Gesundheit — The Storm Watcher","description":"Wie geomagnetische Aktivität den Körper beeinflusst — Kopfschmerzen, Schlaf, Stimmung — und was Sie tun können."},
  "/pricing": {"title":"Preise — The Storm Watcher Pro & Premium Pläne","description":"Wählen Sie Ihren Plan. Kostenloses Aurora-Monitoring oder Pro/Premium mit erweiterten Warnungen und 14-Tage-Test."},
  "/about": {"title":"Über uns — The Storm Watcher","description":"Echtzeit-Weltraumwetter-Überwachung und Aurora-Prognose-App. Erfahren Sie mehr über unsere Mission und Datenquellen."},
  "/privacy": {"title":"Datenschutzrichtlinie — The Storm Watcher","description":"Datenschutzrichtlinie für The Storm Watcher. Erfahren Sie, wie wir Ihre persönlichen Daten erheben und schützen."},
  "/terms": {"title":"Nutzungsbedingungen — The Storm Watcher","description":"Nutzungsbedingungen für The Storm Watcher Weltraumwetter-Anwendung."},
  "/gallery": {"title":"Aurora Fotogalerie — Community Nordlichter-Fotos | The Storm Watcher","description":"Besuchen Sie atemberaubende Polarlichtfotos der Storm Watcher Community aus aller Welt."},
  "/hunt": {"title":"Polarlicht-Jagd — Sichtungen Melden & Abzeichen Verdienen | The Storm Watcher","description":"Melden Sie Polarlicht-Sichtungen, verdienen Sie Abzeichen und treten Sie auf der globalen Rangliste an."},
  "/livestream": {"title":"Aurora Livestream — Live Nordlicht Kameras | The Storm Watcher","description":"Live-Aurora-Kameras aus Norwegen, Island und Finnland. Echtzeit-Nordlicht-Streams rund um die Uhr."},
  "/calendar": {"title":"Aurora Kalender — Beste Nächte für Nordlichter | The Storm Watcher","description":"3-Nächte-Aurora-Vorschau mit Kp-Prognose und Bewölkung. Finden Sie Ihre beste Nacht für Nordlichter."},
};

export default meta;
