// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Panel de Clima Espacial en Tiempo Real","description":"Monitoriza la actividad solar y las auroras. Índice Kp en vivo, viento solar y alertas de tormentas geomagnéticas."},
  "/dashboard": {"title":"Panel de Clima Espacial — Índice Kp en Vivo | The Storm Watcher","description":"Datos de clima espacial en vivo: índice Kp, velocidad del viento solar, componente Bz, flujo de rayos X y gráficos de tormentas."},
  "/forecast": {"title":"Pronóstico Geomagnético 27 Días — Predicciones | The Storm Watcher","description":"Pronóstico extendido de 27 días con predicciones Kp, índice Ap, flujo solar F10.7 y probabilidad de tormentas."},
  "/aurora": {"title":"Pronóstico de Aurora Esta Noche — ¿Puedo Ver la Aurora Boreal? | The Storm Watcher","description":"Comprueba la visibilidad de la aurora boreal para tu ubicación. Modelo OVATION, índice Kp, nubosidad y globo 3D."},
  "/alerts": {"title":"Alertas de Tormenta Solar y CME — Tiempo Espacial en Vivo | The Storm Watcher","description":"Alertas en vivo para tormentas geomagnéticas, erupciones solares y CMEs. Notificaciones NOAA DONKI en tiempo real."},
  "/mood": {"title":"Pulso de Humor Cósmico — ¿Cómo Te Afecta el Clima Espacial? | The Storm Watcher","description":"Monitoriza cómo las tormentas solares afectan tu estado de ánimo. Únete a la comunidad y comparte tu estado de hoy."},
  "/uv": {"title":"Índice UV — Pronóstico de Exposición Solar | The Storm Watcher","description":"Índice UV en tiempo real y pronóstico de exposición solar. Sepa cuándo aplicar protector solar."},
  "/sun": {"title":"Amanecer y Atardecer — Calculadora de Hora Dorada | The Storm Watcher","description":"Horarios precisos de amanecer, atardecer y hora dorada para tu ubicación."},
  "/sky": {"title":"Visibilidad del Cielo Esta Noche — Observación de Estrellas | The Storm Watcher","description":"Cobertura de nubes, condiciones de seeing y pronóstico de auroras esta noche."},
  "/iss": {"title":"Rastreador de la ISS — Posición en Vivo de la Estación Espacial | The Storm Watcher","description":"Sigue la Estación Espacial Internacional en tiempo real. Posición, altitud, velocidad y próximos pases."},
  "/faq": {"title":"Preguntas Frecuentes sobre Auroras — Guía de la Aurora Boreal | The Storm Watcher","description":"Todo lo que necesitas saber sobre la Aurora Boreal, el índice Kp y cómo ver la aurora."},
  "/magnetic-effects": {"title":"Tormentas Magnéticas y Salud Humana — The Storm Watcher","description":"Cómo la actividad geomagnética afecta al cuerpo: dolores de cabeza, sueño, estado de ánimo y qué puedes hacer."},
  "/pricing": {"title":"Precios — Planes Pro y Premium de The Storm Watcher","description":"Elige tu plan. Monitoreo de aurora gratuito o Pro/Premium con alertas avanzadas y prueba gratuita de 14 días."},
  "/about": {"title":"Acerca de — The Storm Watcher","description":"Aplicación de monitoreo de clima espacial y pronóstico de auroras en tiempo real. Conozca nuestra misión y fuentes de datos."},
  "/privacy": {"title":"Política de Privacidad — The Storm Watcher","description":"Política de privacidad de The Storm Watcher. Conozca cómo recopilamos y protegemos sus datos personales."},
  "/terms": {"title":"Términos de Servicio — The Storm Watcher","description":"Términos de servicio de la aplicación de monitoreo de clima espacial The Storm Watcher."},
  "/gallery": {"title":"Galería de Fotos de Auroras — Fotos de la Comunidad | The Storm Watcher","description":"Explora impresionantes fotos de auroras boreales compartidas por la comunidad de Storm Watcher."},
  "/hunt": {"title":"Caza de Auroras — Reporta Avistamientos y Gana Insignias | The Storm Watcher","description":"Reporta avistamientos de auroras, gana insignias y compite en la clasificación global."},
  "/livestream": {"title":"Aurora en Directo — Cámaras en Vivo de la Aurora Boreal | The Storm Watcher","description":"Mira cámaras en vivo de auroras desde Noruega, Islandia y Finlandia. Transmisiones 24/7."},
  "/calendar": {"title":"Calendario de Auroras — Mejores Noches para la Aurora Boreal | The Storm Watcher","description":"Perspectiva de 3 noches para ver auroras con pronóstico Kp y cobertura de nubes."},
  "/aurora-map": {"title":"Mapa de Visibilidad de Auroras — ¿Dónde Ver la Aurora Boreal? | The Storm Watcher","description":"Mapa mundial en vivo con zonas de visibilidad de auroras según el índice Kp actual."},
};

export default meta;
