// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Avaruussää Reaaliajassa","description":"Seuraa auringon aktiivisuutta ja revontuliennusteita. Live Kp-indeksi, aurinkotuuli ja geomagnetismi."},
  "/dashboard": {"title":"Avaruussää Dashboard — Live Kp-indeksi | The Storm Watcher","description":"Reaaliaikaiset avaruussäätiedot: Kp-indeksi, aurinkotuulen nopeus, Bz-komponentti ja geomagneettinen myrsky."},
  "/forecast": {"title":"27 Päivän Geomagneettinen Ennuste | The Storm Watcher","description":"27 päivän geomagneettinen ennuste: Kp-ennusteet, Ap-indeksi, aurinkovuota F10.7 ja myrskytodennäköisyys."},
  "/aurora": {"title":"Revontuliennuste Tänä Yönä — Näenkö Revontulet? | The Storm Watcher","description":"Tarkista revontulien näkyvyys sijainnissasi. Reaaliaikainen OVATION-malli, Kp-indeksi, pilvisyys ja 3D-maapallo."},
  "/alerts": {"title":"Aurinkomyrsky & CME Hälytykset — Avaruussää | The Storm Watcher","description":"Live-hälytykset geomagneettisista myrskyistä, aurinkotuoksahduksista ja CME:istä. Reaaliaikaiset NOAA-ilmoitukset."},
  "/mood": {"title":"Kosminen Mielialaanssi — Miten Avaruussää Vaikuttaa Sinuun? | The Storm Watcher","description":"Seuraa kuinka aurinkoinyrskyt vaikuttavat mielialaasi. Liity yhteisöön ja jaa vointisi."},
  "/uv": {"title":"UV-indeksi — Reaaliaikainen Aurinkoaltistusennuste | The Storm Watcher","description":"Reaaliaikainen UV-indeksi ja aurinkoaltistusennuste sijaintisi perusteella."},
  "/sun": {"title":"Auringonnousu ja -lasku — Kultainen Tunti | The Storm Watcher","description":"Tarkat auringonnousu-, auringonlasku- ja kultaisen tunnin ajat sijaintisi perusteella."},
  "/sky": {"title":"Taivaan Näkyvyys Tänä Yönä — Tähtitaivaan Tarkkailu | The Storm Watcher","description":"Tämän yön pilvisyys, näkyvyysolosuhteet ja revontuliuennuste."},
  "/iss": {"title":"ISS-seuranta — Kansainvälisen Avaruusaseman Sijainti | The Storm Watcher","description":"Seuraa ISS:ää reaaliajassa. Sijainti, korkeus, nopeus ja tulevat ylilennot sijaintisi yllä."},
  "/faq": {"title":"Revontuli UKK — Revontulioppas | The Storm Watcher","description":"Kaikki mitä sinun täytyy tietää revontulista, Kp-indeksistä ja kuinka nähdä revontulet."},
  "/magnetic-effects": {"title":"Magneettiset Myrskyt ja Ihmisen Terveys — The Storm Watcher","description":"Kuinka geomagneettinen aktiivisuus vaikuttaa kehoon: päänsärky, uni, mieliala ja mitä tehdä."},
  "/pricing": {"title":"Hinnoittelu — The Storm Watcher Pro & Premium Paketit","description":"Valitse pakettisi. Ilmainen revontuliseuranta tai Pro/Premium edistyneillä hälytyksillä ja 14 päivän ilmaisella kokeilulla."},
  "/about": {"title":"Tietoja — The Storm Watcher","description":"Reaaliaikainen avaruussään seuranta ja revontuliennustus-sovellus. Tutustu tehtäväämme ja tietolähteisiimme."},
  "/privacy": {"title":"Tietosuojakäytäntö — The Storm Watcher","description":"The Storm Watcherin tietosuojakäytäntö. Katso, kuinka keräämme ja suojaamme henkilökohtaisia tietojasi."},
  "/terms": {"title":"Käyttöehdot — The Storm Watcher","description":"The Storm Watcher -avaruussääsovelluksen käyttöehdot."},
  "/gallery": {"title":"Revontuli-valokuvagalleria — Yhteisön Kuvat | The Storm Watcher","description":"Selaa hämmästyttäviä revontuli-valokuvia, joita Storm Watcher -yhteisö on jakanut ympäri maailmaa."},
  "/hunt": {"title":"Revontulimetsästys — Ilmoita Havainnoista ja Ansaitse Merkkejä | The Storm Watcher","description":"Ilmoita revontulihavainnoista, ansaitse saavutusmerkkejä ja kilpaile globaalilla tulostaululla."},
  "/livestream": {"title":"Revontuli-Suoratoisto — Live Revontuli-Kamerat | The Storm Watcher","description":"Katso live-revontuli-kameroita Norjasta, Islannista ja Suomesta. Reaaliaikaiset suoratoistot 24/7."},
  "/calendar": {"title":"Revontulikalenteri — Parhaat Yöt Revontulia Varten | The Storm Watcher","description":"3 yön revontulennuste Kp-ennusteella ja pilvisyydellä. Löydä paras yö revontulien katseluun."},
};

export default meta;
