// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Tableau de Bord Météo Spatiale en Direct","description":"Surveillez l'activité solaire et les aurores. Indice Kp en direct, vent solaire et alertes de tempêtes géomagnétiques."},
  "/dashboard": {"title":"Tableau de Bord Météo Spatiale — Indice Kp en Direct | The Storm Watcher","description":"Données météo spatiale en direct: indice Kp, vitesse du vent solaire, composante Bz, flux X et graphiques des tempêtes."},
  "/forecast": {"title":"Prévision Géomagnétique 27 Jours — Météo Spatiale | The Storm Watcher","description":"Prévisions sur 27 jours avec prédictions Kp, indice Ap, flux solaire F10.7 et probabilité de tempêtes."},
  "/aurora": {"title":"Prévision Aurore Ce Soir — Puis-je Voir les Aurores Boréales? | The Storm Watcher","description":"Vérifiez la visibilité des aurores boréales pour votre position. Modèle OVATION, indice Kp, couverture nuageuse et globe 3D."},
  "/alerts": {"title":"Alertes Tempête Solaire et CME — Météo Spatiale | The Storm Watcher","description":"Alertes en direct pour tempêtes géomagnétiques, éruptions solaires et CMEs. Notifications NOAA DONKI en temps réel."},
  "/mood": {"title":"Pouls de l'Humeur Cosmique — Comment la Météo Spatiale Vous Affecte-t-elle? | The Storm Watcher","description":"Suivez comment les tempêtes solaires influencent votre humeur. Rejoignez la communauté."},
  "/uv": {"title":"Indice UV — Prévision d'Exposition Solaire | The Storm Watcher","description":"Indice UV en temps réel et prévision d'exposition solaire pour votre position. Sachez quand appliquer votre écran solaire."},
  "/sun": {"title":"Lever et Coucher de Soleil — Heure Dorée | The Storm Watcher","description":"Heures précises du lever, coucher de soleil et heure dorée pour votre position."},
  "/sky": {"title":"Visibilité du Ciel Ce Soir — Observation des Étoiles | The Storm Watcher","description":"Couverture nuageuse, conditions seeing et prévision d'aurores ce soir. Planifiez votre observation."},
  "/iss": {"title":"Suivi ISS — Position en Direct de la Station Spatiale | The Storm Watcher","description":"Suivez la Station Spatiale Internationale en temps réel. Position, altitude, vitesse et prochains passages."},
  "/faq": {"title":"FAQ Aurore — Guide des Aurores Boréales | The Storm Watcher","description":"Tout ce que vous devez savoir sur les aurores boréales, l'indice Kp et comment voir l'aurore."},
  "/magnetic-effects": {"title":"Tempêtes Magnétiques & Santé Humaine — The Storm Watcher","description":"Comment l'activité géomagnétique affecte le corps humain — maux de tête, sommeil, humeur — et quoi faire."},
  "/pricing": {"title":"Tarifs — Plans Pro & Premium de The Storm Watcher","description":"Choisissez votre plan. Surveillance aurore gratuite ou Pro/Premium avec alertes avancées et 14 jours d'essai."},
  "/about": {"title":"À Propos — The Storm Watcher","description":"Application de surveillance météo spatiale et de prévision d'aurores. Découvrez notre mission et nos sources de données."},
  "/privacy": {"title":"Politique de Confidentialité — The Storm Watcher","description":"Politique de confidentialité de The Storm Watcher. Découvrez comment nous collectons et protégeons vos données."},
  "/terms": {"title":"Conditions d'utilisation — The Storm Watcher","description":"Conditions d'utilisation de l'application de surveillance météo spatiale The Storm Watcher."},
  "/gallery": {"title":"Galerie Photos d'Aurores — Photos de la Communauté | The Storm Watcher","description":"Parcourez de superbes photos d'aurores boréales partagées par la communauté Storm Watcher du monde entier."},
  "/hunt": {"title":"Chasse aux Aurores — Signalez des Observations | The Storm Watcher","description":"Signalez des observations d'aurores, gagnez des badges et affrontez d'autres chasseurs sur le classement mondial."},
  "/livestream": {"title":"Aurore en Direct — Caméras Aurores Boréales en Live | The Storm Watcher","description":"Regardez des caméras d'aurores en direct depuis la Norvège, l'Islande et la Finlande. Streams 24h/24."},
  "/calendar": {"title":"Calendrier des Aurores — Meilleures Nuits pour les Aurores Boréales | The Storm Watcher","description":"Prévision aurora sur 3 nuits avec prévision Kp et couverture nuageuse. Trouvez votre meilleure nuit."},
};

export default meta;
