// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Geimveðurspá í Rauntíma","description":"Fylgstu með sólarerfiðleikum og norðurljósaspám. Kp-vísitala, sólvindur og seguleldur í rauntíma."},
  "/dashboard": {"title":"Geimveðurborð — Kp-vísitala í Rauntíma | The Storm Watcher","description":"Rauntímaupplýsingar um geimveður: Kp-vísitala, hraði sólvinds, Bz-hluti og seguleldurrit."},
  "/forecast": {"title":"27 Daga Segulspá | The Storm Watcher","description":"27 daga segulspá með Kp-spám, Ap-vísitölu, sólarflæði F10.7 og líkur á seguleldri."},
  "/aurora": {"title":"Norðurljósaspá í Kvöld — Get Ég Séð Norðurljósin? | The Storm Watcher","description":"Athugaðu sýnileika norðurljósa á þínum stað. OVATION-líkan, Kp-vísitala, skýjahula og 3D-hnöttur."},
  "/alerts": {"title":"Sólstormur & CME Viðvaranir — Geimveður | The Storm Watcher","description":"Viðvaranir í rauntíma um seguleld, sólblossa og kórónalosun. NOAA DONKI tilkynningar."},
  "/mood": {"title":"Kosmískt Skapslagspúls — Hvernig Hefur Geimveður Áhrif á Þig? | The Storm Watcher","description":"Fylgstu með hvernig sólstormar hafa áhrif á skap þitt. Taktu þátt í samfélaginu."},
  "/uv": {"title":"UV-vísitala — Sólargeislaendurstæður í Rauntíma | The Storm Watcher","description":"UV-vísitala og sólargeislaendurstæður í rauntíma fyrir þínum stað."},
  "/sun": {"title":"Sólarupprás og Sólsetur — Gyllti Tíminn | The Storm Watcher","description":"Nákvæmar tímasetningar fyrir sólarupprás, sólsetur og gyllta tímann á þínum stað."},
  "/sky": {"title":"Himinsjón I Kvöld — Stjörnuathugun og Norðurljós | The Storm Watcher","description":"Skýjahula, sjónarskilyrði og norðurljósa-spá í kvöld. Skipuleggðu stjörnuathugun þína."},
  "/iss": {"title":"ISS-rakari — Staðsetning Alþjóðlegu Geimstöðvarinnar | The Storm Watcher","description":"Fylgstu með ISS í rauntíma. Staðsetning, hæð, hraði og komandi yfirflug yfir þinn stað."},
  "/faq": {"title":"Norðurljós Algengar Spurningar — Norðurljósahandbók | The Storm Watcher","description":"Allt sem þú þarft að vita um norðurljós, Kp-vísitölu og hvernig á að sjá norðurljósin."},
  "/magnetic-effects": {"title":"Seguleldur og Mannleg Heilsa — The Storm Watcher","description":"Hvernig segulmagn hefur áhrif á líkamann — höfuðverkur, svefn, skap — og hvað er hægt að gera."},
  "/pricing": {"title":"Verðlag — The Storm Watcher Pro & Premium Áskriftir","description":"Veldu þinn áskriftarpakka. Ókeypis norðurljósaeftirlit eða Pro/Premium með háþróaðar viðvaranir og 14 daga prufutíma."},
  "/about": {"title":"Um okkur — The Storm Watcher","description":"Rauntíma geimveðureftirlit og norðurljósaspá-app. Kynntu þér hlutverk okkar og gagnaveitu."},
  "/privacy": {"title":"Persónuverndarstefna — The Storm Watcher","description":"Persónuverndarstefna The Storm Watcher. Kynntu þér hvernig við söfnum og verndum persónuupplýsingar þínar."},
  "/terms": {"title":"Notkunarskilmálar — The Storm Watcher","description":"Notkunarskilmálar The Storm Watcher geimveðurforritin."},
  "/gallery": {"title":"Norðurljósamyndagallerí — Myndir Samfélagsins | The Storm Watcher","description":"Skoðaðu glæsilegar myndir af norðurljósum sem samfélag Storm Watcher deilir úr öllum heimshornum."},
  "/hunt": {"title":"Norðurljósaveiðar — Tilkynntu Sjónarmiðar | The Storm Watcher","description":"Tilkynntu sjónarmiðar norðurljósa, vinna verðlaun og keppa á heimsvísu."},
  "/livestream": {"title":"Norðurljós í Beinni Útsendingu — Norðurljósavefmyndavélar | The Storm Watcher","description":"Horfðu á norðurljósavefmyndavélar í beinni frá Noregi, Íslandi og Finnlandi. 24/7 streymi."},
  "/calendar": {"title":"Norðurljósadagatal — Bestu Næturnar fyrir Norðurljós | The Storm Watcher","description":"3 nætta norðurljósaspá með Kp-spá og skýjahulu. Finndu þína bestu nótt til að horfa á norðurljósin."},
  "/aurora-map": {"title":"Norðurljósasýnileikakort — Hvar Sérð Þú Norðurljósin? | The Storm Watcher","description":"Bein heimskort sem sýnir norðurljósasýnileikabelt á grundvelli gildandi Kp-vísitölu."},
};

export default meta;
