// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"스톰워처 — 실시간 우주 날씨 대시보드","description":"태양 활동과 오로라 예보를 모니터링하세요. 실시간 Kp 지수, 태양풍, 지자기 폭풍 알림."},
  "/dashboard": {"title":"우주 날씨 대시보드 — 실시간 Kp 지수 | 스톰워처","description":"실시간 우주 날씨 데이터: Kp 지수, 태양풍 속도, Bz 성분, X선 플럭스, 지자기 폭풍 차트."},
  "/forecast": {"title":"27일 지자기 예보 — 우주 날씨 예측 | 스톰워처","description":"27일 지자기 예보: Kp 예측, Ap 지수, 태양 플럭스 F10.7, 폭풍 확률."},
  "/aurora": {"title":"오늘 밤 오로라 예보 — 오로라를 볼 수 있을까요? | 스톰워처","description":"내 위치의 오로라 가시성을 확인하세요. 실시간 OVATION 모델, Kp 지수, 구름량 체크리스트 및 3D 오로라 지구본."},
  "/alerts": {"title":"태양 폭풍 및 CME 경보 — 실시간 우주 날씨 | 스톰워처","description":"지자기 폭풍, 태양 플레어, CME에 대한 실시간 경보. NOAA DONKI 알림으로 우주 날씨를 앞서 확인."},
  "/mood": {"title":"우주 기분 펄스 — 우주 날씨가 당신에게 미치는 영향 | 스톰워처","description":"태양 폭풍이 기분에 미치는 영향을 추적하세요. 커뮤니티에 참여하고 오늘의 기분을 공유하세요."},
  "/uv": {"title":"UV 지수 — 실시간 자외선 예보 | 스톰워처","description":"위치별 실시간 UV 지수 및 자외선 노출 예보. 선크림 도포 시기를 알아보세요."},
  "/sun": {"title":"일출 및 일몰 시간 — 골든 아워 계산기 | 스톰워처","description":"위치별 정확한 일출, 일몰 및 골든 아워 시간. 사진 촬영 및 야외 활동 계획."},
  "/sky": {"title":"오늘 밤 하늘 시야 — 별보기 및 오로라 조건 | 스톰워처","description":"오늘 밤 구름 양, 시야 조건 및 오로라 관측 예보. 실시간 데이터로 별보기를 계획하세요."},
  "/iss": {"title":"ISS 추적기 — 국제우주정거장 실시간 위치 | 스톰워처","description":"국제우주정거장을 실시간으로 추적하세요. 실시간 위치, 고도, 속도 및 상공 통과 시간."},
  "/faq": {"title":"오로라 FAQ — 오로라 가이드 | 스톰워처","description":"오로라, Kp 지수, 태양풍에 대한 모든 것. 우주 날씨 질문에 대한 전문가 답변."},
  "/magnetic-effects": {"title":"자기 폭풍과 인체 건강 — 스톰워처","description":"지자기 활동이 인체에 미치는 영향: 두통, 수면 장애, 기분 변화 및 대처 방법."},
  "/pricing": {"title":"가격 — 스톰워처 Pro & Premium 플랜","description":"플랜을 선택하세요. 무료 오로라 모니터링 또는 고급 알림과 14일 무료 체험이 포함된 Pro/Premium."},
  "/about": {"title":"소개 — 스톰워처","description":"실시간 우주 날씨 모니터링 및 오로라 예보 앱. 우리의 미션과 데이터 소스에 대해 알아보세요."},
  "/privacy": {"title":"개인정보처리방침 — 스톰워처","description":"스톰워처의 개인정보처리방침. 개인 데이터 수집, 사용 및 보호 방법을 확인하세요."},
  "/terms": {"title":"이용약관 — 스톰워처","description":"스톰워처 우주 날씨 모니터링 애플리케이션 이용약관."},
  "/gallery": {"title":"오로라 사진 갤러리 — 커뮤니티 사진 | 스톰워처","description":"스톰워처 커뮤니티가 전 세계에서 공유한 멋진 오로라 사진을 둘러보세요."},
  "/hunt": {"title":"오로라 헌팅 — 목격 보고 및 배지 획득 | 스톰워처","description":"오로라 목격을 보고하고, 성취 배지를 획득하고, 글로벌 리더보드에서 경쟁하세요."},
  "/livestream": {"title":"오로라 라이브스트림 — 오로라 실시간 카메라 | 스톰워처","description":"노르웨이, 아이슬란드, 핀란드의 오로라 실시간 카메라를 시청하세요. 24/7 실시간 스트리밍."},
  "/calendar": {"title":"오로라 캘린더 — 오로라 관측 최적 날짜 | 스톰워처","description":"Kp 예보와 구름량이 포함된 3일간 오로라 예측. 오로라를 보기에 가장 좋은 날 밤을 찾으세요."},
};

export default meta;
