// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Romvær Dashboard i Sanntid","description":"Overvåk solaktivitet og nordlysprognoser. Live Kp-indeks, solvind og geomagnetiske stormvarsler."},
  "/dashboard": {"title":"Romvær Dashboard — Live Kp-indeks | The Storm Watcher","description":"Live romværdata: Kp-indeks, solvindshastighet, Bz-komponent, røntgenstråling og stormdiagrammer."},
  "/forecast": {"title":"27-Dagers Geomagnetisk Prognose | The Storm Watcher","description":"27-dagers geomagnetisk prognose med Kp-forutsigelser, Ap-indeks og stormssannsynlighet."},
  "/aurora": {"title":"Nordlys Prognose I Kveld — Kan Jeg Se Nordlyset? | The Storm Watcher","description":"Sjekk nordlyssynlighet for din plassering. Sanntids OVATION-modell, Kp-indeks, skydekke og 3D-globus."},
  "/alerts": {"title":"Solstorm & CME Varsler — Sanntids Romvær | The Storm Watcher","description":"Live varsler om geomagnetiske stormer, solflares og CME-er. Sanntids NOAA DONKI-varsler."},
  "/mood": {"title":"Kosmisk Humørpuls — Hvordan Påvirker Romvæeret Deg? | The Storm Watcher","description":"Spor hvordan solutbrudd påvirker humøret ditt. Bli med i fellesskapet og del din tilstand."},
  "/uv": {"title":"UV-indeks — Sanntids Solstrålingsprognose | The Storm Watcher","description":"Sanntids UV-indeks og solstrålingsprognose for din plassering."},
  "/sun": {"title":"Soloppgang og Solnedgang — Den Gylne Time | The Storm Watcher","description":"Nøyaktige tider for soloppgang, solnedgang og gylden time for din plassering."},
  "/sky": {"title":"Himmelsikt I Kveld — Stjernekikking & Nordlys | The Storm Watcher","description":"Skydekke, seeingforhold og nordlysprognose i kveld. Planlegg din stjernekikkingsøkt."},
  "/iss": {"title":"ISS Tracker — Live Internasjonal Romstasjons Posisjon | The Storm Watcher","description":"Spor den Internasjonale Romstasjonen i sanntid. Live posisjon, høyde, hastighet og kommende passeringer."},
  "/faq": {"title":"Nordlys FAQ — Nordlysguide | The Storm Watcher","description":"Alt du trenger å vite om nordlyset, Kp-indekset og hvordan du ser nordlyset."},
  "/magnetic-effects": {"title":"Magnetstormer & Menneskelig Helse — The Storm Watcher","description":"Hvordan geomagnetisk aktivitet påvirker kroppen — hodepine, søvn, humør — og hva du kan gjøre."},
  "/pricing": {"title":"Priser — The Storm Watcher Pro & Premium Planer","description":"Velg din plan. Gratis nordlysovervåking eller Pro/Premium med avanserte varsler og 14 dagers gratis prøve."},
  "/about": {"title":"Om oss — The Storm Watcher","description":"Sanntids romværovervåking og nordlysprognose app. Lær om vår misjon og datakilder."},
  "/privacy": {"title":"Personvernpolicy — The Storm Watcher","description":"Personvernpolicy for The Storm Watcher. Lær hvordan vi samler inn og beskytter dine personlige data."},
  "/terms": {"title":"Vilkår for Bruk — The Storm Watcher","description":"Vilkår for bruk av romværovervåkingsapplikasjonen The Storm Watcher."},
  "/gallery": {"title":"Aurora Fotogalleri — Fellesskapets Nordlysbilder | The Storm Watcher","description":"Se fantastiske nordlysbilder delt av Storm Watcher-fellesskapet fra hele verden."},
  "/hunt": {"title":"Nordlysjakt — Rapportér Observasjoner & Tjen Badges | The Storm Watcher","description":"Rapportér nordlysobservasjoner, tjen badges og konkurrér på det globale ledertavlen."},
  "/livestream": {"title":"Aurora Livestream — Live Nordlys Kameraer | The Storm Watcher","description":"Se live nordlys-kameraer fra Norge, Island og Finland. Sanntids nordlysstrømmer 24/7."},
  "/calendar": {"title":"Aurora Kalender — Beste Netter for Nordlys | The Storm Watcher","description":"3-nettersprognoser for nordlys med Kp-prognose og skydekke. Finn din beste natt for nordlys."},
  "/aurora-map": {"title":"Nordlyssynlighetskart — Hvor Kan Du Se Nordlyset? | The Storm Watcher","description":"Direkte verdenskart med nordlyssynlighetssoner basert på gjeldende Kp-indeks."},
};

export default meta;
