// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Pulpit Pogody Kosmicznej w Czasie Rzeczywistym","description":"Monitoruj aktywność słoneczną i prognozy zórz polarnych. Indeks Kp, wiatr słoneczny i burze geomagnetyczne."},
  "/dashboard": {"title":"Panel Pogody Kosmicznej — Indeks Kp na Żywo | The Storm Watcher","description":"Dane pogody kosmicznej na żywo: indeks Kp, prędkość wiatru słonecznego, Bz, promieniowanie rentgenowskie."},
  "/forecast": {"title":"27-Dniowa Prognoza Geomagnetyczna | The Storm Watcher","description":"27-dniowa prognoza geomagnetyczna z przewidywaniami Kp, indeksem Ap i prawdopodobieństwem burz."},
  "/aurora": {"title":"Prognoza Zorzy Polarnej Tej Nocy — Czy Zobaczę Zorzę? | The Storm Watcher","description":"Sprawdź widoczność zorzy polarnej dla twojej lokalizacji. Model OVATION, indeks Kp, zachmurzenie i globus 3D."},
  "/alerts": {"title":"Alerty Burzy Słonecznej i CME — Pogoda Kosmiczna | The Storm Watcher","description":"Alerty o burzach geomagnetycznych, rozbłyskach słonecznych i CME w czasie rzeczywistym."},
  "/mood": {"title":"Kosmiczny Puls Nastroju — Jak Pogoda Kosmiczna Na Ciebie Wpływa? | The Storm Watcher","description":"Śledź wpływ burz słonecznych na swój nastrój. Dołącz do społeczności i podziel się samopoczuciem."},
  "/uv": {"title":"Indeks UV — Prognoza Promieniowania UV | The Storm Watcher","description":"Indeks UV i prognoza promieniowania słonecznego w czasie rzeczywistym dla twojej lokalizacji."},
  "/sun": {"title":"Wschód i Zachód Słońca — Złota Godzina | The Storm Watcher","description":"Dokładne godziny wschodu, zachodu słońca i złotej godziny dla twojej lokalizacji."},
  "/sky": {"title":"Widoczność Nieba Tej Nocy — Obserwacja Gwiazd | The Storm Watcher","description":"Zachmurzenie, warunki seeing i prognoza zorzy polarnej tej nocy."},
  "/iss": {"title":"Śledzenie ISS — Żywa Pozycja Międzynarodowej Stacji Kosmicznej | The Storm Watcher","description":"Śledź ISS w czasie rzeczywistym. Pozycja, wysokość, prędkość i nadchodzące przeloty nad twoją lokalizacją."},
  "/faq": {"title":"FAQ o Zorzach Polarnych — Przewodnik po Zorzach | The Storm Watcher","description":"Wszystko, co musisz wiedzieć o zorzach polarnych, indeksie Kp i jak zobaczyć zorzę."},
  "/magnetic-effects": {"title":"Burze Magnetyczne i Zdrowie Człowieka — The Storm Watcher","description":"Jak aktywność geomagnetyczna wpływa na organizm: bóle głowy, sen, nastrój i co można zrobić."},
  "/pricing": {"title":"Cennik — Plany Pro i Premium The Storm Watcher","description":"Wybierz swój plan. Bezpłatne monitorowanie zorzy lub Pro/Premium z zaawansowanymi alertami i 14-dniowym bezpłatnym okresem."},
  "/about": {"title":"O nas — The Storm Watcher","description":"Aplikacja do monitorowania pogody kosmicznej i prognoz zorzy polarnej w czasie rzeczywistym."},
  "/privacy": {"title":"Polityka Prywatności — The Storm Watcher","description":"Polityka prywatności The Storm Watcher. Dowiedz się, jak zbieramy i chronimy twoje dane osobowe."},
  "/terms": {"title":"Regulamin — The Storm Watcher","description":"Regulamin aplikacji monitorowania pogody kosmicznej The Storm Watcher."},
  "/gallery": {"title":"Galeria Zdjęć Zorzy Polarnej — Zdjęcia Społeczności | The Storm Watcher","description":"Przeglądaj niesamowite zdjęcia zorzy polarnej udostępnione przez społeczność Storm Watcher."},
  "/hunt": {"title":"Polowanie na Zorzę — Zgłaszaj Obserwacje i Zdobywaj Odznaki | The Storm Watcher","description":"Zgłaszaj obserwacje zorzy polarnej, zdobywaj odznaki i rywalizuj na globalnej tablicy wyników."},
  "/livestream": {"title":"Transmisja Zorzy Na Żywo — Kamery Zorzy Polarnej | The Storm Watcher","description":"Oglądaj kamery zorzy polarnej na żywo z Norwegii, Islandii i Finlandii. Transmisje 24/7."},
  "/calendar": {"title":"Kalendarz Zorzy — Najlepsze Noce na Zorzę Polarną | The Storm Watcher","description":"3-dniowa prognoza zorzy z Kp i zachmurzeniem. Znajdź najlepszą noc do obserwacji zorzy."},
  "/aurora-map": {"title":"Mapa Widoczności Zorzy — Gdzie Można Zobaczyć Zorzę Polarną? | The Storm Watcher","description":"Mapa świata na żywo z strefami widoczności zorzy polarnej na podstawie bieżącego indeksu Kp."},
};

export default meta;
