// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — Rymdväder Dashboard i Realtid","description":"Övervaka solaktivitet och norrskensprognoser. Live Kp-index, solvind och geomagnetiska stormvarningar."},
  "/dashboard": {"title":"Rymdväder Dashboard — Live Kp-index | The Storm Watcher","description":"Live rymdväderdatas: Kp-index, solvindshastighet, Bz-komponent, röntgenstrålning och stormdiagram."},
  "/forecast": {"title":"27-Dagars Geomagnetisk Prognos | The Storm Watcher","description":"27-dagars geomagnetisk prognos med Kp-förutsägelser, Ap-index och stormssannolikhet."},
  "/aurora": {"title":"Norrskens Prognos I Natt — Kan Jag Se Norrsken? | The Storm Watcher","description":"Kontrollera norrskenssynlighet för din plats. Realtids OVATION-modell, Kp-index, molntäcke och 3D-glob."},
  "/alerts": {"title":"Solstorm & CME Varningar — Realtids Rymdväder | The Storm Watcher","description":"Live-varningar om geomagnetiska stormar, solfacklor och CME:er. Realtids NOAA DONKI-aviseringar."},
  "/mood": {"title":"Kosmisk Humörpuls — Hur Påverkar Rymdvädret Dig? | The Storm Watcher","description":"Spåra hur solutbrott påverkar ditt humör. Gå med i gemenskapen och dela hur du mår idag."},
  "/uv": {"title":"UV-index — Realtids Solstrålningsprognos | The Storm Watcher","description":"Realtids UV-index och solstrålningsprognos för din plats. Vet när du ska använda solskydd."},
  "/sun": {"title":"Soluppgång och Solnedgång — Gyllene Timmen | The Storm Watcher","description":"Exakta tider för soluppgång, solnedgång och gyllene timmen för din plats."},
  "/sky": {"title":"Himmelsikt I Natt — Stjärnskådning & Norrsken | The Storm Watcher","description":"Molntäcke, seeingförhållanden och norrskenssynlighet i natt. Planera din stjärnskådning."},
  "/iss": {"title":"ISS-spårare — Live Position av Internationella Rymdstationen | The Storm Watcher","description":"Spåra ISS i realtid. Live position, höjd, hastighet och kommande passager."},
  "/faq": {"title":"Norrsken FAQ — Norrskensguide | The Storm Watcher","description":"Allt du behöver veta om norrsken, Kp-index och hur du ser norrsken."},
  "/magnetic-effects": {"title":"Magnetstormar & Mänsklig Hälsa — The Storm Watcher","description":"Hur geomagnetisk aktivitet påverkar kroppen — huvudvärk, sömn, humör — och vad du kan göra."},
  "/pricing": {"title":"Prissättning — The Storm Watcher Pro & Premium Planer","description":"Välj din plan. Gratis norrskensövervakning eller Pro/Premium med avancerade varningar och 14 dagars gratis provperiod."},
  "/about": {"title":"Om oss — The Storm Watcher","description":"Realtids rymdvädersövervakning och norrskensapp. Lär dig om vårt uppdrag och datakällor."},
  "/privacy": {"title":"Integritetspolicy — The Storm Watcher","description":"Integritetspolicy för The Storm Watcher. Lär dig hur vi samlar in och skyddar dina personuppgifter."},
  "/terms": {"title":"Användarvillkor — The Storm Watcher","description":"Användarvillkor för rymdvädersövervakningsapplikationen The Storm Watcher."},
  "/gallery": {"title":"Aurora Fotogalleri — Gemenskapens Norrskensfoton | The Storm Watcher","description":"Se fantastiska norrskensfoton delade av Storm Watcher-gemenskapen från hela världen."},
  "/hunt": {"title":"Norrskenjakt — Rapportera Observationer & Tjäna Märken | The Storm Watcher","description":"Rapportera norrskensobservationer, tjäna prestationsmärken och tävla på den globala topplistan."},
  "/livestream": {"title":"Aurora Livestream — Live Norrskenspåkameror | The Storm Watcher","description":"Se live norrskenspåkameror från Norge, Island och Finland. Realtids norrskenssändningar 24/7."},
  "/calendar": {"title":"Aurora Kalender — Bästa Nätter för Norrsken | The Storm Watcher","description":"3-nätters norrskensöversikt med Kp-prognos och molntäcke. Hitta din bästa natt för norrsken."},
  "/aurora-map": {"title":"Norrskenssynlighetskarta — Var Kan Du Se Norrsken? | The Storm Watcher","description":"Live världskarta med norrskenssynlighetszoner baserat på aktuellt Kp-index."},
};

export default meta;
