// Generated by scripts/generate-page-meta.mjs from scripts/meta-translations.mjs — do not edit.
import type { PageMetaTable } from '../pageMeta';

const meta: PageMetaTable = {
  "/": {"title":"The Storm Watcher — 实时太空天气仪表板","description":"监测太阳活动和极光预报。实时Kp指数、太阳风速度和地磁暴警报。"},
  "/dashboard": {"title":"太空天气仪表板 — 实时Kp指数和太阳风 | The Storm Watcher","description":"实时太空天气数据：Kp指数、太阳风速度、Bz分量、X射线通量和地磁暴图表。"},
  "/forecast": {"title":"27天地磁预报 — 太空天气预测 | The Storm Watcher","description":"27天地磁预报：Kp预测、Ap指数、太阳通量F10.7和风暴概率。"},
  "/aurora": {"title":"今晚极光预报 — 我能看到北极光吗？| The Storm Watcher","description":"查看您所在位置的极光可见性。实时OVATION模型、Kp指数、云层覆盖和3D极光地球仪。"},
  "/alerts": {"title":"太阳风暴和CME警报 — 实时太空天气 | The Storm Watcher","description":"地磁暴、太阳耀斑、CME实时警报。来自NOAA DONKI的实时通知。"},
  "/mood": {"title":"宇宙情绪脉冲 — 太空天气如何影响您？| The Storm Watcher","description":"追踪太阳风暴对您情绪的影响。加入社区，分享您今天的感受。"},
  "/uv": {"title":"紫外线指数 — 实时阳光照射预报 | The Storm Watcher","description":"实时紫外线指数和阳光照射预报。了解何时需要涂抹防晒霜。"},
  "/sun": {"title":"日出日落时间 — 黄金时刻计算器 | The Storm Watcher","description":"精确的日出、日落和黄金时刻时间。规划摄影和户外活动。"},
  "/sky": {"title":"今晚天空能见度 — 观星和极光条件 | The Storm Watcher","description":"今晚的云层覆盖、视宁度条件和极光观测预报。规划您的观星活动。"},
  "/iss": {"title":"国际空间站追踪器 — 实时位置 | The Storm Watcher","description":"实时追踪国际空间站。实时位置、高度、速度和上空过境时间。"},
  "/faq": {"title":"极光常见问题 — 北极光指南 | The Storm Watcher","description":"关于北极光、Kp指数和太阳风的完整指南。常见太空天气问题的专家解答。"},
  "/magnetic-effects": {"title":"磁暴与人体健康 — The Storm Watcher","description":"地磁活动如何影响人体：头痛、睡眠障碍、情绪变化，以及应对措施。"},
  "/pricing": {"title":"价格 — The Storm Watcher Pro 和 Premium 计划","description":"选择您的计划。免费极光监测或Pro/Premium，含高级警报和14天免费试用。"},
  "/about": {"title":"关于我们 — The Storm Watcher","description":"实时太空天气监测和极光预报应用。了解我们的使命和数据来源。"},
  "/privacy": {"title":"隐私政策 — The Storm Watcher","description":"The Storm Watcher的隐私政策。了解我们如何收集、使用和保护您的个人数据。"},
  "/terms": {"title":"服务条款 — The Storm Watcher","description":"The Storm Watcher太空天气监测应用程序的服务条款。"},
  "/gallery": {"title":"极光照片画廊 — 社区北极光照片 | The Storm Watcher","description":"浏览Storm Watcher社区分享的令人惊叹的极光照片。"},
  "/hunt": {"title":"极光猎人 — 报告目击并获得徽章 | The Storm Watcher","description":"报告极光目击事件，获得成就徽章，在全球排行榜上与其他极光猎人竞争。"},
  "/livestream": {"title":"极光直播 — 北极光实时摄像头 | The Storm Watcher","description":"观看挪威、冰岛和芬兰的极光实时摄像头。24/7全天候实时北极光直播。"},
  "/calendar": {"title":"极光日历 — 观看北极光的最佳夜晚 | The Storm Watcher","description":"带Kp预报和云层覆盖的3夜极光展望。找到观看北极光的最佳夜晚。"},
  "/aurora-map": {"title":"极光可见度地图 — 哪里能看到北极光？| The Storm Watcher","description":"根据当前Kp指数显示极光可见区域的实时世界地图。"},
};

export default meta;
