#!/usr/bin/env python3
"""
Sync v2.2 new keys (Mood Cosmic Pulse, 7-day Forecast, Livestream YouTube)
to remaining 8 locales: no, fi, sv, is, da, pl, uk, ko.
Run: python3 scripts/sync_v22_keys.py
"""
import re, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'src', 'locales')


def get_keys(lang):
    return set(re.findall(r"^\s+'([^']+)'\s*:", open(os.path.join(BASE, f'{lang}.ts')).read(), re.MULTILINE))


def escape(v):
    return v.replace("\\", "\\\\").replace("'", "\\'")


def inject(lang, additions):
    path = os.path.join(BASE, f'{lang}.ts')
    content = open(path, encoding='utf-8').read()
    existing = get_keys(lang)
    lines = []
    for k, v in additions.items():
        if k not in existing:
            lines.append(f"  '{k}': '{escape(v)}',")
    if not lines:
        print(f"  [{lang}] nothing to add")
        return
    block = '\n'.join(lines)
    idx = content.rfind('\n};')
    new = content[:idx] + '\n' + block + content[idx:]
    open(path, 'w', encoding='utf-8').write(new)
    print(f"  [{lang}] +{len(lines)} keys")


LOCALES = {

'no': {
    'mood.heroTitle':             'Kosmisk humørpuls',
    'mood.heroSubtitle':          'Spor hvordan solens stormer beveger seg gjennom deg',
    'mood.cosmicForecast':        'Kosmisk varsel',
    'mood.shareMyMood':           'Del humøret mitt',
    'mood.anonymous':             'Anonymt · bidrar til forskning på sol-jord-forbindelsen',
    'mood.communityToday':        'Fellesskapet i dag',
    'mood.betterThan':            'av fellesskapet føler seg verre',
    'mood.didYouKnow':            'Visste du?',
    'mood.didYouKnowText':        'Geomagnetiske stormer kan utløse hodepine, søvnløshet og humørendringer hos følsomme personer. Forskere studerer aktivt sol-jord-helse-forbindelsen.',
    'mood.physical':              'Fysiske symptomer',
    'mood.mental':                'Mentale symptomer',
    'mood.greeting.morning':      'God morgen',
    'mood.greeting.afternoon':    'God ettermiddag',
    'mood.greeting.evening':      'God kveld',
    'forecast.sevenDayTitle':     '7-dagers varsel',
    'forecast.sevenDaySubtitle':  'Daglig geomagnetisk utsikt',
    'forecast.peakKpNext7':       'Topp Kp · 7 dager',
    'forecast.bestDayLabel':      'Beste stormdag',
    'forecast.stormDaysCount':    'Stormdager',
    'forecast.tapToExpand':       'Trykk for 3-timers oversikt',
    'forecast.todayLabel':        'I dag',
    'forecast.tomorrowLabel':     'I morgen',
    'forecast.longRangeTitle':    '27-dagers langtidsvarsel',
    'forecast.longRangeSubtitle': 'Basert på forrige solrotasjon — lavere nøyaktighet',
    'forecast.showLongRange':     'Vis 27-dagers varsel',
    'forecast.hideLongRange':     'Skjul 27-dagers varsel',
    'forecast.detailed':          'Detaljert',
    'forecast.outlookSource':     'Utsikt',
    'livestream.watchYouTube':    'Se på YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Webkamera',
    'livestream.seasonal':        'Sesongbasert',
    'livestream.disclaimerHonest':'De fleste strømmene åpnes i en ny fane — tredjepartssider blokkerer direkte innbygging av sikkerhetshensyn. YouTube-kanaler viser det som sendes live for øyeblikket.',
    'livestream.sectionYouTube':  'YouTube Live-kanaler',
    'livestream.sectionWebcams':  'Webkameraer og nettverk',
},

'fi': {
    'mood.heroTitle':             'Kosminen mielialapulssi',
    'mood.heroSubtitle':          'Seuraa, miten auringon myrskyt vaikuttavat sinuun',
    'mood.cosmicForecast':        'Kosminen ennuste',
    'mood.shareMyMood':           'Jaa mielialani',
    'mood.anonymous':             'Anonyymi · auttaa tutkimaan Aurinko-Maa-yhteyttä',
    'mood.communityToday':        'Yhteisö tänään',
    'mood.betterThan':            'yhteisöstä tuntee olonsa huonommaksi',
    'mood.didYouKnow':            'Tiesitkö?',
    'mood.didYouKnowText':        'Geomagneettiset myrskyt voivat aiheuttaa päänsärkyä, unettomuutta ja mielialamuutoksia herkille henkilöille. Tutkijat tutkivat aktiivisesti Aurinko-Maa-terveys-yhteyttä.',
    'mood.physical':              'Fyysiset oireet',
    'mood.mental':                'Henkiset oireet',
    'mood.greeting.morning':      'Hyvää huomenta',
    'mood.greeting.afternoon':    'Hyvää iltapäivää',
    'mood.greeting.evening':      'Hyvää iltaa',
    'forecast.sevenDayTitle':     '7 päivän ennuste',
    'forecast.sevenDaySubtitle':  'Päivittäinen geomagneettinen ennuste',
    'forecast.peakKpNext7':       'Huippu Kp · 7 päivää',
    'forecast.bestDayLabel':      'Paras myrskypäivä',
    'forecast.stormDaysCount':    'Myrskypäivät',
    'forecast.tapToExpand':       'Napauta nähdäksesi 3 tunnin erittelyn',
    'forecast.todayLabel':        'Tänään',
    'forecast.tomorrowLabel':     'Huomenna',
    'forecast.longRangeTitle':    '27 päivän pitkän ajan ennuste',
    'forecast.longRangeSubtitle': 'Perustuu edelliseen auringon kiertoon — alempi tarkkuus',
    'forecast.showLongRange':     'Näytä 27 päivän ennuste',
    'forecast.hideLongRange':     'Piilota 27 päivän ennuste',
    'forecast.detailed':          'Yksityiskohtainen',
    'forecast.outlookSource':     'Ennuste',
    'livestream.watchYouTube':    'Katso YouTubessa',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Verkkokamera',
    'livestream.seasonal':        'Kausiluonteinen',
    'livestream.disclaimerHonest':'Useimmat suoratoistot avautuvat uudessa välilehdessä — kolmansien osapuolten sivustot estävät suoran upottamisen turvallisuussyistä. YouTube-kanavat näyttävät sen, mitä parhaillaan lähetetään suorana.',
    'livestream.sectionYouTube':  'YouTuben suorat kanavat',
    'livestream.sectionWebcams':  'Verkkokamerat ja -verkot',
},

'sv': {
    'mood.heroTitle':             'Kosmisk humörpuls',
    'mood.heroSubtitle':          'Spåra hur solens stormar rör sig genom dig',
    'mood.cosmicForecast':        'Kosmisk prognos',
    'mood.shareMyMood':           'Dela mitt humör',
    'mood.anonymous':             'Anonym · hjälper forskning om sol-jord-anslutningen',
    'mood.communityToday':        'Gemenskapen idag',
    'mood.betterThan':            'av gemenskapen mår sämre',
    'mood.didYouKnow':            'Visste du?',
    'mood.didYouKnowText':        'Geomagnetiska stormar kan utlösa huvudvärk, sömnlöshet och humörförändringar hos känsliga personer. Forskare studerar aktivt sol-jord-hälsa-anslutningen.',
    'mood.physical':              'Fysiska symptom',
    'mood.mental':                'Mentala symptom',
    'mood.greeting.morning':      'God morgon',
    'mood.greeting.afternoon':    'God eftermiddag',
    'mood.greeting.evening':      'God kväll',
    'forecast.sevenDayTitle':     '7-dagars prognos',
    'forecast.sevenDaySubtitle':  'Daglig geomagnetisk utsikt',
    'forecast.peakKpNext7':       'Topp Kp · 7 dagar',
    'forecast.bestDayLabel':      'Bästa stormdag',
    'forecast.stormDaysCount':    'Stormdagar',
    'forecast.tapToExpand':       'Tryck för 3-timmars uppdelning',
    'forecast.todayLabel':        'Idag',
    'forecast.tomorrowLabel':     'Imorgon',
    'forecast.longRangeTitle':    '27-dagars långtidsprognos',
    'forecast.longRangeSubtitle': 'Baserad på föregående solrotation — lägre noggrannhet',
    'forecast.showLongRange':     'Visa 27-dagars prognos',
    'forecast.hideLongRange':     'Dölj 27-dagars prognos',
    'forecast.detailed':          'Detaljerad',
    'forecast.outlookSource':     'Prognos',
    'livestream.watchYouTube':    'Titta på YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Webbkamera',
    'livestream.seasonal':        'Säsongsbunden',
    'livestream.disclaimerHonest':'De flesta strömmar öppnas i en ny flik — tredjepartssidor blockerar direkt inbäddning av säkerhetsskäl. YouTube-kanaler visar det som sänds live just nu.',
    'livestream.sectionYouTube':  'YouTube Live-kanaler',
    'livestream.sectionWebcams':  'Webbkameror och nätverk',
},

'is': {
    'mood.heroTitle':             'Geimskapaður skapsveiflupúls',
    'mood.heroSubtitle':          'Fylgstu með hvernig stormar sólarinnar fara í gegnum þig',
    'mood.cosmicForecast':        'Geimskapaðar spár',
    'mood.shareMyMood':           'Deila skapinu mínu',
    'mood.anonymous':             'Nafnlaust · hjálpar rannsóknum á sól-jörð-tengingu',
    'mood.communityToday':        'Samfélagið í dag',
    'mood.betterThan':            'samfélagsins líður verr',
    'mood.didYouKnow':            'Vissir þú?',
    'mood.didYouKnowText':        'Jarðsegulsstormar geta valdið höfuðverk, svefnleysi og skapsveiflum hjá viðkvæmum einstaklingum. Vísindamenn rannsaka virkilega sól-jörð-heilsutenginguna.',
    'mood.physical':              'Líkamleg einkenni',
    'mood.mental':                'Andleg einkenni',
    'mood.greeting.morning':      'Góðan daginn',
    'mood.greeting.afternoon':    'Góðan dag',
    'mood.greeting.evening':      'Gott kvöld',
    'forecast.sevenDayTitle':     '7-daga spá',
    'forecast.sevenDaySubtitle':  'Dagleg jarðsegulsspá',
    'forecast.peakKpNext7':       'Hámark Kp · 7 dagar',
    'forecast.bestDayLabel':      'Besti stormadagur',
    'forecast.stormDaysCount':    'Stormadagar',
    'forecast.tapToExpand':       'Smelltu fyrir 3-tíma sundurliðun',
    'forecast.todayLabel':        'Í dag',
    'forecast.tomorrowLabel':     'Á morgun',
    'forecast.longRangeTitle':    '27-daga langtímaspá',
    'forecast.longRangeSubtitle': 'Byggð á fyrri sólarsnúningi — minni nákvæmni',
    'forecast.showLongRange':     'Sýna 27-daga spá',
    'forecast.hideLongRange':     'Fela 27-daga spá',
    'forecast.detailed':          'Ítarleg',
    'forecast.outlookSource':     'Spá',
    'livestream.watchYouTube':    'Horfa á YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Vefmyndavél',
    'livestream.seasonal':        'Árstíðabundið',
    'livestream.disclaimerHonest':'Flest streymi opnast í nýjum flipa — vefsíður þriðja aðila loka á beina innbyggingu af öryggisástæðum. YouTube-rásir sýna það sem er í beinni núna.',
    'livestream.sectionYouTube':  'YouTube beinar rásir',
    'livestream.sectionWebcams':  'Vefmyndavélar og net',
},

'da': {
    'mood.heroTitle':             'Kosmisk humørpuls',
    'mood.heroSubtitle':          'Spor hvordan solens storme bevæger sig gennem dig',
    'mood.cosmicForecast':        'Kosmisk prognose',
    'mood.shareMyMood':           'Del mit humør',
    'mood.anonymous':             'Anonymt · hjælper forskning om Sol-Jord-forbindelsen',
    'mood.communityToday':        'Fællesskabet i dag',
    'mood.betterThan':            'af fællesskabet føler sig værre',
    'mood.didYouKnow':            'Vidste du?',
    'mood.didYouKnowText':        'Geomagnetiske storme kan udløse hovedpine, søvnløshed og humørændringer hos følsomme personer. Forskere undersøger aktivt Sol-Jord-Sundhed-forbindelsen.',
    'mood.physical':              'Fysiske symptomer',
    'mood.mental':                'Mentale symptomer',
    'mood.greeting.morning':      'Godmorgen',
    'mood.greeting.afternoon':    'God eftermiddag',
    'mood.greeting.evening':      'God aften',
    'forecast.sevenDayTitle':     '7-dages prognose',
    'forecast.sevenDaySubtitle':  'Daglig geomagnetisk udsigt',
    'forecast.peakKpNext7':       'Top Kp · 7 dage',
    'forecast.bestDayLabel':      'Bedste stormdag',
    'forecast.stormDaysCount':    'Stormdage',
    'forecast.tapToExpand':       'Tryk for 3-timers opdeling',
    'forecast.todayLabel':        'I dag',
    'forecast.tomorrowLabel':     'I morgen',
    'forecast.longRangeTitle':    '27-dages langtidsprognose',
    'forecast.longRangeSubtitle': 'Baseret på tidligere solrotation — lavere nøjagtighed',
    'forecast.showLongRange':     'Vis 27-dages prognose',
    'forecast.hideLongRange':     'Skjul 27-dages prognose',
    'forecast.detailed':          'Detaljeret',
    'forecast.outlookSource':     'Prognose',
    'livestream.watchYouTube':    'Se på YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Webkamera',
    'livestream.seasonal':        'Sæsonbestemt',
    'livestream.disclaimerHonest':'De fleste streams åbnes i en ny fane — tredjepartssider blokerer direkte indlejring af sikkerhedsmæssige årsager. YouTube-kanaler viser det, der sendes live lige nu.',
    'livestream.sectionYouTube':  'YouTube Live-kanaler',
    'livestream.sectionWebcams':  'Webkameraer og netværk',
},

'pl': {
    'mood.heroTitle':             'Kosmiczny puls nastroju',
    'mood.heroSubtitle':          'Śledź, jak burze słoneczne przepływają przez Ciebie',
    'mood.cosmicForecast':        'Kosmiczna prognoza',
    'mood.shareMyMood':           'Podziel się nastrojem',
    'mood.anonymous':             'Anonimowo · pomaga badaniom połączenia Słońce-Ziemia',
    'mood.communityToday':        'Społeczność dzisiaj',
    'mood.betterThan':            'społeczności czuje się gorzej',
    'mood.didYouKnow':            'Czy wiesz?',
    'mood.didYouKnowText':        'Burze geomagnetyczne mogą wywoływać bóle głowy, bezsenność i zmiany nastroju u wrażliwych osób. Naukowcy aktywnie badają połączenie Słońce-Ziemia-Zdrowie.',
    'mood.physical':              'Objawy fizyczne',
    'mood.mental':                'Objawy psychiczne',
    'mood.greeting.morning':      'Dzień dobry',
    'mood.greeting.afternoon':    'Dzień dobry',
    'mood.greeting.evening':      'Dobry wieczór',
    'forecast.sevenDayTitle':     'Prognoza 7-dniowa',
    'forecast.sevenDaySubtitle':  'Dzienna prognoza geomagnetyczna',
    'forecast.peakKpNext7':       'Szczyt Kp · 7 dni',
    'forecast.bestDayLabel':      'Najlepszy dzień burzy',
    'forecast.stormDaysCount':    'Dni burzowe',
    'forecast.tapToExpand':       'Stuknij, aby zobaczyć podział 3-godzinny',
    'forecast.todayLabel':        'Dzisiaj',
    'forecast.tomorrowLabel':     'Jutro',
    'forecast.longRangeTitle':    'Prognoza długoterminowa 27 dni',
    'forecast.longRangeSubtitle': 'Oparta na poprzednim obrocie słońca — niższa dokładność',
    'forecast.showLongRange':     'Pokaż prognozę 27-dniową',
    'forecast.hideLongRange':     'Ukryj prognozę 27-dniową',
    'forecast.detailed':          'Szczegółowa',
    'forecast.outlookSource':     'Prognoza',
    'livestream.watchYouTube':    'Oglądaj na YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Kamera internetowa',
    'livestream.seasonal':        'Sezonowy',
    'livestream.disclaimerHonest':'Większość transmisji otwiera się w nowej karcie — strony osób trzecich blokują bezpośrednie osadzanie ze względów bezpieczeństwa. Kanały YouTube pokazują to, co jest aktualnie na żywo.',
    'livestream.sectionYouTube':  'Kanały YouTube Live',
    'livestream.sectionWebcams':  'Kamery internetowe i sieci',
},

'uk': {
    'mood.heroTitle':             'Космічний пульс настрою',
    'mood.heroSubtitle':          'Відстежуйте, як сонячні бурі впливають на вас',
    'mood.cosmicForecast':        'Космічний прогноз',
    'mood.shareMyMood':           'Поділитися настроєм',
    'mood.anonymous':             'Анонімно · допомагає дослідженням зв\'язку Сонце-Земля',
    'mood.communityToday':        'Спільнота сьогодні',
    'mood.betterThan':            'спільноти почувається гірше',
    'mood.didYouKnow':            'Чи знаєте ви?',
    'mood.didYouKnowText':        'Геомагнітні бурі можуть викликати головний біль, безсоння та зміни настрою у чутливих людей. Вчені активно вивчають зв\'язок Сонце-Земля-Здоров\'я.',
    'mood.physical':              'Фізичні симптоми',
    'mood.mental':                'Психічні симптоми',
    'mood.greeting.morning':      'Доброго ранку',
    'mood.greeting.afternoon':    'Доброго дня',
    'mood.greeting.evening':      'Добрий вечір',
    'forecast.sevenDayTitle':     'Прогноз на 7 днів',
    'forecast.sevenDaySubtitle':  'Щоденний геомагнітний прогноз',
    'forecast.peakKpNext7':       'Пік Kp · 7 днів',
    'forecast.bestDayLabel':      'Найкращий день бурі',
    'forecast.stormDaysCount':    'Дні з бурями',
    'forecast.tapToExpand':       'Натисніть для розбивки на 3 години',
    'forecast.todayLabel':        'Сьогодні',
    'forecast.tomorrowLabel':     'Завтра',
    'forecast.longRangeTitle':    'Довгостроковий прогноз на 27 днів',
    'forecast.longRangeSubtitle': 'На основі попереднього сонячного оберту — менша точність',
    'forecast.showLongRange':     'Показати прогноз на 27 днів',
    'forecast.hideLongRange':     'Сховати прогноз на 27 днів',
    'forecast.detailed':          'Детальний',
    'forecast.outlookSource':     'Прогноз',
    'livestream.watchYouTube':    'Дивитися на YouTube',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      'Веб-камера',
    'livestream.seasonal':        'Сезонний',
    'livestream.disclaimerHonest':'Більшість трансляцій відкриваються в новій вкладці — сторонні сайти блокують пряме вбудовування з міркувань безпеки. Канали YouTube показують те, що транслюється наживо зараз.',
    'livestream.sectionYouTube':  'YouTube Live-канали',
    'livestream.sectionWebcams':  'Веб-камери та мережі',
},

'ko': {
    'mood.heroTitle':             '코스믹 무드 펄스',
    'mood.heroSubtitle':          '태양의 폭풍이 당신에게 어떻게 영향을 미치는지 추적하세요',
    'mood.cosmicForecast':        '우주 예보',
    'mood.shareMyMood':           '내 기분 공유',
    'mood.anonymous':             '익명 · 태양-지구 연결 연구에 도움',
    'mood.communityToday':        '오늘의 커뮤니티',
    'mood.betterThan':            '의 커뮤니티가 더 나쁘게 느낌',
    'mood.didYouKnow':            '알고 계셨나요?',
    'mood.didYouKnowText':        '지자기 폭풍은 민감한 사람들에게 두통, 불면증, 기분 변화를 유발할 수 있습니다. 과학자들은 태양-지구-건강 연결을 적극적으로 연구하고 있습니다.',
    'mood.physical':              '신체 증상',
    'mood.mental':                '정신적 증상',
    'mood.greeting.morning':      '좋은 아침',
    'mood.greeting.afternoon':    '좋은 오후',
    'mood.greeting.evening':      '좋은 저녁',
    'forecast.sevenDayTitle':     '7일 예보',
    'forecast.sevenDaySubtitle':  '일일 지자기 전망',
    'forecast.peakKpNext7':       '최고 Kp · 7일',
    'forecast.bestDayLabel':      '최고의 폭풍의 날',
    'forecast.stormDaysCount':    '폭풍의 날',
    'forecast.tapToExpand':       '3시간 세분화를 보려면 탭하세요',
    'forecast.todayLabel':        '오늘',
    'forecast.tomorrowLabel':     '내일',
    'forecast.longRangeTitle':    '27일 장기 전망',
    'forecast.longRangeSubtitle': '이전 태양 자전에 기반 — 정확도 낮음',
    'forecast.showLongRange':     '27일 전망 표시',
    'forecast.hideLongRange':     '27일 전망 숨기기',
    'forecast.detailed':          '상세',
    'forecast.outlookSource':     '전망',
    'livestream.watchYouTube':    'YouTube에서 보기',
    'livestream.kindYouTube':     'YouTube',
    'livestream.kindWebcam':      '웹캠',
    'livestream.seasonal':        '계절성',
    'livestream.disclaimerHonest':'대부분의 스트림은 새 탭에서 열립니다 — 제3자 사이트는 보안상의 이유로 직접 임베딩을 차단합니다. YouTube 채널은 현재 라이브로 방송 중인 내용을 표시합니다.',
    'livestream.sectionYouTube':  'YouTube 라이브 채널',
    'livestream.sectionWebcams':  '웹캠 및 네트워크',
},

}

print("Syncing v2.2 keys to remaining 8 locales…")
for lang, additions in LOCALES.items():
    inject(lang, additions)

print("\nVerifying completeness…")
en_keys = get_keys('en')
for lang in LOCALES.keys():
    missing = sorted(en_keys - get_keys(lang))
    if missing:
        print(f"  [{lang}] still missing {len(missing)}: {missing[:3]}...")
    else:
        print(f"  [{lang}] ✅ complete")
