#!/usr/bin/env python3
"""Sync Pricing page i18n keys to all 16 locales."""
import re, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'src', 'locales')


def get_keys(lang):
    return set(re.findall(r"^\s+'([^']+)'\s*:", open(os.path.join(BASE, f'{lang}.ts')).read(), re.MULTILINE))


def escape(v):
    return v.replace("\\", "\\\\").replace("'", "\\'")


def inject(lang, additions):
    path = os.path.join(BASE, f'{lang}.ts')
    content = open(path, encoding='utf-8').read()
    existing = get_keys(lang)
    lines = []
    for k, v in additions.items():
        if k not in existing:
            lines.append(f"  '{k}': '{escape(v)}',")
    if not lines:
        print(f"  [{lang}] nothing to add")
        return
    block = '\n'.join(lines)
    idx = content.rfind('\n};')
    new = content[:idx] + '\n' + block + content[idx:]
    open(path, 'w', encoding='utf-8').write(new)
    print(f"  [{lang}] +{len(lines)} keys")


LOCALES = {
'en': {
    'pricing.title': 'Pricing',
    'pricing.metaDescription': 'Choose your plan. Free space weather monitoring or Pro/Premium with advanced alerts and aurora forecasting.',
    'pricing.heroTitle': 'Choose your plan',
    'pricing.heroSubtitle': 'Unlock the full power of Storm Watcher',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.save25': 'Save 25%',
    'pricing.currentPlan': 'Current plan',
    'pricing.mostPopular': 'Most popular',
    'pricing.perMonth': 'month',
    'pricing.perYear': 'year',
    'pricing.perMonthBilledYearly': 'month billed annually',
    'pricing.loading': 'Loading…',
    'pricing.getPro': 'Get Pro',
    'pricing.getPremium': 'Get Premium',
    'pricing.manageSubscription': 'Manage subscription',
    'pricing.footer': 'Cancel anytime · Secure payments via Stripe · VAT may apply',
    'pricing.pro.tagline': 'For enthusiasts',
    'pricing.premium.tagline': 'For power users',
    'pricing.pro.feat.forecasts': 'Detailed geomagnetic forecasts',
    'pricing.pro.feat.visibility': 'Aurora visibility predictions',
    'pricing.pro.feat.alerts': 'Push notifications & alerts',
    'pricing.pro.feat.adfree': 'Ad-free experience',
    'pricing.pro.feat.basics': 'All basic features',
    'pricing.premium.feat.everything': 'Everything in Pro',
    'pricing.premium.feat.history': 'Historical data & charts',
    'pricing.premium.feat.priority': 'Priority alerts',
    'pricing.premium.feat.iss': 'ISS tracking (advanced)',
    'pricing.premium.feat.export': 'Export data',
    'pricing.premium.feat.earlyAccess': 'Early access to new features',
},
'bg': {
    'pricing.title': 'Цени',
    'pricing.metaDescription': 'Избери своя план. Безплатно наблюдение на космическо време или Pro/Premium с разширени предупреждения и прогнози за аврора.',
    'pricing.heroTitle': 'Избери своя план',
    'pricing.heroSubtitle': 'Отключи цялата мощ на Storm Watcher',
    'pricing.monthly': 'Месечно',
    'pricing.yearly': 'Годишно',
    'pricing.save25': 'Спести 25%',
    'pricing.currentPlan': 'Активен план',
    'pricing.mostPopular': 'Най-популярно',
    'pricing.perMonth': 'месец',
    'pricing.perYear': 'година',
    'pricing.perMonthBilledYearly': 'месец, фактуриран годишно',
    'pricing.loading': 'Зареждане…',
    'pricing.getPro': 'Вземи Pro',
    'pricing.getPremium': 'Вземи Premium',
    'pricing.manageSubscription': 'Управление на абонамент',
    'pricing.footer': 'Отказ по всяко време · Сигурни плащания през Stripe · ДДС може да се прилага',
    'pricing.pro.tagline': 'За ентусиасти',
    'pricing.premium.tagline': 'За опитни потребители',
    'pricing.pro.feat.forecasts': 'Детайлни геомагнитни прогнози',
    'pricing.pro.feat.visibility': 'Прогнози за видимост на аврора',
    'pricing.pro.feat.alerts': 'Push известия и предупреждения',
    'pricing.pro.feat.adfree': 'Без реклами',
    'pricing.pro.feat.basics': 'Всички основни функции',
    'pricing.premium.feat.everything': 'Всичко от Pro',
    'pricing.premium.feat.history': 'Исторически данни и графики',
    'pricing.premium.feat.priority': 'Приоритетни предупреждения',
    'pricing.premium.feat.iss': 'ISS проследяване (разширено)',
    'pricing.premium.feat.export': 'Експорт на данни',
    'pricing.premium.feat.earlyAccess': 'Ранен достъп до нови функции',
},
'de': {
    'pricing.title': 'Preise',
    'pricing.metaDescription': 'Wähle deinen Plan. Kostenlose Weltraumwetterüberwachung oder Pro/Premium mit erweiterten Warnungen und Polarlicht-Vorhersagen.',
    'pricing.heroTitle': 'Wähle deinen Plan',
    'pricing.heroSubtitle': 'Schalte die volle Kraft von Storm Watcher frei',
    'pricing.monthly': 'Monatlich',
    'pricing.yearly': 'Jährlich',
    'pricing.save25': '25% sparen',
    'pricing.currentPlan': 'Aktueller Plan',
    'pricing.mostPopular': 'Am beliebtesten',
    'pricing.perMonth': 'Monat',
    'pricing.perYear': 'Jahr',
    'pricing.perMonthBilledYearly': 'Monat, jährlich abgerechnet',
    'pricing.loading': 'Lädt…',
    'pricing.getPro': 'Pro holen',
    'pricing.getPremium': 'Premium holen',
    'pricing.manageSubscription': 'Abonnement verwalten',
    'pricing.footer': 'Jederzeit kündbar · Sichere Zahlungen über Stripe · MwSt. kann anfallen',
    'pricing.pro.tagline': 'Für Enthusiasten',
    'pricing.premium.tagline': 'Für Power-User',
    'pricing.pro.feat.forecasts': 'Detaillierte geomagnetische Vorhersagen',
    'pricing.pro.feat.visibility': 'Polarlicht-Sichtbarkeitsvorhersagen',
    'pricing.pro.feat.alerts': 'Push-Benachrichtigungen & Warnungen',
    'pricing.pro.feat.adfree': 'Werbefrei',
    'pricing.pro.feat.basics': 'Alle Grundfunktionen',
    'pricing.premium.feat.everything': 'Alles aus Pro',
    'pricing.premium.feat.history': 'Historische Daten & Diagramme',
    'pricing.premium.feat.priority': 'Prioritäts-Warnungen',
    'pricing.premium.feat.iss': 'ISS-Verfolgung (erweitert)',
    'pricing.premium.feat.export': 'Daten exportieren',
    'pricing.premium.feat.earlyAccess': 'Früher Zugang zu neuen Funktionen',
},
'es': {
    'pricing.title': 'Precios',
    'pricing.metaDescription': 'Elige tu plan. Monitoreo gratuito del clima espacial o Pro/Premium con alertas avanzadas y predicciones de auroras.',
    'pricing.heroTitle': 'Elige tu plan',
    'pricing.heroSubtitle': 'Desbloquea todo el poder de Storm Watcher',
    'pricing.monthly': 'Mensual',
    'pricing.yearly': 'Anual',
    'pricing.save25': 'Ahorra 25%',
    'pricing.currentPlan': 'Plan actual',
    'pricing.mostPopular': 'Más popular',
    'pricing.perMonth': 'mes',
    'pricing.perYear': 'año',
    'pricing.perMonthBilledYearly': 'mes facturado anualmente',
    'pricing.loading': 'Cargando…',
    'pricing.getPro': 'Obtener Pro',
    'pricing.getPremium': 'Obtener Premium',
    'pricing.manageSubscription': 'Gestionar suscripción',
    'pricing.footer': 'Cancela cuando quieras · Pagos seguros con Stripe · Puede aplicarse IVA',
    'pricing.pro.tagline': 'Para entusiastas',
    'pricing.premium.tagline': 'Para usuarios avanzados',
    'pricing.pro.feat.forecasts': 'Predicciones geomagnéticas detalladas',
    'pricing.pro.feat.visibility': 'Predicciones de visibilidad de auroras',
    'pricing.pro.feat.alerts': 'Notificaciones push y alertas',
    'pricing.pro.feat.adfree': 'Sin anuncios',
    'pricing.pro.feat.basics': 'Todas las funciones básicas',
    'pricing.premium.feat.everything': 'Todo lo de Pro',
    'pricing.premium.feat.history': 'Datos históricos y gráficos',
    'pricing.premium.feat.priority': 'Alertas prioritarias',
    'pricing.premium.feat.iss': 'Seguimiento ISS (avanzado)',
    'pricing.premium.feat.export': 'Exportar datos',
    'pricing.premium.feat.earlyAccess': 'Acceso anticipado a nuevas funciones',
},
'fr': {
    'pricing.title': 'Tarifs',
    'pricing.metaDescription': 'Choisissez votre plan. Surveillance gratuite de la météo spatiale ou Pro/Premium avec alertes avancées et prévisions d\'aurores.',
    'pricing.heroTitle': 'Choisissez votre plan',
    'pricing.heroSubtitle': 'Débloquez toute la puissance de Storm Watcher',
    'pricing.monthly': 'Mensuel',
    'pricing.yearly': 'Annuel',
    'pricing.save25': 'Économisez 25%',
    'pricing.currentPlan': 'Plan actuel',
    'pricing.mostPopular': 'Le plus populaire',
    'pricing.perMonth': 'mois',
    'pricing.perYear': 'an',
    'pricing.perMonthBilledYearly': 'mois facturé annuellement',
    'pricing.loading': 'Chargement…',
    'pricing.getPro': 'Obtenir Pro',
    'pricing.getPremium': 'Obtenir Premium',
    'pricing.manageSubscription': 'Gérer l\'abonnement',
    'pricing.footer': 'Annulez à tout moment · Paiements sécurisés via Stripe · TVA applicable',
    'pricing.pro.tagline': 'Pour les passionnés',
    'pricing.premium.tagline': 'Pour les utilisateurs avancés',
    'pricing.pro.feat.forecasts': 'Prévisions géomagnétiques détaillées',
    'pricing.pro.feat.visibility': 'Prédictions de visibilité des aurores',
    'pricing.pro.feat.alerts': 'Notifications push et alertes',
    'pricing.pro.feat.adfree': 'Sans publicité',
    'pricing.pro.feat.basics': 'Toutes les fonctionnalités de base',
    'pricing.premium.feat.everything': 'Tout de Pro',
    'pricing.premium.feat.history': 'Données historiques et graphiques',
    'pricing.premium.feat.priority': 'Alertes prioritaires',
    'pricing.premium.feat.iss': 'Suivi ISS (avancé)',
    'pricing.premium.feat.export': 'Exporter les données',
    'pricing.premium.feat.earlyAccess': 'Accès anticipé aux nouvelles fonctionnalités',
},
'ru': {
    'pricing.title': 'Цены',
    'pricing.metaDescription': 'Выберите свой план. Бесплатный мониторинг космической погоды или Pro/Premium с расширенными предупреждениями и прогнозами полярных сияний.',
    'pricing.heroTitle': 'Выберите свой план',
    'pricing.heroSubtitle': 'Откройте полную мощь Storm Watcher',
    'pricing.monthly': 'Ежемесячно',
    'pricing.yearly': 'Ежегодно',
    'pricing.save25': 'Сэкономьте 25%',
    'pricing.currentPlan': 'Активный план',
    'pricing.mostPopular': 'Самый популярный',
    'pricing.perMonth': 'месяц',
    'pricing.perYear': 'год',
    'pricing.perMonthBilledYearly': 'месяц, ежегодная оплата',
    'pricing.loading': 'Загрузка…',
    'pricing.getPro': 'Получить Pro',
    'pricing.getPremium': 'Получить Premium',
    'pricing.manageSubscription': 'Управление подпиской',
    'pricing.footer': 'Отмена в любое время · Безопасные платежи через Stripe · Может применяться НДС',
    'pricing.pro.tagline': 'Для энтузиастов',
    'pricing.premium.tagline': 'Для опытных пользователей',
    'pricing.pro.feat.forecasts': 'Детальные геомагнитные прогнозы',
    'pricing.pro.feat.visibility': 'Прогнозы видимости полярных сияний',
    'pricing.pro.feat.alerts': 'Push-уведомления и предупреждения',
    'pricing.pro.feat.adfree': 'Без рекламы',
    'pricing.pro.feat.basics': 'Все базовые функции',
    'pricing.premium.feat.everything': 'Всё из Pro',
    'pricing.premium.feat.history': 'Исторические данные и графики',
    'pricing.premium.feat.priority': 'Приоритетные предупреждения',
    'pricing.premium.feat.iss': 'Отслеживание МКС (расширенное)',
    'pricing.premium.feat.export': 'Экспорт данных',
    'pricing.premium.feat.earlyAccess': 'Ранний доступ к новым функциям',
},
'zh': {
    'pricing.title': '价格',
    'pricing.metaDescription': '选择您的计划。免费空间天气监测或Pro/Premium，提供高级警报和极光预报。',
    'pricing.heroTitle': '选择您的计划',
    'pricing.heroSubtitle': '解锁Storm Watcher的全部功能',
    'pricing.monthly': '月付',
    'pricing.yearly': '年付',
    'pricing.save25': '节省25%',
    'pricing.currentPlan': '当前计划',
    'pricing.mostPopular': '最受欢迎',
    'pricing.perMonth': '月',
    'pricing.perYear': '年',
    'pricing.perMonthBilledYearly': '月（年度结算）',
    'pricing.loading': '加载中…',
    'pricing.getPro': '获取Pro',
    'pricing.getPremium': '获取Premium',
    'pricing.manageSubscription': '管理订阅',
    'pricing.footer': '随时取消 · 通过Stripe安全支付 · 可能适用增值税',
    'pricing.pro.tagline': '为爱好者',
    'pricing.premium.tagline': '为高级用户',
    'pricing.pro.feat.forecasts': '详细地磁预报',
    'pricing.pro.feat.visibility': '极光可见性预测',
    'pricing.pro.feat.alerts': '推送通知和警报',
    'pricing.pro.feat.adfree': '无广告体验',
    'pricing.pro.feat.basics': '所有基本功能',
    'pricing.premium.feat.everything': 'Pro的所有功能',
    'pricing.premium.feat.history': '历史数据和图表',
    'pricing.premium.feat.priority': '优先警报',
    'pricing.premium.feat.iss': 'ISS追踪（高级）',
    'pricing.premium.feat.export': '导出数据',
    'pricing.premium.feat.earlyAccess': '新功能抢先体验',
},
'ja': {
    'pricing.title': '価格',
    'pricing.metaDescription': 'プランを選択。無料の宇宙天気モニタリングまたは高度なアラートとオーロラ予報を備えたPro/Premium。',
    'pricing.heroTitle': 'プランを選択',
    'pricing.heroSubtitle': 'Storm Watcherの全機能を解放',
    'pricing.monthly': '月額',
    'pricing.yearly': '年額',
    'pricing.save25': '25%節約',
    'pricing.currentPlan': '現在のプラン',
    'pricing.mostPopular': '最も人気',
    'pricing.perMonth': '月',
    'pricing.perYear': '年',
    'pricing.perMonthBilledYearly': '月（年単位で請求）',
    'pricing.loading': '読み込み中…',
    'pricing.getPro': 'Proを取得',
    'pricing.getPremium': 'Premiumを取得',
    'pricing.manageSubscription': 'サブスクリプション管理',
    'pricing.footer': 'いつでもキャンセル可能 · Stripeによる安全な支払い · VATが適用される場合があります',
    'pricing.pro.tagline': '愛好家向け',
    'pricing.premium.tagline': 'パワーユーザー向け',
    'pricing.pro.feat.forecasts': '詳細な地磁気予報',
    'pricing.pro.feat.visibility': 'オーロラ可視性予測',
    'pricing.pro.feat.alerts': 'プッシュ通知とアラート',
    'pricing.pro.feat.adfree': '広告なし',
    'pricing.pro.feat.basics': 'すべての基本機能',
    'pricing.premium.feat.everything': 'Proのすべて',
    'pricing.premium.feat.history': '履歴データとチャート',
    'pricing.premium.feat.priority': '優先アラート',
    'pricing.premium.feat.iss': 'ISS追跡（高度）',
    'pricing.premium.feat.export': 'データエクスポート',
    'pricing.premium.feat.earlyAccess': '新機能への早期アクセス',
},
'no': {
    'pricing.title': 'Priser',
    'pricing.metaDescription': 'Velg din plan. Gratis romværovervåkning eller Pro/Premium med avanserte varsler og nordlys-prognoser.',
    'pricing.heroTitle': 'Velg din plan',
    'pricing.heroSubtitle': 'Lås opp Storm Watchers fulle kraft',
    'pricing.monthly': 'Månedlig',
    'pricing.yearly': 'Årlig',
    'pricing.save25': 'Spar 25%',
    'pricing.currentPlan': 'Nåværende plan',
    'pricing.mostPopular': 'Mest populær',
    'pricing.perMonth': 'måned',
    'pricing.perYear': 'år',
    'pricing.perMonthBilledYearly': 'måned fakturert årlig',
    'pricing.loading': 'Laster…',
    'pricing.getPro': 'Skaff Pro',
    'pricing.getPremium': 'Skaff Premium',
    'pricing.manageSubscription': 'Administrer abonnement',
    'pricing.footer': 'Avbryt når som helst · Sikre betalinger via Stripe · MVA kan gjelde',
    'pricing.pro.tagline': 'For entusiaster',
    'pricing.premium.tagline': 'For avanserte brukere',
    'pricing.pro.feat.forecasts': 'Detaljerte geomagnetiske prognoser',
    'pricing.pro.feat.visibility': 'Nordlys-synlighetsspådommer',
    'pricing.pro.feat.alerts': 'Push-varslinger og advarsler',
    'pricing.pro.feat.adfree': 'Reklamefri opplevelse',
    'pricing.pro.feat.basics': 'Alle grunnleggende funksjoner',
    'pricing.premium.feat.everything': 'Alt i Pro',
    'pricing.premium.feat.history': 'Historiske data og diagrammer',
    'pricing.premium.feat.priority': 'Prioritetsvarsler',
    'pricing.premium.feat.iss': 'ISS-sporing (avansert)',
    'pricing.premium.feat.export': 'Eksporter data',
    'pricing.premium.feat.earlyAccess': 'Tidlig tilgang til nye funksjoner',
},
'fi': {
    'pricing.title': 'Hinnoittelu',
    'pricing.metaDescription': 'Valitse suunnitelmasi. Ilmainen avaruussään seuranta tai Pro/Premium edistyneillä hälytyksillä ja revontulennusteilla.',
    'pricing.heroTitle': 'Valitse suunnitelmasi',
    'pricing.heroSubtitle': 'Avaa Storm Watcherin täysi voima',
    'pricing.monthly': 'Kuukausittain',
    'pricing.yearly': 'Vuosittain',
    'pricing.save25': 'Säästä 25%',
    'pricing.currentPlan': 'Nykyinen suunnitelma',
    'pricing.mostPopular': 'Suosituin',
    'pricing.perMonth': 'kuukausi',
    'pricing.perYear': 'vuosi',
    'pricing.perMonthBilledYearly': 'kuukausi laskutettuna vuosittain',
    'pricing.loading': 'Ladataan…',
    'pricing.getPro': 'Hanki Pro',
    'pricing.getPremium': 'Hanki Premium',
    'pricing.manageSubscription': 'Hallinnoi tilausta',
    'pricing.footer': 'Peruuta milloin tahansa · Turvalliset maksut Stripen kautta · ALV voi olla',
    'pricing.pro.tagline': 'Harrastajille',
    'pricing.premium.tagline': 'Tehokäyttäjille',
    'pricing.pro.feat.forecasts': 'Yksityiskohtaiset geomagneettiset ennusteet',
    'pricing.pro.feat.visibility': 'Revontulien näkyvyysennusteet',
    'pricing.pro.feat.alerts': 'Push-ilmoitukset ja hälytykset',
    'pricing.pro.feat.adfree': 'Mainoksiton kokemus',
    'pricing.pro.feat.basics': 'Kaikki perustoiminnot',
    'pricing.premium.feat.everything': 'Kaikki Prosta',
    'pricing.premium.feat.history': 'Historialliset tiedot ja kaaviot',
    'pricing.premium.feat.priority': 'Prioriteettihälytykset',
    'pricing.premium.feat.iss': 'ISS-seuranta (edistynyt)',
    'pricing.premium.feat.export': 'Vie tiedot',
    'pricing.premium.feat.earlyAccess': 'Varhainen pääsy uusiin ominaisuuksiin',
},
'sv': {
    'pricing.title': 'Priser',
    'pricing.metaDescription': 'Välj din plan. Gratis rymdväderövervakning eller Pro/Premium med avancerade varningar och norrskensprognoser.',
    'pricing.heroTitle': 'Välj din plan',
    'pricing.heroSubtitle': 'Lås upp Storm Watchers fulla kraft',
    'pricing.monthly': 'Månadsvis',
    'pricing.yearly': 'Årligen',
    'pricing.save25': 'Spara 25%',
    'pricing.currentPlan': 'Nuvarande plan',
    'pricing.mostPopular': 'Mest populär',
    'pricing.perMonth': 'månad',
    'pricing.perYear': 'år',
    'pricing.perMonthBilledYearly': 'månad fakturerad årligen',
    'pricing.loading': 'Laddar…',
    'pricing.getPro': 'Skaffa Pro',
    'pricing.getPremium': 'Skaffa Premium',
    'pricing.manageSubscription': 'Hantera prenumeration',
    'pricing.footer': 'Avbryt när som helst · Säkra betalningar via Stripe · Moms kan tillkomma',
    'pricing.pro.tagline': 'För entusiaster',
    'pricing.premium.tagline': 'För avancerade användare',
    'pricing.pro.feat.forecasts': 'Detaljerade geomagnetiska prognoser',
    'pricing.pro.feat.visibility': 'Norrskens-synlighetsprognoser',
    'pricing.pro.feat.alerts': 'Push-meddelanden och varningar',
    'pricing.pro.feat.adfree': 'Reklamfri upplevelse',
    'pricing.pro.feat.basics': 'Alla grundläggande funktioner',
    'pricing.premium.feat.everything': 'Allt i Pro',
    'pricing.premium.feat.history': 'Historisk data och diagram',
    'pricing.premium.feat.priority': 'Prioritetsvarningar',
    'pricing.premium.feat.iss': 'ISS-spårning (avancerad)',
    'pricing.premium.feat.export': 'Exportera data',
    'pricing.premium.feat.earlyAccess': 'Tidig tillgång till nya funktioner',
},
'is': {
    'pricing.title': 'Verðlagning',
    'pricing.metaDescription': 'Veldu þína áætlun. Ókeypis geimveðureftirlit eða Pro/Premium með háþróaðum viðvörunum og norðurljósaspám.',
    'pricing.heroTitle': 'Veldu þína áætlun',
    'pricing.heroSubtitle': 'Opnaðu allan kraft Storm Watcher',
    'pricing.monthly': 'Mánaðarlega',
    'pricing.yearly': 'Árlega',
    'pricing.save25': 'Sparaðu 25%',
    'pricing.currentPlan': 'Núverandi áætlun',
    'pricing.mostPopular': 'Vinsælast',
    'pricing.perMonth': 'mánuður',
    'pricing.perYear': 'ár',
    'pricing.perMonthBilledYearly': 'mánuður innheimtur árlega',
    'pricing.loading': 'Hleður…',
    'pricing.getPro': 'Fá Pro',
    'pricing.getPremium': 'Fá Premium',
    'pricing.manageSubscription': 'Stjórna áskrift',
    'pricing.footer': 'Hættu hvenær sem er · Öruggar greiðslur í gegnum Stripe · VSK kann að gilda',
    'pricing.pro.tagline': 'Fyrir áhugamenn',
    'pricing.premium.tagline': 'Fyrir kraftnotendur',
    'pricing.pro.feat.forecasts': 'Ítarlegar jarðsegulsspár',
    'pricing.pro.feat.visibility': 'Norðurljósasýnileikaspár',
    'pricing.pro.feat.alerts': 'Push-tilkynningar og viðvaranir',
    'pricing.pro.feat.adfree': 'Auglýsingalaus upplifun',
    'pricing.pro.feat.basics': 'Allir grunnaðgerðir',
    'pricing.premium.feat.everything': 'Allt í Pro',
    'pricing.premium.feat.history': 'Söguleg gögn og töflur',
    'pricing.premium.feat.priority': 'Forgangsviðvaranir',
    'pricing.premium.feat.iss': 'ISS-rakning (háþróuð)',
    'pricing.premium.feat.export': 'Flytja út gögn',
    'pricing.premium.feat.earlyAccess': 'Snemmaðgangur að nýjum eiginleikum',
},
'da': {
    'pricing.title': 'Priser',
    'pricing.metaDescription': 'Vælg din plan. Gratis rumvejrsovervågning eller Pro/Premium med avancerede advarsler og nordlysvarsler.',
    'pricing.heroTitle': 'Vælg din plan',
    'pricing.heroSubtitle': 'Lås Storm Watchers fulde kraft op',
    'pricing.monthly': 'Månedligt',
    'pricing.yearly': 'Årligt',
    'pricing.save25': 'Spar 25%',
    'pricing.currentPlan': 'Nuværende plan',
    'pricing.mostPopular': 'Mest populær',
    'pricing.perMonth': 'måned',
    'pricing.perYear': 'år',
    'pricing.perMonthBilledYearly': 'måned faktureret årligt',
    'pricing.loading': 'Indlæser…',
    'pricing.getPro': 'Få Pro',
    'pricing.getPremium': 'Få Premium',
    'pricing.manageSubscription': 'Administrer abonnement',
    'pricing.footer': 'Annullér når som helst · Sikre betalinger via Stripe · Moms kan gælde',
    'pricing.pro.tagline': 'Til entusiaster',
    'pricing.premium.tagline': 'Til avancerede brugere',
    'pricing.pro.feat.forecasts': 'Detaljerede geomagnetiske varsler',
    'pricing.pro.feat.visibility': 'Nordlys-synlighedsforudsigelser',
    'pricing.pro.feat.alerts': 'Push-meddelelser og advarsler',
    'pricing.pro.feat.adfree': 'Reklamefri oplevelse',
    'pricing.pro.feat.basics': 'Alle grundlæggende funktioner',
    'pricing.premium.feat.everything': 'Alt i Pro',
    'pricing.premium.feat.history': 'Historiske data og grafer',
    'pricing.premium.feat.priority': 'Prioritetsadvarsler',
    'pricing.premium.feat.iss': 'ISS-sporing (avanceret)',
    'pricing.premium.feat.export': 'Eksportér data',
    'pricing.premium.feat.earlyAccess': 'Tidlig adgang til nye funktioner',
},
'pl': {
    'pricing.title': 'Cennik',
    'pricing.metaDescription': 'Wybierz swój plan. Bezpłatne monitorowanie pogody kosmicznej lub Pro/Premium z zaawansowanymi alertami i prognozami zorzy.',
    'pricing.heroTitle': 'Wybierz swój plan',
    'pricing.heroSubtitle': 'Odblokuj pełną moc Storm Watcher',
    'pricing.monthly': 'Miesięcznie',
    'pricing.yearly': 'Rocznie',
    'pricing.save25': 'Oszczędź 25%',
    'pricing.currentPlan': 'Aktualny plan',
    'pricing.mostPopular': 'Najpopularniejszy',
    'pricing.perMonth': 'miesiąc',
    'pricing.perYear': 'rok',
    'pricing.perMonthBilledYearly': 'miesiąc rozliczany rocznie',
    'pricing.loading': 'Ładowanie…',
    'pricing.getPro': 'Pobierz Pro',
    'pricing.getPremium': 'Pobierz Premium',
    'pricing.manageSubscription': 'Zarządzaj subskrypcją',
    'pricing.footer': 'Anuluj w dowolnym momencie · Bezpieczne płatności przez Stripe · Może obowiązywać VAT',
    'pricing.pro.tagline': 'Dla entuzjastów',
    'pricing.premium.tagline': 'Dla zaawansowanych użytkowników',
    'pricing.pro.feat.forecasts': 'Szczegółowe prognozy geomagnetyczne',
    'pricing.pro.feat.visibility': 'Prognozy widoczności zorzy',
    'pricing.pro.feat.alerts': 'Powiadomienia push i alerty',
    'pricing.pro.feat.adfree': 'Bez reklam',
    'pricing.pro.feat.basics': 'Wszystkie podstawowe funkcje',
    'pricing.premium.feat.everything': 'Wszystko z Pro',
    'pricing.premium.feat.history': 'Dane historyczne i wykresy',
    'pricing.premium.feat.priority': 'Priorytetowe alerty',
    'pricing.premium.feat.iss': 'Śledzenie ISS (zaawansowane)',
    'pricing.premium.feat.export': 'Eksportuj dane',
    'pricing.premium.feat.earlyAccess': 'Wczesny dostęp do nowych funkcji',
},
'uk': {
    'pricing.title': 'Ціни',
    'pricing.metaDescription': 'Виберіть свій план. Безкоштовний моніторинг космічної погоди або Pro/Premium з розширеними сповіщеннями та прогнозами полярного сяйва.',
    'pricing.heroTitle': 'Виберіть свій план',
    'pricing.heroSubtitle': 'Розблокуйте повну потужність Storm Watcher',
    'pricing.monthly': 'Щомісяця',
    'pricing.yearly': 'Щороку',
    'pricing.save25': 'Заощадьте 25%',
    'pricing.currentPlan': 'Поточний план',
    'pricing.mostPopular': 'Найпопулярніший',
    'pricing.perMonth': 'місяць',
    'pricing.perYear': 'рік',
    'pricing.perMonthBilledYearly': 'місяць, оплата щороку',
    'pricing.loading': 'Завантаження…',
    'pricing.getPro': 'Отримати Pro',
    'pricing.getPremium': 'Отримати Premium',
    'pricing.manageSubscription': 'Керування підпискою',
    'pricing.footer': 'Скасуйте будь-коли · Безпечні платежі через Stripe · ПДВ може застосовуватися',
    'pricing.pro.tagline': 'Для ентузіастів',
    'pricing.premium.tagline': 'Для досвідчених користувачів',
    'pricing.pro.feat.forecasts': 'Детальні геомагнітні прогнози',
    'pricing.pro.feat.visibility': 'Прогнози видимості полярного сяйва',
    'pricing.pro.feat.alerts': 'Push-сповіщення та попередження',
    'pricing.pro.feat.adfree': 'Без реклами',
    'pricing.pro.feat.basics': 'Усі базові функції',
    'pricing.premium.feat.everything': 'Усе з Pro',
    'pricing.premium.feat.history': 'Історичні дані та графіки',
    'pricing.premium.feat.priority': 'Пріоритетні сповіщення',
    'pricing.premium.feat.iss': 'Відстеження МКС (розширене)',
    'pricing.premium.feat.export': 'Експорт даних',
    'pricing.premium.feat.earlyAccess': 'Ранній доступ до нових функцій',
},
'ko': {
    'pricing.title': '가격',
    'pricing.metaDescription': '플랜을 선택하세요. 무료 우주 날씨 모니터링 또는 고급 알림과 오로라 예보가 포함된 Pro/Premium.',
    'pricing.heroTitle': '플랜을 선택하세요',
    'pricing.heroSubtitle': 'Storm Watcher의 전체 기능을 잠금 해제',
    'pricing.monthly': '월간',
    'pricing.yearly': '연간',
    'pricing.save25': '25% 절약',
    'pricing.currentPlan': '현재 플랜',
    'pricing.mostPopular': '가장 인기',
    'pricing.perMonth': '월',
    'pricing.perYear': '년',
    'pricing.perMonthBilledYearly': '월 (연간 청구)',
    'pricing.loading': '로딩 중…',
    'pricing.getPro': 'Pro 받기',
    'pricing.getPremium': 'Premium 받기',
    'pricing.manageSubscription': '구독 관리',
    'pricing.footer': '언제든지 취소 · Stripe를 통한 안전한 결제 · VAT이 적용될 수 있음',
    'pricing.pro.tagline': '애호가를 위한',
    'pricing.premium.tagline': '파워 유저를 위한',
    'pricing.pro.feat.forecasts': '상세한 지자기 예보',
    'pricing.pro.feat.visibility': '오로라 가시성 예측',
    'pricing.pro.feat.alerts': '푸시 알림 및 경고',
    'pricing.pro.feat.adfree': '광고 없음',
    'pricing.pro.feat.basics': '모든 기본 기능',
    'pricing.premium.feat.everything': 'Pro의 모든 기능',
    'pricing.premium.feat.history': '과거 데이터 및 차트',
    'pricing.premium.feat.priority': '우선 알림',
    'pricing.premium.feat.iss': 'ISS 추적 (고급)',
    'pricing.premium.feat.export': '데이터 내보내기',
    'pricing.premium.feat.earlyAccess': '새 기능에 대한 빠른 액세스',
},
}

print("Syncing pricing keys…")
for lang, additions in LOCALES.items():
    inject(lang, additions)

en = get_keys('en')
for lang in LOCALES.keys():
    missing = sorted(en - get_keys(lang))
    print(f"  [{lang}] {'✅' if not missing else 'MISSING: ' + str(missing[:3])}")
