#!/usr/bin/env python3
"""Inject referral-program i18n keys into all 16 locales. Idempotent."""
import os, re

BASE = os.path.join(os.path.dirname(__file__), '..', 'src', 'locales')

KEYS = {
    'en': {
        'nav.referrals': 'Refer & Earn',
        'referrals.title': 'Refer friends, get free Pro',
        'referrals.subtitle': 'Your friends get a longer free trial. You get 30 days of Pro for every friend who subscribes.',
        'referrals.yourLink': 'Your referral link',
        'referrals.copy': 'Copy',
        'referrals.copied': 'Copied!',
        'referrals.share': 'Share',
        'referrals.how': 'How it works',
        'referrals.step1': 'Share your link with friends',
        'referrals.step2': 'They sign up and get an extended free trial',
        'referrals.step3': 'When they subscribe, you earn 30 days of free Pro',
        'referrals.invited': 'Friends invited',
        'referrals.subscribed': 'Subscribed',
        'referrals.proEarned': 'Free Pro days earned',
        'referrals.proActiveUntil': 'Free Pro active until',
        'referrals.signInPrompt': 'Sign in to get your referral link and start earning free Pro.',
        'referrals.signIn': 'Sign in',
    },
    'bg': {
        'nav.referrals': 'Покани и печели',
        'referrals.title': 'Покани приятели, получи безплатен Pro',
        'referrals.subtitle': 'Приятелите ти получават по-дълъг безплатен период. Ти получаваш 30 дни Pro за всеки приятел, който се абонира.',
        'referrals.yourLink': 'Твоят реферален линк',
        'referrals.copy': 'Копирай',
        'referrals.copied': 'Копирано!',
        'referrals.share': 'Сподели',
        'referrals.how': 'Как работи',
        'referrals.step1': 'Сподели линка си с приятели',
        'referrals.step2': 'Те се регистрират и получават удължен безплатен период',
        'referrals.step3': 'Когато се абонират, печелиш 30 дни безплатен Pro',
        'referrals.invited': 'Поканени приятели',
        'referrals.subscribed': 'Абонирани',
        'referrals.proEarned': 'Спечелени дни Pro',
        'referrals.proActiveUntil': 'Безплатен Pro до',
        'referrals.signInPrompt': 'Влез, за да получиш реферален линк и да печелиш безплатен Pro.',
        'referrals.signIn': 'Вход',
    },
    'de': {
        'nav.referrals': 'Empfehlen & Verdienen',
        'referrals.title': 'Freunde einladen, Pro gratis erhalten',
        'referrals.subtitle': 'Deine Freunde erhalten eine längere Testphase. Du bekommst 30 Tage Pro für jeden Freund, der abonniert.',
        'referrals.yourLink': 'Dein Empfehlungslink',
        'referrals.copy': 'Kopieren',
        'referrals.copied': 'Kopiert!',
        'referrals.share': 'Teilen',
        'referrals.how': 'So funktioniert es',
        'referrals.step1': 'Teile deinen Link mit Freunden',
        'referrals.step2': 'Sie registrieren sich und erhalten eine verlängerte Testphase',
        'referrals.step3': 'Wenn sie abonnieren, erhältst du 30 Tage gratis Pro',
        'referrals.invited': 'Eingeladene Freunde',
        'referrals.subscribed': 'Abonniert',
        'referrals.proEarned': 'Verdiente Pro-Tage',
        'referrals.proActiveUntil': 'Gratis Pro aktiv bis',
        'referrals.signInPrompt': 'Melde dich an, um deinen Empfehlungslink zu erhalten und gratis Pro zu verdienen.',
        'referrals.signIn': 'Anmelden',
    },
    'es': {
        'nav.referrals': 'Recomienda y gana',
        'referrals.title': 'Recomienda amigos, consigue Pro gratis',
        'referrals.subtitle': 'Tus amigos obtienen una prueba más larga. Tú ganas 30 días de Pro por cada amigo que se suscriba.',
        'referrals.yourLink': 'Tu enlace de referido',
        'referrals.copy': 'Copiar',
        'referrals.copied': '¡Copiado!',
        'referrals.share': 'Compartir',
        'referrals.how': 'Cómo funciona',
        'referrals.step1': 'Comparte tu enlace con amigos',
        'referrals.step2': 'Se registran y obtienen una prueba gratuita ampliada',
        'referrals.step3': 'Cuando se suscriben, ganas 30 días de Pro gratis',
        'referrals.invited': 'Amigos invitados',
        'referrals.subscribed': 'Suscritos',
        'referrals.proEarned': 'Días de Pro ganados',
        'referrals.proActiveUntil': 'Pro gratis activo hasta',
        'referrals.signInPrompt': 'Inicia sesión para obtener tu enlace de referido y empezar a ganar Pro gratis.',
        'referrals.signIn': 'Iniciar sesión',
    },
    'fr': {
        'nav.referrals': 'Parrainez et gagnez',
        'referrals.title': 'Parrainez des amis, obtenez Pro gratuit',
        'referrals.subtitle': "Vos amis bénéficient d'un essai plus long. Vous gagnez 30 jours de Pro pour chaque ami qui s'abonne.",
        'referrals.yourLink': 'Votre lien de parrainage',
        'referrals.copy': 'Copier',
        'referrals.copied': 'Copié !',
        'referrals.share': 'Partager',
        'referrals.how': 'Comment ça marche',
        'referrals.step1': 'Partagez votre lien avec vos amis',
        'referrals.step2': "Ils s'inscrivent et bénéficient d'un essai gratuit prolongé",
        'referrals.step3': "Quand ils s'abonnent, vous gagnez 30 jours de Pro gratuit",
        'referrals.invited': 'Amis invités',
        'referrals.subscribed': 'Abonnés',
        'referrals.proEarned': 'Jours de Pro gagnés',
        'referrals.proActiveUntil': "Pro gratuit actif jusqu'au",
        'referrals.signInPrompt': 'Connectez-vous pour obtenir votre lien de parrainage et gagner du Pro gratuit.',
        'referrals.signIn': 'Se connecter',
    },
    'ja': {
        'nav.referrals': '紹介して特典をゲット',
        'referrals.title': '友達を紹介してProを無料でゲット',
        'referrals.subtitle': '友達はより長い無料トライアルを利用できます。友達が登録するたびに、あなたは30日間のProを獲得します。',
        'referrals.yourLink': 'あなたの紹介リンク',
        'referrals.copy': 'コピー',
        'referrals.copied': 'コピーしました！',
        'referrals.share': '共有',
        'referrals.how': '仕組み',
        'referrals.step1': 'リンクを友達に共有しましょう',
        'referrals.step2': '友達が登録すると延長された無料トライアルを利用できます',
        'referrals.step3': '友達が登録すると30日間の無料Proを獲得できます',
        'referrals.invited': '招待した友達',
        'referrals.subscribed': '登録済み',
        'referrals.proEarned': '獲得したPro日数',
        'referrals.proActiveUntil': '無料Proの有効期限',
        'referrals.signInPrompt': 'ログインして紹介リンクを取得し、無料Proを獲得しましょう。',
        'referrals.signIn': 'ログイン',
    },
    'ru': {
        'nav.referrals': 'Приглашай и зарабатывай',
        'referrals.title': 'Приглашайте друзей, получайте Pro бесплатно',
        'referrals.subtitle': 'Ваши друзья получают более длинный пробный период. Вы получаете 30 дней Pro за каждого друга, который оформит подписку.',
        'referrals.yourLink': 'Ваша реферальная ссылка',
        'referrals.copy': 'Копировать',
        'referrals.copied': 'Скопировано!',
        'referrals.share': 'Поделиться',
        'referrals.how': 'Как это работает',
        'referrals.step1': 'Поделитесь ссылкой с друзьями',
        'referrals.step2': 'Они регистрируются и получают расширенный бесплатный период',
        'referrals.step3': 'Когда они оформят подписку, вы получите 30 дней бесплатного Pro',
        'referrals.invited': 'Приглашено друзей',
        'referrals.subscribed': 'Оформили подписку',
        'referrals.proEarned': 'Заработано дней Pro',
        'referrals.proActiveUntil': 'Бесплатный Pro активен до',
        'referrals.signInPrompt': 'Войдите, чтобы получить реферальную ссылку и зарабатывать бесплатный Pro.',
        'referrals.signIn': 'Войти',
    },
    'zh': {
        'nav.referrals': '推荐赚奖励',
        'referrals.title': '推荐好友，免费获得 Pro',
        'referrals.subtitle': '你的好友可获得更长的免费试用。每有一位好友订阅，你就获得 30 天 Pro。',
        'referrals.yourLink': '你的推荐链接',
        'referrals.copy': '复制',
        'referrals.copied': '已复制！',
        'referrals.share': '分享',
        'referrals.how': '运作方式',
        'referrals.step1': '将链接分享给好友',
        'referrals.step2': '他们注册并获得延长的免费试用',
        'referrals.step3': '当他们订阅时，你将获得 30 天免费 Pro',
        'referrals.invited': '已邀请好友',
        'referrals.subscribed': '已订阅',
        'referrals.proEarned': '已获得 Pro 天数',
        'referrals.proActiveUntil': '免费 Pro 有效期至',
        'referrals.signInPrompt': '登录以获取你的推荐链接并开始赚取免费 Pro。',
        'referrals.signIn': '登录',
    },
    'da': {
        'nav.referrals': 'Henvis og tjen',
        'referrals.title': 'Henvis venner, få gratis Pro',
        'referrals.subtitle': 'Dine venner får en længere gratis prøveperiode. Du får 30 dages Pro for hver ven, der abonnerer.',
        'referrals.yourLink': 'Dit henvisningslink',
        'referrals.copy': 'Kopiér',
        'referrals.copied': 'Kopieret!',
        'referrals.share': 'Del',
        'referrals.how': 'Sådan virker det',
        'referrals.step1': 'Del dit link med venner',
        'referrals.step2': 'De tilmelder sig og får en udvidet gratis prøveperiode',
        'referrals.step3': 'Når de abonnerer, får du 30 dages gratis Pro',
        'referrals.invited': 'Inviterede venner',
        'referrals.subscribed': 'Abonnenter',
        'referrals.proEarned': 'Optjente Pro-dage',
        'referrals.proActiveUntil': 'Gratis Pro aktiv indtil',
        'referrals.signInPrompt': 'Log ind for at få dit henvisningslink og begynde at tjene gratis Pro.',
        'referrals.signIn': 'Log ind',
    },
    'fi': {
        'nav.referrals': 'Suosittele ja ansaitse',
        'referrals.title': 'Suosittele ystäville, saa Pro ilmaiseksi',
        'referrals.subtitle': 'Ystäväsi saavat pidemmän ilmaisen kokeilun. Sinä saat 30 päivää Pro jokaisesta ystävästä, joka tilaa.',
        'referrals.yourLink': 'Suosittelulinkkisi',
        'referrals.copy': 'Kopioi',
        'referrals.copied': 'Kopioitu!',
        'referrals.share': 'Jaa',
        'referrals.how': 'Näin se toimii',
        'referrals.step1': 'Jaa linkkisi ystäville',
        'referrals.step2': 'He rekisteröityvät ja saavat pidennetyn ilmaisen kokeilun',
        'referrals.step3': 'Kun he tilaavat, ansaitset 30 päivää ilmaista Pro',
        'referrals.invited': 'Kutsutut ystävät',
        'referrals.subscribed': 'Tilanneet',
        'referrals.proEarned': 'Ansaitut Pro-päivät',
        'referrals.proActiveUntil': 'Ilmainen Pro voimassa',
        'referrals.signInPrompt': 'Kirjaudu sisään saadaksesi suosittelulinkkisi ja ansaitaksesi ilmaista Pro.',
        'referrals.signIn': 'Kirjaudu',
    },
    'is': {
        'nav.referrals': 'Mæltu með og fáðu fríðindi',
        'referrals.title': 'Mæltu með vinum, fáðu Pro frítt',
        'referrals.subtitle': 'Vinir þínir fá lengri ókeypis prufutíma. Þú færð 30 daga af Pro fyrir hvern vin sem gerist áskrifandi.',
        'referrals.yourLink': 'Tilvísunarhlekkurinn þinn',
        'referrals.copy': 'Afrita',
        'referrals.copied': 'Afritað!',
        'referrals.share': 'Deila',
        'referrals.how': 'Hvernig það virkar',
        'referrals.step1': 'Deildu hlekknum þínum með vinum',
        'referrals.step2': 'Þeir skrá sig og fá lengri ókeypis prufutíma',
        'referrals.step3': 'Þegar þeir gerast áskrifendur færð þú 30 daga af fríu Pro',
        'referrals.invited': 'Boðnir vinir',
        'referrals.subscribed': 'Áskrifendur',
        'referrals.proEarned': 'Áunnir Pro-dagar',
        'referrals.proActiveUntil': 'Frítt Pro virkt til',
        'referrals.signInPrompt': 'Skráðu þig inn til að fá tilvísunarhlekkinn þinn og byrja að vinna þér inn frítt Pro.',
        'referrals.signIn': 'Skrá inn',
    },
    'ko': {
        'nav.referrals': '추천하고 혜택 받기',
        'referrals.title': '친구를 추천하고 Pro를 무료로 받으세요',
        'referrals.subtitle': '친구는 더 긴 무료 체험을 받습니다. 구독하는 친구마다 30일의 Pro를 받습니다.',
        'referrals.yourLink': '내 추천 링크',
        'referrals.copy': '복사',
        'referrals.copied': '복사됨!',
        'referrals.share': '공유',
        'referrals.how': '이용 방법',
        'referrals.step1': '친구에게 링크를 공유하세요',
        'referrals.step2': '친구가 가입하면 연장된 무료 체험을 받습니다',
        'referrals.step3': '친구가 구독하면 30일의 무료 Pro를 받습니다',
        'referrals.invited': '초대한 친구',
        'referrals.subscribed': '구독함',
        'referrals.proEarned': '획득한 Pro 일수',
        'referrals.proActiveUntil': '무료 Pro 사용 가능 기한',
        'referrals.signInPrompt': '로그인하여 추천 링크를 받고 무료 Pro를 받으세요.',
        'referrals.signIn': '로그인',
    },
    'no': {
        'nav.referrals': 'Verv og tjen',
        'referrals.title': 'Verv venner, få gratis Pro',
        'referrals.subtitle': 'Vennene dine får en lengre gratis prøveperiode. Du får 30 dager Pro for hver venn som abonnerer.',
        'referrals.yourLink': 'Din vervelenke',
        'referrals.copy': 'Kopier',
        'referrals.copied': 'Kopiert!',
        'referrals.share': 'Del',
        'referrals.how': 'Slik fungerer det',
        'referrals.step1': 'Del lenken din med venner',
        'referrals.step2': 'De registrerer seg og får en utvidet gratis prøveperiode',
        'referrals.step3': 'Når de abonnerer, får du 30 dager gratis Pro',
        'referrals.invited': 'Inviterte venner',
        'referrals.subscribed': 'Abonnenter',
        'referrals.proEarned': 'Opptjente Pro-dager',
        'referrals.proActiveUntil': 'Gratis Pro aktiv til',
        'referrals.signInPrompt': 'Logg inn for å få vervelenken din og begynne å tjene gratis Pro.',
        'referrals.signIn': 'Logg inn',
    },
    'pl': {
        'nav.referrals': 'Poleć i zarabiaj',
        'referrals.title': 'Poleć znajomym, zdobądź darmowe Pro',
        'referrals.subtitle': 'Twoi znajomi otrzymują dłuższy darmowy okres próbny. Ty otrzymujesz 30 dni Pro za każdego znajomego, który się zapisze.',
        'referrals.yourLink': 'Twój link polecający',
        'referrals.copy': 'Kopiuj',
        'referrals.copied': 'Skopiowano!',
        'referrals.share': 'Udostępnij',
        'referrals.how': 'Jak to działa',
        'referrals.step1': 'Udostępnij link znajomym',
        'referrals.step2': 'Rejestrują się i otrzymują wydłużony darmowy okres próbny',
        'referrals.step3': 'Gdy się zapiszą, otrzymujesz 30 dni darmowego Pro',
        'referrals.invited': 'Zaproszeni znajomi',
        'referrals.subscribed': 'Subskrybenci',
        'referrals.proEarned': 'Zdobyte dni Pro',
        'referrals.proActiveUntil': 'Darmowe Pro aktywne do',
        'referrals.signInPrompt': 'Zaloguj się, aby otrzymać link polecający i zdobywać darmowe Pro.',
        'referrals.signIn': 'Zaloguj się',
    },
    'sv': {
        'nav.referrals': 'Tipsa och tjäna',
        'referrals.title': 'Tipsa vänner, få gratis Pro',
        'referrals.subtitle': 'Dina vänner får en längre gratis provperiod. Du får 30 dagar Pro för varje vän som prenumererar.',
        'referrals.yourLink': 'Din värvningslänk',
        'referrals.copy': 'Kopiera',
        'referrals.copied': 'Kopierat!',
        'referrals.share': 'Dela',
        'referrals.how': 'Så fungerar det',
        'referrals.step1': 'Dela din länk med vänner',
        'referrals.step2': 'De registrerar sig och får en förlängd gratis provperiod',
        'referrals.step3': 'När de prenumererar får du 30 dagar gratis Pro',
        'referrals.invited': 'Inbjudna vänner',
        'referrals.subscribed': 'Prenumeranter',
        'referrals.proEarned': 'Intjänade Pro-dagar',
        'referrals.proActiveUntil': 'Gratis Pro aktivt till',
        'referrals.signInPrompt': 'Logga in för att få din värvningslänk och börja tjäna gratis Pro.',
        'referrals.signIn': 'Logga in',
    },
    'uk': {
        'nav.referrals': 'Запрошуй і заробляй',
        'referrals.title': 'Запрошуйте друзів, отримуйте безкоштовний Pro',
        'referrals.subtitle': 'Ваші друзі отримують довший безкоштовний пробний період. Ви отримуєте 30 днів Pro за кожного друга, який оформить підписку.',
        'referrals.yourLink': 'Ваше реферальне посилання',
        'referrals.copy': 'Копіювати',
        'referrals.copied': 'Скопійовано!',
        'referrals.share': 'Поділитися',
        'referrals.how': 'Як це працює',
        'referrals.step1': 'Поділіться посиланням з друзями',
        'referrals.step2': 'Вони реєструються й отримують подовжений безкоштовний пробний період',
        'referrals.step3': 'Коли вони оформлять підписку, ви отримаєте 30 днів безкоштовного Pro',
        'referrals.invited': 'Запрошені друзі',
        'referrals.subscribed': 'Оформили підписку',
        'referrals.proEarned': 'Зароблені дні Pro',
        'referrals.proActiveUntil': 'Безкоштовний Pro активний до',
        'referrals.signInPrompt': 'Увійдіть, щоб отримати реферальне посилання та заробляти безкоштовний Pro.',
        'referrals.signIn': 'Увійти',
    },
}


def escape(v):
    return v.replace("\\", "\\\\").replace("'", "\\'")


def inject(lang, additions):
    path = os.path.join(BASE, f'{lang}.ts')
    content = open(path, encoding='utf-8').read()
    existing = set(re.findall(r"^\s+'([^']+)'\s*:", content, re.MULTILINE))
    lines = [f"  '{k}': '{escape(v)}'," for k, v in additions.items() if k not in existing]
    if not lines:
        print(f"  [{lang}] nothing to add")
        return
    idx = content.rfind('\n};')
    new = content[:idx] + '\n' + '\n'.join(lines) + content[idx:]
    open(path, 'w', encoding='utf-8').write(new)
    print(f"  [{lang}] added {len(lines)} keys")


if __name__ == '__main__':
    for lang, additions in KEYS.items():
        inject(lang, additions)
    print('done')
